### ISSUE TITLE
"EU Phone Numbers" Sensitive information type not yet available?

### ISSUE THREAD

**Issue by RafCox** [MicrosoftDocs/OfficeDocs-o365seccomp#100]
hi, 
Is this "EU Phone Numbers" Sensitive information type already available? even this documentation seems a bit orphaned (no link to it from elsewhere) and i couldn't find it in O365... when will it be available?

thanks!
Raf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b2a68a4-670f-906b-3ccc-e8ca491d29b3
* Version Independent ID: c0ad2607-240b-e090-fdbd-d7a72bf8af31
* Content: [EU Phone Number](https://docs.microsoft.com/en-us/office365/securitycompliance/eu-phone-number)
* Content Source: [SecurityCompliance/eu-phone-number.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eu-phone-number.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@RafCox Thank you for this feedback. 

I don't know when this will be available. I will get this over to the o365seccomp team so we can get some information on when this will be available. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @RafCox, thank you for your feedback.

It's not available yet and I don't have information about adding phone numbers to "Sensitive info types" on Security & Compliance.

Where did you access this file?

Thanks again!

**Comment by scanum** [comment]
@RafCox We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
