### ISSUE TITLE
Table is missing the "MailFlow Administrator"

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/OfficeDocs-o365seccomp#101]
...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@chrislehr Thank you for this feedback

We apricate you pointing out that we are missing the mailflow administer in the table. I will get this over to the o365seccomp team for updating. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by stephow-MSFT** [comment]
The article's been updated with this info.
