### ISSUE TITLE
Please provide clarification on port requirements

### ISSUE THREAD

**Issue by sgreenlee11** [MicrosoftDocs/OfficeDocs-o365seccomp#104]
Hello,

It is unclear based on the following statement if only port 25 is required for these IP ranges:

The following Microsoft data center IP addresses are used by Microsoft Exchange Online Protection (EOP) when sending email, receiving email, or for Exchange Online Protection portal and administrative services

Could you please clarify this, or add which ranges may need additional ports.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90bba8f1-54aa-85f9-a311-2b4240c40202
* Version Independent ID: ae5462b5-141b-cef2-72dc-3f62f19b708c
* Content: [Exchange Online Protection IP addresses](https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/exchange-online-protection-ip-addresses)
* Content Source: [SecurityCompliance/eop/exchange-online-protection-ip-addresses.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/exchange-online-protection-ip-addresses.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@sgreenlee11 Thank you for this feedback

I agree that it's not directly stated what ports these addresses are needing to be added to. I do see in the article that they said it is for sending and receiving email as well as exchange online so I would say make these IP's available for the ports your tenant uses for these. 

Just to double check on this I will make sure to get this inquiry in front of the o365seccomp team.

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@sgreenlee11 I have forwarded your question to the product team owners, who will reopen this issue when they provide an answer.
