### ISSUE TITLE
What is the status of Government SKUs G1, G3, G5 etc.?

### ISSUE THREAD

**Issue by grywalskita** [MicrosoftDocs/OfficeDocs-o365seccomp#105]
Can you include information on this functionality in the government plans? -Thanks  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e607177-4e5b-69af-5408-caa6337bbd0e
* Version Independent ID: c82bbeaa-9df1-c070-644b-a666406464b5
* Content: [Alert policies in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies?redirectSourcePath=%252farticle%252f8927b8b9-c5bc-45a8-a9f9-96c732e58264#feedback)
* Content Source: [SecurityCompliance/alert-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/alert-policies.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@grywalskita Thank you for this feedback

I will get this inquiry over to the o365seccomp team so we can get a status of these skus included in the article. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by grywalskita** [comment]
Thank you!

------------------------------------------------
Tristina A. Grywalski
Business Systems Analyst II
Gainesville Regional Utilities
Certified Usability Analyst  2007-1434
------------------------------------------------
Phone: (352) 393-6963

Mail Stop: E1-C


Location: EOC

**Comment by markjjo** [comment]
@grywalskita We've added info about government clouds to alert policies topic. The summary is that Office 365 US Government plans include alert policies like their corresponding Enterprise counterparts. See the topic for details.
