### ISSUE TITLE
Message ID

### ISSUE THREAD

**Issue by dnides** [MicrosoftDocs/OfficeDocs-o365seccomp#106]
Is there a way to export a email using eDiscovery or something else to PST by a message ID or list or message IDs?

**Comment by AndreaBarr** [comment]
@dnides Thank you for this inquiry. 

I am not sure if there is another way to export an email. I will get this over to the o365seccomp team so we can get this answered for you. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@dnides Please see this help topic: https://docs.microsoft.com/en-us/office365/securitycompliance/csv-file-for-an-id-list-content-search -- After you create and run a "search by ID list" content search, you can exports the result to a PST file.

**Comment by AndreaBarr** [comment]
@dnides It looks like Mark was able to find an article that explains a different way to export these emails. I am going to close this as resolved. If this does not answer your question please re-open this issue.
