### ISSUE TITLE
How to get all list Audited activities

### ISSUE THREAD

**Issue by loongdefect** [MicrosoftDocs/OfficeDocs-o365seccomp#107]
Hi all,
I wan get all list Audited activities. How to i get it?

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@loongdefect Thank you for this Inquiry. 

I am not sure how to get a list of all the Audited activities. I agree that the instructions for this should be included in the article. Let me get this over to the Teams/Skype for Business team so we can get this investigated and the article updated. 
The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@loongdefect The activities drop-down list is probably the most comprehensive way to get a list of audited activities. However, activities from the Exchange admin audit log aren't list here and any non-Get cmdlet from Exchange Online could be returned in an audit log search. You could also run the Search-UnifiedAuditLog | FL Operations command in EXO PowerShell for the activities that are actually logged in your tenant.

**Comment by AndreaBarr** [comment]
@loongdefect Sorry for the wrong team mention there. My screen was being odd apparently. Did what Mark shared with you answer your question?

**Comment by markjjo** [comment]
@loongdefect Nothing to add past my last response; there isn't really a way to get a list of all activities that are audited; one other thought is that you could search the audit log for a 90-day period, export the results to a csv file, and then collect all the unique values in the Operation column. This would give you all the activities that have been performed/relevant to your organization.
