### ISSUE TITLE
Bing search

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#108]
This article doesn't appear to be returned in the first few pages of bing search results around EOP false positives anymore

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78678fe5-0473-27f2-1600-122267386c3d
* Version Independent ID: ab96b413-3d71-a9ae-5887-e80696b30f3f
* Content: [Submit spam, non-spam, and phishing scam messages to Microsoft for analysis](https://docs.microsoft.com/en-gb/office365/SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis)
* Content Source: [SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@aldoug Thank you for this feedback

I'm not sure why it's no long on the first few pages of the Bing search results. I'll get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by KCCross** [comment]
SEO changes constantly. New articles published can change the results for existing articles. Thanks for letting us know this one no longer makes the top page.
