### ISSUE TITLE
API

### ISSUE THREAD

**Issue by darryllane** [MicrosoftDocs/OfficeDocs-o365seccomp#11]
Is there anyway to create these global blocks via an API? If so what API? Ive seem to have been searching for hours to no avail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0785746b-cad9-9f3f-20f9-1fb3552abf6f
* Version Independent ID: e34bbfea-0bbe-4f21-e49a-2cee9d3860af
* Content: [Create organization-wide safe sender or blocked sender lists in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365)
* Content Source: [SecurityCompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@darryllane, thank you for the question. We're looking into this.

**Comment by chrisda** [comment]
@darryllane, does PowerShell count as an API?

[Get-TransportRule](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/get-transportrule)

[New-TransportRule](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/new-transportrule)

[Remove-TransportRule](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/remove-transportrule)

[Set-TransportRule](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/set-transportrule)

[Get-HostedConnectionFilterPolicy](https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-hostedconnectionfilterpolicy)

[Set-HostedConnectionFilterPolicy](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/set-hostedconnectionfilterpolicy)

**Comment by darryllane** [comment]
No, although technically PS interface would be an API but I was thinking more of a traditional web service api access. Like a REST based service, however since posting this thread I have learnt the PS cmdlets are pretty much the only interface in, unless you want to use their web gui.
