### ISSUE TITLE
Small Typo in ATP Safe Attachments

### ISSUE THREAD

**Issue by rickkrieger** [MicrosoftDocs/OfficeDocs-o365seccomp#112]
"designed to steal the Lee's user credentials"
should be:
"designed to steal Lee's user credentials"
https://docs.microsoft.com/en-us/office365/securitycompliance/atp-safe-attachments 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306d3529-a3a2-5400-6135-fcc6059c0b20
* Version Independent ID: dbd596b8-14f3-a4c0-5ac7-084573a7d559
* Content: [Office 365 ATP Safe Attachments](https://docs.microsoft.com/en-us/office365/securitycompliance/atp-safe-attachments)
* Content Source: [SecurityCompliance/atp-safe-attachments.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/atp-safe-attachments.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AndreaBarr** [comment]
@rickkriger Thank you for this feedback

I fixed this typo and submitted a pull request. I am waiting on approval to merge it with the live document.

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
Thank you @rickkrieger and @AndreaBarr. Changes are now live.
