### ISSUE TITLE
Do I need to be a Global Admin to manage privileged access in Office 365

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-o365seccomp#114]
The answer to this question is incorrect, all you need is to have the "Role management" role assigned. It would be nice if it gets restricted to GAs though :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ecef9b9-7010-7353-b744-657e6823036e
* Version Independent ID: 7c5821b1-b5d5-a694-c6ff-b4058a59410f
* Content: [Privileged access management in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/privileged-access-management-overview#do-i-need-to-be-a-global-admin-to-manage-privileged-access-in-office-365)
* Content Source: [SecurityCompliance/privileged-access-management-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/privileged-access-management-overview.md)
* Service: **o365-solutions**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@michevnew Thank you for this feedback

I will make sure to get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@michevnew - the current answer is correct in this topic, privileged access management administration requires the Global Admin role. If you are seeing a different experience in your tenant, please contact product support so we can investigate. Thanks!

**Comment by robmazz** [comment]
@michevnew - after digging a bit deeper into this feedback, the product group has now confirmed your feedback and the topic is now updated with more accurate guidance. Thanks so much for your feedback and apologies for any confusion that may have resulted from my initial response.

**Comment by cmanuel83** [comment]
If you are a different administrator than the global admin, then it doesn't work. Only Global admins can request access. I would like to apply this functionality to Exchange Administrators but it doesn't work because if you don't have Global Admin permission you cannot access the "Security & privacy" blade and therefore cannot access the Privileged Access section. Even if you assign the Exchange Role Management role to the Exchange Administrators, it doesn't work.
Regards.
