### ISSUE TITLE
Allow 3rd party spoofing but limit to Internal domains

### ISSUE THREAD

**Issue by RichITPerson** [MicrosoftDocs/OfficeDocs-o365seccomp#117]
Is it possible to allow the spoofed user to be any sender from an Internal domain only?  With 3rd party mailing services, we get added to their mailing lists, so we try and limit that via Rules and only allow e-mails from the spoofed domain where the sender e-mail address contains our domain while all other e-mails from the 3rd party mailing service get sent to Quarantine.  The downside of that is we can't allow users to see those messages in their Quarantine because messages sent to Quarantine based on a Rule aren't viewable by the end user and there is no option to allow that anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2346da88-037b-1ef9-e3c4-c6d448b9688e
* Version Independent ID: 0292959f-9f3d-a34f-156e-bb8488fdc251
* Content: [Learn more about spoof intelligence](https://docs.microsoft.com/en-us/office365/securitycompliance/learn-about-spoof-intelligence?redirectSourcePath=%252fen-us%252farticle%252fLearn-more-about-spoof-intelligence-978c3173-3578-4286-aaf4-8a10951978bf)
* Content Source: [SecurityCompliance/learn-about-spoof-intelligence.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/learn-about-spoof-intelligence.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@RichITPerson Thank you for this feedback

I am not sure if there is a way to allow the spoofed user to be any sender from an internal domain only. 
I will get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @RichITPerson, thank you for your feedback.

Sorry but I think it's not possible. In this article is explained all the customization you can do:
https://docs.microsoft.com/office365/securitycompliance/set-up-anti-phishing-policies

**Comment by scanum** [comment]
@RichITPerson We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
