### ISSUE TITLE
Incorrect instructions

### ISSUE THREAD

**Issue by jasonfare** [MicrosoftDocs/OfficeDocs-o365seccomp#118]
The instructions state that you go to eDiscovery and then Advanced eDiscovery, but you cannot access Advanced eDiscovery until you have opened a case from Core eDiscovery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81d43203-b11c-3606-a24f-7d0fb76e8986
* Version Independent ID: 888256a6-8f89-d972-6324-413d7ddd8765
* Content: [Run the Process module and load data in Office 365 Advanced eDiscovery](https://docs.microsoft.com/en-us/office365/securitycompliance/run-the-process-module-and-load-data-in-advanced-ediscovery)
* Content Source: [SecurityCompliance/run-the-process-module-and-load-data-in-advanced-ediscovery.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/run-the-process-module-and-load-data-in-advanced-ediscovery.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by AndreaBarr** [comment]
@jasonfare Thank you for this feedback

I will get this information for the eDiscovery over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrfox** [comment]
Thanks for the feedback. This procedure to use this feature is part of a much larger set of features and procedures and must be used in the context of full eDiscovery.

**Comment by jasonfare** [comment]
Hi Chris,

Perhaps I was misunderstood.

Step 2: Go to Search & investigation > eDiscovery and then click Go to Advanced eDiscovery.

You can’t go that route as there is no “Go to Advanced eDiscovery” option from that screen.  You have to open the case first and then go to Advanced eDiscovery by clicking “Switch to Advanced eDiscovery.”

At this time, when I click the Advanced eDiscovery option from the menu on the left, It opens saying I have no cases despite having cases I can access from eDiscovery and switch to Advanced eDiscovery.

A customer was the one who brought this up while doing an M365 E5 Enablement as it is incorrect instructions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-o365seccomp%2Fissues%2F118%23issuecomment-490157202&data=02%7C01%7C%7C6b90b5202e754601333a08d6d30ab4ad%7C88889efb873847e69ea0b1a0d685be46%7C0%7C0%7C636928440273049587&sdata=M2zQK2OsBp65r8uxDGcX4NNXirmSxVgoOe%2BoJUQXIKQ%3D&reserved=0>, or mute the thread<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJPNU5JIV7XKG62G2AYYYCTPUGWHRANCNFSM4F3RVBUA&data=02%7C01%7C%7C6b90b5202e754601333a08d6d30ab4ad%7C88889efb873847e69ea0b1a0d685be46%7C0%7C0%7C636928440273049587&sdata=iOrOxgz0h3c%2FzSLWDUSVc5gfPR9RPrgFUTB67EmGTGM%3D&reserved=0>.

Jason Fare
Cloud Solutions Architect | PMO | Application Consulting Training Solutions, Inc.
Direct: (904) 203-1546
E-mail: JFare@actsolution.net

[cid:actslogoc2-1_8018580a-d076-4ecd-a40f-d9b9bdf7a40f.png]<http://www.actsolution.net/>

This e-mail, including attachments, contains privileged and confidential information and may be protected by the licensee/client or other privileges and constitutes non-public information intended to be conveyed only to the designated recipient(s). If you are not the intended recipient or the agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination or copying of this e-mail is strictly prohibited. If you have received this e-mail in error, please notify us by reply e-mail and delete this e-mail from your records. The unauthorized use, dissemination, distribution or reproduction of this e-mail; including attachments, is prohibited and may be unlawful. Disclaimer regarding Uniform Electronic Transactions Act (UETA) (Florida Statutes Section 668.50): If this communication concerns negotiation of a contract or agreement, UETA does not apply to this communication; contract formation in this matter shall occur only with manually-affixed original signatures on original documents.
