### ISSUE TITLE
Scope of Change

### ISSUE THREAD

**Issue by chrisscerbo** [MicrosoftDocs/OfficeDocs-o365seccomp#119]
Does this apply to tenants that use Exchange Online Plan 1, Exchange Online Plan 2, Enterprise E1, or Enterprise E3 licensing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab02396-69f6-5a83-fc27-7a2ba9ab78eb
* Version Independent ID: 63266ff4-ef2a-84b3-f1b9-c7b3e4d8a1b7
* Content: [Anti-spoofing protection in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/anti-spoofing-protection)
* Content Source: [SecurityCompliance/anti-spoofing-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spoofing-protection.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@chrisscerbo Thank you for this feedback

I am not sure what version this applies to. Let me get this over to the o365seccomp team for investigation and answers. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by KCCross** [comment]
Hi!
Microsoft's anti-spoofing technology was initially deployed to its organizations that had an Office 365 Enterprise E5 subscription or had purchased the Office 365 Advanced Threat Protection (ATP) add-on for their subscription. As of October, 2018 we've extended the protection to all organizations that have Exchange Online Protection (EOP) as well. This includes organizations that have purchased EOP as a separate add-on to their existing SKU.

**Comment by chrisscerbo** [comment]
For clarity, do tenants that use Exchange Online Plan 1, Exchange Online Plan 2, Enterprise E1, or Enterprise E3 licensing have Exchange Online Protection or do they need to purchase the EOP add-on license as well?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @chrisscerbo, 

Yes, EOP is included on EXO Plan 1, 2, E1 and E3. You don't need to buy EOP as an add-on in those cases.

**Comment by scanum** [comment]
@chrisscerbo We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
