### ISSUE TITLE
Imported or migrated mailboxes

### ISSUE THREAD

**Issue by the-blesss** [MicrosoftDocs/OfficeDocs-o365seccomp#12]
Are all email messages and attachments scanned for malware when importing during a migration to O365 Exchange Online? The above states messages sent or received are scanned, but does not mention imported or migrated email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cceea227-4814-9132-2ce1-700ea1773cd4
* Version Independent ID: f72742e9-7d11-a09e-b48f-930316c8fd1c
* Content: [Anti-malware protection FAQ ](https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-malware-protection-faq-eop)
* Content Source: [SecurityCompliance/anti-malware-protection-faq-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-malware-protection-faq-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@the-blesss, thank you for the question. We're looking into this.

**Comment by Joey40** [comment]
Hi @denisebmsft @KCCross , Is there any update on this request?

**Comment by KCCross** [comment]
HI! I've forwarded the question onto parties that are responsible for migration. I'll post when I find out more.

**Comment by AndreaBarr** [comment]
@the-blesss thank you for this feedback

I am going to get this to the O365seccomp team for investigation and updating. 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
@the-blesss Most likely no. It would depend on how you're migrating, but, generally speaking, it's by some sort of direct ingestion that bypasses the standard Transport pipeline and, therefore, the standard filtering stack.
