### ISSUE TITLE
Can't find Spoofing safety tips

### ISSUE THREAD

**Issue by teraco** [MicrosoftDocs/OfficeDocs-o365seccomp#122]
Hi, I can't find "Spoofing safety fips" function. I have E1 + ATP licenses. Is this function effectiveness? If isn't, I'll delete step 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2346da88-037b-1ef9-e3c4-c6d448b9688e
* Version Independent ID: 0292959f-9f3d-a34f-156e-bb8488fdc251
* Content: [Learn more about spoof intelligence](https://docs.microsoft.com/en-us/office365/securitycompliance/learn-about-spoof-intelligence)
* Content Source: [SecurityCompliance/learn-about-spoof-intelligence.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/learn-about-spoof-intelligence.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by dfantham** [comment]
@teraco Thank you for the feedback. We have temporarily disabled the spoof safety tips, so you can ignore the step that references this option. We have removed this step from the documentation to remove any confusion moving forward. 

Currently, there is no plan in the near future to re-enable this feature, but we will add this item to the sprint backlog and take it up accordingly. Thanks again for your feedback!
-David

**Comment by teraco** [comment]
@dfantham Thank you for your Correspondence! I'm hoping good improvement!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@teraco Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
