### ISSUE TITLE
Link for Security & Compliance PowerShell takes you to Exchange Online PowerShell

### ISSUE THREAD

**Issue by andyschan** [MicrosoftDocs/OfficeDocs-o365seccomp#123]
In the "Find the PowerShell cmdlets for labels" section, the "Connect to the Office 365 Security & Compliance Center using remote PowerShell" link takes you to instructions for Exchange Online, not Security & Compliance Center. Also, the link for "Office 365 Security & Compliance Center cmdlets" takes you to Exchange Online as well; I haven't found a collection of Security & Compliance cmdlets yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels#find-the-powershell-cmdlets-for-labels)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by easayahiya** [comment]
Great job noticing!
I have made a PR regarding this issue.

**Comment by andyschan** [comment]
Not sure why was re-opened; it wasn't me :)
