### ISSUE TITLE
Please add product limits/details

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/OfficeDocs-o365seccomp#124]
Came to this looking for Attack Simulator limits, specifically:

How many passwords (how big can the list be) can be included in the attack?
What does the password attempt look like? Will it trigger audit alerts? Will it lock out the target accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator#password-spray-attack)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AndreaBarr** [comment]
@jwojan Thank you for this feedback

I am not sure how many passwords can be in the simulator or what it looks like. Let me get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jwojan** [comment]
I tested with 15,000,000 passwords and got errors,so there are limits. We just need to formally document them so people don't have to guess.

📱💬

On Oct 18, 2018, at 3:21 PM, AndreaBarr <notifications@github.com<mailto:notifications@github.com>> wrote:


@jwojan<https://github.com/jwojan> Thank you for this feedback

I am not sure how many passwords can be in the simulator or what it looks like. Let me get this over to the o365seccomp team for investigation.

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by haaranenjarmo** [comment]
I have tested with following password sets10,000,000/5,000,000/1,000,000/10,000/2500 and I will get internal error 500. Magic was 999 passwords in text file. Hmm is this really an a test/preview feature or demo from Microsoft side?

**Comment by elcuevero** [comment]
As of this date the limit has not been lifted and is still 999 making it pretty useless.

**Comment by denisebmsft** [comment]
Thanks to all who posted questions/comments here. I'm told that the limit has less to do with a number of passwords and more to do with file size. 10 MB is the maximum file size.
