### ISSUE TITLE
update for unified labeling

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-o365seccomp#126]
does this need updated for unified labeling?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd417c8-d12a-c8b6-4d76-eb6c979414c8
* Version Independent ID: a2c332e7-9553-85f8-63cd-3cdc265bc872
* Content: [Secure SharePoint Online sites and files](https://docs.microsoft.com/en-us/office365/securitycompliance/secure-sharepoint-online-sites-and-files#azure-information-protection)
* Content Source: [SecurityCompliance/secure-sharepoint-online-sites-and-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/secure-sharepoint-online-sites-and-files.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by AndreaBarr** [comment]
@bakerm00 Thank you for this feedback

I am not sure if this needs updated for Unified labeling. Let me get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by BrendaCarter** [comment]
Updated!

**Comment by jemsjose** [comment]
Site-level device access controls are already available. Would help others if updated:
https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-a-specific-sharepoint-site-or-onedrive

**Comment by BrendaCarter** [comment]
Updated. Will go live soon. Thank you for the note!
