### ISSUE TITLE
Sensitive Information Types missing from this document

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/OfficeDocs-o365seccomp#128]
I have labels with conditions matching "EU GPS Coordinates" and "EU Phone Number" however neither of these are defined in this document.  There may be other conditions as well and they should all be included.  Without their inclusion, it is not possible to customize them as they generate false positives in my dataset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401c22ca-51e6-82c5-6500-7320a6bb99a6
* Version Independent ID: 6c7dba02-0f25-9db2-742f-d12a60e32b26
* Content: [What the sensitive information types look for](https://docs.microsoft.com/en-us/office365/securitycompliance/what-the-sensitive-information-types-look-for?redirectSourcePath=%252farticle%252fWhat-the-sensitive-information-types-look-for-fd505979-76be-4d9f-b459-abef3fc9e86b#feedback)
* Content Source: [SecurityCompliance/what-the-sensitive-information-types-look-for.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
EU GPS Coordinates and EU Phone Number are not documented because they have been removed from the product. It's possible they may be re-released in the future.
