### ISSUE TITLE
Term Update

### ISSUE THREAD

**Issue by byteben** [MicrosoftDocs/OfficeDocs-o365seccomp#129]
Please replace “Office 365 Admin Center” with “Microsoft 365 Admin Center” 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b2adbe3-be71-88ae-26d7-9f4956510c50
* Version Independent ID: 66c9e386-40f0-cbf8-a9c6-91e20c968049
* Content: [Use your free Azure Active Directory subscription in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-your-free-azure-ad-subscription-in-office-365)
* Content Source: [SecurityCompliance/use-your-free-azure-ad-subscription-in-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-your-free-azure-ad-subscription-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@byteben Thanks for the heads up. The team who writes O365 admin center help content is working on a plan to cutover to the new M365 name, screenshots, etc for all help topics. Updating this topic will snap to that plan.
