### ISSUE TITLE
Audited activities are missing from documentation

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/OfficeDocs-o365seccomp#130]
Audited activities: "Kaizala" and "Microsoft Workplace analytics" appear to be new activiteis, are missing in documentation, but visible in audit search menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center#feedback)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@scottsa-msft Thank you for this feedback

We appricate you pointing this information out to us. I will get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/132
