### ISSUE TITLE
Audited activities are missing from documentation

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/OfficeDocs-o365seccomp#132]
Audited activities: "Kaizala" and "Microsoft Workplace analytics" appear to be new activiteis, are missing in documentation, but visible in audit search menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance?redirectSourcePath=%252fen-us%252farticle%252fsearch-the-audit-log-in-the-office-365-security-compliance-center-0d4d0f35-390b-4518-800e-0c7ec95e946c#audited-activities)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@scottsa-msft Thank you for this feedback

We appricate you pointing this out. I will get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by timmytandian** [comment]
Is it possible to put the table (Friendly Name, Operation, Description) of audited activities for Microsoft Stream, Microsoft Flow, Power BI, and eDiscovery on this page as well? Reasons:
1. For easier access
2. To standardize documentation format. For example, the list of Operation is missing for Microsoft Stream and Microsoft Flow (in another page). I cannot use Search-UnifiedAuditLog from PowerShell to audit Stream and Flow.

**Comment by markjjo** [comment]
@timmytandian The reason we link off to the specific service page for these sevices is because these product groups document their auditing events and are the authority on the activities. While this may not be ideal for the reasons you cite, the hope is that linking off will provide the "latest and greatest" and most up-to-date descriptions.

**Comment by markjjo** [comment]
@scottsa-msft We have published descriptions for workplace analytics activities; see https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#microsoft-workplace-analytics-activities - I will follow up with Kaizala product group; when you first posted this issue, they weren't ready to document the activities.
