### ISSUE TITLE
Retention Period for Unified Audit and Exchange Audit

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-o365seccomp#133]
Hi, there is stated that logs are stored for 90 days and 365 days based on plan assigned for Enterprise plans. What about Business plans? Like Microsoft 365 Business. And Exchange Online has for auditing separate AuditLogAgeLimit parameter when turning on auditing, and there is no stated limit in this. So Exchange can retain for example for 5 years, even if the Unified Audit store only 1 year. Does someone have storage/performance impacts metrics for this? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance?WT.mc_id=twitter)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@Kazzan Thank you for this feedback

I don't have the metrics for this. Let me get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by colinrippeyfinarne** [comment]
I'd also like to know what the retention periods are for other plans such as A1, A3, A5 etc.. Is there any reference with the complete set of audit log retention periods for all licenses?

**Comment by AndreaBarr** [comment]
@Kazzan We have investigated the document and it is correct. I am closing this issue at this time.

**Comment by Kazzan** [comment]
Hi @AndreaBarr, sorry, but how it can be correct if it does not contain a full description of all plans with access to "Search & Investigation" section in "Protection & Compliance Center"? Just follow my or customer path.

Microsoft 365 Business Service Description contain a link to a description of "[Security & Compliance Center](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)".

Which says just plain "Yes" for all plans for "Search & Investigation" without more detail. And also contain a broken link to Office Support Page.

And this one commented article is only one about retention periods inside this functionality does not state the retention periods for such plans.

I read also Product Usage Terms and they say "Microsoft logs, or enables Customer to log, access and use of information systems containing Customer Data, registering the access ID, time, authorization granted or denied, and relevant activity." It does not state how long and how to enable. For this reason, this document should be updated by a proper team.

Thanks for consideration.

**Comment by AndreaBarr** [comment]
@Kazzan I was told that it was all correct by the article owner. Let me have someone dig into this for us. 

@markjjo Could you please help with this issue?

**Comment by markjjo** [comment]
@Kazzan Closing this issue logged against the Office 365 audit logging, as I answered your original questions offline; to recap, *1 and *3 subscriptions provide a 90-day unified audit record retention; *5 provide 365 days, but this new limit is in Preview. Exchange mailbox auditing records can be retained for longer than 90 days, but for anything longer than the duration supported by the organization's O365 subscription will have to be search for by searching the mailbox audit logs using the Search-MailboxAuditLog cmdlet in EXO. Also as per performance, the only thing I can offer is that mailbox audit records are stored in the Audits subfolder in the Recoverable Items folder; EXO has a folder limit of 3 million items. It's possible that longer audit log retention periods would result in exceeding this limit. Hope this helps.
