### ISSUE TITLE
On by default

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-o365seccomp#134]
Folks, according to the Roadmap, the update to enable mailbox auditing in O365 by default (ID 32224) has been rolled out. I can certainly update the article to reflect that on my own, but figured you might want to check internally whether the rollout has actually completed...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by rpil17** [comment]
We are still in hybrid mode and migration is in process. Do I have to run these cmdlets everytime an mailbox is migrated to enable auditing?

**Comment by xNiklasJern** [comment]
Any update on this?

**Comment by xNiklasJern** [comment]
@AndreaBarr it says in the first section of this article :

> By default, mailbox auditing in Office 365 isn't turned on.

**Comment by markjjo** [comment]
@xNiklasJern The engineering team is still in the process of rolling out this feature for tenants; there have been a few issues to contend with. When the roll out is 100% complete, we will update this topic with new info about managing default mailbox audit logging. Until then, we suggest enabling auditing on a per mailbox basis (as per the current topic) and then searching for corresponding events in the Office 365 audit log. I will update this issue when the auditing topic has been updated with the new info about default mailbox auditing.

**Comment by urbi129** [comment]
Hello,

 Currently audit log search is disabled in our tenant. Could you advise if enabling it will have any cost impact?

**Comment by markjjo** [comment]
@urbi129 I assume you are referring to enable the Office 365 audit log search (not mailbox auditing). In either case, no cost impacts, monetary or performance-wise. If you have the ability to enable audit log search, here's how: https://docs.microsoft.com/en-us/office365/securitycompliance/turn-audit-log-search-on-or-off
