### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by stemy-msft** [MicrosoftDocs/OfficeDocs-o365seccomp#138]
Change: "If your Office 365 organization has and E5 subscription"
To: "If your Office 365 organization has an E5 subscription"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f686e2-5490-094c-179d-de263070693c
* Version Independent ID: 854769aa-3d8a-ed63-2f36-0da770ef4767
* Content: [Manage legal investigations in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/manage-legal-investigations?redirectSourcePath=%252fen-us%252farticle%252fmanage-legal-investigations-in-office-365-2e5fbe9f-ee4d-4178-8ff8-4356bc1b168e#analyze-case-data-using-office-365-advanced-ediscovery)
* Content Source: [SecurityCompliance/manage-legal-investigations.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/manage-legal-investigations.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@stemy-msft fixed; change will be published live within in hour. thanks for the heads up.
