### ISSUE TITLE
5321.MailFrom not respected if added to safe senders

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#14]
It appears that if the 5321.MailFrom is added alone to safe senders in Outlook, this is not respected. Suggest this should be added to article for clarity.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0fc37b9-c1fc-146d-eee7-8d15e70f1408
* Version Independent ID: 5dd2357f-c1fd-76b1-aa8e-cafa98e21d66
* Content: [Manage safe sender lists for bulk mailers](https://docs.microsoft.com/en-gb/office365/SecurityCompliance/manage-safe-sender-lists-for-bulk-mailers)
* Content Source: [SecurityCompliance/manage-safe-sender-lists-for-bulk-mailers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/manage-safe-sender-lists-for-bulk-mailers.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Thank you for the feedback, @aldoug. We are looking into this.

**Comment by AndreaBarr** [comment]
@aldoug Thank you for this feedback

I will get this to the O365seccomp team for investigation and updating. 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
