### ISSUE TITLE
Better context for uploading password lists

### ISSUE THREAD

**Issue by tkirktx** [MicrosoftDocs/OfficeDocs-o365seccomp#142]
When you upload a list, the only instructions in the app is something like "only one password per line." No details about supported file types, commas, no commas, etc. Each time I upload a document for a brute force attack, I receive an error before being able to perform it. It then will let me send the attack, but I've tested lists to see if they are working and they don't seem to work, even on dummy accounts I'm using to verify the process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator#brute-force-password-attack)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by tkirktx** [comment]
Also, I'll add that the list works fine when adding each password manually, but that's too laborious if I want to use a comprehensive list.

**Comment by AndreaBarr** [comment]
@tkirktx Thank you for this feedback

I will get this over the o365seccomp team. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by trfleming3745** [comment]
I am with @tkirktx, what format should the uploaded file be. An example file would for us to download and look at would be ideal, then we just match that. 

ALSO, if we could use regular expression in the password field that would be amazing. It then tested every combination from the regex against the users.

**Comment by denisebmsft** [comment]
@trfleming and @tkirktx, thank you both for the good questions and feedback. I'm looking into this and will follow up soon.

**Comment by denisebmsft** [comment]
@tkirktx, @trfleming3745, and @AndreaBarr, thank you for the feedback. I've updated this article to include information about the passwords list. It's a text file that can't exceed 10 MB. You should have one password per line, and make sure to have a hard return after the last password in the list. 

As far as the REGEX idea, that has been passed along to the product team (they said thanks!). I am closing this issue for now.
