### ISSUE TITLE
Sensitivity Labels are not displaying for end users

### ISSUE THREAD

**Issue by NavaneethaDev** [MicrosoftDocs/OfficeDocs-o365seccomp#143]
We have created sensitivity labels and published. We have waited for 1 day, but still it is not displaying the end users. Please let me know how long does it take to display to end users after publish the labels. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01a3978-dbe9-0507-49d2-9e57ec52d9a1
* Version Independent ID: a617379c-9182-eed2-5cd0-c05b36a6e4cb
* Content: [Overview of sensitivity labels](https://docs.microsoft.com/en-us/office365/securitycompliance/sensitivity-labels)
* Content Source: [SecurityCompliance/sensitivity-labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/sensitivity-labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@NavaneethaDev Thank you for this feedback

I am not sure how long it takes to reflect the labels after they are published. Let me get this inquiry over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by NavaneethaDev** [comment]
@AndreaBarr Thanks for your response and investigation over to the O365seccomp team. 

I would to know can we "Sensitivity Labels" in production environment or it is currently work in progress by Microsoft? Please let me know as we are planning to rolling out this feature in our production environment. Thanks for your response.

**Comment by stephow-MSFT** [comment]
The article says sensitivity labels take less than 1 hour to be deployed.

Are you enrolled in the Office Insider program? Note that support for sensitivity labels in Office apps is still forthcoming. To view the current availability for specific apps and platforms, see 

https://support.office.com/en-us/article/apply-sensitivity-labels-to-your-documents-and-email-within-office-2f96e7cd-d5a4-403b-8bd7-4cc636bae0f9?ad=US&ui=en-US&rs=en-US#bkmk_whereavailable

**Comment by stephow-MSFT** [comment]
The article clearly says sensitivity labels are available in one hour or less. 

As the linked article describes, if you're not enrolled in the Office Insider program, you won't see sensitivity labels in Office apps.
