### ISSUE TITLE
Rename "Content Filter" to "Spam Filter". Already posted by another user 2 months back

### ISSUE THREAD

**Issue by vishalgd** [MicrosoftDocs/OfficeDocs-o365seccomp#144]
[Enter feedback here]

Rename "Content Filter" to "Spam Filter". Already posted by another user 2 months back.

Wasted my many hours from last 2 days finding the "content filter" option in O365

Why it has not been updated when another user (ticket #40 by "rpodric" user) has reported the same critical improvement 2 months back.

Also the issue posted was closed after 2 weeks and the document is still the same. This issue should be open right as the incorrect data is present in document which wastes a lot of time of all users.

![image](https://user-images.githubusercontent.com/44430168/47498694-a247ed80-d87b-11e8-8d93-f6828e9113a9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8252ddfb-8d51-29d8-0e8a-01c70c07db45
* Version Independent ID: ddc36cea-faf5-78b0-5542-e4ef41692083
* Content: [Configure end-user spam notifications in Exchange Online](https://docs.microsoft.com/en-us/office365/SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online)
* Content Source: [SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@vishalgd Thank you for this feedback

We have changed our process since that ticket was created. I agree we need to have this looked into. Let me get this over to the o365seccomp team so we can get this change investigated. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@vishalgd thank you for the feedback, and @AndreaBarr thank you for your help. We have fixed this. Please let us know if anything else is needed.

**Comment by vishalgd** [comment]
Thanks

**Comment by vishalgd** [comment]
Thanks team

Thanks & Regards,
Vishal Govind Dewane
Head - Systems & Networks | Dusane Infotech India Private Limited
Email ID - vishald@dusaneinfotech.com<mailto:vishald@dusaneinfotech.com> | http://www.dusaneinfotech.com<http://www.dusaneinfotech.com/>
