### ISSUE TITLE
REGEX Support for Brute Force

### ISSUE THREAD

**Issue by trfleming3745** [MicrosoftDocs/OfficeDocs-o365seccomp#145]
When it comes to the Brute Force attack option, it would be amazing if we could put in a REGEX expression that used every generated string and ran it against someone's account. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator#brute-force-password-attack)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AndreaBarr** [comment]
@trfleming3745 Thank you for this suggestion. 

I will get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@trfleming3745 I passed your suggestion along to the product team. They appreciate your feedback and are looking into this. I'm going to close this issue for now, but know that your feedback did get through.
