### ISSUE TITLE
DLP Policies based on sensitivity labels

### ISSUE THREAD

**Issue by franciso** [MicrosoftDocs/OfficeDocs-o365seccomp#146]
It is not very clear if both type of labels (retention and sensitivity) can be used with DLP policies. Once in the interface of the DLP rules, only the retention labels show up but the UI shows "labels" without making much distinction between both types.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af67a18-fa30-fcb7-b5de-c67c0ecf0754
* Version Independent ID: a30ba5ec-9e74-62fc-8896-837696e3098c
* Content: [Overview of data loss prevention policies](https://docs.microsoft.com/en-ca/Office365/SecurityCompliance/data-loss-prevention-policies#using-a-label-as-a-condition-in-a-dlp-policy)
* Content Source: [SecurityCompliance/data-loss-prevention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/data-loss-prevention-policies.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@franciso Thank you for this feedback

Let me get this labels issue over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by stephow-MSFT** [comment]
I've updated the article with this -

Support for sensitivity labels is coming

Note that you can currently use only a retention label as a condition, not a sensitivity label. We're currently working on support for using a sensitivity label in this condition.
