### ISSUE TITLE
Slight change when applying this to GoDaddy DNS

### ISSUE THREAD

**Issue by hahntech** [MicrosoftDocs/OfficeDocs-o365seccomp#147]
When adding the CNAME records in GoDaddy it is required that you leave off the domain from the Host Name field. So instead of using: selector1._domainkey.mydomain.com you must use ONLY selector1._domainkey

Authoritative source: https://www.godaddy.com/community/Office-365-From-GoDaddy/Unable-to-add-CNAME-for-Office-365-DKIM/m-p/99689#M1006

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM to validate outbound email sent from your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dkim-to-validate-outbound-email)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@hahntech Thank you for this information. 

I am going to get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by New-Meadow** [comment]
The same would seem to apply to Network Solutions.

**Comment by electricblue81** [comment]
I hope this works this has been driving me insane!!!!

**Comment by KCCross** [comment]
Hi everyone! I'm now aware of this and have handed off testing for each ISP to the product team. I hope to have this resolved and the documentation updated as soon as humanly possible.

**Comment by Mike-Crowley** [comment]
@hahntech, this is a common user-interface approach to DNS. When you're on the screen to manage the domain, the domain name is implied. Be aware however, the domain name is appended when you save the configuration. Microsoft is providing accurate values here, but its up to the DNS administrator to know how their UI works.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@hahntech Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
