### ISSUE TITLE
Reviewer permissions

### ISSUE THREAD

**Issue by NikitaSkitsko** [MicrosoftDocs/OfficeDocs-o365seccomp#149]
If Reviewer role doesn't have a permission to view items returned from a Content Search, then it's not clear what's this role is intended for. I've just watched a video on Lynda.com, which states that reviewer has a permission to view search results. It seems something is missing in "Preview" and "Review" permissions description.

---
#### Dokumendi üksikasjad

⚠ *Ärge seda jaotist redigeerige. See on vajalik docs.microsoft.com-i ➟ GitHubi probleemide linkimiseks.*

* ID: cab39527-b636-35d8-43f7-88e8ad8e92e3
* Version Independent ID: f710f562-129e-8d15-54d2-46f8d61c828b
* Content: [Assign eDiscovery permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/et-ee/office365/securitycompliance/assign-ediscovery-permissions?redirectSourcePath=%252fet-EE%252farticle%252fassign-ediscovery-permissions-in-the-office-365-security-compliance-center-5b9a067b-9d2e-4aa5-bb33-99d8c0d0b5d7)
* Content Source: [SecurityCompliance/assign-ediscovery-permissions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/assign-ediscovery-permissions.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@NikitaSkitsko The primary purpose of the Review role is to let a user access case data in Office 365 Advanced eDiscovery. A user with this role can be added a member of an eDiscovery case in the Security & Compliance Center. Then that user can see and access the eDiscovery cases they are a member of. After they access the case in the Security & Compliance Center, they can click "Switch to Advanced eDiscovery" to access the case data in Advanced eDiscovery. The Review role doesn't give permissions to preview/view Content Search results in the Security & Compliance Center. I will update the topic to clarify this,

**Comment by markjjo** [comment]
Topic has been undated with more detailed info about the Review role: https://docs.microsoft.com/et-ee/office365/securitycompliance/assign-ediscovery-permissions?redirectSourcePath=%252fet-EE%252farticle%252fassign-ediscovery-permissions-in-the-office-365-security-compliance-center-5b9a067b-9d2e-4aa5-bb33-99d8c0d0b5d7#rbac-roles-related-to-ediscovery
