### ISSUE TITLE
EOP IP address ranges

### ISSUE THREAD

**Issue by RvdHout** [MicrosoftDocs/OfficeDocs-o365seccomp#15]
@JoeDavies-MSFT 

There is at (least) one fault in the complete list of EOP IP address ranges as of 7/2/2018.
https://docs.microsoft.com/nl-nl/office365/SecurityCompliance/eop/exchange-online-protection-ip-addresses

40.107.128.0/18 should be 40.107.128.0/17

**Comment by JoeDavies-MSFT** [comment]
@RvdHout This range has been removed in the latest English version of the document here: https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/exchange-online-protection-ip-addresses Your localized version of this article has not yet been updated for the 8/1 changes.
