### ISSUE TITLE
Report Message add-in doesn't exist

### ISSUE THREAD

**Issue by valentijnscholten** [MicrosoftDocs/OfficeDocs-o365seccomp#150]
Hi,

When following the link to get/enable the report message add-in, I am getting a "no such addon" error. 

Link: https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in?redirectSourcePath=%252farticle%252f4250c4bc-6102-420b-9e0a-a95064837676#get-the-report-message-add-in-for-yourself

When using the search function at https://appsource.microsoft.com/en-us/marketplace/apps?src=office&search=report%20message&page=1 there are no results for "Report message" or "reportmessage".
Nor are there results for "phishing", "junk", "report", "reporting", ...

Valentijn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62304805-117a-0e04-038b-a42a89e12162
* Version Independent ID: 7c12ba44-3c56-7607-7e63-84b0073a25df
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in?redirectSourcePath=%252farticle%252f4250c4bc-6102-420b-9e0a-a95064837676)
* Content Source: [SecurityCompliance/enable-the-report-message-add-in.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-the-report-message-add-in.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by valentijnscholten** [comment]
Looks like this link works (found via googling): https://appsource.microsoft.com/en-us/product/office/wa104381180

**Comment by AndreaBarr** [comment]
@valentijnscholten Thank you for pointing this out to us

I will get this link information over to the o356seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@valentijnscholten and @AndreaBarr thank you for the feedback and help. I've updated the article with a better link.
