### ISSUE TITLE
What does SKI mean?

### ISSUE THREAD

**Issue by rhymeswithmogul** [MicrosoftDocs/OfficeDocs-o365seccomp#151]
I received a message that failed SPF, DKIM, ADSP, and DMARC, and had an unknown spam filtering verdict of SKI, and it still got through Office 365.  What does SKI mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0c22e-ec20-d8dc-bbc5-cfbb9e98350e
* Version Independent ID: d9a1bac2-69ef-5fa7-23f1-417d7454c4cc
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-spam-message-headers)
* Content Source: [SecurityCompliance/anti-spam-message-headers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@rhymeswithmogul Thank you for your inquiry. 

I am not sure what SKI means. Let me get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by rroddy24** [comment]
It's listed in the article:
SFV:SKI
Similar to SFV:SKN, the message skipped filtering for another reason such as being intra-organizational email within a tenant.

**Comment by MSFTTracyP** [comment]
@rhymeswithmogul Be sure to report the whole header to make it easier for me and other community members to interpret the header. SKI usually means 'skipped' (as @rroddy24 reported). You can find that definition in a matrix right here: https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-spam-message-headers. If the header is something different, and not mentioned in the matrix, please let me know and reopen this thread!
