### ISSUE TITLE
Spam email

### ISSUE THREAD

**Issue by kramdenantivirus** [MicrosoftDocs/OfficeDocs-o365seccomp#153]
I get spam which I cannot block. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13dd34ae-60cf-db1d-0dbd-5b9bc8cdc6bf
* Version Independent ID: 5a430055-9b49-69c6-46f1-e55d0c06457d
* Content: [Report junk email and phishing scams in Outlook on the web ](https://docs.microsoft.com/en-us/office365/SecurityCompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop)
* Content Source: [SecurityCompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@kramdenantivirus Thank you for this feedback

I want to make sure you get the appropriate attention on this spam issue. I want to get you over to Support since they have more resources to help dig in and see how to resolve this.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by kramdenantivirus** [comment]
Videos are a problem for me. I need text. And I am about to leave for the day. Can I forward the spam email to someone? And is there something I need to do so they can see the details?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by kramdenantivirus** [comment]
I was told by the tech support person to use this number: 1446939302

The directions for blocking do not work because there is no “from” email address. I just noticed it says it is from a “trusted sender” and is of “high importance”.

I am through for the day and do not intend to stay on the computer. I will follow your directions tomorrow. If I am doing this wrong I am sorry but this is all I know how to do.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by kramdenantivirus** [comment]
I think I solved this problem. Let me see if I can find it.

**Comment by kramdenantivirus** [comment]
Found it.

https://answers.microsoft.com/en-us/edge/forum/all/please-update-your-credentials/71e95624-401b-44d2-a86e-e674fdcc1704

**Comment by scanum** [comment]
@kramdenantivirus Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
