### ISSUE TITLE
Please clarify the difference between impersonated user & impersonated domain

### ISSUE THREAD

**Issue by chk1982** [MicrosoftDocs/OfficeDocs-o365seccomp#155]
While setting up policy I am confused about the Actions tab. What is the difference between an impersonated user and an impersonated domain? Perhaps my understanding is false, but I thought that SPF/DKIM authenticated email based on the mail domain, so why is there an option for impersonated user? What do you mean by "user"? Please add more documentation and use case for these two options in the Actions section. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies)
* Content Source: [SecurityCompliance/set-up-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-anti-phishing-policies.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@chk1982 Thank you for your feedback

I will the request for further documentation to the 0365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
This is documented in the section, _Anti-phishing policy to protect a user and a domain_, in the article [Set up Office 365 ATP anti-phishing and anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies). Domains to protect, works based on the domain name, while users to protect takes a different tact and protects high-visibility / high-profile target emails. I've pasted the link so that you could read more.

I hope it helps. Thanks for your question!

**Comment by chk1982** [comment]
Hello. I am not satisfied with this answer. The topic you describe is very
clear to me and is made very clear in the article you linked. However, the
topic I am describing is a completely separate topic and section of the
policy configuration which requires clarification. Mail is always
spoofed/impersonated using domain names. Domains and DNS are how mail
routes throughout the internet...not via username. But, all SMTP addresses
require a username. What I don't understand is why there are separate
action setting for both spoofed/impersonated users and domains on this
page. You cannot separate the user from the domain from perspective of a
source server, therefore Microsoft must have some proprietary logic behind
this technology which has not been described in full detail. I am asking
for clarification on what Microsoft's perceived difference is between an
impersonated domain and an impersonated user and the implications here. If
badguy@contos0.com is a spoof message of goodguy@contoso.com, it appears to
me that in all possible cases both a user (goodguy) and a domain (
contoso.com) have been impersonated. Why two action settings? Please
correct me and explain. Thanks.

**Comment by aldoug** [comment]
User impersonation will look for display name impersonation in addition to SMTP address
