### ISSUE TITLE
Timing information

### ISSUE THREAD

**Issue by Mindzweeper** [MicrosoftDocs/OfficeDocs-o365seccomp#158]
I think many people reading this article would want to know how quickly an eDiscovery hold takes effect once created.  Is this instant, or do I need to wait some time?  Is the delay different for Exchange vs. SharePoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98d1f72-c381-3056-c1c4-7e54a9ab05af
* Version Independent ID: f5771dac-209a-433b-1967-a6ef3118eec6
* Content: [eDiscovery cases in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/ediscovery-cases?redirectSourcePath=%252farticle%252fediscovery-cases-in-the-office-365-security-compliance-center-8dd335ab-29d0-41c3-8dd8-9f7c7481e60c#step-4-place-content-locations-on-hold)
* Content Source: [SecurityCompliance/ediscovery-cases.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ediscovery-cases.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Mindzweeper It takes up to 24 hours for the hold to take affect, for mailboxes and sites. The article has been updated with this info: https://docs.microsoft.com/en-us/office365/securitycompliance/ediscovery-cases#step-4-place-content-locations-on-hold
