### ISSUE TITLE
Not listed

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-o365seccomp#159]
Global Admin account is currently assigned an O365 Enterprise E5 license, has all permissions, and spoof protection is enabled - yet the insights tile above isn't visible anywhere on Threat Management &gt; Dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4996610-62bb-26d8-e3f1-1372a1ceeff0
* Version Independent ID: 4e2ca21b-1f0c-78fd-525a-a7d88842f6ce
* Content: [Walkthrough spoof intelligence insight](https://docs.microsoft.com/en-us/office365/securitycompliance/walkthrough-spoof-intelligence-insight)
* Content Source: [SecurityCompliance/walkthrough-spoof-intelligence-insight.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/walkthrough-spoof-intelligence-insight.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@pyoungberg Thank you for this feedback

I am not sure why it's not listed. Let me get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@pyoungberg thank you for letting us know that support was able to resolve this. I'm going to close this issue now, but please let us know if any other content updates are needed. We appreciate your feedback.
