### ISSUE TITLE
Moved to Services and Addins

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-o365seccomp#160]
O365 has moved the location for deploying this feature to O365 Admin &gt; Settings &gt; Services and Addins &gt; Deploy Addin button

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62304805-117a-0e04-038b-a42a89e12162
* Version Independent ID: 7c12ba44-3c56-7607-7e63-84b0073a25df
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in?redirectSourcePath=%252farticle%252f4250c4bc-6102-420b-9e0a-a95064837676#get-and-enable-the-report-message-add-in-for-your-organization)
* Content Source: [SecurityCompliance/enable-the-report-message-add-in.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-the-report-message-add-in.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AndreaBarr** [comment]
@pyoungberg Thank you for pointing this out

I will get this updated location path over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@pyoungberg thank you for the feedback. I've updated the article and you should see the changes live within minutes.
