### ISSUE TITLE
Confusing "UNRESOLVED_TOKEN_VAL(exMCSS)" in the middle of a sentence

### ISSUE THREAD

**Issue by tambry** [MicrosoftDocs/OfficeDocs-o365seccomp#161]
Seems to be a copy-paste error or the like. It makes no sense to me in the given context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0615d38b-7ed4-1cd6-c775-450ee84b479e
* Version Independent ID: 3ba5ff6f-5361-7286-d369-b3563495820c
* Content: [Support for anonymous inbound email messages over IPv6](https://docs.microsoft.com/en-us/office365/SecurityCompliance/support-for-anonymous-inbound-email-messages-over-ipv6#feedback)
* Content Source: [SecurityCompliance/support-for-anonymous-inbound-email-messages-over-ipv6.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/support-for-anonymous-inbound-email-messages-over-ipv6.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by chrisda** [comment]
@tambry I fixed this.
