### ISSUE TITLE
 On average, messages are retried every 5 minutes.

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-o365seccomp#162]
This statement is incorrect.
How we do it in EXO is:
The general basics are: The first few deferrals are 15 minutes or less, with subsequent retries (over the next half dozen or so) increasing the interval over multiple retries to a max of 60 minutes. The interval duration expansion is dynamic, taking into consideration multiple variables like queue sizes, internal message priority, and other things, but basically it's 15 minutes (or less) to start, then expanding from there over the next few hours to 60 mins max. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afba520e-06bd-30d9-3bd0-0117e343d249
* Version Independent ID: 2a2cbdb9-5a6f-474e-624f-e83708c9f021
* Content: [EOP queued, deferred, and bounced messages FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/eop/eop-queued-deferred-and-bounced-messages-faq)
* Content Source: [SecurityCompliance/eop/eop-queued-deferred-and-bounced-messages-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/eop-queued-deferred-and-bounced-messages-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@JeroenDronkers Thank you for pointing this out 

I will get this information about retiring messages to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
Hi @JeroenDronkers! Thanks for your update. I'll be moving it into the document now, and I do hope it makes things easier on our customers!
