### ISSUE TITLE
Great solution

### ISSUE THREAD

**Issue by petermcm** [MicrosoftDocs/OfficeDocs-o365seccomp#164]
Clear, Concise and Works 10/10

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63192844-fbfe-bd5a-45b7-84ac6c1bbb2c
* Version Independent ID: a02659bc-0cfd-e145-8dd4-6c55877e4ff3
* Content: [Use the delist portal to remove yourself from the Office 365 blocked senders list](https://docs.microsoft.com/en-au/office365/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis)
* Content Source: [SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@petermcm Thank you we try to be clear and concise.
