### ISSUE TITLE
Which plans include Office 365 Data Loss Prevention? Please include!

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-o365seccomp#165]
A3? E3? A5?  There's no clue!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af67a18-fa30-fcb7-b5de-c67c0ecf0754
* Version Independent ID: a30ba5ec-9e74-62fc-8896-837696e3098c
* Content: [Overview of data loss prevention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/data-loss-prevention-policies)
* Content Source: [SecurityCompliance/data-loss-prevention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/data-loss-prevention-policies.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by RebekkaAalbers** [comment]
Check this article:
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#office-365-security--compliance-center-features

**Comment by stephow-MSFT** [comment]
Yes this is the best link for plans info -

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#office-365-security--compliance-center-features
