### ISSUE TITLE
Licensing for auto-apply

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-o365seccomp#169]
So, do we have any document that specifies who needs to be assigned an E5 license, and how many, for auto-apply to work? Do they even need to be assigned, as this is a "server-side" functionality? And if no assignment is needed, is there a minimum number of licenses needed? Really any information you can add to clarify on how this is supposed to work...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@michevnew Thank you for this inquiry

I am not sure about the licences for auto-apply. Let me get this over to the o365seccomp team for investigatoin. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by stephow-MSFT** [comment]
Article updated with this info -

 Note
The capability to apply labels automatically requires an Office 365 Enterprise E5 license for each user who has permissions to edit content that's been automatically labeled in a site or mailbox. Users who simply have read-only access do not require a license.
