### ISSUE TITLE
Japanese title is not displayed properly.

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/OfficeDocs-o365seccomp#173]
[フィードバックをこちらに入力してください]
Japanese title is not displayed properly.
It would be appreciated if you could put the proper title in Japanese version.

Current

&

Expected
監査ログを検索する

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [&](https://docs.microsoft.com/ja-jp/office365/securitycompliance/search-the-audit-log-in-security-and-compliance?redirectSource)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@AkikoTsukahara Thank you for pointing this out

I will get this title issue over to the o365seccomp team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@AkikoTsukahara our localization team is taking care of this. They say the main issue is fixed and they are going to take care of the extra &. Thank you for letting us know about this!
