### ISSUE TITLE
Members of "Security Reader" cannot access DLP Incident Report details 

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-o365seccomp#177]
Added a user to the "Security Reader" role; they can access Security and Compliance, and view the "DLP Incident Report" part, but when they click "View details table", it fails with...

Request: /api/Report/GetReportDetailData?reportId=DlpIncidentReport&dataSourceId=DlpIncidentDetailReport
Status code: 500
Exception: Microsoft.Exchange.PswsClient.PswsException
Diagnostic information: {Version:16.00.2696.005,Environment:WEUPROD,DeploymentId:463ea13f2476437a9b3657e5546b4819,InstanceId:WebRole_IN_3,SID:c022c252-111f-487b-9381-d3771b3f15d7,CID:66858665-d0a1-45ff-b4ce-a1aadd63a377}
Time: 2018-11-13T15:41:08.3915061Z

Does "Note" *also* apply to the "Security Reader" role?  Does the documentation need updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by anwarmahmood1** [comment]
When you click "View details table", it shows "Client Error" "You don't have access to DLP incident Data."  When you expand the "Show details" control, it shows the full information in my first message.

**Comment by anwarmahmood1** [comment]
strange! the account I added to Security Reader appears in "View-Only Organization Management" role in Exchange Online, but not the "Security Reader" role.

**Comment by AndreaBarr** [comment]
@anwarmahmood1 Thank you for pointing this out. 

I will get this information over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by stephow-MSFT** [comment]
For perms needed to view DLP reports, see 

https://docs.microsoft.com/en-us/office365/securitycompliance/view-the-dlp-reports#permissions-for-dlp-reportshttps://docs.microsoft.com/en-us/office365/securitycompliance/view-the-dlp-reports#permissions-for-dlp-reports
