### ISSUE TITLE
Malware Detection Response Options are different

### ISSUE THREAD

**Issue by sairao77** [MicrosoftDocs/OfficeDocs-o365seccomp#179]
Can the Malware Detection Response Options be updated, it now by default quarantines the message and the option it gives now to configure is whether notify the end-user or not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21a8303e-b3fe-70a3-f1a2-3dc4be912e73
* Version Independent ID: 702b9f1c-4f07-eb61-7a0d-82677de4fd9c
* Content: [Configure anti-malware policies](https://docs.microsoft.com/en-us/office365/SecurityCompliance/configure-anti-malware-policies)
* Content Source: [SecurityCompliance/configure-anti-malware-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-anti-malware-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@sairao77 Thank you for pointing this out

I will get this update about the Malware Detection Responses to the o365seccomp team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
I'm looking into this right now. Thanks for the feedback!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by aldoug** [comment]
Still need to get this updated

**Comment by lightupdifire** [comment]
Hello,
Confirmed, policy settings missing some options that are described in this article.

**Comment by scanum** [comment]
@MSFTTracyP Hi Tracy, any updates on this? Thanks!

**Comment by chrisda** [comment]
OK I fixed this and did other massive updates to the topic to reflect reality.

Thanks for the feedback.
