### ISSUE TITLE
Link "View or Edit Managed Domains in EOP" is broken

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/OfficeDocs-o365seccomp#18]
The link goes to "Exchange Online Protection overview". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e9890c1-2a44-ca44-7a19-3cc239c49c18
* Version Independent ID: 3ca13874-1321-9332-a1ea-c49a6806f471
* Content: [Mail flow in EOP](https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/mail-flow-in-eop)
* Content Source: [SecurityCompliance/eop/mail-flow-in-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/mail-flow-in-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@dkotars, thank you so much for letting us know about this. We have fixed the link.
