### ISSUE TITLE
Initial Domain

### ISSUE THREAD

**Issue by susiecallaw** [MicrosoftDocs/OfficeDocs-o365seccomp#180]
Section re Initial Domain seems overcomplicated 'initialDomain is the domain that you used when you signed up for Office 365. For information about determining your initial domain, see Domains FAQ'. 
This can be found by going to Home &gt; Domains and will be the domain ending 'onmicrosoft.com' 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM to validate outbound email sent from your custom domain in Office 365](https://docs.microsoft.com/en-gb/office365/SecurityCompliance/use-dkim-to-validate-outbound-email)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
Unfortunately, those instructions don't work for all sovereignties and the UI is highly likely to change. I'm not including that UI content in this piece for those reasons. I realize it appears overly complex but it is accurate and will stay accurate for those reasons. However, you make an excellent point about the domain always ending in onmicrosoft.com. I have amended the doc to include that. Thanks!
