### ISSUE TITLE
Only 2 actions available: spam folder or Quarantine

### ISSUE THREAD

**Issue by DawidKoziol** [MicrosoftDocs/OfficeDocs-o365seccomp#182]
According to documentation the actions available for policy should be: Quarantine message, Redirect message to another email address, Move message to the recipients' Junk email folder, Deliver the message and add other addresses to the Bcc line, Don't apply any action, Turn on phishing protection tips
but we have only 2: Quarantine message and Move message to the recipients' Junk email folder.
Is that correct? We have E3 plan
Link: https://docs.microsoft.com/pl-pl/office365/securitycompliance/set-up-anti-phishing-policies

**Comment by AndreaBarr** [comment]
@DawidKoziol Thank you for your inquiry

It is possible that those options are being rolled out in our ring rollout system and you haven't recieved them yet. To double check on that contact Support and they can help determain if these options should be seen in your inviroment or if it's coming soon. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
