### ISSUE TITLE
Typo in the second paragraph - SFV:NSPM

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftDocs/OfficeDocs-o365seccomp#187]
As far as i know and documented the Header SFV:NSPM should say it's NOT spam.. so the first paragraph is wrong. as it should say SFV:SPM states its spam.
Reference: https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-spam-message-headers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b6674e7-d943-db79-4cca-410299a36837
* Version Independent ID: c2da9b51-7a0c-7e4e-a932-5d9fb241ffca
* Content: [How to prevent real email from being marked as spam in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/prevent-email-from-being-marked-as-spam?redirectSourcePath=%252farticle%252fhow-to-prevent-real-email-from-being-marked-as-spam-in-office-365-34823bbc-a3e3-4949-ba42-97c73997eeed)
* Content Source: [SecurityCompliance/prevent-email-from-being-marked-as-spam.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@chwilfing Thank you for pointing this out

I will get this typo information over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@chwilfing Thank you for reaching out and helping improve MS Docs.  I've just checked the article and it seems like it has been rectified in the interim.  Please could you let me know if it's reflecting correctly on your side as well. Thank you.

**Comment by scanum** [comment]
@chwilfing Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
