### ISSUE TITLE
Availability Key

### ISSUE THREAD

**Issue by dwedelman** [MicrosoftDocs/OfficeDocs-o365seccomp#190]
Is there a different availability key for each DEP? or for each Enterprise account? Or is there one that is used globally?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f99b78-95e3-a7e2-35df-97b0d5d245e9
* Version Independent ID: aad3a634-7428-3eb0-ab69-a68f04431514
* Content: [Service encryption with Customer Key for Office 365 FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/service-encryption-with-customer-key-faq)
* Content Source: [SecurityCompliance/service-encryption-with-customer-key-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/service-encryption-with-customer-key-faq.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@dwedelman Thank you for this inquiry

I am not sure on the answer for the DEP availability keys. Let me get this over tot he o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
For the Exchange version of the Customer Key feature: there is a different availability key per DEP. I hope that helps answer your question!
