### ISSUE TITLE
Note and Tips are shown as plain text

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/OfficeDocs-o365seccomp#191]
Note and Tips are shown as plain text.

![image](https://user-images.githubusercontent.com/6519947/48742358-fd65d800-eca1-11e8-936c-156e838a742f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1851022e-16b2-345d-7b88-82576f7fe41d
* Version Independent ID: ba06c46e-fece-e686-b6aa-8b33d31b246f
* Content: [Advanced spam filtering  options](https://docs.microsoft.com/en-us/office365/securitycompliance/advanced-spam-filtering-asf-options)
* Content Source: [SecurityCompliance/advanced-spam-filtering-asf-options.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/advanced-spam-filtering-asf-options.md)

* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@hishikitetsuya thank you for pointing this out

I will get this formatting issue over to the o365seccomp team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by KCCross** [comment]
Thanks for the catch. These errors (and others like them) have been fixed in the content and republished.
