### ISSUE TITLE
How to discover OneNote content?

### ISSUE THREAD

**Issue by nickjrobinson** [MicrosoftDocs/OfficeDocs-o365seccomp#192]
Customer asked me where we document if OneNote is discoverable in Office 365 eDiscovery. Didn't see that in the article, can we add that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f686e2-5490-094c-179d-de263070693c
* Version Independent ID: 854769aa-3d8a-ed63-2f36-0da770ef4767
* Content: [Manage legal investigations in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/manage-legal-investigations)
* Content Source: [SecurityCompliance/manage-legal-investigations.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/manage-legal-investigations.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
Please see: https://docs.microsoft.com/en-us/office365/securitycompliance/keyword-queries-and-search-conditions#search-conditions
