### ISSUE TITLE
Licensing requirements for SPO?

### ISSUE THREAD

**Issue by jordi-j** [MicrosoftDocs/OfficeDocs-o365seccomp#194]
Hi,
licensing requirements for SharePoint Online do not appear at all, and those for Exchange are only lightly mentioned. Perhaps a specific section about licensing will be necessary. It seems licensing requirements for retention are not easy to find (see https://techcommunity.microsoft.com/t5/Security-Privacy-Compliance/License-requirements-for-retention-policy-OneDrive-for-Business/td-p/205639) so any improvement is welcome. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@jordi-j Thank you for this feedback

I will get this request for the licensing requirements over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by stephow-MSFT** [comment]
You can licensing info for the Security & Compliance Center here -

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center
