### ISSUE TITLE
Please explain SCL ratings 2,3,4

### ISSUE THREAD

**Issue by Houndsong** [MicrosoftDocs/OfficeDocs-o365seccomp#196]
"SCL ratings of 2,3,4... are not set by the service." Does that mean there is no such rating, and thus no description or interpretation exists? On the other hand, "SCL ratings of … 7, and 8 are not set by the service;"  however, an interpretation and default action are provided for them.  Is it possible that ratings in these ranges exist but nothing is done about them because there is no default action (in absence of a transport rule setting SCL of 7,8, or 9?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efba1d2-3632-553d-435e-9a1c90839480
* Version Independent ID: 49853657-0d95-f438-25d4-d8026e542e14
* Content: [Spam confidence levels](https://docs.microsoft.com/en-us/office365/SecurityCompliance/spam-confidence-levels)
* Content Source: [SecurityCompliance/spam-confidence-levels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/spam-confidence-levels.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@Houndsong Thank you for this feedback

Robert just updated this article. Did his updates resolve your issue?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sub2d** [comment]
Still not answered. What does content filter do if transport rule sets SCL to 2,3,4? What will be behavior? Will it scan message again and adjust SCL score itself again?

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
