### ISSUE TITLE
Set up DKIM so that a third-party service can send, or spoof, email on behalf of your custom domain

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/OfficeDocs-o365seccomp#198]
This issue was created by @DrupalLT from https://github.com/MicrosoftDocs/feedback/issues/892

on https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dkim-to-validate-outbound-email#DKIMMultiDomain in article "Set up DKIM so that a third-party service can send, or spoof, email on behalf of your custom domain" is written "2. Contoso published the DKIM key to its DNS record." .
BUT HAW to make it for third-party domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM to validate outbound email sent from your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dkim-to-validate-outbound-email#set-up-dkim-so-that-a-third-party-service-can-send-or-spoof-email-on-behalf-of-your-custom-domain)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@Powerhelmsman Thank you for this feedback

I will get this inquiry over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by KCCross** [comment]
Hi @Powerhelmsman. I need to confirm a few things internally here, but the way I understand it is that the key itself is published by the originating domain to DNS. In this case, Contoso may also publish the copy it received or, the docs may be in error and what may actually be going on is that Contoso looks up the public key published by the originating domain in DNS upon receipt of the message. See https://blogs.msdn.microsoft.com/tzink/2013/04/26/how-to-set-up-your-dkim-records-if-you-are-outsourcing-some-or-all-of-your-email/ for more information while I investigate. In any case, you have no action to take as an administrator for this step to the best of my knowledge (right now). These steps should be taken care of for you.

**Comment by Powerhelmsman** [comment]
@DrupalLT Can you response KCCross since you are the one submitted the issue.

**Comment by Mike-Crowley** [comment]
@Powerhelmsman, this is a common user-interface approach to DNS. When you're on the screen to manage the domain, the domain name is implied. Be aware however, the domain name is appended when you save the configuration. Microsoft is providing accurate values here, but its up to the DNS administrator to know how their UI works.

**Comment by RyanEwen** [comment]
Hi - I am confused by this documentation as well. 

Say I have some-domain.com with Office 365 and I setup the 2 CNAME records and enable DKIM..

Do I then have to get and store the same key on my third-party sender's server so that they can sign the messages using the same key? Or do I get them to generate a key and add it to Office 365 to use? Or do both sign differently?

Trying to allow automated emails from our website to be signed.

**Comment by DrupalLT** [comment]
Thanks!

It seems to me, today all work OK.



ср, 13 мар. 2019 г. в 20:50, Ryan Ewen <notifications@github.com>:

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Powerhelmsman Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
