### ISSUE TITLE
Will Anti-Virus detection work on encrypted files?

### ISSUE THREAD

**Issue by gtageek** [MicrosoftDocs/OfficeDocs-o365seccomp#199]
If a user uploads (or syncs via the OneDrive for Business sync client) encrypted files to SharePoint Online or OneDrive for Business, will the anti-virus detect infections inside the encrypted files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce4ee6e0-64e4-cad9-5b20-60ce1914e3dc
* Version Independent ID: c647c66b-5a0d-f00f-99e4-f6cc2c76c1b2
* Content: [Virus detection in SharePoint Online](https://docs.microsoft.com/en-us/office365/securitycompliance/virus-detection-in-spo)
* Content Source: [SecurityCompliance/virus-detection-in-spo.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/virus-detection-in-spo.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@gtageek Thank you for this inquiry

I am not sure if the antivirus will detect things inside an encrypted file. Let me get this over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by deltasway** [comment]
my firm is performing an ODfB pilot and testing the antivirus function. we have uploaded some virus into our test environment and find one of virus can't be detected.
The virus name is Windows 10 Activator, it can be detected by most of the other antivirus software. We would like to know how antivirus scan is done during file upload, at rest & download, and if this windows activator virus can be detected by ODfB online.

**Comment by MSFTTracyP** [comment]
@gtageek OneDrive for Business files are encrypted in transit by a TLS stream, and encrypted at rest in the datacenter. Since all the certificates used for encryption are owned by Microsoft, in this case, files can be scanned on upload/sync, and download. If you encrypt your files with a 3rd party then, no, OneDrive for Business may not be able to decrypt and scan the files. Your 3rd party may well be doing that work. The files will still be encrypted across the TLS channel and in-place in the datacenter.

**Comment by MSFTTracyP** [comment]
@Deltasway - Sorry for the delay! That's good testing. Okay. So if you've read the thread, you know that I told @gtageek that OneDrive and OneDrive for Business files are encrypted in transit and at rest. In transit, they are encrypted by TLS on the connection, and, as with the encryption in the datacenters, the certificates are held by Microsoft (which means the encrypted files can be scanned on upload unless there is a 3rd party encryption on the files). What you seem to need is a diagram outlining the route that files take as they go across the encrypted connection and into the data center, which is here: 
![image](https://user-images.githubusercontent.com/33558605/51701768-07b89100-1fc7-11e9-836c-33ed9b96a390.png).

**Comment by MSFTTracyP** [comment]
If you get a blank page on that link, @deltasway, you can find this diagram by going to http://download.microsoft.com/. Use the Search magnifying glass tucked away at the top of the page and search for "How does OneDrive for Business synchronize files". You should get results that list [How does OneDrive for Business synchronize files?](https://www.microsoft.com/en-us/search?q=%22How+does+OneDrive+for+Business+synchronize+files%22)
