### ISSUE TITLE
Diagram should show Junk Email folder

### ISSUE THREAD

**Issue by moonman7** [MicrosoftDocs/OfficeDocs-o365seccomp#2]
The diagram is very useful.  
However, it seems like it should also show how EOP can be used to send email to the **_Junk Email_** folder in the Recipient mailbox.
For example, as an alternative to Quarantine.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 367b33ce-7559-a660-5bf2-64cdc50b605d
* Version Independent ID: 55366d4f-69cf-f500-9485-5e61e386a4f8
* Content: [Exchange Online Protection overview](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/eop/exchange-online-protection-overview)
* Content Source: [SecurityCompliance/eop/exchange-online-protection-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/exchange-online-protection-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@moonman7, thank you for the feedback. We are looking into this.

**Comment by robmazz** [comment]
@KCCross - opened bug to track. Please close this comment if already resolved.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
