### ISSUE TITLE
x-header text value missing from table

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#200]
The customer header for Bulk Mail is missing above. Should be "X-CustomSpam: Bulk Mail | Bulk Mail"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1851022e-16b2-345d-7b88-82576f7fe41d
* Version Independent ID: ba06c46e-fece-e686-b6aa-8b33d31b246f
* Content: [Advanced spam filtering  options](https://docs.microsoft.com/en-us/office365/SecurityCompliance/advanced-spam-filtering-asf-options)
* Content Source: [SecurityCompliance/advanced-spam-filtering-asf-options.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/advanced-spam-filtering-asf-options.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by aldoug** [comment]
Note, the header will still apply even though method to set it has changed

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
