### ISSUE TITLE
Users cannot view messages quarantined via Transport Rule

### ISSUE THREAD

**Issue by RichITPerson** [MicrosoftDocs/OfficeDocs-o365seccomp#203]
Users cannot view messages that are quarantined via Transport Rule.  It doesn't make sense because if we really didn't want a user to see a message quarantined by a Transport Rule, we could either redirect it to another mailbox or just delete it.  

We try to limit messages we get from 3rd party mailing services to just people who are listed as a sender from one of our domains and send the rest to Quarantine so we don't get junk mail from other customers of the 3rd party mailing service.  But, there are many valid services that also utilize these 3rd party mailing services, so they may have valid e-mails, thus the desire for a user to be able to see messages quarantined via Transport Rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e487b445-a3ef-ec1e-43b6-bd9f7afa3f62
* Version Independent ID: 34d5e5a4-4bdc-47bd-3638-bcf80ee935d6
* Content: [Find and release quarantined messages as a user in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/find-and-release-quarantined-messages-as-a-user)
* Content Source: [SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@RichITPerson Thank you for your feedback. 

I will get this inquiry over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
As this is the intended design, I passed this information up the chain for consideration. Thanks.
