### ISSUE TITLE
In addition, check this

### ISSUE THREAD

**Issue by gicronin** [MicrosoftDocs/OfficeDocs-o365seccomp#205]
We found when someones O365 account was compromised the hacker uploaded some files to OneDrive and created a Flow to send emails to the list inside one of these files. It was triggered by when a shared mailbox received an email. You should check OneDrive and flow for any recent changes not made by the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f5a81ec-6747-1bf6-cb92-612d26554e4b
* Version Independent ID: 851bec9d-104e-94e7-a0d8-b8d73b91576c
* Content: [Responding to a Compromised Email Account in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/responding-to-a-compromised-email-account)
* Content Source: [SecurityCompliance/responding-to-a-compromised-email-account.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/responding-to-a-compromised-email-account.md)
* Service: **o365-solutions**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by AndreaBarr** [comment]
@gicronin Thank you for this feedback

I will get this information over to the 0365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
