### ISSUE TITLE
https://blogs.msdn.microsoft.com/tzink/2014/08/25/different-levels-of-bulk-mail-filtering-in-office-365/

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#206]
This article is outdated and we really shouldn't point to blog posts. Probably better to refer to section in https://docs.microsoft.com/en-us/office365/SecurityCompliance/configure-your-spam-filter-policies

"Under Bulk email, you can select a threshold to treat bulk email as spam. This threshold is based on the bulk complaint level of the message. You can choose a threshold setting from 1 to 9, where 1 indicates most bulk email as spam, and 9 allows the most bulk email to be delivered. The service then performs the configured action, such as sending the message to the recipient's Junk Email folder. See Bulk Complaint Level values and What's the difference between junk email and bulk email? for more details".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b6674e7-d943-db79-4cca-410299a36837
* Version Independent ID: c2da9b51-7a0c-7e4e-a932-5d9fb241ffca
* Content: [How to prevent real email from being marked as spam in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/prevent-email-from-being-marked-as-spam)
* Content Source: [SecurityCompliance/prevent-email-from-being-marked-as-spam.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@aldoug Thank you for this feedback

I will get this request to update the article to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
Hi @aldoug, thanks for bringing this to my attention. I'll be looking into this document for update.
