### ISSUE TITLE
need a Step 4a

### ISSUE THREAD

**Issue by limjianan** [MicrosoftDocs/OfficeDocs-o365seccomp#208]
Yes, this article is good as it assign the new retention policy to user mailboxes, but i recommend to put this to mailboxplan so this policy will apply to all newly created mailboxes. that also can mark as optional . (maybe a step 5 then push the other one to step 6)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f85af13-2155-ac42-2e6f-25f3457f79c1
* Version Independent ID: 03361b16-a7c9-6a31-2f0b-0fefeb8b3493
* Content: [Set up an archive and deletion policy for mailboxes in your Office 365 organization](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-an-archive-and-deletion-policy-for-mailboxes)
* Content Source: [SecurityCompliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@limjianan Thank you for this feedback

I will get this suggestion over to the 0365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@limjianan Thanks for the suggestion; the article has been updated with this additional step: https://docs.microsoft.com/en-us/Office365/SecurityCompliance/set-up-an-archive-and-deletion-policy-for-mailboxes#optional-step-6-make-the-new-retention-policy-the-default-for-your-organization
