### ISSUE TITLE
Please provide a way for recipients to report a compromised account to Microsoft Directly.

### ISSUE THREAD

**Issue by brianwing** [MicrosoftDocs/OfficeDocs-o365seccomp#210]
I've had occasions where I have received SPAM from a compromised x.onmicrosoft.com domain and would like to have a feedback loop directly to MS so you can shut down affected domains, or at a minimum inform the tenant owner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f5a81ec-6747-1bf6-cb92-612d26554e4b
* Version Independent ID: 851bec9d-104e-94e7-a0d8-b8d73b91576c
* Content: [Responding to a Compromised Email Account in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/responding-to-a-compromised-email-account)
* Content Source: [SecurityCompliance/responding-to-a-compromised-email-account.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/responding-to-a-compromised-email-account.md)
* Service: **o365-solutions**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by AndreaBarr** [comment]
@brianwing Thank you for this feedback

I will get this request over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@KingJoshi, have you opened a support ticket on this?

**Comment by chrfox** [comment]
To report spam email directly to Microsoft and your admin [Use the Report Message add-in](https://support.office.com/en-us/article/Use-the-Report-Message-add-in-b5caa9f1-cdf3-4443-af8c-ff724ea719d2).  A link to the topic has been added to the See also section

**Comment by chrfox** [comment]
To report spam email directly to Microsoft and your admin Use the Report Message add-in. A link to the topic has been added to the See also section

**Comment by brianwing** [comment]
This is not a workable solution for Outlook Desktop.  You can't even get to the Store from the desktop app.

**Comment by brianwing** [comment]
Doesn't look like you can add this into the OWA either.  :-(

**Comment by denisebmsft** [comment]
@brianwing, have you seen this article: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in)? It includes steps for getting the add-in for a single user, or for the entire organization, and does cover Outlook as well as OWA.

**Comment by brianwing** [comment]
Thanks @denisebmsft That did the trick.
