### ISSUE TITLE
Examples used in the article can be tweaked to become more inituitive

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/OfficeDocs-o365seccomp#212]
I have a couple suggested tweaks to make the examples used to illustrate event-driven labels easier to understand.

here's the suggestions:
- In the diagram, change Event Type from "Product lifetime" to "Product Retirement" (since lifetime would suggest people can create events like "product launch", "product price increase", etc, which is not what this feature is designed for
- In the same diagram, change Label 2 from "Product certifications" to "Product design documents" (it's easily for people to relate to)
- In Step 4, change the screenshot to show a label from the top diagram (it currently shows "Project Closure" which is not a sample label shown above), also show Asset ID = XYZ
- In Step 5, provide a sample name for the event (e.g. Retirement of Product XYZ)

if you want to provide another example, here's one:
- Event Type: Project closure
- Labels: "Project Plan", "Project Deliverable", "Budget Document"
- Event: "Project ABC closure", "Project XYZ closure"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa8bea84-e38c-1780-59a7-261e0112208b
* Version Independent ID: 7a9cb33b-cb67-5c77-14b0-36123c3c12c8
* Content: [Overview of event-driven retention](https://docs.microsoft.com/en-us/office365/securitycompliance/event-driven-retention?redirectSourcePath=%252fen-us%252farticle%252fOverview-of-event-driven-retention-dd851332-747b-45b9-82de-e3cd7d01c8a7)
* Content Source: [SecurityCompliance/event-driven-retention.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/event-driven-retention.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@bernardlam Thank you for this feedback

I'll get your suggestions over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by stephow-MSFT** [comment]
Thanks for the feedback, Bernard.
