### ISSUE TITLE
List items and formatting

### ISSUE THREAD

**Issue by mindcontrols** [MicrosoftDocs/OfficeDocs-o365seccomp#213]
List items go up to 14 and then back to 10 and 11. Bullets aren't indented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b37016-da2f-6e2a-c3e7-360c3e9ec5ed
* Version Independent ID: 395a4420-1d14-5b0a-0be8-8f2b36fdb081
* Content: [Configure your spam filter policies](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-your-spam-filter-policies#feedback)
* Content Source: [SecurityCompliance/configure-your-spam-filter-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-your-spam-filter-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@mindcontrols Thank you for this feedback

I will get this information over to the o365seccomp writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@mindcontrols thank you for the feedback. This is now fixed and you should see the changes live.
