### ISSUE TITLE
condition when it cannot pull the data out

### ISSUE THREAD

**Issue by limjianan** [MicrosoftDocs/OfficeDocs-o365seccomp#214]
i have tried to send an email to my college, it took 4 minutes to appear in this tracker. and if he read it, i unable to pull the email away even it is sit in the inbox. a list of condition will help so no one panic when it cannot delete the email

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00591b3a-0e82-b0e1-fa3b-350c689eefee
* Version Independent ID: 397f05c8-7dc6-5935-f973-5146fc647808
* Content: [Find and investigate malicious email that was delivered (Office 365 Threat Intelligence)](https://docs.microsoft.com/en-us/office365/securitycompliance/investigate-malicious-email-that-was-delivered)
* Content Source: [SecurityCompliance/investigate-malicious-email-that-was-delivered.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/investigate-malicious-email-that-was-delivered.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AndreaBarr** [comment]
@limjianan Thank you for this feedback

I will get this email suggestion over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@limjianan thank you for posting your question. I'm looking into this but I have a couple of questions for you. Were you trying to delete an email that you sent to someone at your college? And is your suggestion that we include a list of conditions such as examples of what you can or cannot do using this feature?

**Comment by limjianan** [comment]
@denisebmsft yup. I have tried to delete an email that I sent to someone but it failed. the condition of delete is subjective. could it be not working because the user read item? or the user move the item? Meanwhile, I can't even delete the email yet. and I probably will go to support to get a better answer for that. But it will be good to understand if it failed to remediate, what could be the potential reason instead of "FAIL"

**Comment by denisebmsft** [comment]
@limjianan this Threat Intelligence feature won't delete email sent to another organization. It is designed to work on messages that came in and that are deemed suspicious. A global administrator or security administrator for your organization (and I assume you are one) would be able to delete those messages but not messages that were sent to another organization. Now your point about the notification you got is a valid one - just seeing FAIL isn't necessarily useful. And I can take the action item of adding to the content to explain what this is designed to do. Would that help?

**Comment by limjianan** [comment]
that would help. at the moment i am logging a incident with Microsoft support as well. Ticket #:12323789
As it still FAIL for whatever action i chose. (move to deleted item, soft delete, hard delete)
