### ISSUE TITLE
DKIM records are setup with TXT...

### ISSUE THREAD

**Issue by fallingrock** [MicrosoftDocs/OfficeDocs-o365seccomp#215]
... not CNAME.

http://www.dkim.org/specs/draft-ietf-dkim-deployment-11.html#rfc.section.4.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM to validate outbound email sent from your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dkim-to-validate-outbound-email#Publish2CNAME)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
Hi! Thanks so much for your feedback. While the RFC was indeed originally written with TXT records, you use CNAME when pointing to the key in your provider’s DNS as described in this article. Office 365 requires the use of CNAME records for DKIM.
