### ISSUE TITLE
Step 3: Create a CSV file... incredibly vague and unhelpful. 

### ISSUE THREAD

**Issue by bmercernccer** [MicrosoftDocs/OfficeDocs-o365seccomp#216]
There is no detail whatsoever on how this CSV file should be formatted, what it should be called, or where it should be placed. And there is no link to another document including such details either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06eed57d-9f15-100a-62e2-183e00801e0d
* Version Independent ID: a407a4cd-1e98-ba74-5199-81b77c3db711
* Content: [Overview of importing your organization PST files to Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/importing-pst-files-to-office-365?redirectSourcePath=%252farticle%252fba688e0a-0fcb-4bd7-8e57-2b669564ea84#BKMK_NetworkUpload)
* Content Source: [SecurityCompliance/importing-pst-files-to-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/importing-pst-files-to-office-365.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@bmercernccer Please see the detailed instructions in this article: https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files#step-4-create-the-pst-import-mapping-file

**Comment by FC-EricWeller** [comment]
That's helpful....how about including that link on Step 4 where it says to create the mapping file?
