### ISSUE TITLE
Instant Notification

### ISSUE THREAD

**Issue by kvwesely** [MicrosoftDocs/OfficeDocs-o365seccomp#217]
The Exchange spam filter, while relatively effective, catches a wide swath of emails, including emails we need now.  Getting a once daily notification is often a major issue for us.  One example of this was when creating an account on a website, the email confirmation emails were caught up in the spam filter and expired in 15 minutes.

There should be a setting for receiving spam notifications in real time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8252ddfb-8d51-29d8-0e8a-01c70c07db45
* Version Independent ID: ddc36cea-faf5-78b0-5542-e4ef41692083
* Content: [Configure end-user spam notifications in Exchange Online](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-end-user-spam-notifications-in-exchange-online)
* Content Source: [SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@kvwesely thank you for the feedback! We are looking into this.

**Comment by cfizz34** [comment]
I do not see an option for setting the recipients domain.  I only see where I can set the sender is located inside/outside the organization.

**Comment by kbull1984** [comment]
I agree that the once a day notifications are a big problem. At a minimum we should be able to select the time of day that the quarantine digests are sent out. With other spam protection providers you can send multiple digests out per day at various set times. Ours O365 digests typically are received late in the evening so any email caught won't be discovered for upwards of 24 hours which can be very bad for business and customer relations.

**Comment by MSFTTracyP** [comment]
@kvwesely - I think your argument needs to go into the SPAM & Phishing section of Uservoice for the folks who create the problem (and others who are experiencing the problem) to see, in fact. Right here: 
[Office 365 Security & Compliance](https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=137178)

**Comment by cfizz34** [comment]
I wish you could also allow the user to preview the messages like the admins can
