### ISSUE TITLE
Script needs improvement

### ISSUE THREAD

**Issue by pracsol** [MicrosoftDocs/OfficeDocs-o365seccomp#22]
The file will not be generated if there are no policies in the case. Setting aside the fact that white-space in the above script is horrible. The script iterates through all cases; for open cases, it will gather all members and then all polices. However, it will only output content to the file if there are policies in the case. If no policies are found in the cases, you'll never have called the function to output to the file. So the script ends saying it created a file at the path specified, with the ostensible name, but if there were no policies on the case, there will be no file. So script should be modified to either create an empty file, maybe with list of cases and respective members, or a line that says it had nothing to report on, or set a flag if the file has been touched, and if flag not set, change the final status output to indicate that no file was created. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34dd1a2c-da6d-c75c-4fee-fa6747cc8e91
* Version Independent ID: e36f465f-3c2f-bca7-4bcf-70805de73be3
* Content: [Create a report on holds in eDiscovery cases in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/create-a-report-on-holds-in-ediscovery-cases)
* Content Source: [SecurityCompliance/create-a-report-on-holds-in-ediscovery-cases.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-a-report-on-holds-in-ediscovery-cases.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
fixed; script revised with these changes: 1) generates an additional report with a list of case names that do not have holds; 2) when processing a case, the script will display the following message if the case doesn't have holds: "No hold policies found in case:" $cc.name

Revised topic w/ revised script: https://docs.microsoft.com/en-us/office365/securitycompliance/create-a-report-on-holds-in-ediscovery-cases
