### ISSUE TITLE
Step 2 Clarity edit request.

### ISSUE THREAD

**Issue by SatiricalJack** [MicrosoftDocs/OfficeDocs-o365seccomp#221]
Step 2 needs a line break as FullAccessSet-Mailbox  is not a valid cmdlet or attribute. This causes unnecessary confusion that could easily be avoided. The correct syntax is as follows

1: Add-MailboxPermission "SupervisoryReview{GUID}@domain.onmicrosoft.com" -User &lt;alias or email address of the account that has reviewer permissions to the supervision mailbox&gt; -AccessRights FullAccess

2: Set-Mailbox "&lt;SupervisoryReview{GUID}@domain.onmicrosoft.com&gt;" -HiddenFromAddressListsEnabled: $false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cdd7f75-3b44-9eb0-6d57-05bd20aa22bf
* Version Independent ID: 220e58f4-9543-7bec-cd37-a6e68f76af2b
* Content: [Install the Supervision add-in for Outlook desktop](https://docs.microsoft.com/en-us/office365/securitycompliance/install-the-supervision-add-in-for-outlook-desktop)
* Content Source: [SecurityCompliance/install-the-supervision-add-in-for-outlook-desktop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/install-the-supervision-add-in-for-outlook-desktop.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
@SatiricalJack thank you very much for this. Formatting is fixed, and you should see the changes live now.
