### ISSUE TITLE
Blocking My Website

### ISSUE THREAD

**Issue by sanguivel** [MicrosoftDocs/OfficeDocs-o365seccomp#222]
Hello,
I run a movie reviewing website and it appears that your program is blocking viewers from accessing it by having classified my website as "Malicious." I can assure you and prove that my website is not malicious in any way and would like to know if there is a process in which I can remove my website from such a list as I'm losing viewership that has taken me years to build up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5939440-a0f8-0938-e61e-27aeca97888a
* Version Independent ID: 0314d705-b3fd-8533-22bd-a14039362e0f
* Content: [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-atp?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-Advanced-Threat-Protection-e100fe7c-f2a1-4b7d-9e08-622330b83653#feedback)
* Content Source: [SecurityCompliance/office-365-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-atp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@sanguivel thank you for the feedback. I am looking into this and will post an update as soon as I know more.

**Comment by PCPitstopDevin** [comment]
@denisebmsft We are also having an issue with our password reset link being deemed "Malicious". Is there a place to submit our URL for review?

**Comment by denisebmsft** [comment]
@sanguivel, can you please send me your website URL so our experts can look into this? And @PCPitstopDevin thank you for your question. I'll check on that, too.

**Comment by sanguivel** [comment]
sure www.youngcriticmovies.com<http://www.youngcriticmovies.com>
Thanks

Guillermo

On Dec 6, 2018, at 6:18 PM, Denise Vangel-MSFT <notifications@github.com<mailto:notifications@github.com>> wrote:


@sanguivel<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsanguivel&data=02%7C01%7C%7Cee9e7d5ca3354aa7064708d65bd10e9e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636797350783919543&sdata=pwSlWrbgNahqSZ4fYrUdfsrNP09LsKWr2zzZmxbUwBo%3D&reserved=0>, can you please send me your website URL so our experts can look into this? And @PCPitstopDevin<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPCPitstopDevin&data=02%7C01%7C%7Cee9e7d5ca3354aa7064708d65bd10e9e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636797350783919543&sdata=3A5CiFvjTRKfTBBroSldaXkjlIC1iDCuubRHFmKwnqY%3D&reserved=0> thank you for your question. I'll check on that, too.

**Comment by sanguivel** [comment]
apologies I think I send a faulty link. It's www.youngcriticmovies.com and just in case for another page in my website here's another link: https://www.youngcriticmovies.com/copy-of-the-greatest-showman-1

**Comment by djsimonc** [comment]
@denisebmsft

Hi Denise, I am also getting a false report for malicious content, please can you also investigate and remove the warning.

Thanks!

https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Flinks.pb07.wixshoutout.com%2Fwf%2Fclick%3Fupn%3Dn-2B0luYJUth6vGGbu1Q0-2F3FQFNg-2BuKtzdHR6j02YcJbFOq-2F4zuWGZ4MZ9DuHL7wBWOpb0K-2BAiD9rW5k3Iv8ee7hOgP5Vsg6sS55INI8-2FBNJhc-2BCkXMV1-2BREhy26t1-2BmRsyXrp2Ly3JvXaW3SCSYzDYNgJxUMENuMocHXQ7xottGkAhpm3HZfi1e2r55uU5fnP_QM2W-2BBF-2FTN0sScj1BbAAg0IQTVtltIHXGIdKGnLco-2F2a6Ms9xQfOOnLT-2BXypfI3-2B4UrMzJf7fDeyKGfz4DsNmJsNGCqPdoNlklPTMwdYcAmmbwh0CBBJYUU89CHjWlbjZtLpaVEI1eiMgE8U4UKeiF-2BhkoaeEn7Dj4U1nGguGHHGONFOg7kFYfa9sEV-2F4CtduDIxZU3-2BEY-2FL83WgtyKwmiH-2FgLuVRgxjr78xRyAMMSBCHiP4Pdf06zv5gnFXd-2Fug5l0i5YscWsAB729PhiV4qDAlrVJVzvNgKaukcFCIovZZhC74FbD76F-2BcleD331fKQFsCcB9MKZUIR-2FFL026NvgBmKmKaJkjE2rBbcDu53JN0B-2FNCydtI2LoslZyEkyOmZKg3tvp9VRyifVPVBGtA-2B-2B286Rhaoqb4jafXE-2FBMhwtaysrB9vDKSlgYsOpZlH7ODLaUOO8VtmkuvjP4gfWBbIa2nhXN-2Bm0YLxmxZZMfyMYTuVYtUyKpcjKjFhEZGVIsb9ZGe2ZjkFuGdzBDm6TktjdhIvlbILczXrV87YRgCAyScK2TjmTc-2Bjmjl8nL1Gob&data=02%7C01%7C%7C4016d3ad087847b2092308d65d7c0581%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636799184574826244&sdata=fBCNP9lk7AxEBAsRjteh4%2F4ou9QIG3F%2B%2BL8DWL9Gz8w%3D&reserved=0

**Comment by denisebmsft** [comment]
@sanguivel, @PCPitstopDevin, @djsimonc, and @chad, please send a "false positive" request to safelinksfeedback@microsoft.com. Include your URL and the issue you are having, and our product team will take it from there. And I'll get this information added to my article.
