### ISSUE TITLE
What permissions are needed?

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/OfficeDocs-o365seccomp#223]
We should include what are the minimum permissions needed for an admin to use the restricted users page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baecd02e-eaff-0822-1cf2-dc7f02e4a218
* Version Independent ID: f97b946a-3306-6cfa-d26a-90e425d5789b
* Content: [Removing a user, domain, or IP address from a block list after sending spam email](https://docs.microsoft.com/en-us/office365/securitycompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email)
* Content Source: [SecurityCompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@scottsa-msft thank you for your question. We are looking into this, and we'll post an update soon.

**Comment by andreasks4000** [comment]
Following this - need answer to exactly this question.

**Comment by JasonSCarter** [comment]
> 
> 
> @scottsa-msft thank you for your question. We are looking into this, and we'll post an update soon.

I need this information also.  Our help desk has a role in Exchange Online to do this task, but we can't give them Global Admin for them to do this in the Security and Compliance Center.

**Comment by JasonSCarter** [comment]
@denisebmsft update please?

**Comment by KCCross** [comment]
I'm escalating this and other questions related to the delist portal internally. Thanks guys.

**Comment by MSFTTracyP** [comment]
The minimum requirements re. permissions are included in the article now. I'll close this out. Please create a comment if you have any other issues.
