### ISSUE TITLE
Exchange MRM

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-o365seccomp#225]
Are there plans to bring default folder policies and move to archive features from Exchange MRM into security & compliance center label policies?  Please add more clarification to the differences between the two and when you should use each.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels?redirectSourcePath=%252farticle%252faf398293-c69d-465e-a249-d74561552d30)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@danmyhre thank you for the feedback. We are looking into this.

**Comment by DeanGross** [comment]
its been 2 months, when can we see the results of your investigation?

**Comment by stephow-MSFT** [comment]
We're aware that retention policies don't have "move to archive" like Exchange MRM. In general, that's the only reason to continue to use MRM. For retention, we recommend the new policies -

https://docs.microsoft.com/en-us/office365/securitycompliance/labels#use-retention-labels-instead-of-these-features
