### ISSUE TITLE
Sample mapping file missing a column

### ISSUE THREAD

**Issue by JulietteLaurier** [MicrosoftDocs/OfficeDocs-o365seccomp#226]
The sample mapping file provided is missing a column. The example provided works, but the downloadable CSV file is missing a column which means it is not useable when you try to use it for a network upload. Please correct this and upload a template with the missing column. Missing column is: ContentCodePage

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a65de3-b878-b20a-3823-11a9dbc3e37c
* Version Independent ID: 28499237-e103-b204-12b2-11d72f685370
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files)
* Content Source: [SecurityCompliance/use-network-upload-to-import-pst-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@JulietteLaurier thank you for the feedback. We are looking into this.

**Comment by markjjo** [comment]
@JulietteLaurier ContentCodePage is an optional parameter, as per the documentation. It is not required for the CSV file to validated when you're creating an import job. You can add the ContentCodePage column to the CSV file if you need to import PST files in CJK organizations. We are looking into adding the column to the downloadable CSV file.

**Comment by markjjo** [comment]
@JulietteLaurier FYI that the downloadable PST mapping CSV file now contains the ContentCodePage column. https://go.microsoft.com/fwlink/p/?LinkId=544717

**Comment by JulietteLaurier** [comment]
Thanks! @markjjo
