### ISSUE TITLE
What is the SFS: field for? 

### ISSUE THREAD

**Issue by geo101** [MicrosoftDocs/OfficeDocs-o365seccomp#230]
The field SFS: shows up in  under X-Forefront-Antispam-Report but is not documented here.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0c22e-ec20-d8dc-bbc5-cfbb9e98350e
* Version Independent ID: d9a1bac2-69ef-5fa7-23f1-417d7454c4cc
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-spam-message-headers)
* Content Source: [SecurityCompliance/anti-spam-message-headers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@geo101 thank you for the feedback. We are looking into this and will update this issue soon.

**Comment by MSFTTracyP** [comment]
Thanks, @epsilon42. True. @geo101, please take a look at https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.
