### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by wzmclaren** [MicrosoftDocs/OfficeDocs-o365seccomp#232]
Without the ability to sort by name this new "restricted users" page is slightly less than useless.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baecd02e-eaff-0822-1cf2-dc7f02e4a218
* Version Independent ID: f97b946a-3306-6cfa-d26a-90e425d5789b
* Content: [Removing a user, domain, or IP address from a block list after sending spam email](https://docs.microsoft.com/en-gb/office365/securitycompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email)
* Content Source: [SecurityCompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@wzmclaren thank you for the feedback! We will pass this along; however, you also have a way to provide feedback to our product team here: https://office365.uservoice.com/forums/289138-office-365-security-compliance
