### ISSUE TITLE
Entering URL Custom list

### ISSUE THREAD

**Issue by gd2009** [MicrosoftDocs/OfficeDocs-o365seccomp#233]
The fact that you have to do this one at a time is ridiculous , you should have the option to import a list of URL from a txt or csv file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af472c4-2294-606d-2d92-73905ae99dd6
* Version Independent ID: 0ef91fba-13ee-8181-71fc-b5cc74cdc643
* Content: [Set up a custom blocked URLs list using Office 365 ATP Safe Links](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-a-custom-blocked-urls-list-wtih-atp?redirectSourcePath=%252farticle%252f896a7efb-1683-465e-a394-261349e5d866)
* Content Source: [SecurityCompliance/set-up-a-custom-blocked-urls-list-wtih-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-a-custom-blocked-urls-list-wtih-atp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@gd2009 thank you for the feedback! I will pass this along; however, you have a way to submit feedback for our product team, too: https://office365.uservoice.com/forums/289138-office-365-security-compliance
