### ISSUE TITLE
01-문구 수정-1210

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/OfficeDocs-o365seccomp#234]
As-Is
식별 하 고 SharePoint, OneDrive 및 Microsoft 팀의 ATP 와 온라인 라이브러리에 악의적인 파일을 차단
To-Be
SharePoint, OneDrive 및 Microsoft 팀용 ATP를 사용하여 온라인 라이브러리의 악성 파일 식별 및 차단

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: f5939440-a0f8-0938-e61e-27aeca97888a
* Version Independent ID: 0314d705-b3fd-8533-22bd-a14039362e0f
* Content: [Office 365 Advanced Threat Protection](https://docs.microsoft.com/ko-kr/office365/securitycompliance/office-365-atp?redirectSourcePath=%252farticle%252fe100fe7c-f2a1-4b7d-9e08-622330b83653)
* Content Source: [SecurityCompliance/office-365-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-atp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you very much for the feedback. I have reached out to our localization team, and they are looking into this.

@AnnTaeYoun 피드백을 주셔서 대단히 감사 합니다. 나는 우리의 현지화 팀에 도달 했 고, 그들은 이것을 찾고 있습니다.

**Comment by denisebmsft** [comment]
@AnnTaeYoun, hello! This should now be fixed. Please let us know if there are any further issues. And thank you for helping us improve our content!
