### ISSUE TITLE
02-문구 수정-1210

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/OfficeDocs-o365seccomp#235]
As-Is
SharePoint, OneDrive 및 팀이 Microsoft Office 365 ATP의 개요 (영문)
To-Be
SharePoint, OneDrive 및 Microsoft 팀용 Office 365 ATP 개요

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a7f6ebd5-e0c1-978a-8d8d-415510b09a48
* Version Independent ID: 18b839e1-f53d-90a3-d97a-7249b54d762b
* Content: [SharePoint, OneDrive 및 Microsoft Teams에 대한 Office 365 ATP](https://docs.microsoft.com/ko-kr/office365/securitycompliance/atp-for-spo-odb-and-teams)
* Content Source: [SecurityCompliance/atp-for-spo-odb-and-teams.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/atp-for-spo-odb-and-teams.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@AnnTaeYoun, thank you very much for the feedback. I have reached out to our localization team, and they are looking into this.

피드백을 주셔서 대단히 감사 합니다. 나는 우리의 현지화 팀에 도달 했 고, 그들은 이것을 찾고 있습니다.

**Comment by denisebmsft** [comment]
@AnnTaeYoun, hello! This should now be fixed. Please let us know if there are any further issues. And thank you for helping us improve our content!
