### ISSUE TITLE
How to manage Security Admin and Reader

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#237]
It states that we cannot manage the Security Admin and Reader roles through the portal, but does not tell how they can be managed. Please add this information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center?redirectSourcePath=%252farticle%252fd10608af-7934-490a-818e-e68f17d0e9c1)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@DeanGross thank you for the feedback. We're looking into this, and an update will be posted here soon.

**Comment by pawp81** [comment]
I am looking for the same information. Is there any progress on updating the content about how to manage Security Admin and Security Reader?

**Comment by stephow-MSFT** [comment]
I've updated the topic with Azure Active Directory info and link to their topic.
