### ISSUE TITLE
APAC filtering routing update

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#238]
In the EOP Datacenters paragraph "In Asia-Pacific (APAC), all Exchange Online mailboxes are located in APAC datacenters, but messages are currently routed through EMEA datacenters for EOP filtering. This is targeted to be changing in the fourth quarter of 2014, when messages will be routed through APAC datacenters for EOP filtering". Do we have update if this routing was moved to APAC and documentation should be refreshed? Or the change was postponed and the target date should be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f54a0b9a-a1a6-3f33-46f7-8f21989189fb
* Version Independent ID: 36ef546f-93c7-68e0-2330-07a658a17150
* Content: [Exchange Online Protection overview](https://docs.microsoft.com/en-us/office365/securitycompliance/eop/exchange-online-protection-overview)
* Content Source: [SecurityCompliance/eop/exchange-online-protection-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/exchange-online-protection-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@Larryngolog thank you for posting this question. We are looking into this, and we'll post an update here soon.

**Comment by MSFTTracyP** [comment]
@Larryngolog Hi there! Thank you for bringing this to my attention! There is EOP in all the regions of Office 365 now. I'll update the document to remove that information. Thanks again!
