### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-o365seccomp#239]
Please correct this line:

Are there other ways to get auditing logs other than suing 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@r-milne Thanks for the heads up. The typo is fixed: https://docs.microsoft.com/en-us/Office365/SecurityCompliance/search-the-audit-log-in-security-and-compliance#frequently-asked-questions
