### ISSUE TITLE
Differences between simple retention labels and labels defined as "record"

### ISSUE THREAD

**Issue by pbinksma** [MicrosoftDocs/OfficeDocs-o365seccomp#240]
The section "Using retention labels for records management" seem to indicate that labels which define "records" enforce folllowing behaviour:
- The item can't be permanently deleted.
- The item can't be edited.
- The label can't be changed.
- The label can't be removed.

Based on this article the difference to a "simple" retention label is not clear for me. I would  e.g. expect that non-records labels would work similar to simple retention policies described in this article: https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies. That would mean that you are able to delete a labled document and that it would go into the preservation hold library. Instead simple retention labels seem to show the same behaviour as record-labels. Deletion is not possible at all.

So at the end the only difference between record lable and non-record retention label seem to be the face that I as an enduser cannot change/remove a label. The other mentioned points are already covered by normal retention labels.

It would be very helpful to have e.g. a table where you outline differences between deletion policy, retention policy, deletion labels, retention flags and records flags.

thanks
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
You're right, the main difference is the record label can't be changed/removed. But also, the item can't be edited. And in SharePoint, content with record label can't be deleted at all -

https://docs.microsoft.com/en-us/office365/securitycompliance/labels#records-cant-be-deleted

**Comment by EricaToelle** [comment]
Also, a record label only prevents the document from being edited. You can still edit the metadata on the document.

**Comment by RobBath** [comment]
To add to Erica's point, while a record label (immutable retention label) continues to allow file metadata to be edited, if you apply the same label to a custom list item it has the opposite effect preventing the metadata from being edited.
