### ISSUE TITLE
Missing details about what is subject to site-level retention policies

### ISSUE THREAD

**Issue by pbinksma** [MicrosoftDocs/OfficeDocs-o365seccomp#241]
I would like to have a clear list of objects/types of objects which are subject to a site-level retention policy in SPO/OneDrive. Right now it seems that pages are not affected by a policy. The same applies to lists/list items. OneNote-Notebooks doesn't seem to be deleted but individual sections seem to disappear when a policy was applied.

Thanks
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@pbinksma thank you for your feedback. We've added this to our queue and will look into it soon. We'll post an update here. Thank you again!

**Comment by stephow-MSFT** [comment]
Good question, article will be updated with this info - in the meantime, a retention policy preserves list items and pages in addition to documents.

**Comment by stephow-MSFT** [comment]
For OneNote, retention policies work like this -

Retention Policies apply at the file level. However, OneNote notebooks are a special case because SPO considers each OneNote notebook a folder and each section as a file in that folder. In this exception case, Retention Policies act at a folder (notebook) level and will only commence the disposition action specified in the retention policy when ALL sections of the notebook have met the retention duration. Therefore, a retention policy will not cause individual sections of a notebook to be deleted.

**Comment by pbinksma** [comment]
@stephow-MSFT 
This is not what I observe when testing retention policy.
Scenario:
- Retention Policy with retention and deletion after 14 days applied to the Site containing a plain document library.
- Created a OneNote with two sections (Section A and Section B). created one page in each section.
- After Week 1: Update Section B by adding an additional page.
-After week 2 + delay (deletion job seem to run on weekends): Only section A was deleted. Section B still exists.

So is your description incorrect or is that a bug in SPO?

**Comment by stephow-MSFT** [comment]
@pbinksma Thanks for the feedback, turns out the description is not correct, currently researching the OneNote behavior, pls stay tuned.

**Comment by pbinksma** [comment]
@stephow-MSFT
any news on the OneNote-topic?
