### ISSUE TITLE
I'm confused about what encryption level is being used to encrypt OME messages

### ISSUE THREAD

**Issue by oedo808** [MicrosoftDocs/OfficeDocs-o365seccomp#242]
The first table mentions BitLocker for Exchange Online and AES-128+ but is labeled Office 365 Multi-tenant and Government Cloud Community environments.  The second table also says BitLocker for Exchange Online but says AES-256.  How can I determine the encryption strength for a message encrypted by transport rules?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090d20f3-044b-076c-ac26-a554018daa97
* Version Independent ID: 712712d7-457d-7432-c769-2ce99df0a87a
* Content: [Office 365 Encryption Risks and Protections](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-encryption-risks-and-protections)
* Content Source: [SecurityCompliance/office-365-encryption-risks-and-protections.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-encryption-risks-and-protections.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
@oedo808 thank you for your feedback. We have this in our queue and will take a look as soon as possible. We appreciate your taking the time to help us improve our content. Thanks again, and we'll post an update here soon.

**Comment by robmazz** [comment]
@oedo808 - thanks for the feedback. I've updated the table labeling and formatting to make this clearer. The multi-tenant and government tables were not clearly labeled. For multi-tenant, most servers in the Exchange Online multi-tenant environment have been deployed with AES 256-bit encryption for BitLocker. Servers using AES 128-bit are being phased out.
