### ISSUE TITLE
Breakdown of "assigned roles" 

### ISSUE THREAD

**Issue by jegilber** [MicrosoftDocs/OfficeDocs-o365seccomp#243]
The roles within the "role group" needs to be expanded on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center?redirectSourcePath=%252farticle%252fd10608af-7934-490a-818e-e68f17d0e9c1)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@jegilber thank you for the feedback. We have added this to our queue and will post an update soon.

**Comment by stephow-MSFT** [comment]
The article's been updated with roles info.
