### ISSUE TITLE
Great Article

### ISSUE THREAD

**Issue by rleeoconnor** [MicrosoftDocs/OfficeDocs-o365seccomp#244]
Great article, any idea when this feature will be part of  the user interface? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669fab80-1970-8598-dad2-076f2e9ef7a9
* Version Independent ID: e074d4d5-7616-0e9d-30a4-c9e0b642175e
* Content: [Use a script to add users to a hold in an eDiscovery case in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/use-a-script-to-add-users-to-a-hold-in-ediscovery)
* Content Source: [SecurityCompliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rleeoconnor Thanks for the feedback. Bulk-assigning content locations to an eDiscovery hold is not on the roadmap for changes to the hold UI within in eDiscovery case. What is on roadmap is ability to place a custodian's mailbox and OneDrive location on hold by clicking checkboxes. For preserving content outside of a short-lived legal investigation, you can use organization- or location-wide retention policies. See: https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies#applying-a-retention-policy-to-an-entire-organization-or-specific-locations.
