### ISSUE TITLE
Error in document

### ISSUE THREAD

**Issue by Orta373** [MicrosoftDocs/OfficeDocs-o365seccomp#245]
The document above says that Sharepoint Online has versioning turned off by default.  I believe that changed and now it is turned on by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2db4e9b-cd96-96b5-08b8-d2f61db73f75
* Version Independent ID: 6b41374b-20d5-614c-9e33-b2ff87234796
* Content: [Office 365 Malware and Ransomware Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-malware-and-ransomware-protection)
* Content Source: [SecurityCompliance/office-365-malware-and-ransomware-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-malware-and-ransomware-protection.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
@Orta373 thank you for the feedback. We will look into this, and an update will be posted here soon.

**Comment by robmazz** [comment]
@Orta373 - thanks for the feedback, the topic has been updated to reflect this change.
