### ISSUE TITLE
Not possible to configure retention time in recycle  bin.

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/OfficeDocs-o365seccomp#247]
According to support it is not possible to configure the retention time in recycle bin.
As stated in 

>  " If you delete content from a Site Recycle Bin, it's sent to the Site Collection Recycle Bin, which has a retention time of 93 days. The length of time to keep things in the recycle bin can be configured by an administrator, but in the absence of that, the default retention period is about 90 days. "

Please update the aricle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4522f966-a190-4582-f168-a1c72c6fc858
* Version Independent ID: a285bcae-0adf-9625-beb1-5e190aded751
* Content: [Office 365 SharePoint Online Data Deletion](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-sharepoint-online-data-deletion)
* Content Source: [SecurityCompliance/office-365-sharepoint-online-data-deletion.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-sharepoint-online-data-deletion.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
@xNiklasJern thank you for the feedback. We'll look into this as soon as possible, and we'll post an update here.

**Comment by robmazz** [comment]
@xNiklasJern - thank you for your feedback, this topic has been updated.
