### ISSUE TITLE
Minimum licensing needed list for each secure score point

### ISSUE THREAD

**Issue by bilalAchahbar** [MicrosoftDocs/OfficeDocs-o365seccomp#248]
I want to figure out which license I need for each control in the secure score total list. 
Based on this blog : https://justaucguy.wordpress.com/2018/01/10/office-365-secure-score-practical-in-depth-analysis/ 
and the update blog : https://justaucguy.wordpress.com/2018/10/24/microsoft-secure-score-new-task-practical-analysis/ 
I figured out the total controls of the secure score and some of the licensing but i can't figure out the minimum licensing need for the controls

**Comment by denisebmsft** [comment]
@bilalAchahbar, I'm assuming that your feedback applies to this article: https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-secure-score

Is that correct? 

We are looking into this, and we'll post an update here soon.

Thank you very much for the feedback!

**Comment by bilalAchahbar** [comment]
Yeah that's true , In the official documentation (the article you referenced) i didn't found any thorough explanation. In the blog i referenced in my question there i could find a more detailed explanation about each point. Unfortunately not enough , that's why i asked it here.

**Comment by denisebmsft** [comment]
Hello @bilalAchahbar, I have an update for you. As you probably already know, Secure Score only includes points and recommendations for features that are included in your organization's subscription. And only administrators can view Secure Score or configure the recommendations to improve the security posture. There isn't an easy answer to the question of minimum required license for each item, but I do have a few resources to offer that I hope might be helpful.

1. [Microsoft 365 Enterprise overview](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-overview). This includes a poster that you can use to see various features at a glance.
2. [Office 365 Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library). Stay tuned for these to be updated for Microsoft 365 features and service descriptions.
3. [Compare Microsoft 365 plans](https://www.microsoft.com/en-us/microsoft-365/compare-all-microsoft-365-plans).

I hope this helps!
