### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by RobertDring** [MicrosoftDocs/OfficeDocs-o365seccomp#25]
The link for "Microsoft Malware Protection Center" is broken, it has an extra "h" at the beginning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2db4e9b-cd96-96b5-08b8-d2f61db73f75
* Version Independent ID: 6b41374b-20d5-614c-9e33-b2ff87234796
* Content: [Office 365 Malware and Ransomware Protection](https://docs.microsoft.com/en-us/office365/SecurityCompliance/office-365-malware-and-ransomware-protection)
* Content Source: [SecurityCompliance/office-365-malware-and-ransomware-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-malware-and-ransomware-protection.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
@RobertDring thank you for catching that. It's fixed. Please let us know if you have any other questions or feedback.
