### ISSUE TITLE
Retention Labels?

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-o365seccomp#250]
It makes no sense to be creating DLP policies off of retention labels.  Sensitivity labels should be used for DLP...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fce61-99c1-279d-9978-7e59e445fb84
* Version Independent ID: 77c05a43-ff13-c240-4de7-a5d5d47ed2cb
* Content: [Protect SharePoint Online files with Office 365 labels and DLP](https://docs.microsoft.com/en-us/office365/securitycompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp)
* Content Source: [SecurityCompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@danmyhre thank you for the feedback! We have added this to our queue, and we'll post an update here soon. Thank you for helping us improve our content!

**Comment by JoeDavies-MSFT** [comment]
@danmyhre Hi Dan, You are correct. Because Office 365 currently does not support the use of Senstivity labels for SharePoint Online site, the article has been removed. Thanks for letting us know.
