### ISSUE TITLE
Conflicting Information

### ISSUE THREAD

**Issue by john-louden** [MicrosoftDocs/OfficeDocs-o365seccomp#251]
Hi,

Just some conflicting information in this article. Just before step one in "get Office 365 ATP" in the notice box there is this comment

"Office 365 ATP is included in subscriptions, such as Microsoft 365 Enterprise, Office 365 Enterprise E5, Office 365 Education A5, and Microsoft 365 Business."

In Step 3 there is this information

If you see Office 365 Enterprise E5, Office 365 Education A5, or Microsoft 365 Business, then your organization has ATP. 
If you see a different subscription, such as Office 365 Enterprise E3 or Office 365 Enterprise E1, consider adding ATP. To do that, choose + Add subscription.

Step 3 is either missing a reference to Microsoft 365 Enterprise, or the notice box has Microsoft 365 Enterprise listed in error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5939440-a0f8-0938-e61e-27aeca97888a
* Version Independent ID: 0314d705-b3fd-8533-22bd-a14039362e0f
* Content: [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-atp)
* Content Source: [SecurityCompliance/office-365-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-atp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@john-louden thank you for your feedback. I'm looking into this and will post an update here soon.

**Comment by denisebmsft** [comment]
@john-louden thank you again! I've updated the article to make it more clear. Thank you for helping us to improve our content!
