### ISSUE TITLE
Typo - "If the request is denied, task is block and no access" should be "...blocked..."

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/OfficeDocs-o365seccomp#252]
Typo - "If the request is denied, task is block and no access" should be "...blocked..."

Under Step 3: Access approval

**Comment by denisebmsft** [comment]
@bingoglossy it was this article, yes? https://docs.microsoft.com/en-us/Office365/SecurityCompliance/privileged-access-management-overview 

We have fixed the error. Thank you for calling this to our attention!

**Comment by bingoglossy** [comment]
YAY TEAM! Thanks denisebmsft!
