### ISSUE TITLE
Script for labels that are auto-applied

### ISSUE THREAD

**Issue by pananapple** [MicrosoftDocs/OfficeDocs-o365seccomp#254]
This document mentions that this script does not support labels that are auto-applied to content. Is there a script that can be used for labels that are auto-applied or is this just not possible with PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b92b5fa4-7162-c415-2fc7-2c1183b1dc42
* Version Independent ID: 12dac4a7-ea9f-81f5-7de8-5c51f307fc37
* Content: [Bulk create and publish retention labels by using PowerShell](https://docs.microsoft.com/en-us/office365/securitycompliance/bulk-create-publish-labels-using-powershell)
* Content Source: [SecurityCompliance/bulk-create-publish-labels-using-powershell.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/bulk-create-publish-labels-using-powershell.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by beigewell** [comment]
ideally breaking this script up into its component parts would be ideal as well rather than having to do both sections at once

**Comment by stephow-MSFT** [comment]
The script is provided as is but you can now do this via the UI by using the file plan import -

https://docs.microsoft.com/en-us/Office365/securitycompliance/file-plan-manager
