### ISSUE TITLE
Retention of Emails/Document after a person leaves the org (license removed)

### ISSUE THREAD

**Issue by dbroussa** [MicrosoftDocs/OfficeDocs-o365seccomp#256]
One thing that is not clear is what happens when we have a retention policy that is retaining content is applied to a mailbox or OneDrive location and the user is deleted from the org.  The Mailbox will be gone in 30 days, but what happens to any content that is being retained?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@dbroussa thank you for the feedback. We have this in our queue, and we'll post an update soon.

**Comment by tallpaul43** [comment]
Just following up on the same question. To maintain the email/file retention does a organization need to maintain old/former employee users licenses in Office 365? Or is the email/files retained regardless of the status of the user license?

**Comment by stephow-MSFT** [comment]
When an employee leaves the org, you typically want to *retain* the data as required by law/regulation, not delete it in 30 days. 

To do so for mailboxes, you use an inactive mailbox - https://docs.microsoft.com/en-us/office365/securitycompliance/inactive-mailboxes-in-office-365

Content in SPO and OD that's subject to a retention policy will be retained after an employee leaves the org. There's no automated way to permanently delete all files created/modified by a specific user.

**Comment by tallpaul43** [comment]
Thanks Stephen.

This answered my question.

**Comment by slrattan** [comment]
Hi There, this link https://docs.microsoft.com/en-us/office365/securitycompliance/inactive-mailboxes-in-office-365
doesn't address what happens with data retention for former employees OneDrive for Business accounts.  How is that data retained?

**Comment by dbroussa** [comment]
OneDrive content is kept for a default of 30 days after the license is removed.  You can extend this date in the OneDrive Admin center.

If you place a retention hold on the OneDrive content, then the site collection will not be removed because retained content is in the site collection preventing it from being deleted.  Once those retention holds are cleared (manually or automatically), the site collection will be removed by the system per the normal schedule.
