### ISSUE TITLE
Update for Advanced Phishing Threshold

### ISSUE THREAD

**Issue by weeyeh** [MicrosoftDocs/OfficeDocs-o365seccomp#26]
Hi, please update the docs to include Advanced Phishing Threshold

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-anti-phishing-policies?redirectSourcePath=%252farticle%252f5a6f2d7f-d998-4f31-b4f5-f7cbf6f38578#feedback)
* Content Source: [SecurityCompliance/set-up-atp-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-anti-phishing-policies.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@weeyeh Thank you for this update

I will get this over to the O365seccomp team for updating. 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
@weeyeh I'm not aware of any thresholds or limits documentation on this topic. I'm also not aware of a group testing with the intention of publishing the statistics. However, I've passed this request up the line from here. Thanks, and I wish I had better news for you on this topic. If I've missed something pertinent to this issue, please let me know.
