### ISSUE TITLE
How to review the rules?

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/OfficeDocs-o365seccomp#260]
I'm not seeing any documentation on how to review the audit for rule actions. The "How  do I know this worked" relates to checking the Antispam settings on a user - not on reviewing the audit trails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e9890c1-2a44-ca44-7a19-3cc239c49c18
* Version Independent ID: 3ca13874-1321-9332-a1ea-c49a6806f471
* Content: [Mail flow in EOP](https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/mail-flow-in-eop)
* Content Source: [SecurityCompliance/eop/mail-flow-in-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/mail-flow-in-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@Absoblogginlutely thank you for the feedback. We are looking into this, and we will post an update here in the near future.

**Comment by MSFTTracyP** [comment]
This information might help! 

[Search the Office 365 audit log to troubleshoot common scenarios](https://docs.microsoft.com/en-us/office365/securitycompliance/auditing-troubleshooting-scenarios)

[Detailed properties in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log)
