### ISSUE TITLE
Missing info?

### ISSUE THREAD

**Issue by bmmartindale** [MicrosoftDocs/OfficeDocs-o365seccomp#261]
Does this process crawl attachments as well or do these items need to be in the body of the message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53928430-079b-8f72-82ff-9923bb7dba02
* Version Independent ID: c97bb1c4-fe56-95ca-3821-6a995b1628fd
* Content: [New Office 365 Message Encryption policy for sensitive information](https://docs.microsoft.com/en-us/office365/securitycompliance/new-ome-encryption-policy)
* Content Source: [SecurityCompliance/new-ome-encryption-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/new-ome-encryption-policy.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
@bmmartindale thank you for posting this question. We're looking into this, and we will post an update here soon.

**Comment by sibethale** [comment]
When will this be released?

**Comment by MSFTTracyP** [comment]
The process crawls attachments as well. Thanks. I hope that helps!
