### ISSUE TITLE
How do I configure this in Security & Compliance	

### ISSUE THREAD

**Issue by cfizz34** [MicrosoftDocs/OfficeDocs-o365seccomp#262]
I want to only use Security & Compliance and not EAC as well.  I do not see a place where I can archive it when at this screen - Decide if you want to retain content, delete it, or both

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f85af13-2155-ac42-2e6f-25f3457f79c1
* Version Independent ID: 03361b16-a7c9-6a31-2f0b-0fefeb8b3493
* Content: [Set up an archive and deletion policy for mailboxes in your Office 365 organization](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-an-archive-and-deletion-policy-for-mailboxes)
* Content Source: [SecurityCompliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@cfizz34 Thanks for the question. You can't use retention policies in the Security & Compliance Center to move items to the archive. Retention policies can only retain, delete, or retain then delete content. Only Exchange MRM archive policies can move items to the archive mailbox.
