### ISSUE TITLE
Site administration activities are not correctly tracked if glbal admin assign himself to a user's oneDrive

### ISSUE THREAD

**Issue by stche** [MicrosoftDocs/OfficeDocs-o365seccomp#263]
we stumbled over this "issue" while we were testing out what happens wiht the onedrive content if a user is leaving the company.
When this happens it usually triggers the ODB site to be deleted after 30 days e.g.
Now to get access to the ODB content, you can actually use the admin portal, active users and in thed etails pane you can activate a link that points to a users onedrive. Once done the admin has access based on site admin privileges but THIS EVENT IS NOT TRACKED!!! - if you search the unified audit log you wont see this activity logged as a n event. only if that admin right now access the users onedrive, this will be logged with an "View page" event.  So the "issue" now is, that an global admin can actually gain access anytime to any user's onedrive without being tracked.  It gets even more worse because the admin can right after remove himself as a site admin which again IS NOT LOGGED! although its in both cases a modification of the site admins and permission settings. Assuming this is not intended behavior maybe this should be brought to the attention of the engineering team as it actually is on purpose for customers to have the "full logging" flavor even if it is an admin that performs such actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance?redirectSourcePath=%252fen-US%252farticle%252fSearch-the-audit-log-in-the-Office-365-Protection-Center-0d4d0f35-390b-4518-800e-0c7ec95e946c#site-administration-activities)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@stche thank you for the feedback! We are looking into this, and we will post an update here soon.

**Comment by markjjo** [comment]
@stche In fact, both of the these events are audited. When an admin gives themselves access to the users OneDrive account in the O365/M365 admin center, the SiteCollectionAdminAdded operation/event is logged. (In the activities picker in the audit log search UI, the friendly name for this is "Added site collection admin".) As per your scenario, when the admin removes themselves as a site admin for the user's OneDrive account (by going to User Profiles > Manage User Profiles in the SharePoint admin center) the SiteCollectionAdminRemoved operation/event is logged. Unfortunately, this activity is not listed in the Activities picker UI, which is a bug. The engineering team has been notified about this. For your testing, one suggestion is to export the audit log search results and then filter for these events in the Operations column. It might be that they were not displayed in the search results pane in the search audit log UI. Additionally, we will add info about the SiteCollectionAdminRemoved to the audit log search to this topic and add info that both of these events are also pertinent to admin adding/removing access to a user's OneDrive. Thanks for heads up.
