### ISSUE TITLE
Threat Intelligence license required for every user, or only for admin users?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/OfficeDocs-o365seccomp#266]
Can you clarify who requires an Office 365 Threat Intelligence license?  Is it required for every user in the tenant, or only for the users who would be assigned an admin role and access the security dashboard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73681216-32f3-f9a2-51b1-690e4b7c4c38
* Version Independent ID: c3213d50-3e63-4324-7a74-651d4c2b0492
* Content: [Get started with Office 365 Threat Intelligence](https://docs.microsoft.com/en-us/office365/securitycompliance/get-started-with-ti)
* Content Source: [SecurityCompliance/get-started-with-ti.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/get-started-with-ti.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@NeighborGeek thank you for your question. I'm getting confirmation on the answer and will post an update here soon.

**Comment by denisebmsft** [comment]
@NeighborGeek I got confirmation on the licenses required and have updated the content accordingly. The answer is that all active users should have a license in order for their data to show up in Threat Intelligence reports, such as Explorer. Hope this helps!
