### ISSUE TITLE
CathyWalton

### ISSUE THREAD

**Issue by CathyW42** [MicrosoftDocs/OfficeDocs-o365seccomp#269]
great.  Very interesting, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f54a0b9a-a1a6-3f33-46f7-8f21989189fb
* Version Independent ID: 36ef546f-93c7-68e0-2330-07a658a17150
* Content: [Exchange Online Protection overview](https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/exchange-online-protection-overview#for-more-information)
* Content Source: [SecurityCompliance/eop/exchange-online-protection-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/exchange-online-protection-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Thank you, Cathy!
