### ISSUE TITLE
Missing information about reports

### ISSUE THREAD

**Issue by bedo1976** [MicrosoftDocs/OfficeDocs-o365seccomp#272]
Hello

I like the documentation about monitoring-mode. But how are this statistics, reports available? 

Also DMARC supports additional parameter for email sending like rua and ruf. Are this parameter supported with office365 or not?

How can reports of DMARC be generated and sent to external email adress? 

I found one other link with a powershell script:

https://blogs.msdn.microsoft.com/tzink/2018/05/21/a-way-to-sort-of-approximate-dmarc-aggregate-reports-in-office-365/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df985369-7b10-20c3-c09e-651e7e216d93
* Version Independent ID: 3336ab94-64b0-a2a9-a9e9-e8a56d15941d
* Content: [Use DMARC to validate email in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dmarc-to-validate-email#DMARCbestpractices)
* Content Source: [SecurityCompliance/use-dmarc-to-validate-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@bedo1976 thank you for the feedback on this article. We're looking into this, and an update will be posted here soon.

**Comment by MSFTTracyP** [comment]
Micosoft (which supports both rua and ruf) hosts the mailboxes for Office 365 and sends its reports to 3rd party Agari (see [Use DMARC to validate email](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dmarc-to-validate-email) in the 'What is a DMARC TXT record' section). For the most part, third parties do the reporting, apart from some Spoof Reporting around inbound mail to O365. You could route mails to your Office 365 inbox, there aren't many reports available by default.

I hope this clarifies!

**Comment by costa1108** [comment]
@MSFTTracyP - as an organisation, Msft may send the dmarc reports to a 3rd party. But as a service provider of email services such as O365, Msft must at least comply with the relevant RFC frameworks. With DMARC, O365 is essentially the DMARC reporting agent and as other recipient email gateways, both appliance or cloud based, O365 needs to send rua and ruf DMARC reports to the domain owner. There are so many Msft docs talking about spf, dkim and dmarc but O365 sends no rua reports.
