### ISSUE TITLE
Broken Nav Link

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-o365seccomp#273]
the next nav link down from this page is broke.  Titled "Define mail flow rules to encrypt email message in Office 365"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12629dc8-4ce5-f4f9-dc32-8356eb357f33
* Version Independent ID: 877bf185-bd2f-c546-933e-a69b660737a9
* Content: [Set up new Office 365 Message Encryption capabilities](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-new-message-encryption-capabilities)
* Content Source: [SecurityCompliance/set-up-new-message-encryption-capabilities.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-new-message-encryption-capabilities.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@danmyhre thank you for calling this to our attention. We have fixed that link. Happy New Year!
