### ISSUE TITLE
Recipient impact

### ISSUE THREAD

**Issue by claygSPS** [MicrosoftDocs/OfficeDocs-o365seccomp#275]
Will the recipient of the message need to do anything in order to view the message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53928430-079b-8f72-82ff-9923bb7dba02
* Version Independent ID: c97bb1c4-fe56-95ca-3821-6a995b1628fd
* Content: [New Office 365 Message Encryption policy for sensitive information](https://docs.microsoft.com/en-us/office365/securitycompliance/new-ome-encryption-policy)
* Content Source: [SecurityCompliance/new-ome-encryption-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/new-ome-encryption-policy.md)
* Service: **office 365 administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@claygSPS thank you for posting your question. We're looking into this, and an update will be posted here soon. Happy New Year!

**Comment by KCCross** [comment]
Hi ClaygSPS - for information on receiving encrypted messages, take a look at this article: [Send, view, and reply to encrypted messages in Outlook for PC](https://support.office.com/article/eaa43495-9bbb-4fca-922a-df90dee51980).  We recently released the encrypt-only policy in Outlook for PC versions 2019 and Office 365. That means messages that have the new encrypt-only policy applied can be read directly in Outlook on the web, in Outlook for iOS and Android, and now Outlook for PC versions 2019 and Office 365. Other customers will see a message with a link. That link will take Office 365 users to Outlook on the web to read the message. Users with other email accounts will be prompted to obtain a one-time passcode and read the message in a browser window.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
