### ISSUE TITLE
PDF Clarification

### ISSUE THREAD

**Issue by Joe-Rhodes** [MicrosoftDocs/OfficeDocs-o365seccomp#279]
Great intro but it should be noted that no .PDFs can be previewed (apparently) at this time from a mobile device.  Frustratingly, the option presents itself before you get an error from Word Mobile Viewer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a4e2d7-73c3-464a-75a6-bb3bc54442a7
* Version Independent ID: 629cc24e-c828-41f8-dc47-89ce5dc2e7fa
* Content: [Dynamic Delivery and previewing with Office 365 ATP Safe Attachments](https://docs.microsoft.com/en-us/office365/securitycompliance/dynamic-delivery-and-previewing)
* Content Source: [SecurityCompliance/dynamic-delivery-and-previewing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/dynamic-delivery-and-previewing.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@Joe-Rhodes thank you so much for the helpful feedback. I'll look into this and get the content updated accordingly. I appreciate you reaching out to us about this. Thanks again!

**Comment by denisebmsft** [comment]
@Joe-Rhodes thanks again for your help. I have updated the article. Wishing you a great day!
