### ISSUE TITLE
Please expunge all mentions of on-premise

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-o365seccomp#280]
Please, correct to on-premises

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df985369-7b10-20c3-c09e-651e7e216d93
* Version Independent ID: 3336ab94-64b0-a2a9-a9e9-e8a56d15941d
* Content: [Use DMARC to validate email in Office 365](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dmarc-to-validate-email#implement-dmarc-for-inbound-mail)
* Content Source: [SecurityCompliance/use-dmarc-to-validate-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@r-milne, thank you for catching this! I've gone through and hopefully caught all instances of this. Thank you for helping us improve our content.
