### ISSUE TITLE
Exchange Hybrid clarity

### ISSUE THREAD

**Issue by MikeParker365** [MicrosoftDocs/OfficeDocs-o365seccomp#281]
This doc isn't 100% clear whether or not Exchange Hybrid is required. Although the article states that this is for an organisation with Exchange Hybrid - what about an organisation with users without mailboxes at all (i.e. in hybrid but no on-premises mailboxes for those particular users) or who are licensed for E3, but not currently Hybrid (mailboxes on-premises but no Exchange Hybrid sync options in AAD Connect) and no mailboxes enabled in O365. Would these users still get a cloud based mailbox for on-premises users or not? Would be good to clarify that. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ba92a5-4a61-1697-b296-29b05f3d3683
* Version Independent ID: 46e8b5bd-7449-a4e6-8950-eba74db03315
* Content: [Searching cloud-based mailboxes for on-premises users in Office 365](https://docs.microsoft.com/en-gb/office365/securitycompliance/search-cloud-based-mailboxes-for-on-premises-users)
* Content Source: [SecurityCompliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@MikeParker365 thank you for your feedback. We have added this to our queue and will look into it soon. We'll post an update here soon.

**Comment by markjjo** [comment]
The context/assumption of this topic is an Exchange hybrid deployment. If a user has an on-premises mailbox, a corresponding mail user account is synced to AAD and therefore 1xN chats are stored and can be searched. If a user has a cloud-based mailbox, then their identity is already in the cloud and 1xN chats are stored and can be searched. The common trait of both of these is that the user has a cloud-based identity, which is the requirement. In other words, if a user's identity is synced to ADD, then 1xN chats that they participate in are stored and can be searched. So as per the topic: "The user accounts in your on-premises directory service (such as Active Directory) must be synchronized with Azure Active Directory, the directory service in Office 365."
