### ISSUE TITLE
Not Junk email address

### ISSUE THREAD

**Issue by modangsr** [MicrosoftDocs/OfficeDocs-o365seccomp#282]
Hi, 
if you select the add-in option "not junk" and email is sent to: not_junk@office365.microsoft.com. Can it be added to the ETR/rule section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62304805-117a-0e04-038b-a42a89e12162
* Version Independent ID: 7c12ba44-3c56-7607-7e63-84b0073a25df
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in#set-up-a-rule-to-get-a-copy-of-email-messages-reported-by-your-users)
* Content Source: [SecurityCompliance/enable-the-report-message-add-in.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-the-report-message-add-in.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@modangsr thank you for raising this question. I'll get the answer and will post an update here soon.

**Comment by denisebmsft** [comment]
@modangsr thank you again for the feedback. If you use the Report Message add-in to mark a message as Not Junk, you can choose whether to report that email message to Microsoft. If you right-click the message and mark it as Not Junk, you can choose whether to add the sender to your own safe sender's list. An Exchange admin can set mail transport rules to mark a sender as safe for the organization, but neither the Report Message add-in nor the junk mail reporting feature in Outlook would create or edit such a rule. I hope this helps!

**Comment by modangsr** [comment]
Hi Denise,
You completely misunderstood my request. In the article in the transport rule section we list 2 SMTP address to BCC junk and phish reported messages via the add-in with an Exchange Transport rule.
Why we not add the 3rd address?
To let customers know how to BCC messages reported a not junk.
Customer security teams wants BCC all 3 type not just 2.
You can ping me internally on Teams if you have more question
Daniel Mozes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
