### ISSUE TITLE
Major changes to this doc over December with no change notes or reference.

### ISSUE THREAD

**Issue by tolarianNZ** [MicrosoftDocs/OfficeDocs-o365seccomp#285]
Having written a strategy and solution paper based on the prior edit of this site, which included comprehensive information relating to DLP/O365 Labels, in Nov/Dec last year, we have noticed all this content has been removed.  We have good use-cases for those aspects of the design, and to see them removed without any supporting reference is a bit difficult to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd417c8-d12a-c8b6-4d76-eb6c979414c8
* Version Independent ID: a2c332e7-9553-85f8-63cd-3cdc265bc872
* Content: [Secure SharePoint Online sites and files](https://docs.microsoft.com/en-us/office365/securitycompliance/secure-sharepoint-online-sites-and-files)
* Content Source: [SecurityCompliance/secure-sharepoint-online-sites-and-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/secure-sharepoint-online-sites-and-files.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by robmazz** [comment]
@tolarianNZ - thank you for your feedback. We have added this to our queue and we'll post an update here soon.

**Comment by denisebmsft** [comment]
@tolarianNZ thanks again for your feedback. This is now fixed! The DLP and Office 365 labels information has been added back to the article. Thank you for reaching out to us about this.
