### ISSUE TITLE
MessageBind not valid anymore

### ISSUE THREAD

**Issue by grzegorzwierzbicki** [MicrosoftDocs/OfficeDocs-o365seccomp#286]
As of January 10, MessageBind is no longer valid and will not be accepted by the server.
Any script using that will require an update.

MessageBind audit operation type is deprecated. Use MailItemsAccessed audit operation type instead.
    + CategoryInfo          : NotSpecified: (:) [Set-Mailbox], RecipientTaskException
 [FailureCategory=Cmdlet-RecipientTaskException] BE3E7708,Microsoft.Exchange.Management.RecipientTasks.SetMailbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing?redirectSourcePath=%252fen-us%252farticle%252fenable-mailbox-auditing-in-office-365-aaca8987-5b62-458b-9882-c28476a66918)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by robmazz** [comment]
@grzegorzwierzbicki - thank you for your feedback. We have added this to our queue and we'll post an update here soon.

**Comment by markjjo** [comment]
@grzegorzwierzbicki Messagebind has been deprecated in EXO. It'sno longer available to be added to AuditAdmin logon type. The documentation has been updated. https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing#mailbox-auditing-actions
