### ISSUE TITLE
Export-Certificate link broken

### ISSUE THREAD

**Issue by grzegorzwierzbicki** [MicrosoftDocs/OfficeDocs-o365seccomp#289]
"Export-Certificate" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b64f4f1-a549-268d-9fe3-94aeb174723b
* Version Independent ID: 0c1b03db-96c8-1460-309d-ba5bb3db16b4
* Content: [Set up virtual certificate collection to validate S/MIME](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-virtual-certificate-collection-to-validate-s-mime)
* Content Source: [SecurityCompliance/set-up-virtual-certificate-collection-to-validate-s-mime.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-virtual-certificate-collection-to-validate-s-mime.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by robmazz** [comment]
@grzegorzwierzbicki - thanks for the feedback, I'll get this over to the Enterprise content team for action.

**Comment by MSFTTracyP** [comment]
Thanks for bringing this to my attention @grzegorzwierzbicki, I've updated the link! I'll shut this down. Please send more feedback if the new link doesn't work!
