### ISSUE TITLE
There is a missing content

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/OfficeDocs-o365seccomp#29]
Hi, 
In sections:
- Get the Report Message add-in for yourself
- Get and enable the Report Message add-in for your organization
There are tips as follow:
"Tip: After the add-in is installed and enabled, people in your organization will see the following icons:"

... but there are no icons which users will see after installing this add-in. Can you correct it, please?

BR
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62304805-117a-0e04-038b-a42a89e12162
* Version Independent ID: 7c12ba44-3c56-7607-7e63-84b0073a25df
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in?redirectSourcePath=%252farticle%252f4250c4bc-6102-420b-9e0a-a95064837676)
* Content Source: [SecurityCompliance/enable-the-report-message-add-in.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-the-report-message-add-in.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@Michal-Ziemba thank you for letting us know about this. i will look into this right away.

**Comment by denisebmsft** [comment]
Thank you for letting us know about this. The issue is fixed.
