### ISSUE TITLE
Preserve the Unread status of emails Reported as Not Junk

### ISSUE THREAD

**Issue by oohgodyeah** [MicrosoftDocs/OfficeDocs-o365seccomp#290]
The Junk E-mail Reporting Add-in (version 10.2.112.0) should not be changing the Unread status of false positive messages when moved back to the Inbox using the 'Report as Not Junk' button.  Currently an Unread message in the Junk folder that is Reported as Not Junk to Microsoft is changed from Unread to Read when the add-in moves it back to my Inbox.  This makes finding these unprocessed emails difficult to find because they look like messages I have already seen (AKA read) before.  But messages in the Junk folder can't be fully read by default because Outlook displays them in plain text.  If one only previews the false positive using the Reading Pane (and does not double click on the message to open in separate window), the message remains Unread in Junk.  Please change the add-in to preserve the Unread status of false positive Report Not As Junk emails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62304805-117a-0e04-038b-a42a89e12162
* Version Independent ID: 7c12ba44-3c56-7607-7e63-84b0073a25df
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in?redirectSourcePath=%252farticle%252f4250c4bc-6102-420b-9e0a-a95064837676)
* Content Source: [SecurityCompliance/enable-the-report-message-add-in.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-the-report-message-add-in.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@oohgodyeah thank you again for posting your feedback. We are not seeing the behavior you describe. Several of us have tried this, and what we're seeing is, email reported as Not Junk is being moved without being marked as read. This happens whether we're using the Report Message add-in or the junk mail mechanism in Outlook. If you are still having trouble with this, please let us know.

**Comment by oohgodyeah** [comment]
@denisebmsft I continue to experience this issue with every message I report as not junk, every time.  What's the best way to show you this issue?
