### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by philipp-schaerer-lambdait** [MicrosoftDocs/OfficeDocs-o365seccomp#295]
At the end of point 1.4 [To add or update your SPF TXT record](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-spf-in-office-365-to-help-prevent-spoofing#to-add-or-update-your-spf-txt-record):
Is there a typo at **include.spf.protection.outlook.de**? I think it should be **include:spf.protection.outlook.de**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f757d12f-4987-89dd-4baf-1b79a8e947b2
* Version Independent ID: 593bc9f0-6457-a942-cde8-be2a3a77af15
* Content: [Set up SPF in Office 365 to help prevent spoofing](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-spf-in-office-365-to-help-prevent-spoofing)
* Content Source: [SecurityCompliance/set-up-spf-in-office-365-to-help-prevent-spoofing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-spf-in-office-365-to-help-prevent-spoofing.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@philipp-schaerer-lambdait, thank you so much for catching that! Yes, it was a typo, and it's now fixed. Thank you for helping us improve our documentation!

**Comment by philipp-schaerer-lambdait** [comment]
Only thanks to the nice and easy way to contribute, I like the way how the feedback possibilities for the documentations are handled. Nice work.
