### ISSUE TITLE
EOP IP address ranges (Complete List)

### ISSUE THREAD

**Issue by Dagriff** [MicrosoftDocs/OfficeDocs-o365seccomp#3]
How can the "Complete List" be shorter than the list for the Americas Region?  Further, there are discrepancies in several of the CIDR addresses network masks between the "Complete List" and the Regional Lists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90bba8f1-54aa-85f9-a311-2b4240c40202
* Version Independent ID: ae5462b5-141b-cef2-72dc-3f62f19b708c
* Content: [Exchange Online Protection IP addresses](https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/exchange-online-protection-ip-addresses)
* Content Source: [SecurityCompliance/eop/exchange-online-protection-ip-addresses.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/exchange-online-protection-ip-addresses.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Dagriff The overall list is shorter because it contains a larger address space (ranges with a lower prefix length). Some of the ranges in the complete list are subnetted and allocated to the different regions. The region tables have been updated with removed address ranges.

**Comment by Dagriff** [comment]
Well, that’s embarrassing!  You are quite right and thanks for explaining.  We will user Complete List rather than regionals now.

**Comment by johnjcampbell** [comment]
Can you confirm that "The region tables have been updated with removed address ranges", as the APAC region's list still seems to contain 3 address ranges that aren't covered by any of the larger address spaces in the "Complete List":
134.170.132.0/24
134.170.140.0/24
207.46.51.64/26
Are these 3 address ranges in addition to the complete list, but specific to and required for just the APAC region?

**Comment by denisebmsft** [comment]
Thanks @johnjcampbell... we are looking into this.

**Comment by JoeDavies-MSFT** [comment]
@johnjcampbell  These are removed. They were waiting on a publishing cycle and I just didn't get back to you when they were published. Thanks for your ongoing efforts to help us improve our documentation. Joe
