### ISSUE TITLE
Link to test lab is not working 

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/OfficeDocs-o365seccomp#30]
[Enter feedback here]

https://docs.microsoft.com/en-us/enterprise/cloud-app-security-for-your-office-365-dev-test-environment.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a6ab073-3a52-c9ac-0388-951bd7f3170d
* Version Independent ID: b8ff52ba-3ca2-87a2-f3c3-ad6a09105aba
* Content: [Get ready for Office 365 Cloud App Security](https://docs.microsoft.com/en-us/office365/securitycompliance/get-ready-for-office-365-cas?redirectSourcePath=%252farticle%252fGet-started-with-Advanced-Management-Security-d9ee4d67-f2b3-42b4-9c9e-c4529904990a)
* Content Source: [SecurityCompliance/get-ready-for-office-365-cas.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/get-ready-for-office-365-cas.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@alexverboon it looks like your comment or question didn't come through. Can you re-enter it?

**Comment by denisebmsft** [comment]
Issue is fixed. Thank you for letting us know about this.
