### ISSUE TITLE
Is the data wiped (overwritten)?

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/OfficeDocs-o365seccomp#303]
Is the data also overwritten so that a new tenant cannot recover it by creating large data sets? This is very important to know if data is simply deleted by removing the pointer to the data or if it is overwritten such that no one else can try to recover the data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4dcd460-112d-867f-cace-4bb13ffa5d32
* Version Independent ID: 65eeb5df-4cfe-578e-35aa-867f783f90b2
* Content: [Data Retention, Deletion, and Destruction in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-data-retention-deletion-and-destruction-overview)
* Content Source: [SecurityCompliance/office-365-data-retention-deletion-and-destruction-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-data-retention-deletion-and-destruction-overview.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@lesterw1  - thanks for the feedback! I'm adding the following to the Data Destruction topic (https://docs.microsoft.com/office365/securitycompliance/office-365-data-destruction) to clarify how virtual data destruction and available free-space are handled in Office 365:

"Microsoft has data handling policies and procedures that also address effective virtual destruction of data to protect against the possibility of data being inappropriately shared between service tenants, or being accessible after hard deletion in the service. Data that is deleted from the service in one tenant is not accessible to another service tenant even if some or all of the same underlying physical storage is later reassigned. This is an outcome of the compounded effects of multiple virtualization and fragmentation technologies used to scale virtual environments, the active delete behaviors of applications within each service tenant (such as page zeroing), and the required media and application content encryption processes."
