### ISSUE TITLE
Broken link on this page.

### ISSUE THREAD

**Issue by jmpawson** [MicrosoftDocs/OfficeDocs-o365seccomp#304]
WDSI link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c57b5515-12f8-2221-aa94-7883cc58fe1b
* Version Independent ID: 44327e0a-c461-013c-cb20-a0427d74f4f0
* Content: [Submitting malware and non-malware to Microsoft for analysis](https://docs.microsoft.com/en-us/office365/securitycompliance/submitting-malware-and-non-malware-to-microsoft-for-analysis)
* Content Source: [SecurityCompliance/submitting-malware-and-non-malware-to-microsoft-for-analysis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/submitting-malware-and-non-malware-to-microsoft-for-analysis.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@jmpawson thank you for the feedback! We've fixed the link so it should be working now. Thank you for helping us improve our documentation!
