### ISSUE TITLE
Default Auditing

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/OfficeDocs-o365seccomp#305]
According to a different Microsoft article, auditing is enabled by default now:

https://social.technet.microsoft.com/wiki/contents/articles/52198.office-365-enable-mailbox-audit.aspx
(See last two paragraphs)

"Over the next several months, Microsoft will enable the default-auditing configuration on all tenants with a steady ramp-up with all commercial customers to be covered by the end of the calendar year. So we can expect this to be covered for all tenants by the end of this calendar year.

Mailbox audits will be stored for all user mailboxes within the commercial service by default.
The default audit configuration will change and include more audit events."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing#mailbox-auditing-actions)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@kevintaber The product group is still in the process of rolling this out. The topic will be updated when that is complete and available to organizations worldwide.
