### ISSUE TITLE
Adding actions to AuditOwner not working

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/OfficeDocs-o365seccomp#306]
When attempting to add actions to the AuditOwner property, a warning is shown and it is not added.

Set-Mailbox -Identity test@contoso.com -AuditOwner @{Add="MailboxLogin","HardDelete","SoftDelete"}
WARNING: The command completed successfully but no settings of 'Test User' have been modified.

Get-Mailbox -Identity test@contoso.com | Select-Object -ExpandProperty AuditOwner
UpdateFolderPermissions
UpdateInboxRules
UpdateCalendarDelegation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing#mailbox-auditing-actions)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by kevintaber** [comment]
This works:

Get-Mailbox -ResultSize Unlimited -Filter {RecipientTypeDetails -eq "UserMailbox"} | Set-Mailbox -AuditEnabled $true -AuditDelegate Update,MoveToDeletedItems,SoftDelete,HardDelete,SendAs,SendOnBehalf,Create,UpdateFolderPermissions,UpdateInboxRules -AuditOwner MailboxLogin,SoftDelete,HardDelete,UpdateFolderPermissions,UpdateInboxRules,UpdateCalendarDelegation -AuditAdmin Update,MoveToDeletedItems,SoftDelete,HardDelete,SendAs,SendOnBehalf,Create,UpdateFolderPermissions,UpdateInboxRules,UpdateCalendarDelegation

**Comment by denisebmsft** [comment]
@kevintaber thank you so much for the feedback. We are looking into this, and an update will be posted here soon.

**Comment by YuriySamorodov** [comment]
@kevintaber 
is this a bug indeed? the following events are tracked for mailbox owner by default:

- Update
- Move
- SoftDelete
- HardDelete
- Create
- MailboxLogin

Reference:
[https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mailbox-audit-logging/mailbox-audit-logging?view=exchserver-2019](url)

According to your command, you are trying to add events that are already there. 
If you try to add extra item to the collection it would work just fine:
```set-mailbox -Identity vladimir.podgorny@veeam.com -AuditOwner @{ Add = 'MoveToDeletedItems' }```

It looks like the original response is legit.

**Comment by markjjo** [comment]
@kevintaber We've updated the mailbox auditing topic. If you change the actions that are audited for any logon type, then you'll have to add any new actions release by Microsoft. That's explained here: https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing#change-or-restore-mailbox-actions-logged-by-default
