### ISSUE TITLE
No Section Called "Threat Explorer"

### ISSUE THREAD

**Issue by jaypatrick** [MicrosoftDocs/OfficeDocs-o365seccomp#307]
In step 2: Choose Threat management &gt; Threat explorer -- There is no section called Threat Explorer. There is a threat tracker, but it doesn't have a "more" menu, nor anywhere to choose WDATP Settings. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b67a503-1b5a-41c0-d3e6-19fcf5433b73
* Version Independent ID: 83e20865-ee1b-2341-f009-73d2f2f31671
* Content: [Integrate Office 365 Threat Intelligence with Windows Defender Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/integrate-office-365-ti-with-wdatp)
* Content Source: [SecurityCompliance/integrate-office-365-ti-with-wdatp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/integrate-office-365-ti-with-wdatp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@jaypatrick thank you for the feedback. I'll take a look at this, and will post an update here soon. Really appreciate you letting me know about this.

**Comment by denisebmsft** [comment]
@jaypatrick thanks again for the feedback. "Threat Explorer" has been recently renamed to "Explorer," and the article has been updated to include screenshots. Thanks for helping us improve our documentation!
