### ISSUE TITLE
Cloud App Security Portal URL

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/OfficeDocs-o365seccomp#308]
Please include the Cloud App Security URL in the section titled "How to find the Office 365 Cloud App Security portal". You don't have to find it through protection.microsoft.com. It is located at:
https://portal.cloudappsecurity.com/

It took me 20 minutes to find the URL for this portal, even using the instructions above. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d9ce7b-7062-0580-9189-7a1459f708ca
* Version Independent ID: eb4843fc-01d7-6673-badf-25722911d5c2
* Content: [Overview of Office 365 Cloud App Security](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-cas-overview)
* Content Source: [SecurityCompliance/office-365-cas-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-cas-overview.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@lesterw1 thank you so much for the feedback. I'm looking into this, and I'll post an update here soon.

**Comment by denisebmsft** [comment]
@lesterw1 I wanted to let you know this is now fixed. Thanks again for the feedback!
