### ISSUE TITLE
Consider updating for ATP tips

### ISSUE THREAD

**Issue by jpwgc** [MicrosoftDocs/OfficeDocs-o365seccomp#31]
Would you consider updating this document to reflect some of the new safety tips included with advanced threat protection? Also it would be great to have a list of all the various options and key factors which caused the message to be flagged to help determine if it is a false positive or not. The new flags are also gray, which doesn't match the description here. This is the only published example I've been able to find of these new gray flags, but I know there are others: http://aka.ms/LearnAboutSenderIdentification

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bee8f6fb-3ea4-492c-449a-3510529bf3cb
* Version Independent ID: 947bc3fa-55c5-f55e-a9cb-248e2ccf27c6
* Content: [Safety tips in email messages in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/safety-tips-in-office-365)
* Content Source: [SecurityCompliance/safety-tips-in-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/safety-tips-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@jpwgc Thank you for this feedback

We apricate you taking time to make the docs better. I'm going to get this over to the o365seccomp team for investigation and updating. 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
We didn't forget about you! We have this in our queue and will have an update coming. Thank you for letting us know about this in the feedback.

**Comment by fthorsen76** [comment]
For the next update, will you address the colors of the flags, what causes the messages to be flagged or both? Any updated timeline?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by amberru1** [comment]
still waiting on the updated ATP tip examples...  Thank you!

**Comment by scanum** [comment]
@MSFTTracyP Hi Tracy, any updates on this? Thanks!

**Comment by jjtitos** [comment]
Also, need an update on this, please! We have no idea what these anti-spam message headers mean!

https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-spam-message-headers

22	X-Microsoft-Antispam-Mailbox-Delivery	ucf:0;jmr:0;ex:0;auth:0;dest:I;ENG:(20160514016)(750119)(520011016)(944506303)(944626516);

**Comment by MSFTTracyP** [comment]
I have this in my queue of work at this point and will be shutting this thread in favour of the queue. Thank you for your patience. I hope to update this article in the near future.

**Comment by MSFTTracyP** [comment]
@JJTitos If you're not aware of what your message headers mean, it may be time to open a ticket with Support and keep record of the outcome of their investigation. You can open tickets here:

https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone
