### ISSUE TITLE
eDiscovery Manager role group and alerts

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-o365seccomp#310]
The doc says "Members of the eDiscovery Manager role group can't view any alerts because none of the assigned roles provide permission to view alerts from any alert category." However, there is a default alert policy called "eDiscovery search started or exported." Why are these two not linked? Is another alert category for eDiscovery needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e607177-4e5b-69af-5408-caa6337bbd0e
* Version Independent ID: c82bbeaa-9df1-c070-644b-a666406464b5
* Content: [Alert policies in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/alert-policies)
* Content Source: [SecurityCompliance/alert-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/alert-policies.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Michael-Sampson The default eDiscovery related alert policy is assigned to theThreat management category. That means that users who are assigned the Security Administration or Security Reader roles will be able to see alerts triggered by this policy. I think the idea is that running searches or exporting search data could be a possible insider threat incident and so you'd want to expose these alerts to the to the folks who are monitoring threats and possible data leakage outside to the org (and not necessarily the members of the eDiscovery managers role group who are running searches/exporting data as part of their day to day jobs. That said, you could always add the Security Reader role to the eDiscovery Managers role group or create a custom role group that's assigned the Security Reader role and added eDiscovery managers as members. Please feel free to give product feedback about this or open an Microsoft Support ticket and submit a DCR. Thanks.
