### ISSUE TITLE
RBAC for Creating Alert Policies too?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-o365seccomp#311]
Does the pending change to RBAC for viewing alerts extend also to the ability to create New Alert Policies? For example, if you're a Compliance person, you shouldn't be able to create alert policies for Mail Flow or Permissions. Or is this creation right not included?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e607177-4e5b-69af-5408-caa6337bbd0e
* Version Independent ID: c82bbeaa-9df1-c070-644b-a666406464b5
* Content: [Alert policies in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/alert-policies)
* Content Source: [SecurityCompliance/alert-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/alert-policies.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Michael-Sampson The RBAC permissions required to view alerts and required to create alert policies are unrelated. To create alert policies (of any category type), you have to be assigned either the Organization Configuration role or the Manage Alerts role (I will add this permissions requirement to the alert policies topic. Coincidentally, you'll notice in the RBAC permissions table in this topic that people assigned these two roles can only view alerts that are in the Others category. Thanks!
