### ISSUE TITLE
Update Documentation for Unified Labels with Azure Information Protection?

### ISSUE THREAD

**Issue by cap273** [MicrosoftDocs/OfficeDocs-o365seccomp#312]
It is not clear in this document how the experience with Office 365 labels change once Unified Labeling with Azure Information Protection is turned on. (Documentation here: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels)

In particular, this documentation goes through how to apply Office 365 labels to SharePoint Online sites and files. However, the FAQ for "classification and labeling in Azure Information Protection" states that: "There are a few limitations with the current release, which include the following: No classification and labeling integration with Exchange Online or SharePoint Online." (Documentation: https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect)

So if a customer turns on Unified Labeling for their tenant (and essentially merges AIP labels and Office 365 labels into a single unified labeling experience), does that mean that currently SharePoint Online files and sites CANNOT be tagged with either the "old" Office 365 labels OR the "new" unified labels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fce61-99c1-279d-9978-7e59e445fb84
* Version Independent ID: 77c05a43-ff13-c240-4de7-a5d5d47ed2cb
* Content: [Protect SharePoint Online files with Office 365 labels and DLP](https://docs.microsoft.com/en-us/office365/securitycompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp)
* Content Source: [SecurityCompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@cap273 thank you very much for the feedback. We're looking into this, and we'll post an update here soon. Thanks for raising these good questions.

**Comment by JoeDavies-MSFT** [comment]
@cap273 This article has been updated for Office 365 retention labels. Unified labels with AIP use sensitivity labels. However for this solution, we are choosing to use a sub-label of an AIP label to provide the encryption and permissions.
