### ISSUE TITLE
Seven days to auto-apply a label retroactively

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/OfficeDocs-o365seccomp#313]
My understanding is that it takes seven days to apply a label *retroactively*. Once the label is set up it takes much less than seven days. Can you please update the documentation to be more clear about this? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels#auto-apply-retention-labels)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by EricaToelle** [comment]
@denisebmsft Chris McNulty (MSFT) can verify this information.

**Comment by stephow-MSFT** [comment]
Not sure what you mean by applying a label "retroactively." Are you talking about auto-applying retention labels?

**Comment by EricaToelle** [comment]
When you first create a new auto-applied label it has to be retroactively applied to the content that already exists. This can take up to seven days. Going forward, it would not take up to seven days to apply the label to new content that has been added to the system. In my tests, it usually takes 15 minutes.

I present on this topic at Microsoft conferences around the world and was asked by the product team to clarify this point in my presentation. Therefore, I think this should be reflected in the documentation.

**Comment by stephow-MSFT** [comment]
Yep, agreed, thanks for the feedback, keep it coming.

Article updated with "If you auto-apply retention labels to content matching specific conditions, it can take seven days for the retention labels to be applied to all existing content that matches the conditions. But note that after your retention labels are deployed, they are applied to new content quickly, typically in 15 minutes or less."
