### ISSUE TITLE
Different third screenshot?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-o365seccomp#314]
The third screenshot - of Outlook on Mac with the email message saying that sensitivity labels are now available - doesn't show a Sensitivity button on the toolbar. My edition of Outlook for Mac doesn't have the Sensitivity button at all, so I can't test this, but I assume the Sensitivity button only shows when composing an email message. What about replacing that screenshot with the compose message version of that email, which would then show both the sensitivity button and the Public label on the email message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01a3978-dbe9-0507-49d2-9e57ec52d9a1
* Version Independent ID: a617379c-9182-eed2-5cd0-c05b36a6e4cb
* Content: [Overview of sensitivity labels](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/sensitivity-labels#protect-content-on-windows-devices-by-using-endpoint-protection-in-microsoft-intune)
* Content Source: [SecurityCompliance/sensitivity-labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/sensitivity-labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
Hi Michael, I'm not quite sure which screenshot you mean. The third image has an applied label with the tag icon highlighted. The purpose of that image is to explain that an applied label is essentially like a tag.
