### ISSUE TITLE
Love it!

### ISSUE THREAD

**Issue by cdev45** [MicrosoftDocs/OfficeDocs-o365seccomp#316]
Love this feature. Data is no longer maintained behind firewalls, and is guaranteed to migrate beyond the corporate network. DLP and other related technologies such as encryption is pivotal in today's modern workforce. Thank you Microsoft for this excellent security feature, and excellent content on the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01a3978-dbe9-0507-49d2-9e57ec52d9a1
* Version Independent ID: a617379c-9182-eed2-5cd0-c05b36a6e4cb
* Content: [Overview of sensitivity labels](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/sensitivity-labels)
* Content Source: [SecurityCompliance/sensitivity-labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/sensitivity-labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@cdev45 thank you so much for the feedback! We are glad you found the content (and feature!) helpful. Thanks for taking the time to share this with us.
