### ISSUE TITLE
Support of OME mesages to Shared Mailboxes

### ISSUE THREAD

**Issue by ernelso** [MicrosoftDocs/OfficeDocs-o365seccomp#32]
I understand this is a known support gap when OME messages are sent to a shared mailbox.  We should update this FAQ to annotate status.  (I'm currently reaching out to PM's to get a status on work to address this)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ad427d-d869-2ab6-3d2c-f846efc99256
* Version Independent ID: 606eaa37-2713-8087-015f-012ae9c90090
* Content: [Office 365 Message Encryption FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-faq#feedback)
* Content Source: [SecurityCompliance/ome-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-faq.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Chris-tina-Testing** [comment]
Please cast your vote for OME messages to shared mailboxes:

https://office365.uservoice.com/forums/264636-general/suggestions/35684506-allow-encrypted-emails-to-be-viewed-in-a-shared-ma

**Comment by scanum** [comment]
@ernelso Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by ernelso** [comment]
How has this issue been resolved?  This issue still exists.

**Comment by stevep4** [comment]
I wanted to know the same answer... how has it been resolved. Very unsatisfactory answer from @scanum there.
#open
