### ISSUE TITLE
IP Allow List Intended Behavior

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-o365seccomp#322]
I think there's a problem here because of the name of this feature.  "Connection Filtering" implies to me that addresses which are NOT on the IP Allow LIst *won't be able to connect*.  This documentation seems to imply rather that mail from such addresses simply bypasses spam checking.  

If that's the case, I really think that this document needs to have a bright-red disclaimer in the "What you need to know" section making this clear and providing a link to a discussion on how to block all inbound connections except for those from desired IP addresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3368430-e303-8e6f-65d9-22b7e6c6c6b7
* Version Independent ID: 94dddc16-eb0a-b5c3-262b-c1712566e68e
* Content: [Configure the connection filter policy](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-the-connection-filter-policy)
* Content Source: [SecurityCompliance/configure-the-connection-filter-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-the-connection-filter-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@FC-EricWeller thank you so much for the feedback. We're looking into this, and an update will be posted here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @FC-EricWeller, thank you for your feedback.

Let me understand what you want to do. Do you want to block all the "Internet" IP addresses on EOP and just allow few IPs to send emails to your tenant?
If it's the case, it's a very strange/special situation.

**Comment by FC-EricWeller** [comment]
Is it?  We use a security service (Mimecast) as our MX.  The reason that I wound up researching this in the first place was because at some point we realized we had received mail which had been delivered direct to the EOP MX, bypassing our publicly published MX records.  We would want to refuse such a connection.

THAT said, I think my comment was borne out of frustration at realizing I had misunderstood the intent of the feature, which was my own damned fault for not reviewing the documentation.  Looking at the document today, it's very clear what the purpose of the feature is.

**Comment by dariomws306** [comment]
Hi @FC-EricWeller,

It's true maybe could be some scenarios where this can apply. I am thinking on Exchange Hybrid where the MX is pointing to on-premises, customers never request it to me, but maybe they want to close connections on port 25 to all IPs except Exchange on-premises servers.

On the second sentence, yes, it's the typical IP allow/block list of each anti-spam solution.

Did you try to do it using Receive Connectors?

**Comment by MSFTTracyP** [comment]
@FC-EricWeller, my apologizes. No need to assign yourself the blame. The truth is somewhere in the middle, I think. Talking about filters is challenging, because you can be talking about two things at the same time. The first thing is what is caught in the filter, and the second is what the filter allows to pass through. It's a challenge when it comes to explanations because some visualize filtering as letting the Allow list people through filters, and some see it as catching only the Allowed accounts so that they can bypass filtering, while everyone else passes through. So this issue crops up from time to time. I'm sorry for any frustration, but glad that the documentation helped to answer your questions. Thank you!
