### ISSUE TITLE
Email fails beyond first page

### ISSUE THREAD

**Issue by CaSauls** [MicrosoftDocs/OfficeDocs-o365seccomp#323]
Sounds like I have the same problem as everyone else. Outlook is refusing to recognize normal and secure addresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5939440-a0f8-0938-e61e-27aeca97888a
* Version Independent ID: 0314d705-b3fd-8533-22bd-a14039362e0f
* Content: [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-atp?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-Advanced-Threat-Protection-e100fe7c-f2a1-4b7d-9e08-622330b83653)
* Content Source: [SecurityCompliance/office-365-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-atp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@CaSauls I have reached out to our product team about this, and they are investigating. Several other folks have said that they are no longer having this issue.... can you check and let us know if it's resolved for you as well?

**Comment by CaSauls** [comment]
It seems to be working as usual today. Thank you!
________________________________

**Comment by denisebmsft** [comment]
@CaSauls thank you!
