### ISSUE TITLE
Need to update version number of AZure copy command 

### ISSUE THREAD

**Issue by kadorken** [MicrosoftDocs/OfficeDocs-o365seccomp#324]
(I got 8.1 in the download stepzc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a65de3-b878-b20a-3823-11a9dbc3e37c
* Version Independent ID: 28499237-e103-b204-12b2-11d72f685370
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files#step-4-create-the-pst-import-mapping-file)
* Content Source: [SecurityCompliance/use-network-upload-to-import-pst-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@kadorken Thanks for the heads up. I will update the documentation. v8.1 is fine. The key point is to use the version that will be downloaded when you click "Download Azure AzCopy" under step 3 in the Import data wizard.

**Comment by ilantz** [comment]
Was just about to add the same feedback. the link on the wizard redirects to https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy so you would use the new version and not v8.1

The new version is working as long as you'll use the right parameters.. for example:

AzCopy.exe copy "C:\nonO365data" "https://speur01salinkexternal003.blob.core.windows.net/7a6b766d-04fc-4840-91bc-xxxxxxx-xxxxxx-externalstore/?sv=2017-07-29&sr=c&si=ExternalStore63%7C1&sig=QK%xxxxXXXXXxxx%2FLDk%3D" --recursive

Believe we should update both the docs and the wizard in the product itself.
