### ISSUE TITLE
SMTP Being Used

### ISSUE THREAD

**Issue by thebitjockey** [MicrosoftDocs/OfficeDocs-o365seccomp#325]
Is there a way to block a O365 credentials from being used to authenticated to O365 SMTP servers and send email?  We block most access with MFA but it appears this is not used by the SMTP servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f5a81ec-6747-1bf6-cb92-612d26554e4b
* Version Independent ID: 851bec9d-104e-94e7-a0d8-b8d73b91576c
* Content: [Responding to a Compromised Email Account in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/responding-to-a-compromised-email-account)
* Content Source: [SecurityCompliance/responding-to-a-compromised-email-account.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/responding-to-a-compromised-email-account.md)
* Service: **o365-solutions**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by asdcristi** [comment]
https://support.microsoft.com/en-ca/help/324958/how-to-block-open-smtp-relaying-and-clean-up-exchange-server-smtp-queu

**Comment by denisebmsft** [comment]
@thebitjockey thanks for posting your question, and @asdcristi thank you for sharing the link. We're looking into this, and an update will be posted here soon.

**Comment by denisebmsft** [comment]
@thebitjockey thank you for posting your question, and @asdcristi thank you for sharing the link. We are looking into this, and an update will be posted here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrfox** [comment]
@thebitjockey thanks for your question. The best place to ask your question is in the [TechCenter forums for Exchange](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsocial.technet.microsoft.com%2FForums%2Foffice%2Fen-us%2Fhome%3Fcategory%3Dexchangeserver&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7Ca062ac4c8d574f363b9408d6bf8bde4d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636907004778934791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=g3x34Up0ds0YM0Cq32XQurEXx1fDZFiStfx3Du9k7J0%3D&reserved=0)
