### ISSUE TITLE
Plans?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/OfficeDocs-o365seccomp#326]
Please make it obvious which Office 365 plans this applies to.

I can't find where an exception is mentioned for Home/Personal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1ed2ee-04a9-d958-1652-3d9562134660
* Version Independent ID: a5457702-6307-4e41-a2c2-3a115f9a9797
* Content: [Office 365 ATP Safe Links](https://docs.microsoft.com/en-us/office365/securitycompliance/atp-safe-links)
* Content Source: [SecurityCompliance/atp-safe-links.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/atp-safe-links.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by asdcristi** [comment]
[Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)

**Comment by denisebmsft** [comment]
@BR77BE thank you for the feedback, and @asdcristi thank you as well. I'll update the article very soon to make it more clear.

**Comment by denisebmsft** [comment]
@BR77BE and @asdcristi I wanted to let you know that I updated the article and republished it. Please let me know if you have any further questions.
