### ISSUE TITLE
Users to protect: please update article from 20 to 60. 

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-o365seccomp#33]
RE: "You can add up to 20 internal and external addresses that you want to protect from impersonation."
Customer feedback also led us to increase coverage of our anti-impersonation rule to 60 users and we simplified the spoof protection configurations within the ATP anti-phishing policy. https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Enhancements-to-the-Office-365-ATP-admin-experience/ba-p/218569 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-anti-phishing-policies?redirectSourcePath=%252farticle%252fset-up-office-365-atp-anti-phishing-policies-5a6f2d7f-d998-4f31-b4f5-f7cbf6f38578#feedback)
* Content Source: [SecurityCompliance/set-up-atp-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-anti-phishing-policies.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@hudish Thank you for this feedback

We appriciate you taking the time to make the docs better. I will get this over to the o365seccomp team for updating. 


I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
