### ISSUE TITLE
Related articles link gives 404 error

### ISSUE THREAD

**Issue by RobertDring** [MicrosoftDocs/OfficeDocs-o365seccomp#330]
Link to https://docs.microsoft.com/SkypeForBusiness/MicrosoftTeams/information-barriers-in-teams in the Related Articles section  leads to a 404 Content not Found error page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ddb4a04-f1de-180f-5f98-4f8d6893ce42
* Version Independent ID: 6b6fb7da-b919-f35a-5a86-d6d21a5dc193
* Content: [Information barriers](https://review.docs.microsoft.com/en-us/Office365/SecurityCompliance/information-barriers?branch=infobarriers-working)
* Content Source: [SecurityCompliance/information-barriers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/information-barriers.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@RobertDring correct - this content isn't live yet so the link isn't working yet. Thank you for reaching out on this.
