### ISSUE TITLE
Categories for the default alert policies

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#333]
Please identify which alert category applies to each of the default alert policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e607177-4e5b-69af-5408-caa6337bbd0e
* Version Independent ID: c82bbeaa-9df1-c070-644b-a666406464b5
* Content: [Alert policies in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies#viewing-cloud-app-security-alerts)
* Content Source: [SecurityCompliance/alert-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/alert-policies.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
Hello @DeanGross, and thank you for the feedback! We have this in our queue, and we'll post an update here soon.

**Comment by markjjo** [comment]
@DeanGross Done. Category column added to the table of default alert policies. Also, the category for each policy is displayed in the list of alert policies in the SCC. You can also get this info for the default policies by running this command in SCC PowerShell: Get-ProtectionAlert | where {$_.IsSystemRule -eq "True"} | FL Name,Category
