### ISSUE TITLE
Coming Soon Statement

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#334]
This states that unified labels are coming soon. It has been one year since the article was written, please provide some Notes to update the status of this functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5296046e-fbd3-6129-49f3-107eac720f4e
* Version Independent ID: 283f997c-cd12-00c7-36f0-ff938422ebff
* Content: [Apply labels to personal data in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/apply-labels-to-personal-data-in-office-365)
* Content Source: [SecurityCompliance/apply-labels-to-personal-data-in-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/apply-labels-to-personal-data-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by denisebmsft** [comment]
@DeanGross thank you for the feedback! We are looking into this, and we'll post an update here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by BrendaCarter** [comment]
This has been fixed. The article was updated 3/28/2019.
