### ISSUE TITLE
Page length/navigation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#335]
This page is very long and difficult to navigate with multiple vertical scroll bars. It would be helpful to separate it into more pages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
Feedback taken but it's beyond scope of current work to break up this article. Using the TOC in right nav might help.
