### ISSUE TITLE
Protecting Shared Mailboxes

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/OfficeDocs-o365seccomp#336]
Are shared mailboxes protected by these features if the end users who are accessing them are protected by EOP and ATP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bcce70-896f-5699-6d54-e6b8f540bbdb
* Version Independent ID: 28cbbb6c-8298-c452-98b4-ee5e78169ce5
* Content: [Feature permissions in EOP](https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/feature-permissions-in-eop)
* Content Source: [SecurityCompliance/eop/feature-permissions-in-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/feature-permissions-in-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@AndySanchezVM thank you for the good question! We are looking into this, and we'll post an update here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @AndySanchezVM, thank you for your feedback.

I understand that you need an additional ATP license for Shared Mailbox but no additional EOP license.

**Comment by scanum** [comment]
@AndySanchezVM We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
