### ISSUE TITLE
RBAC Table Improvement

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#340]
The RBAC table would be easier to use if it just included the title of the roles and the definitions were moved to the body of the text (outside of the table itself). By having all of the text in each row it makes it hard to keep track of the columns and their headers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab39527-b636-35d8-43f7-88e8ad8e92e3
* Version Independent ID: f710f562-129e-8d15-54d2-46f8d61c828b
* Content: [Assign eDiscovery permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/assign-ediscovery-permissions)
* Content Source: [SecurityCompliance/assign-ediscovery-permissions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/assign-ediscovery-permissions.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@DeanGross thank you for the feedback! We have this in our queue, and we'll look into it.

**Comment by markjjo** [comment]
Fixed; descriptions moved out of table.
