### ISSUE TITLE
tips and trick - last bullet point to be updated as it is incorrect. 

### ISSUE THREAD

**Issue by stvollet** [MicrosoftDocs/OfficeDocs-o365seccomp#342]
tips and tricks section : 
 You can export items based on the item type. For example, to export Skype IM messages recived by a user, use the syntax 'Kind:IM'. This search query return all IM message.

this would return not only Skype For Business Online IM but also Teams IM . I suggest you take a different example such as kind:microsoftteams for all message related to Teams. thanks 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b84ade-fa24-3ca7-adb8-1a3398faa0a0
* Version Independent ID: b601bd4d-aa7e-63aa-0404-4cd84d817a9d
* Content: [Keyword queries and search conditions for Content Search](https://docs.microsoft.com/en-gb/office365/securitycompliance/keyword-queries-and-search-conditions?redirectSourcePath=%252fen-us%252farticle%252fKeyword-queries-and-search-conditions-for-Content-Search-c4639c2e-7223-4302-8e0d-b6e10f1c3be3)
* Content Source: [SecurityCompliance/keyword-queries-and-search-conditions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/keyword-queries-and-search-conditions.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@stvollet thank you so much for calling this out. We'll take a look, and an update will be posted here soon.

**Comment by markjjo** [comment]
fixed; changed example
