### ISSUE TITLE
Same feature mentioned twice.

### ISSUE THREAD

**Issue by student-forever** [MicrosoftDocs/OfficeDocs-o365seccomp#343]
Under "Side-by-side comparison of features and capabilities",

the feature : Experience for internal recipient has been given twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efa2f7c1-8703-b46d-870f-8bf83e48888d
* Version Independent ID: 3f4219fa-e443-31a5-a767-5450438173ff
* Content: [Office 365 Message Encryption version comparison](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-version-comparison)
* Content Source: [SecurityCompliance/ome-version-comparison.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-version-comparison.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
Yikes! Thanks for catching these errors. I've fixed these and republished the document.
