### ISSUE TITLE
Update Video

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#344]
In the Prevent data loss (DLP) section the link points to a video from 2017. I'm sure there is newer content that would be more relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deff2463-655e-f984-8d32-6b8f1eac6283
* Version Independent ID: 8bd62a52-dc23-8b62-d358-9a8f0e3d237c
* Content: [Form a query to find sensitive data stored on sites](https://docs.microsoft.com/en-us/office365/securitycompliance/form-a-query-to-find-sensitive-data-stored-on-sites)
* Content Source: [SecurityCompliance/form-a-query-to-find-sensitive-data-stored-on-sites.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/form-a-query-to-find-sensitive-data-stored-on-sites.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
There are newer Ignite videos but we still choose to link to this one because it provides the best comprehensive overview.
