### ISSUE TITLE
Out of date info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#345]
There are several statements about 'coming later in 2018' it is now 2019, those statements should be reworded to reflect what was actually implemented last year. 
Also, this article is very long, it would be easier to read if it was divided into several articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab02396-69f6-5a83-fc27-7a2ba9ab78eb
* Version Independent ID: 63266ff4-ef2a-84b3-f1b9-c7b3e4d8a1b7
* Content: [Anti-spoofing protection in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/anti-spoofing-protection)
* Content Source: [SecurityCompliance/anti-spoofing-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spoofing-protection.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by MSFTTracyP** [comment]
Yes, I agree with you, @DeanGross. I'm putting this on my To Do, and want to thank you for raising it back to my attention. I appreciate your note!
