### ISSUE TITLE
article length

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#346]
This article is very long, please break it up into several articles so that it is easier to read online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5617e6-38cf-c93e-5c68-933288f89014
* Version Independent ID: 6b7f1370-2b76-a6f1-4a32-4569aeec27db
* Content: [Use Compliance Manager to help meet data protection and regulatory requirements when using Microsoft cloud services](https://docs.microsoft.com/en-us/office365/securitycompliance/meet-data-protection-and-regulatory-reqs-using-microsoft-cloud#assessments-in-compliance-manager)
* Content Source: [SecurityCompliance/meet-data-protection-and-regulatory-reqs-using-microsoft-cloud.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/meet-data-protection-and-regulatory-reqs-using-microsoft-cloud.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@DeanGross thank you very much for the feedback. We have a work item to look into this, and we'll post an update here soon.

**Comment by markjjo** [comment]
@DeanGross Engineering and content team are working on vNext version of compliance manager. The article will be updated to support this new version and it's length will be evaluated. Until then, the bookmarks in the right pane can help you navigate the topic.
