### ISSUE TITLE
Formula error

### ISSUE THREAD

**Issue by mtisov** [MicrosoftDocs/OfficeDocs-o365seccomp#348]
Hi Team,
The formula in this document contains error:
Maximum Capacity / (Maximum Capacity X Growth Rate) = Time to Impact

Simple math reduction removes Maximum Capacity from the equation. Moreover, unit measure of Growth Rate should be Bytes / Second (or any other data volume to time unit measures). There for the formula won't give a time measure. The correct formula should be:

Maximum Capacity / Growth Rate = Time to Impact

Thanks in advance and regards,
MT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af62f28f-bce0-f060-c973-981a25ab198c
* Version Independent ID: 72b196dc-246c-c7b1-2ab5-c6d5e93e2b3f
* Content: [Office 365 Core Principles of Defense Against Denial-of-Service Attacks](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-core-principles-of-defense-against-dos-attacks)
* Content Source: [SecurityCompliance/office-365-core-principles-of-defense-against-dos-attacks.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-core-principles-of-defense-against-dos-attacks.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
@mtisov thank you very much for pointing this out. We are looking into it, and we will post an update here soon.

**Comment by robmazz** [comment]
@mtisov - thanks for the feedback, the way it is currently could cause incorrect simplification to 1/growth rate = time to impact. Your suggestion is correct and more straight forward and I’ve added the update and clarification on bytes/second to the article. Thanks!

**Comment by mtisov** [comment]
@robmazz Happy to help! 
But I wouldn't be so sure if Capacity and Time, both measured in  bytes/sec! ;)
