### ISSUE TITLE
Missing information about wildcard "." character

### ISSUE THREAD

**Issue by HansSchulze** [MicrosoftDocs/OfficeDocs-o365seccomp#35]
I was searching for the text ".NV", and the "." is ignored.  There doesn't seem to be an escape character to include wildcard characters as exact match ie looking for "A\*C" should only match "A*C".  I tried "\.NV" and that is ignored.
I have NV* everywhere in my email (99%) and only 2 emails SOMEWHERE that talk about ".NV".  Frustrated.
Please discuss "." and escape characters, or implement escape characters and document that.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b84ade-fa24-3ca7-adb8-1a3398faa0a0
* Version Independent ID: b601bd4d-aa7e-63aa-0404-4cd84d817a9d
* Content: [Keyword queries and search conditions for Content Search](https://docs.microsoft.com/en-us/office365/securitycompliance/keyword-queries-and-search-conditions)
* Content Source: [SecurityCompliance/keyword-queries-and-search-conditions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/keyword-queries-and-search-conditions.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
investigating

**Comment by markjjo** [comment]
@HansSchulze - Periods and other special characters (such as hyphen) are ignored in KQL search query (KQL is used in content search). Periods are not wildcards; the asterix is the only wildcard and only suffix wildcards are supported (so only AC* is supported; not *AC or A*C). No escape characters are supported. Looking into adding list of special characters that are ignored to the Keyword queries help topic, though special characters may be different for mail and sites.

**Comment by HansSchulze** [comment]
Appreciated detail.  How can I search for ..g in Outlook?

**Comment by AndreaBarr** [comment]
@HansSchulze Thank you for this feedback. 

I have sent this to the o365seccomp team to get more information added to this artivle.  For expidated answers please put in a support ticket. Below is a vido on creating a support ticket. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
