### ISSUE TITLE
Lack of information about minimum permissions required

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#353]
I am sorry but there is no information what the minimum permissions required are. This article redirect to the other article:
(https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center) for the permission information but the other article doesn't cover Office 365 ATP permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5375df5a-9955-47d9-5ef4-8adbd219f77b
* Version Independent ID: 5b191c2a-bfde-a531-9c3b-4b295efea56c
* Content: [Set up Office 365 ATP Safe Links policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-safe-links-policies)
* Content Source: [SecurityCompliance/set-up-atp-safe-links-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-safe-links-policies.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@pawp81 thank you so much for the feedback. I will get this content updated ASAP to include the necessary permissions.

**Comment by denisebmsft** [comment]
@pawp81 I have updated this (and other ATP articles) with details about required permissions. I hope this helps! Thank you again for the feedback, and for helping us improve our documentation.
