### ISSUE TITLE
Lack of information about minimum permissions required

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#354]
I am sorry but there is no information what the minimum permissions required are. This article redirect to the other article:
(https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center) for the permission information but the other article doesn't cover Office 365 ATP permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721eb3a3-eb0d-77a8-0c74-1b9ddb8e963a
* Version Independent ID: 9b8b98f1-2b65-9c11-3fbc-09dcd1c2ed84
* Content: [Set up Office 365 ATP Safe Attachments policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-safe-attachments-policies)
* Content Source: [SecurityCompliance/set-up-atp-safe-attachments-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-safe-attachments-policies.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@pawp81 thank you for the feedback! As with the ATP Safe Links content. I'll fix this ASAP.

**Comment by denisebmsft** [comment]
@pawp81 I have updated this (and other ATP articles) with details about required permissions. I hope this helps! Thank you again for the feedback, and for helping us improve our documentation.

**Comment by pawp81** [comment]
Thank you. However, assigning just Azure AD Security Administrator role doesn't grant access to: https://protection.office.com/threatpolicy where policies are configurable. Could you please double-check what are the minimum permissions required? It also applies to ATP Safe Links, ATP for SPO and ATP Anti-phishing articles.
