### ISSUE TITLE
What permissions are needed to manage Office 365 ATP policies?

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#355]
This article does not include information about what permissions are needed to manage Office 365 ATP policies settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@pawp81 thank you for your feedback on this and the other two ATP articles. We are looking into this, and an update will be posted here soon.

**Comment by stephow-MSFT** [comment]
We've just updated the ATP content to include the necessary permissions -
https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-atp#get-office-365-atp
