### ISSUE TITLE
2 minutes to read?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-o365seccomp#357]
Hi Team,
Although the words are few, the images are many on this one. I'd say 5 minutes to read it properly would be a good change from the 2 minutes it currently says. My assumption is the 2 minutes is auto-generated based on the number of words; do you have an option to change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1162dfe-1b69-0e06-b3d2-eb5818786e7c
* Version Independent ID: aff337de-d029-6aa4-400b-521069165089
* Content: [Overview of file plan manager](https://docs.microsoft.com/en-us/office365/securitycompliance/file-plan-manager)
* Content Source: [SecurityCompliance/file-plan-manager.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/file-plan-manager.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@Michael-Sampson thank you so much for the feedback. We cannot control the reading estimate.... as you suspect, it is auto-generated. I'm going to close this, but please let us know if you have any other questions.
