### ISSUE TITLE
Now at GA

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-o365seccomp#358]
Hi Team,
I came here from this announcement - https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Simplify-processes-and-meet-your-requirements-with-new-records/ba-p/327335. That says File Plan Manager is now generally available, and is therefore out of the preview phase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1162dfe-1b69-0e06-b3d2-eb5818786e7c
* Version Independent ID: aff337de-d029-6aa4-400b-521069165089
* Content: [Overview of file plan manager](https://docs.microsoft.com/en-us/office365/securitycompliance/file-plan-manager)
* Content Source: [SecurityCompliance/file-plan-manager.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/file-plan-manager.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
We're currently working on updating documentation for this feature.
