### ISSUE TITLE
Import to update existing labels?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-o365seccomp#359]
"To import new retention labels and make updates existing retention labels, go to file plan manager &gt; file plan actions &gt; import labels."

Do we know what checks and balances are put in place with this so existing label values are not ... inappropriately overwritten? Is there, for example, an opportunity after import to compare and contrast the previous value with the new proposed one ... or does the import just do a direct overwrite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1162dfe-1b69-0e06-b3d2-eb5818786e7c
* Version Independent ID: aff337de-d029-6aa4-400b-521069165089
* Content: [Overview of file plan manager](https://docs.microsoft.com/en-us/office365/securitycompliance/file-plan-manager)
* Content Source: [SecurityCompliance/file-plan-manager.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/file-plan-manager.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@Michael-Sampson thank you for posting your questions on this. We are looking into it, and an update will be posted here soon.

**Comment by stephow-MSFT** [comment]
Importing retention labels via file plan, supports create and edit retention label actions, and only those edit actions that can be achieved via the UI. 

File plan import does not support deleting, overwriting or other retention label actions that cannot be done via the UI.
