### ISSUE TITLE
RecordType value not listed

### ISSUE THREAD

**Issue by dagroll** [MicrosoftDocs/OfficeDocs-o365seccomp#362]
My customer is doing messaging analysis by pull unified audit log data into SplunkCloud.  They are pulling the RecodType property and are seeing a value of 28, which is not referenced in this article.  Can you update this article to include the meanings for all values?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2748572-d1b7-6bb3-a4ed-c58da8a232bb
* Version Independent ID: 6f16b647-f313-9ec9-c26a-934aac9c3c00
* Content: [Detailed properties in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log)
* Content Source: [SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@dagroll Thanks for feedback. Until topic gets updated, please see: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#common-schema

An value of 28 for RecordType corresponds to ThreatIntelligence/ATP.

**Comment by dagroll** [comment]
Awesome.  Thank you Mark.  I greatly appreciate the link and quick response.


Dave Groll
Premier Field Engineer | Business Productivity
Messaging
mobile: 940.300.6291
dagroll@microsoft.com<mailto:dagroll@microsoft.com>

[cid:image001.jpg@01CFFABC.851698C0]<http://www.microsoft.com/>

**Comment by markjjo** [comment]
Topic updated with additional enum values for RecordType.

https://docs.microsoft.com/en-us/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log
