### ISSUE TITLE
One suggetsion that has been made that might be worth consideration

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#363]
[Enter feedback here]Comment in section "How to get ATP Safe Links protection
"
The statement - "Your organization's email is hosted in Office 365." has been considered by some to be confusing, as Safe Links can protect mailboxes that are not hosted in O365. The emails need to only pass through EOP, and the recipient be part of a scoped policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1ed2ee-04a9-d958-1652-3d9562134660
* Version Independent ID: a5457702-6307-4e41-a2c2-3a115f9a9797
* Content: [Office 365 ATP Safe Links](https://docs.microsoft.com/en-us/office365/securitycompliance/atp-safe-links#how-to-get-atp-safe-links-protection)
* Content Source: [SecurityCompliance/atp-safe-links.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/atp-safe-links.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@aldoug thank you for the feedback. I am working on this, and I will post an update here soon.

**Comment by denisebmsft** [comment]
@aldoug thanks again for your helpful suggestion. I've updated the content. Thank you for helping us improve the quality of our documentation!
