### ISSUE TITLE
60 users to protect

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/OfficeDocs-o365seccomp#364]
Hello, 

The documentation describes the "Add users to protect as following:

_Defines which email addresses will be protected by the policy. You can add up to 60 internal and external addresses that you want to protect from impersonation._ 

Suppose i have a large customer who has more than 60 users to protect, is my assumption correct that we can just create multiple policies or is the # of 60 users a tenant wide limitation?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies)
* Content Source: [SecurityCompliance/set-up-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-anti-phishing-policies.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@alexverboon thank you for posting your question. I'm looking into this, and I will post an update here soon.

**Comment by denisebmsft** [comment]
@alexverboon you are correct that the 60-user limit is per policy. Please note that this list of users would include your organization's Office 365 admins, high-level executives, business owners, external board members, and the like. These are accounts you'd want to prevent from being impersonated. 

Once an ATP anti-phishing policy is defined, that policy can be applied to everyone in your organization. What this means is, if someone tried to impersonate one of the user accounts on that "list of 60" if you would, and sends email to one of the users in the "Applies to" part of the policy, ATP would catch it and quarantine that email message. 

If you have more than 60 accounts to specify in your policy, you would want to define multiple policies. 

I hope this helps! Please let us know if you have any other questions. For now, I am going to close this issue out.
