### ISSUE TITLE
Office 365 Security Administrator

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#365]
I am sorry but there is no such a admin role as "Office 365 Security Administrator" that can be configured in aka.ms/admincenter. Are you referring to Azure AD Security Admin role configurable in Azure AD Portal (aad.portal.azure.com)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5375df5a-9955-47d9-5ef4-8adbd219f77b
* Version Independent ID: 5b191c2a-bfde-a531-9c3b-4b295efea56c
* Content: [Set up Office 365 ATP Safe Links policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-safe-links-policies)
* Content Source: [SecurityCompliance/set-up-atp-safe-links-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-safe-links-policies.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@pawp81 thank you for raising this question/issue. And yes, I did mean Security Administrator that is assigned in the Azure Active Directory portal. I've updated the content accordingly. Thanks again! I do want the content to be accurate and not confusing.
