### ISSUE TITLE
Any other method to download the content search report? there is a PowerShell method ? 

### ISSUE THREAD

**Issue by christiangomez92** [MicrosoftDocs/OfficeDocs-o365seccomp#366]
There is any other method to avoid the plugin to download the content search report? 
The best option for me would be a script to do this actions. This feature is on your current dev roadmap ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14d3f714-fce8-5a09-c3f7-d7728bda96ae
* Version Independent ID: 36e50843-d3f3-4748-8b95-ef00844035a6
* Content: [Export a Content Search report](https://docs.microsoft.com/en-us/office365/securitycompliance/export-a-content-search-report)
* Content Source: [SecurityCompliance/export-a-content-search-report.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/export-a-content-search-report.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@christiangomez92 You can use New-ComplianceSearchAction -Export -Report command. You might also need to include the -Scenario GenerateReportsOnly parameter/value. Please see https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearchaction?view=exchange-ps
