### ISSUE TITLE
Microsoft 365 Business?

### ISSUE THREAD

**Issue by vwethan** [MicrosoftDocs/OfficeDocs-o365seccomp#367]
Under the "What subscriptions do I need to use the new OME capabilities?" section I don't see Microsoft 365 Business - please explain if OME is available with that subscription, and if not, if adding AIP P1 will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ad427d-d869-2ab6-3d2c-f846efc99256
* Version Independent ID: 606eaa37-2713-8087-015f-012ae9c90090
* Content: [Office 365 Message Encryption FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-faq)
* Content Source: [SecurityCompliance/ome-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-faq.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@vwethan thank you again for your feedback. Microsoft 365 Business includes AIP Plan 1, which includes Office Message Encryption (https://azure.microsoft.com/en-us/pricing/details/information-protection). We've updated the article accordingly, and you should see the changes live now (or within a minute or two). Thank you for helping us improve our documentation!
