### ISSUE TITLE
"電源の BI" needs to be replaced with "Power BI"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-o365seccomp#370]
https://docs.microsoft.com/ja-jp/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2748572-d1b7-6bb3-a4ed-c58da8a232bb
* Version Independent ID: 6f16b647-f313-9ec9-c26a-934aac9c3c00
* Content: [Detailed properties in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log)
* Content Source: [SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@hyoshioka0128 thank you so much for letting us know about this. We are looking into it.

**Comment by MollyMalone** [comment]
I shared with the localization vendors who should fix it soon.   We have a known issue where product names are often translated in machine translated topics when they should be left in English.

**Comment by hyoshioka0128** [comment]
Similarly "電源 BI","電源双".
I found out [Kaizala コンテンツ パック](https://docs.microsoft.com/ja-jp/office365/kaizala/content-pack). #254 
(Sorry for my poor English.)

**Comment by MollyMalone** [comment]
@samanthaw can you arrange to fix the Kaizala issue (overlocalization of "Power BI")

**Comment by OfficeGSX** [comment]
The article was previously MachineTranslated. Currently it's human translated, reported string "Power BI" left unlocalized. Updated article was published live

Best Regards,
Michal
