### ISSUE TITLE
Characters are visible instead of .png(media/6df582ae-d339-4735-b1a6-80914fb77a08.png)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-o365seccomp#371]
https://docs.microsoft.com/ja-jp/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2748572-d1b7-6bb3-a4ed-c58da8a232bb
* Version Independent ID: 6f16b647-f313-9ec9-c26a-934aac9c3c00
* Content: [Detailed properties in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log)
* Content Source: [SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@hyoshioka0128 thank you so much for letting us know about this. We are looking into this issue, and we'll post an update here soon.

**Comment by MollyMalone** [comment]
This one also shared with the localization vendors.

**Comment by hyoshioka0128** [comment]
Thanks! @MollyMalone

**Comment by OfficeGSX** [comment]
The article was updated and image is being displayed properly

Best Regards,
Michal
