### ISSUE TITLE
Issue with Instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#374]
Step 3, item 5 shows that we should be able to choose Exchange or Office 365. I only get the option to choose Exchange, are the instructions wrong or do I have a problem in my tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50efcd2f-907b-7c61-3fbe-befe11a05146
* Version Independent ID: 4d7a2223-8622-7461-cf25-9426d33921e6
* Content: [Configuring privileged access management in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/privileged-access-management-configuration)
* Content Source: [SecurityCompliance/privileged-access-management-configuration.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/privileged-access-management-configuration.md)
* Service: **o365-solutions**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
@DeanGross thank you for the feedback! We are looking into this. Watch for an update to be posted here soon.

**Comment by robmazz** [comment]
@DeanGross - thanks so much for the feedback, yes - you are correct about only seeing Exchange and this is correct. At the current time, only Exchange is available as an option. Office 365 is on our roadmap and isn't available yet. The topic will be updated shortly. Thanks!
