### ISSUE TITLE
Users to protect

### ISSUE THREAD

**Issue by jesterj85** [MicrosoftDocs/OfficeDocs-o365seccomp#377]
Just curious, as I can't seem to find the answer...regarding the 'Users to protect' field in the ATP policy, what if I just want all users of the organization to be protected under the policy? Do I have to explicitly add them to this list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies)
* Content Source: [SecurityCompliance/set-up-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-anti-phishing-policies.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @jesterj85. Thank you for posting your question. We are looking into this, and an update will be posted here soon.

**Comment by denisebmsft** [comment]
Hello @jesterj85. 

The list of 60 users is intended to include your organization's Office 365 admins, high-level executives, business owners, external board members, and the like. These are accounts you'd want to prevent from being impersonated.

Once an ATP anti-phishing policy is defined, that policy can be applied to everyone in your organization. What this means is, if someone tried to impersonate one of the user accounts on that "list of 60" if you would, and sends email to one of the users in the "Applies to" part of the policy, ATP would catch it and quarantine that email message.

If you have more than 60 accounts to specify in your policy, you would want to define multiple policies.

I hope this helps! Please let us know if you have any other questions. For now, I am going to close this issue out.
