### ISSUE TITLE
Support of OME mesages to Shared Mailboxes?

### ISSUE THREAD

**Issue by pbarsan** [MicrosoftDocs/OfficeDocs-o365seccomp#378]
Is this planned to be rolled out soon? Or is there a technical limitation in regards to this?

At this moment, I see this behavior:
- emails sent as a shared mailbox to an user can be opened by the recipient user. All other members of the shared mailbox can see the content of the email. In case the recipient replies back, only the original sender can read the message.
- new emails sent directly to shared mailboxes cannot be read/opened by any members

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ad427d-d869-2ab6-3d2c-f846efc99256
* Version Independent ID: 606eaa37-2713-8087-015f-012ae9c90090
* Content: [Office 365 Message Encryption FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-faq)
* Content Source: [SecurityCompliance/ome-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-faq.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by IanMartin56** [comment]
We are in the process of selecting an email encryption product and we also need to know if/when OME will be supported for Shared Mailboxes.

**Comment by denisebmsft** [comment]
Hello @pbarsan and @IanMartin56. Thank you for posting your questions. We have this in our queue and you can expect an update to be posted here soon.

**Comment by semwealth** [comment]
This would be a huge plus for us as well. We use use Shared Mailboxes for operations almost exclusively and when external parties send us encrypted messages - which is often - it's a huge hassle to open them.

**Comment by MSFTTracyP** [comment]
Yes. There appears to be plan to support sending and receiving encrypted mails to shared mailbox, but I'm afraid the details will need to wait until release. Not sure how helpful this is, but thank you for the question!

**Comment by stevep4** [comment]
So, 2 months on from last reply, and nothing.... MS coloured tumbleweed. @MSFTTracyP Details may need to be drip fed here to keep people on board, even a rough ETA would help. Please. Pretty please. Come on. :)

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Chris-tina-Testing** [comment]
Please post your vote for OME support for shared mailboxes:

https://office365.uservoice.com/forums/264636-general/suggestions/35684506-allow-encrypted-emails-to-be-viewed-in-a-shared-ma

**Comment by scanum** [comment]
@pbarsan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by stevep4** [comment]
Hi @scanum could you please expand on your answer, how has the issue been resolved? The documentation clearly still says it's not possible.

#reopenplease
