### ISSUE TITLE
Download Reports( Message Trace)

### ISSUE THREAD

**Issue by alicejames007** [MicrosoftDocs/OfficeDocs-o365seccomp#379]
[Enter feedback here]
Hi,
Till when Downloadable Reports(Message Trace) will be visible? Is there any option of clear report? 
Its difficult to search desirable report because there is no option of filtering or sorting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89002086-f4a5-145f-1a65-b47566eecb1f
* Version Independent ID: a36a7664-1de1-c4c9-9caf-2caadbf1d138
* Content: [Message trace in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/message-trace-scc)
* Content Source: [SecurityCompliance/message-trace-scc.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/message-trace-scc.md)
* Product: **office-online-server**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by denisebmsft** [comment]
@alicejames007 thank you for posting your question! We are looking into this, and an update will be posted here soon.

**Comment by chrisda** [comment]
@alicejames007, the topic says this about downloadable reports:

> Enhanced summary and Extended reports are prepared using archived message trace data, and **it can take up to several hours before your report is available to download**. Depending on how many other admins have also submitted report requests around the same time, you might also notice a delay before your queued request starts to be processed.

If you feel that you've waited a reasonable amount of time, and the reports still aren't visible, I would encourage you to file a support ticket.

And you are correct, there's no way to sort or delete downloadable reports, although some combination of autosaved queries, custom queries, and downloadable reports (some? all?) are supposed to age out (disappear) after 10 days.
