### ISSUE TITLE
"365 企業の Microsoft" needs to be replaced with "Microsoft 365 Enterprise"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-o365seccomp#380]
https://docs.microsoft.com/ja-jp/office365/securitycompliance/office-365-atp?cid=kerryherger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5939440-a0f8-0938-e61e-27aeca97888a
* Version Independent ID: 0314d705-b3fd-8533-22bd-a14039362e0f
* Content: [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-atp?cid=kerryherger)
* Content Source: [SecurityCompliance/office-365-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-atp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@hyoshioka0128 thank you so much for letting us know about this. We are looking into this issue and we will post an update here soon.

**Comment by MollyMalone** [comment]
@hyoshioka0128 Thank you for reporting this issue. However we will not fix the over-translation of "Microsoft 365 Enterprise" at this time. It is a known issue that some of our Product names (including Microsoft 365 Enterprise) are being unnecessarily translated by the machine translation tool. We are investigating a tool solution to fix these issues. At this time we can not fix each issue individually.
