### ISSUE TITLE
Permissions for viewing DLP report

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/OfficeDocs-o365seccomp#381]
Based on info from PG and my own testing, the following roles are required to view DLP reports:
- SCC: View-Only DLP Compliance Management
- EAC: View-Only Recipients

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0acad6-537d-7e40-6eff-202475dff41b
* Version Independent ID: 4ace04a0-5cf4-88cd-7248-59d0ab6b54da
* Content: [Reports in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/reports-in-security-and-compliance#data-loss-prevention-reports)
* Content Source: [SecurityCompliance/reports-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/reports-in-security-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@bernardlam thank you so much for the feedback. We are looking into this, and we'll post an update here soon.

**Comment by markjjo** [comment]
@bernardlam Fixed; updated topic with roles required to view DLP reports
