### ISSUE TITLE
Creating Office 365 Groups in Azure AD

### ISSUE THREAD

**Issue by adnan-iqbal** [MicrosoftDocs/OfficeDocs-o365seccomp#384]
Phase 1, Step 4 mentions to create Office 365 as the group type when creating Groups in Azure AD - should this not be Security as group type? An Office 365 group created in Azure AD shows up in the Groups on Office 365 Admin Centre as an Office 365 group and not a Security - would a SharePoint Online site not be created due to the group being an Office 365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6b7a2a-6724-5993-7fec-b4aa22110675
* Version Independent ID: 4c9db0b4-8db9-e14c-c97d-7e5a1a163cc6
* Content: [Deploy an isolated SharePoint Online team site](https://docs.microsoft.com/en-us/office365/securitycompliance/deploy-an-isolated-sharepoint-online-team-site)
* Content Source: [SecurityCompliance/deploy-an-isolated-sharepoint-online-team-site.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/deploy-an-isolated-sharepoint-online-team-site.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@adnan-iqbal thank you for posting your question here. We are looking into this, and you can expect an update to be posted here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by JoeDavies-MSFT** [comment]
@adnan-iqbal For the reasons described in the note, it needs to be an Office 365 group type. 

In my testing, groups created in Azure AD (either Office 365 or Security) will allow a SharePoint site to be created with the same name. 

However, you cannot create a team site with the same name as an Office 365 group that was created in the Office 365 admin center.
