### ISSUE TITLE
Set-Mailbox The input audit operation(s) is/are already being audited.

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/OfficeDocs-o365seccomp#385]
When running the command below on a set of mailboxes:
```Get-mailbox -ResultSize Unlimited | %{ Set-mailbox $_.identity -AuditOwner @{ Add = 'MoveToDeletedItems',"Update","UpdateFolderPermissions","UpdateInboxRules","UpdateCalendarDelegation"} }```
it would throw the following error eventually:

> The input operation(s) is/are already being audited

![image](https://user-images.githubusercontent.com/5260172/52652249-d6185300-2efe-11e9-842d-55d338b3f7a8.png)

**Comment by denisebmsft** [comment]
@YuriySamorodov thank you for posting your feedback here. I am assuming this pertains to this article: https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing. Is this correct?

**Comment by YuriySamorodov** [comment]
@denisebmsft Correct

**Comment by markjjo** [comment]
@YuriySamorodov Documetnation has been updated with the release of mailbox auditing on by default; your issue may have been related to that roll out; please see https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing
