### ISSUE TITLE
Does not work on Business version of Office suite.

### ISSUE THREAD

**Issue by Elderfield500** [MicrosoftDocs/OfficeDocs-o365seccomp#386]
Please update to specify that this will not work with Business version of Office suite. Only ProPlus.
Correct me if I am wrong.
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1ed2ee-04a9-d958-1652-3d9562134660
* Version Independent ID: a5457702-6307-4e41-a2c2-3a115f9a9797
* Content: [Office 365 ATP Safe Links](https://docs.microsoft.com/en-us/office365/securitycompliance/atp-safe-links)
* Content Source: [SecurityCompliance/atp-safe-links.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/atp-safe-links.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @Elderfield500. Just to clarify your question, are you requesting that the ATP Safe Links article be updated to state that Safe Links protection is not included with Office 365 Business?

**Comment by denisebmsft** [comment]
Hello @Elderfield500. I wanted to let you know that I updated this article. Hopefully it's more clear now what's required to have ATP Safe Links protection in place. Thank you for the feedback!

**Comment by aldoug** [comment]
I believe the following is still true (looking to confirm). You need to make sure the user is running the ProPlus version on “Monthly Channel (Targeted)” builds for Office 365 integration
