### ISSUE TITLE
Additional Reasons Missing

### ISSUE THREAD

**Issue by AzureGuineaPig** [MicrosoftDocs/OfficeDocs-o365seccomp#387]
Some of our messages are getting marked with reason=904 and reason=601, these are not listed values in the Authentication-results message header fields used by Office 365 email authentication.  Please update the missing reason value codes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0c22e-ec20-d8dc-bbc5-cfbb9e98350e
* Version Independent ID: d9a1bac2-69ef-5fa7-23f1-417d7454c4cc
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/office365/securitycompliance/anti-spam-message-headers#authentication-results-message-header)
* Content Source: [SecurityCompliance/anti-spam-message-headers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@AzureGuineaPig thank you so much for pointing this out. We have a work item for this in our queue, and we are looking into it. You can expect an update to be posted here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by ianc911** [comment]
"You can expect an update to be posted here soon."

Forgotten about us?

**Comment by victor-onofrei** [comment]
601 is when SPF domain is different from DKIM domain is different from DMARC domain.
Make sure at least DKIM / DMARC domain are the same.
In my case, the DMARC was done on sub.domain.com (as it should) but DKIM was done on domain.com
Solution was to create a new dkim config w/ New-DkimSigningConfig -DomainName domain.com -Enabled $false.
This way, Office 365 knows how to perform the DKIM check using sub.domain.com not the parent domain.

**Comment by scanum** [comment]
@AzureGuineaPig Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
