### ISSUE TITLE
Teams and Sharepoint URLs associated with a specific user

### ISSUE THREAD

**Issue by OlgaMalosh** [MicrosoftDocs/OfficeDocs-o365seccomp#389]
Get-UnifiedGroupLinks cmdlet helps finding what mailboxes and Sharepoint teams are associated with a group. However, we are looking for a solution to help identifying Teams and Sharepoint URLs associated with a specific user. Any guidance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98d1f72-c381-3056-c1c4-7e54a9ab05af
* Version Independent ID: f5771dac-209a-433b-1967-a6ef3118eec6
* Content: [eDiscovery cases in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/ediscovery-cases#more-information)
* Content Source: [SecurityCompliance/ediscovery-cases.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ediscovery-cases.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@OlgaMalosh thank you for posting your question here. We are looking into this, and an update will be posted here soon.

**Comment by markjjo** [comment]
@OlgaMalosh When the next version of Advanced eDiscovery (which is currently in Preview: https://docs.microsoft.com/en-us/Office365/SecurityCompliance/compliance20/overview-ediscovery-20) releases to general availability, you will be able to get a list of Teams that a given custodian is a member of. Today, you would have to create a script and use Microsoft Graph (beta); see https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta - 

Similarly, you would have to use a script to get a list of all users who have access to all the site collections in your organization; for example: https://gallery.technet.microsoft.com/office/How-to-get-all-the-users-3bc917b0 

A couple of other suggestions for workarounds, though they're not very user friendly:

-Use the "modifiedby" and "createdby" site properties in a content search (connected by OR) and search all sites in your org to return all the docs that a specific user created or changed, then export the report which will list the site that each doc was located.

-Use the audit log search tool and search file activities for files accessed or pages viewed by a specific user. The site where the file/page is located will be include in the audit record. See https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#audited-activities
