### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by bulgie** [MicrosoftDocs/OfficeDocs-o365seccomp#392]
Trying to see my quarantine as a user.  Logging in with my work address, it says the password is wrong.  I followed the link to reset it (in case my EOP password is different from my work domain PW?), and it says the account doesn't exist.  I am getting email and spam is being quarantined, which proves the account exists, so what's the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e487b445-a3ef-ec1e-43b6-bd9f7afa3f62
* Version Independent ID: 34d5e5a4-4bdc-47bd-3638-bcf80ee935d6
* Content: [Find and release quarantined messages as a user in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/find-and-release-quarantined-messages-as-a-user)
* Content Source: [SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @bulgie. Thank you so much for letting us know about this. We are looking into this, and we will post an update here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@bulgie thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
