### ISSUE TITLE
I tried to report a phish, but got an error message

### ISSUE THREAD

**Issue by andrehinds** [MicrosoftDocs/OfficeDocs-o365seccomp#393]
I tried to report a phish to phish@office365.microsoft.com, but after sending it, I immediately received this error message in my email:

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of
its recipients. This is a permanent error. The following address(es)
failed:

phish@office365.microsoft.com:
SMTP error from remote server for RCPT TO command, host: microsoft-com.mail.protection.outlook.com (104.47.53.36) reason: 550 5.7.1 Service unavailable, Client host [82.165.159.133] blocked using 
Spamhaus. To request removal from this list see https://www.spamhaus.o
rg/query/ip/[82.165.159.133] (AS16012611) [BL2NAM06FT009.Eop-nam06.pro
d.protection.outlook.com]

--- The header of the original message is following. ---

Received: from andres-mac-mini.fios-router.home ([173.48.166.45]) by
mrelay.perfora.net (mreueus003 [74.208.5.2]) with ESMTPSA (Nemesis) id
0Limct-1hUYxq0RXZ-00d1DI for &lt;phish@office365.microsoft.com&gt;; Thu, 14 Feb
2019 05:06:03 +0100
From: ANDRE HINDS &lt;ahinds@andrehinds.com&gt;
Content-Type: multipart/mixed;
	boundary="Apple-Mail=_3DF60243-9B61-4EA4-B0FE-2721996A6F03"
Mime-Version: 1.0 (Mac OS X Mail 11.5 \(3445.9.1\))
Subject: Fwd: Your account has been limited. ID: #R5131.6D9R406MH 
Message-Id: &lt;0E1C642A-366B-4CDC-B633-F6641CBB2F98@andrehinds.com&gt;
Date: Wed, 13 Feb 2019 23:06:02 -0500
To: phish@office365.microsoft.com
X-Mailer: Apple Mail (2.3445.9.1)
X-Provags-ID: V03:K1:MeUPi7I4PPHRxHPBY0zQWs+NvJEAaCCSbnkiasEiwDVnDYxoWWg
4vFp3dJhoNce724pPJ2IddngyfP3PqI1DaqXvnw45wjD2dE01ePiBXroNDa7hMrxs4zWqGe
u1p2dgb1r/WyfR0yCMSWTcW8XLtPnFHJdq2MhhXLQDk08wR5q/qMo7xPHrnPuCmU7zgREyc
+K5Ouejr2Qq0l67taXFJQ==
X-Spam-Flag: YES
X-UI-Out-Filterresults: junk:10;V03:K0:UZTKkyFpY6k=:p8wdSiJi725xak88tsKHIgSP
gvSraQizPVOkuhaPkTly9WvZxR9HVb3LGc+5bYWgaiyOCEzKCBCvzE0EUGWfk7VsrFIhZ1otC
LPclDM1kBvF8lF69lIFfam3TrO3sMgSBMjWJhLnr3tbHZF0zEMDwa0Kie/kLOvKvUtFtwEDrv
70r/0rJXBoSNUETVzbkn3jkKU0uryED5GfcYvUHkjkpXMR1Vbq5CyYh/xp0MvI37BkHnG1bYe
m+71XVqhDtc9Cj34CKIoEfD7kzbJ8mwCrB3c3GyxMvydTrFf4mJwELxUxEstY9MoTmsTYmxL/
kJpNA9j6MV/7sT6JKyU9YsMrQznj77fvLn54K+2oIbCh5f5SzkidqJ4s3HcUg9HsvUUGe/eBO
uw08e6/PdtaK45G6CaeaDn7PT+wm11iaFaxm3zgl+ep9IO0V8h+KtUikE0/XyyrW+YJm7N/zx
/4chBjE63y7i1zc2ty89C7I7164jhc7/yxe1ZytXvHH5yt8YQ+N1UGQCfo5lRpZpAKtUnyjWK
+kn/Hokn9UR4xzmQKqmQspHP4B2PS7dzfIPM2/cjRfsN9H9t+dCXm6v3//dqdPExCoTc8e4yL
LaxQ+AR/ANQ1LRyJdaXb9AIjifppIAW3wd++7uQys8pFz4DzR4qThEy1wBa3wAqbSq2nFtJH4
bAMarcZT6KGXc8+Dhp/dFfIc0jhCO30dnKd57iUVzPkLb/l5XdYVyFuT9pCVuSM+khACqFDPR
V7U3JQXJCsCr4DDq+14JtGSqrR3JAe09nNm3eGeMhqJpEBbq4gxPkmdXsBWc0cnTZ4tlHkoCy
Eph6M2GKbrifTqvrI/RcOwpVFVhALwopoy6uwQ7nT/tEmrkSHM3aTAMeaVE8i8sQhsK4FoyDG
+YsjK2h7znvwLwa5V3/mdcbWvI/ti0qWgF0/4TQ=

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78678fe5-0473-27f2-1600-122267386c3d
* Version Independent ID: ab96b413-3d71-a9ae-5887-e80696b30f3f
* Content: [Submit spam, non-spam, and phishing scam messages to Microsoft for analysis](https://docs.microsoft.com/en-us/office365/securitycompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis)
* Content Source: [SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @andrehinds and thank you so much for letting us know about this. We are looking into this issue, and we will post an update here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@andrehinds thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
