### ISSUE TITLE
Audit log in Office 365 and E1 & F1 licensing

### ISSUE THREAD

**Issue by eduardpaul** [MicrosoftDocs/OfficeDocs-o365seccomp#394]
Hi all, reading this documentation I am not able to understand what happens in the E1 and F1 licenses. I mean, E3 and E5 are very explicit:

    E3: 90-day retention. 
    E5: 365-day retention.

Does this mean that E1 and F1 licensed users are not logged in the audit? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@eduardpaul thank you for raising this question. We are looking into this, and a response will be posted here soon.

**Comment by markjjo** [comment]
@eduardpaul Auditing is available for E1 and F1 organizations; retention of audit logs would be 90 days, similar to E3. As per the topic, retention period of audit log is based on per-user license.

**Comment by eduardpaul** [comment]
Thank you very much for your clarification @markjjo .
