### ISSUE TITLE
Minimum permissions for SIEM integration

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#395]
I guess Office 365 global administrator privileges to set up SIEM integration are needed to grant tenant admin Azure AD consent? Wouldn't Application administrator AAD role be sufficient for that task?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad24c82-7386-740e-871b-4ae98878e723
* Version Independent ID: 111db64d-6dcf-19e7-4545-1610363ee0d4
* Content: [SIEM integration with Office 365 Threat Intelligence and Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/siem-integration-with-office-365-ti)
* Content Source: [SecurityCompliance/siem-integration-with-office-365-ti.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/siem-integration-with-office-365-ti.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@pawp81 this is a good question. Thank you for posting this. I am looking into this issue and will follow up as soon as possible.

**Comment by denisebmsft** [comment]
Hello again @pawp81. As it turns out, to configure SIEM integration with Office 365 ATP and TI, you must be an Office 365 global administrator.
