### ISSUE TITLE
Characters are visible instead of .png(media/8639d09c-2843-44e4-8b4b-9f45974ff7f1.png)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-o365seccomp#396]
https://docs.microsoft.com/ja-jp/office365/securitycompliance/auditing-troubleshooting-scenarios

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b6c995c-1cd6-5af6-edb7-c37a2cb5eca5
* Version Independent ID: bd63c608-597d-e26f-11b4-201d7bc1e43e
* Content: [Search the Office 365 audit log to troubleshoot common scenarios](https://docs.microsoft.com/en-us/office365/securitycompliance/auditing-troubleshooting-scenarios)
* Content Source: [SecurityCompliance/auditing-troubleshooting-scenarios.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/auditing-troubleshooting-scenarios.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@hyoshioka0128 thank you for letting us know about this. We'll look into this as soon as possible.

**Comment by markjjo** [comment]
@hyoshioka0128 Until the Ja-jp version is fixed, attached is the missing image

![8639d09c-2843-44e4-8b4b-9f45974ff7f1](https://user-images.githubusercontent.com/36746813/53038895-ab645800-3432-11e9-80c3-b912936c75b8.png)

**Comment by MollyMalone** [comment]
@hyoshioka0128 Many thanks for reporting it.  I shared with the localization vendors and they will fix it soon.

**Comment by MollyMalone** [comment]
@hyoshioka0128 Just an update on this issue.  We found that this same issue occurs in about ~90 machine translated Japanese topics.  It's caused by an extra "]" in ART tool tip translation in our translation memory.   We will fix the translation and then retranslate all of the topics.    Thank you again for reporting it, you are really helping to improve the quality of the Japanese content.

**Comment by OfficeGlobal** [comment]
Article has been HumanTranslated and published live. Images are displayed properly
