### ISSUE TITLE
Step 6 info

### ISSUE THREAD

**Issue by MacPhistopt** [MicrosoftDocs/OfficeDocs-o365seccomp#397]
Reference to Create DNS records for Office 365 article leads to:
"Sorry, the page you’re looking for can’t be found.
You may have clicked an old link or the page may have moved.
Please try browsing from our main page."

Please also consider adding an example under the same step 6 on the MX endpoint format in EOP, like:

" MX record format is &lt;domainKey&gt;.mail.protection.outlook.com
For example, the domain contoso.com should have the MX record contoso-com.mail.protection.outlook.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda14449-28cb-ce67-ecc2-e0a94bffa89c
* Version Independent ID: b16da5b3-a788-35cf-32ca-2173d74020ad
* Content: [Set up your EOP service](https://docs.microsoft.com/en-us/office365/securitycompliance/eop/set-up-your-eop-service)
* Content Source: [SecurityCompliance/eop/set-up-your-eop-service.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/set-up-your-eop-service.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@MacPhistopt thank you so much for the feedback. We are looking into this, and we'll post an update here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msbemba** [comment]
@MacPhistopt Thank you for your feedback. The link to Create DNS records for Office 365 article is now routed to an active and correct Page. Meanwhile for the example we reference the Article which has information about MX records and how to set them up.

Hope this helps!

Thanks
Sri

**Comment by scanum** [comment]
@MacPhistopt 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
