### ISSUE TITLE
End User Actions

### ISSUE THREAD

**Issue by Breaker119** [MicrosoftDocs/OfficeDocs-o365seccomp#398]
The end user actions are not correct. Currently a user can only "Release to Inbox" or "Report as Not Junk". They should be able to review the message prior to applying a disposition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8252ddfb-8d51-29d8-0e8a-01c70c07db45
* Version Independent ID: ddc36cea-faf5-78b0-5542-e4ef41692083
* Content: [Configure end-user spam notifications in Exchange Online](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-end-user-spam-notifications-in-exchange-online)
* Content Source: [SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@Breaker119 thank you for the feedback! We have a work item for this in our queue, and an update will be posted here soon.

**Comment by msbemba** [comment]
@Breaker119  The end user spam notification should ideally include what is mentioned in the document. We can see that in the test tenant (Attached Snip). Let us know if this is still an issue.

![image](https://user-images.githubusercontent.com/45987684/61231114-669acf80-a6f9-11e9-87b3-49c0dc7accb8.png)

Thanks
Sri

**Comment by scanum** [comment]
@Breaker119 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
