### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-o365seccomp#40]
It's now called Spam filter, not Content filter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8252ddfb-8d51-29d8-0e8a-01c70c07db45
* Version Independent ID: ddc36cea-faf5-78b0-5542-e4ef41692083
* Content: [Configure end-user spam notifications in Exchange Online](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-end-user-spam-notifications-in-exchange-online)
* Content Source: [SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@rpodric thank you for the feedback!

**Comment by AndreaBarr** [comment]
@rpodric thank you for this feedback

I will get this over to the o365seccomp team for updating. 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
