### ISSUE TITLE
Unblock Restricted user using powershell

### ISSUE THREAD

**Issue by umgpg** [MicrosoftDocs/OfficeDocs-o365seccomp#402]
There is still no way to resolve these EOP Restricted User issues via Powershell; no note indicating this limitation in the documentation. This is a major workflow problem.

**Comment by denisebmsft** [comment]
Hello @umgpg, and thank you for posting your feedback. Unfortunately, I am not clear which article this refers to. Does your feedback pertain to this: https://docs.microsoft.com/en-us/office365/securitycompliance/eop/manage-mail-users-in-eop#use-remote-windows-powershell-to-manage-mail-users

**Comment by umgpg** [comment]
@denisebmsft,
This document: http://go.microsoft.com/fwlink/?LinkId=2006677 (aka https://docs.microsoft.com/en-us/office365/securitycompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email). Linked to by: https://protection.office.com/#/restrictedusers and also by the Action Center in https://outlook.office365.com/ecp as http://go.microsoft.com/fwlink/?LinkId=2015593 (aka https://docs.microsoft.com/en-us/office365/securitycompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email)

The function to get this list and removing restrictions for a Blocked account does not exist in Powershell. It should be documented that this needed feature does not exist. This feature is desired to integrate into other homegrown systems and workflows to remediate accounts and to remove the need of logging into Microsoft portals.

**Comment by denisebmsft** [comment]
@umgpg thank you for the clarification. We have a new work item for this in our queue. We're looking into this, and we will post an update here soon. Thank you for letting us know about this!

**Comment by MSFTTracyP** [comment]
Currently, we don't document when cmdlets _aren't_ there. Across the entire set of features involved in Office 365, documenting where a PowerShell cmdlet doesn't appear would be an effort that takes a lot of Tech Writer attention away from writing-up what does exist. Rather, there's a focus on documenting when cmdlets _are_ there, and what they do. I'm also very reluctant to add notes such as 'There is no PowerShell for this' in the shifting environment of the Cloud. Please let me know if there's more I can do, and thank you!
