### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by aprmike** [MicrosoftDocs/OfficeDocs-o365seccomp#404]
The link for the item "For more information, see Office 365 Advanced Threat Protection plans and pricing" returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2431ea89-86b7-5af7-a528-a9b3c31d21a9
* Version Independent ID: 8ade760a-f092-8d93-9f3d-485be3a1ecd7
* Content: [Office 365 Threat Intelligence](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-ti)
* Content Source: [SecurityCompliance/office-365-ti.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-ti.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @aprmike. Thank you for the feedback. I just checked every link and didn't see any 404 issues. I am not sure why you are getting those errors, but can you please try again?

**Comment by denisebmsft** [comment]
@aprmike i am going to close this issue for now, but if you run into any further problems, please let me know.
