### ISSUE TITLE
Rule text pattern correct?

### ISSUE THREAD

**Issue by cgoosen** [MicrosoftDocs/OfficeDocs-o365seccomp#405]
Some of these seem mangled, just wanted to confirm that they are indeed correct. Especially these ones:
\&lt;img height="?1"? width="?1"? src=.?http://
To stop receiving these\s+emails:http://

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e97743da-8e83-7fbd-45aa-945dd38899fc
* Version Independent ID: 2c7484e5-81ca-19fb-2646-c241782fd897
* Content: [Use mail flow rules to configure bulk email filtering in Exchange Online Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/use-transport-rules-to-configure-bulk-email-filtering)
* Content Source: [SecurityCompliance/use-transport-rules-to-configure-bulk-email-filtering.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-transport-rules-to-configure-bulk-email-filtering.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@cgoosen thank you so much for raising this question. We are looking into this, and an update will be posted here soon.

**Comment by cgoosen** [comment]
Excellent, thanks @denisebmsft

**Comment by denisebmsft** [comment]
@cgoosen I fixed the formatting in an attempt to make the line items more clear. I also inquired as to whether those are correct, especially with the escape characters ("/"), and I believe that they are. These are text patters for Regular Expressions (RegEx). I'm going to close this issue for now, but please let us know if you have any further questions or problems. And thanks again for the feedback!
