### ISSUE TITLE
Customise default auditing

### ISSUE THREAD

**Issue by lakesdan** [MicrosoftDocs/OfficeDocs-o365seccomp#406]
Is there a way to change what is audited by default rather than changing auditing for each mailbox every time a new mailbox is added?

I have changed the settings for all my existing mailboxes but I will have to remember to update this for each new mailbox, rather than just being able to change the default which is applied automatically to new mailboxes.

**Comment by denisebmsft** [comment]
Hello @lakesdan! Thanks for the feedback. Just to clarify, does your question pertain to this article: https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing

**Comment by lakesdan** [comment]
@denisebmsft yes that's right.

**Comment by markjjo** [comment]
@lakesdan Unfortunately, there isn't a way to do this. You will have to assign explicit mailbox auditing permissions to audit a set of action that are different than the actions that are enabled by default. For the functionality you describe, you can submitting a request to Office User Voice (https://office365.uservoice.com)

Note that audited actions are defined by the mailbox plan, you can't use Set-MailboxPlan to edit these.
