### ISSUE TITLE
Please define "spoofing" more clearly

### ISSUE THREAD

**Issue by gbluma** [MicrosoftDocs/OfficeDocs-o365seccomp#407]
Spoofing can mean different things to different people. It could mean exact matches of domains in question or syntactically similar domains (one letter missing, utf-8 letter replacements, etc). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2346da88-037b-1ef9-e3c4-c6d448b9688e
* Version Independent ID: 0292959f-9f3d-a34f-156e-bb8488fdc251
* Content: [Learn more about spoof intelligence](https://docs.microsoft.com/en-us/office365/securitycompliance/learn-about-spoof-intelligence?redirectSourcePath=%252farticle%252f978c3173-3578-4286-aaf4-8a10951978bf)
* Content Source: [SecurityCompliance/learn-about-spoof-intelligence.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/learn-about-spoof-intelligence.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@gbluma thanks very much for the feedback. We have opened a work item for this, and it's in our queue. We will post an update here in the near future.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msbemba** [comment]
@gbluma Thank you for your feedback. Email spoofing is the forgery of an email header so that the message appears to have originated from someone or somewhere other than the actual source in other words if the header exactly matches of domains in question but coming from another source.

Hope this helps!

Thanks
Sri

**Comment by gbluma** [comment]
The lack of clarity was around the kind of matching that occurs. Is it an
exact match (every character the same as original) or is does it take
*similarity* into account (for example, rnicrosoft.com, which uses R and N
instead of M)? There are lexicographical algorithms that can accomplish the
latter, and it seems like that would be in Microosft's wheelhouse.

**Comment by msbemba** [comment]
@gbluma 

I agree with you that there could be a lot of lexicographical algorithms that can accomplish the latter. But At the moment spoof intelligence works If every character is the same as original domain.
Microsoft user voice has a few to do items or good to have features for Spoof intelligence. So Yes,  They are working on it to make it better and we may soon see changes on the product.

Thanks
Sri

**Comment by scanum** [comment]
@gbluma 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
