### ISSUE TITLE
Mailbox Auditing Actions table & defaults needs updating

### ISSUE THREAD

**Issue by cg6** [MicrosoftDocs/OfficeDocs-o365seccomp#408]
Since MC171679 we have seen MoveToDeletedItems in the default auditing for mailbox owners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing#mailbox-auditing-actions)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@cg6 thank you for your feedback. We are looking into this, and an update will be posted here soon.

**Comment by RikardStrand** [comment]
Agree, all tables needs updating;
 Actions table: Change the defaults, add MailItemsAccessed
 AuditLog => Audit Search verify names and actions (copy not available as audit option any longer)

**Comment by markjjo** [comment]
@cg6 The mailbox auditing topic has been updated; this includes the mailbox actions that are audited by default for each logon type. https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing#mailbox-actions-logged-by-default
