### ISSUE TITLE
Duplicated text in How does ZAP work bullets

### ISSUE THREAD

**Issue by Spaceman78** [MicrosoftDocs/OfficeDocs-o365seccomp#411]
The first 2 bullets under the How does ZAP work section both reference Spam but have differing actions.  Shouldn't one of the bullets reference phishing emails? Thnx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c88a1bea-b981-89e7-57db-14b7887618a8
* Version Independent ID: 16dc4701-b3f9-3d6a-f699-418d1201840c
* Content: [Zero-hour auto purge - protection against spam and malware](https://docs.microsoft.com/en-us/office365/securitycompliance/zero-hour-auto-purge)
* Content Source: [SecurityCompliance/zero-hour-auto-purge.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/zero-hour-auto-purge.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@Spaceman78 good catch! We're confirming this, and will correct the content ASAP.

**Comment by denisebmsft** [comment]
Hello @Spaceman78, I believe this issue is now fixed. Please let us know if you have any other questions. And thank you for the feedback. It helps us improve our documentation!
