### ISSUE TITLE
Where is data (emails) stored?

### ISSUE THREAD

**Issue by IanMartin56** [MicrosoftDocs/OfficeDocs-o365seccomp#412]
Hi, if one of our users sends an OME encrypted email, where is the data (email) that is sent stored?  Where is the email that is received stored?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ad427d-d869-2ab6-3d2c-f846efc99256
* Version Independent ID: 606eaa37-2713-8087-015f-012ae9c90090
* Content: [Office 365 Message Encryption FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-faq)
* Content Source: [SecurityCompliance/ome-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-faq.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @IanMartin56. Thank you for posting your question here. We will follow up on this soon.

**Comment by DJ-MSFT** [comment]
The content is stored in the mailbox per normal, however it's encrypted and you'll be redirected to the OME portal in that region to access the content. Hope that helps.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@IanMartin56 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
