### ISSUE TITLE
Office 365 Preview Program - how to join?

### ISSUE THREAD

**Issue by MrNigel** [MicrosoftDocs/OfficeDocs-o365seccomp#413]
Our tenant is set for 'Targeted Release for everyone', can we evaluate the file plan manager?  I have no idea how to join the Office 365 Preview Program as mandated above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1162dfe-1b69-0e06-b3d2-eb5818786e7c
* Version Independent ID: aff337de-d029-6aa4-400b-521069165089
* Content: [Overview of file plan manager](https://docs.microsoft.com/en-us/office365/securitycompliance/file-plan-manager)
* Content Source: [SecurityCompliance/file-plan-manager.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/file-plan-manager.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
Thanks for the question, you can contact your account rep. Some features are released to private preview in which only a few customers are invited to participate. Private preview is different from the targeted release program.
