### ISSUE TITLE
Internet Explorer dependency 

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/OfficeDocs-o365seccomp#414]
Hi,
This addin when used in Outlook on Windows seems to require Internet Explorer.
This being documented would be useful, and ideally removing that as a dependency entirely.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62304805-117a-0e04-038b-a42a89e12162
* Version Independent ID: 7c12ba44-3c56-7607-7e63-84b0073a25df
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in)
* Content Source: [SecurityCompliance/enable-the-report-message-add-in.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@Conan1989 thank you for raising this question. I'm looking into this, and I will post an update here soon.

**Comment by denisebmsft** [comment]
Hello again @Conan1989. I looked into this, and updated the article. Thank you for helping me improve this article. 

Additionally, you do have a forum for providing feedback to the product team at office365.uservoice.com. Here [(https://office365.uservoice.com/search?filter=merged&query=report%20message%20add-in)](https://office365.uservoice.com/search?filter=merged&query=report%20message%20add-in) you can find several ideas/suggestions people have posted for the Report Message add-in. I invite you to take a look and add to the suggestions there. 

Thanks again!

**Comment by Conan1989** [comment]
Request to re-open.

the diff looks like the following was added
"Your existing web browser should suffice for the Report Message add-in to work; however, if you notice the add-in is not available or not working as expected, try a different browser"

to further explain, this issue is with the addin when used on desktop Outlook such as o365 Pro Plus / 2016 / 2019

To reproduce, remove IE.
Report an email as phishing / spam / etc from the desktop Outlook client menu.
Expect to see this error
"We're sorry, we couldn't access Report Message. Make sure you have a network connection. If the problem continues, please try again later."

re-enable IE, all works fine

**Comment by Conan1989** [comment]
screenshots

![2](https://user-images.githubusercontent.com/6946596/53862042-e68f8b00-3fdd-11e9-8f6f-413f512621ad.png)

![1](https://user-images.githubusercontent.com/6946596/53862043-e7282180-3fdd-11e9-9cc8-82c8eaa92a38.png)

**Comment by Dipeshpatel84** [comment]
We have the same problem in outlook O365 MSO 16.0.11328.20156. is there any particular port numbers that need to be opened for this addin. or anything in particular which would help running of this. everything seen so far is vague

**Comment by bplus** [comment]
Any information on this would be really great.  

There is almost no information available when you search (via google) for the "We're sorry, we couldn't access [your plugin name  here]. Make sure you have a network connection. If the problem continues, please try again later." 

We get this error on some client machines, but not others.  And, only when trying to use the desktop Outlook application, not via a web browser. 

This affects several of my clients but I can't replicate the issue in my development setup, so I'm at a loss right now.

**Comment by aldoug** [comment]
Could I ask whether support calls are submitted for the above scenarios? I would like to get this addressed but we will need to collaborate through support channels

**Comment by robbo600** [comment]
I'm seeing these issues too, lodging a ticket with O365 support now, we'll see how it goes.

**Comment by bplus** [comment]
@aldoug I haven't done any support calls.  If you have advice on how to contact support on this I would be interested.  Thank you!

**Comment by aldoug** [comment]
I’m support😉 ping me next week and we can discuss

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 09:00 - 18:00
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by Conan1989** [comment]
how did you go?

**Comment by Dipeshpatel84** [comment]
For us it’s working as long as enabled protected mode is enabled in security settings for internet

________________________________
