### ISSUE TITLE
Type in last paragraph

### ISSUE THREAD

**Issue by arielmoisis** [MicrosoftDocs/OfficeDocs-o365seccomp#415]
recipients' email should read recipients' email

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ff37f5-934e-b357-5835-12f0cae0eb5b
* Version Independent ID: 9106918c-29a1-b327-38cf-b35411232994
* Content: [Create a schedule for a report in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/create-a-schedule-for-a-report)
* Content Source: [SecurityCompliance/create-a-schedule-for-a-report.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-a-schedule-for-a-report.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@arielmoisis thank you so much for catching this. Yikes! It's fixed now. Thank you for helping us improve our documentation!
