### ISSUE TITLE
Office 365 message encryption with non federated accounts like Gmail, Yahoo and saved to disk-attachments.

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-o365seccomp#416]
This article says that Office 365 Message Encryption works with Outlook.com, Yahoo, Gmail, and other email services.
This is however not really correct in regards to Encrypted attachments being stored to disk for viewing later.

Signing into 3rd party accounts such as google or Yahoo is not supported in Rich clients like MS Office to view OME protected attachments.
OME Encrypted files must be opened in the browser directly if they were received by external (non-federated) recipients.
Viewing Attachments saved to disk, will not work unless viewed online, or attachment encryption is disabled.

There is however a workaround available:
You could disable Attachment Encryption for encrypted emails. Like that the attachments will always open no matter where they are stored after being saved to disk.

It would be a global change using Set-IRMConfiguration as described here:
You would need to set DecryptAttachmentForEncryptOnly parameter to $True which by default is set to "False"
https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/set-irmconfiguration?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e8c7180-4b5f-37eb-32b8-c87512ce0820
* Version Independent ID: 33c43b5c-b035-8c8b-7e59-a38492924cf3
* Content: [Office 365 Message Encryption](https://docs.microsoft.com/en-us/office365/securitycompliance/ome)
* Content Source: [SecurityCompliance/ome.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@JeroenDronkers thank you for the feedback. We have a work item in the queue for this, and we will post an update here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
Hi @JeroenDronkers and thank you for raising this issue!  I'll be looking into your question and seeing how it can be used to improve the documentation.

**Comment by TokyoScarab** [comment]
The workaround seems interesting though I would have to look more into it before putting it in the documentation.  It seems like a more streamlined method would be better suited to being added in the documentation.  I can make some changes informing readers about the encrypted attachments though and the limitations with non-federated email accounts.

**Comment by TokyoScarab** [comment]
@JeroenDronkers I found an [article](https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Admin-control-for-attachments-now-available-in-Office-365/ba-p/204007) on this that could be useful for the method you described above.  It is something that an admin would have to set up, but might be more beneficial than the workaround.

**Comment by scanum** [comment]
@JeroenDronkers We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
