### ISSUE TITLE
Add these features to Outlook desktop application

### ISSUE THREAD

**Issue by peterlukerow** [MicrosoftDocs/OfficeDocs-o365seccomp#417]
There is no way to report phishing emails from the Outlook desktop application. At work we're running the Office 365 edition, version 16.0.10730.20264, 64 bit.

Expect users to switch from the application to the web is crazy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13dd34ae-60cf-db1d-0dbd-5b9bc8cdc6bf
* Version Independent ID: 5a430055-9b49-69c6-46f1-e55d0c06457d
* Content: [Report junk email and phishing scams in Outlook on the web ](https://docs.microsoft.com/en-us/office365/securitycompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop)
* Content Source: [SecurityCompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@peterlukerow thank you for the feedback! We are looking into this, and we will post an update here soon.

**Comment by crownschmidtb** [comment]
I believe this is where the Report Message Add-in comes into play, which will work with the office install from the Office 365 portal.

https://support.office.com/en-us/article/use-the-report-message-add-in-b5caa9f1-cdf3-4443-af8c-ff724ea719d2?ui=en-US&rs=en-US&ad=US

https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in

**Comment by peterlukerow** [comment]
I subsequently discovered this plug-in. However I'd argue it should be built into the Office 365 version of the product.

The fact it's not part of the product by default speaks to why Office 365 email doesn't seem to stop much spam. I get plenty of spam, even emails that are obviously phishing attempts none of them get stopped.

**Comment by crownschmidtb** [comment]
Agree @peterlukerow 

Also, per someone on the MS Community forum who I believe knows what they are talking about, I discovered that the Report Message Add-In does not work in the Office MSI installation in the Junk Email, so that is why the Report Message Add-In does not work in my Outlook client version.  I don't get why it wouldn't work in the Junk Email folder or why that would be a limitation.  It seems dumb that it doesn't work.

**Comment by crownschmidtb** [comment]
@denisebmsft Please see my previous responses as well. Thanks.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@peterlukerow thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by peterlukerow** [comment]
Seriously scanum?!
User gives feedback and all you can say is effectively - yeah, well, errm, tell someone else to tell us?!
WTH!

**Comment by denisebmsft** [comment]
Hello @peterlukerow. The suggestion of opening a support ticket isn't to give you the runaround, even though it might seem that way to you. As technical writers publishing help content, we don't have access to internal customer support databases and processes. In your case, something isn't working as expected, and you have valuable feedback to give the product teams. We understand it's frustrating, but in this case, your best bet is to file the support ticket. And we will review the content from our side as well. Thank you @peterlukerow and @crownschmidtb for the feedback, and thank you @scanum for helping with this as well.

**Comment by peterlukerow** [comment]
@denisebmsft - it's not about something not working it's about a MS product giving their users a poor experience by expecting them to download a bunch of MS add-ons when the feature should be built directly into the product.

I guess I am use to Windows 10 feedback app and forgot/didn't realise this was a docs only github thing - in my head I associate github with code not docs.

MS should stop forcing users to go through other people and provide direct channels (see Win 10 feedback app) for feeding back. In large organisations users may not even know the correct person that would need to speak to in order to play the game of chinese whispers. I also would have thought that hearing it direct from the person who is raising the suggestion/issue would be better for MS as well.
