### ISSUE TITLE
Automatic sensitivity label assigned interface

### ISSUE THREAD

**Issue by franciso** [MicrosoftDocs/OfficeDocs-o365seccomp#419]
The document does not explain clearly where the user can go to manage how automatic sensitivity label are assigned (as show in https://docs.microsoft.com/en-us/office365/securitycompliance/media/sensitivity_labels_auto_labeling_options.png) What is the url or steps to access this interface?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a51b92d-11ce-5c5d-bbd0-0229aba04784
* Version Independent ID: 3cdddabc-fa4e-9210-0b09-ef7cb98b4b3e
* Content: [Apply a sensitivity label to content automatically](https://docs.microsoft.com/en-us/office365/securitycompliance/apply_sensitivity_label_automatically#how-automatic-or-recommended-labels-are-applied)
* Content Source: [SecurityCompliance/apply_sensitivity_label_automatically.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/apply_sensitivity_label_automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
All options for sensitivity labels are in the same place - Classifications > Labels > Sensitivity tab > Create label

**Comment by franciso** [comment]
The auto labeling option is nowhere to be seen using my tenant. Is this option (https://docs.microsoft.com/en-us/office365/securitycompliance/media/sensitivity_labels_auto_labeling_options.png) in preview?

**Comment by stephow-MSFT** [comment]
The feature is still in process of rolling out to customers.
