### ISSUE TITLE
Aggregating dispositions

### ISSUE THREAD

**Issue by Russ-Scheveningen** [MicrosoftDocs/OfficeDocs-o365seccomp#425]
What I understand from this discussion, is that dispositions function at individual item level. Does Microsoft have a way to run dispositions on aggregations of data (for example, an entire site collection, library or document set)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d6bbdc-15c0-1f90-85c3-eb950d3a4837
* Version Independent ID: f4810537-30d6-0451-f9fa-62da1af72f2b
* Content: [Overview of disposition reviews](https://docs.microsoft.com/en-us/office365/securitycompliance/disposition-reviews)
* Content Source: [SecurityCompliance/disposition-reviews.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
@Russ-Scheveningen, this is a good question. Thanks for posting this. We are looking into it, and will post an update here soon.

**Comment by stephow-MSFT** [comment]
The disposition feature has been updated so that you can view all pending dispositions by assigned label. You can then bulk select items and dispose them at once.
