### ISSUE TITLE
MailItemsAccessed action Missing

### ISSUE THREAD

**Issue by ksmarker** [MicrosoftDocs/OfficeDocs-o365seccomp#427]
The MailItemsAccessed action started appearing on Feb 16 in the default auditing, however it was removed on Feb 20.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing?redirectSourcePath=%252farticle%252fEnable-mailbox-auditing-in-Office-365-aaca8987-5b62-458b-9882-c28476a66918)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ksmarker Apologies for the intermittent experience. This is related to the rolling out of mailbox auditing on-by-default and the deprecation the MessageBind action. FWIW, I've had the same experience in my tenants. This new auditing action should be available once the default mailbox auditing is fully rolled out. Please open a ticket with Microsoft Support if this continues to be an issue.

**Comment by ksmarker** [comment]
This is not an intermittent issue.  It has not being logging since 2/20.  When is the default mailbox auditing scheduled to be completely rolled out?
