### ISSUE TITLE
Needs an Alert function

### ISSUE THREAD

**Issue by jessecoopercc** [MicrosoftDocs/OfficeDocs-o365seccomp#429]
The Quarantine section needs an alert function so you can set up an email/sms alert to admin account(s) so admin knows they have emails to review. There used to be alerts sent out, but this seems to have stopped for some reason

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de340d87-f658-2c76-c99a-c7a87be7755a
* Version Independent ID: 1ceac9b2-1e6f-7f13-0d32-0fcc92d87244
* Content: [Manage quarantined messages and files as an administrator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/manage-quarantined-messages-and-files?redirectSourcePath=%252farticle%252f065cc2cf-2f3a-47fd-a434-2a20b8f51d0c)
* Content Source: [SecurityCompliance/manage-quarantined-messages-and-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @jessecoopercc, and thank you for the feedback. We're looking into this, and we will post an update here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by mohan1921** [comment]
any update on this feature?

**Comment by jessecoopercc** [comment]
Unfortunately not, I seem to get alerts for malware quarantine but not for spam quarantine...

**Comment by scanum** [comment]
@jessecoopercc thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
