### ISSUE TITLE
 Rule Information

### ISSUE THREAD

**Issue by Demoniak69008** [MicrosoftDocs/OfficeDocs-o365seccomp#43]
Hello,

This rule also works when the message is reported directly by Office365 ?

Or it only works by using the add-in in Outlook 2016 ?

Thank you in advance for your answer.

Best regards

**Comment by denisebmsft** [comment]
@Demoniak69008 can you tell us for which article you have a question?

**Comment by Demoniak69008** [comment]
Hello,

I refer to this article

https://docs.microsoft.com/fr-fr/office365/securitycompliance/enable-the-report-message-add-in?redirectSourcePath=%252fen-us%252farticle%252fenable-the-report-message-add-in-4250c4bc-6102-420b-9e0a-a95064837676&WT.mc_id=email

Best regards

**Comment by denisebmsft** [comment]
@Demoniak69008 thanks. I am working on this. Expect a reply sometime next week.

**Comment by AndreaBarr** [comment]
@Demoniak69008 Thank you for this feedback

I have added this to the backlock for Denise to track.

**Comment by denisebmsft** [comment]
Thanks @Demoniak69008 and @AndreaBarr for the feedback. I have updated the article. Please let me know if anything else is needed.
