### ISSUE TITLE
How to set “Allowed to spoof” to "NO" as default for "Review new senders”

### ISSUE THREAD

**Issue by KikoMarc** [MicrosoftDocs/OfficeDocs-o365seccomp#432]
When reviewing Spoof Intelligence under Threat Management in the Security and Compliance center of Office 365, then choosing “Review new senders” I see that “Allowed to spoof” is set to “Yes” for several users, whereby Admin did not explicitly set it to Yes. Kindly explain why this is happening and if possible, how to set the default to “No” for all spoofed users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2346da88-037b-1ef9-e3c4-c6d448b9688e
* Version Independent ID: 0292959f-9f3d-a34f-156e-bb8488fdc251
* Content: [Learn more about spoof intelligence](https://docs.microsoft.com/en-us/office365/securitycompliance/learn-about-spoof-intelligence)
* Content Source: [SecurityCompliance/learn-about-spoof-intelligence.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/learn-about-spoof-intelligence.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @FrancisMarcelino and thanks for raising this question. We are looking into this, and we will post an update here soon.

**Comment by KikoMarc** [comment]
I hope to hear from you soon regarding my inquiry. Thanks!

**Comment by KikoMarc** [comment]
Hi @denisebmsft, I'd like to get updates regarding this. Thank you!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by smith-ll** [comment]
Any updates on this?

**Comment by lenaklassen** [comment]
Hello @denisebmsft, I'd also like to get updates regarding this. Thank you!

**Comment by scanum** [comment]
@KikoMarc thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
