### ISSUE TITLE
Where to find the option of "Detailed view" to check more details about the spoofed sender under Spoof intelligence.

### ISSUE THREAD

**Issue by LogixOffice365** [MicrosoftDocs/OfficeDocs-o365seccomp#433]
I am only able to view the users listed under "Review new senders" under Spoof intelligence for Internal and External domains but i am unable to get the option for Detailed view as mentioned under the "What you need to do". Kindly suggest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2346da88-037b-1ef9-e3c4-c6d448b9688e
* Version Independent ID: 0292959f-9f3d-a34f-156e-bb8488fdc251
* Content: [Learn more about spoof intelligence](https://docs.microsoft.com/en-us/office365/securitycompliance/learn-about-spoof-intelligence?redirectSourcePath=%252farticle%252f978c3173-3578-4286-aaf4-8a10951978bf)
* Content Source: [SecurityCompliance/learn-about-spoof-intelligence.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/learn-about-spoof-intelligence.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @LogixOffice365. We are looking into this, and we will post an update soon.

**Comment by amberru1** [comment]
any answer on this yet?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by smith-ll** [comment]
Any updates on this?

**Comment by southwick7320** [comment]
Any update, this seems like an important feature?

**Comment by scanum** [comment]
@LogixOffice365 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
