### ISSUE TITLE
Quarantine Retention Time

### ISSUE THREAD

**Issue by jdotto02** [MicrosoftDocs/OfficeDocs-o365seccomp#435]
The maximum configurable quarantine retention time is now 30 days (https://docs.microsoft.com/en-ca/office365/SecurityCompliance/quarantine-faq) and not 15 days as is stated in this document.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b37016-da2f-6e2a-c3e7-360c3e9ec5ed
* Version Independent ID: 395a4420-1d14-5b0a-0be8-8f2b36fdb081
* Content: [Configure your spam filter policies](https://docs.microsoft.com/en-ca/office365/SecurityCompliance/configure-your-spam-filter-policies)
* Content Source: [SecurityCompliance/configure-your-spam-filter-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-your-spam-filter-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
@jdotto02 thank you very much for the feedback. We have a work item in the queue and we are looking into this. Watch for an update to be posted here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msbemba** [comment]
@jdotto02 Thank you for the feedback. The changes are made to reflect maximum configurable quarantine retention time to 30 days.

Thanks
Sri

**Comment by scanum** [comment]
@jdotto02 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
