### ISSUE TITLE
Wrong variable name. New-DlpSensitiveInformationType missing.

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#438]
I think this code box :
$Employee_Template = Get-Content "C:\My Documents\Contoso Customer Information Form.docx" -Encoding byte -ReadCount 0
$Customer_Fingerprint = New-DlpFingerprint -FileData $Customer_Form -Description "Contoso Customer Information Form"
New-DlpSensitiveInformationType -Name "Contoso Customer Confidential" -Fingerprints $Customer_Fingerprint -Description "Message contains Contoso customer information."

should be 
$Customer_Form = Get-Content "C:\My Documents\Contoso Customer Information Form.docx" -Encoding byte -ReadCount 0
$Customer_Fingerprint = New-DlpFingerprint -FileData $Customer_Form -Description "Contoso Customer Information Form"
New-DlpSensitiveInformationType -Name "Contoso Customer Confidential" -Fingerprints $Customer_Fingerprint -Description "Message contains Contoso customer information."

Moreover I don't understand why I the first code box we only suggest to run these two commands:
$Employee_Template = Get-Content "C:\My Documents\Contoso Employee Template.docx" -Encoding byte -ReadCount 0
$Employee_Fingerprint = New-DlpFingerprint -FileData $Employee_Template -Description "Contoso Employee Template"
I think we should run also New-DlpSensitiveInformationType. Article itself says that: "Because the results of New-DlpFingerprint aren't stored outside the data classification rule, you always run New-DlpFingerprint and New-DlpSensitiveInformationType"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33048da1-661a-5c5d-91ee-e4e4031c6022
* Version Independent ID: 9558f091-9ffc-c950-277a-7509910bf5ae
* Content: [Document Fingerprinting](https://docs.microsoft.com/en-us/office365/securitycompliance/document-fingerprinting#feedback)
* Content Source: [SecurityCompliance/document-fingerprinting.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/document-fingerprinting.md)
* Service: **exchange-online**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
Hello @pawp81, and thank you for the feedback. We're looking into this, and an update will be posted here soon.

**Comment by Esaggese** [comment]
I can confirm that pawp81 feedback is correct. The example in the document will throw an error stating that the document contains no data (since it is pointing to an empty variable).

**Comment by stephow-MSFT** [comment]
@pawp81 good catch
@Esaggese thanks for confirming
I've updated that code block in the article.

Also, the 2nd code block runs New-DlpSensitiveInformationType - that's why it's not in the 1st.
