### ISSUE TITLE
MFA requirement

### ISSUE THREAD

**Issue by CraigHumphrey** [MicrosoftDocs/OfficeDocs-o365seccomp#439]
Can you flesh out the MFA requirement?
We have MFA on most but not all (we'll never have it on all - thanks to service accounts) accounts, including the one I'm using to access the service, but it wont allow me to run any of the attacks.
I get the "You must enable multi-factor authentication (MFA) to schedule or terminate attacks. Learn more about enabling MFA." warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator#spearphish)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @CraigHumphrey. I am working on this, and I should have an update for you soon. Thank you for the feedback!

**Comment by denisebmsft** [comment]
Hello again, @CraigHumphrey. MFA must be turned on for the Office 365 global administrator account. However, we do recommend that MFA be enabled for all user accounts. 

I have updated the article to include mention that the global admin account be configured to use MFA. 

Hope this helps!

And thank you for helping me improve the documentation!

**Comment by CraigHumphrey** [comment]
Thanks @denisebmsft!
Though I think it's still not quite right.  We have multiple O365 Global Admins (don't ask...), they all have MFA enabled and mine is one of them.  But it's still asking me to turn on MFA.

Note: I'm expecting it to complain we're not using Exchange Online (we're still on-prem).

Perhaps this is a bug, rather than a documentation issue?

**Comment by CSTSEC** [comment]
I encountered the same issue. I was able to get it working by creating an account required to use MFA for all apps in Azure 'conditional access'. This makes it so I have to use MFA when logging into the Security and Compliance portal, which apparently satisfies the Attack Simulator MFA requirement.
