### ISSUE TITLE
'RYUK' ransomware

### ISSUE THREAD

**Issue by Rahulo365** [MicrosoftDocs/OfficeDocs-o365seccomp#44]
Office365 also seem to protect new ransomware "Ryuk". It would good to see this article update about the same 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2db4e9b-cd96-96b5-08b8-d2f61db73f75
* Version Independent ID: 6b41374b-20d5-614c-9e33-b2ff87234796
* Content: [Office 365 Malware and Ransomware Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-malware-and-ransomware-protection)
* Content Source: [SecurityCompliance/office-365-malware-and-ransomware-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-malware-and-ransomware-protection.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
Thanks for the feedback, topic updated to remove mentioning any specific ransomware - this topic is scoped to address malware and ransomware all-up for Office 365 and the link to the Windows Defender Security Intelligence site covers specific ransomware threat mitigation.
