### ISSUE TITLE
Missing users from list of members

### ISSUE THREAD

**Issue by CMSPhil** [MicrosoftDocs/OfficeDocs-o365seccomp#440]
I am trying to give a user a Security Administrator permission, but their name does not appear in members to select them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center#feedback)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
Hello @CMSPhil. Thank you for letting us know about this issue. We're looking into it, and an update will be posted here soon.

**Comment by stephow-MSFT** [comment]
Check the user exists in the Office 365 Admin Center - if not, add them here

https://admin.microsoft.com/Adminportal/Home?source=applauncher#/users
