### ISSUE TITLE
Print screen is misleading

### ISSUE THREAD

**Issue by razvan-b** [MicrosoftDocs/OfficeDocs-o365seccomp#441]
In the print screen example we have folderid:FD58AF.... . This is misleading. You need to add &lt;&gt; before and after the folder id in order for the search to work. If not, you will have the error : Application error occurred. Please try again later. (CS012-002) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9162d31-5514-df46-aff8-679814ed5060
* Version Independent ID: a6ffc7a8-ffe0-9f72-9371-27b6ee51e8e5
* Content: [Use Content Search in Office 365 for targeted collections](https://docs.microsoft.com/en-us/office365/securitycompliance/use-content-search-for-targeted-collections#feedback)
* Content Source: [SecurityCompliance/use-content-search-for-targeted-collections.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-content-search-for-targeted-collections.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
Hello @razvan-b. Thank you for the feedback. We're looking into this, and an update will be posted here soon.

**Comment by markjjo** [comment]
@razvan-b The lack of "<>" in the keyword query is unrelated. I checked with engineering team and the error you encountered is a transient error. Please re-try your search (without the brackets). Also, be sure that you're only searching a single mailbox; in this case, the mailbox where the folder is located. Here's a little more info about CS012-002: https://docs.microsoft.com/en-us/Office365/SecurityCompliance/retry-failed-content-search  

The use of the bracket in this article is just to denote a placeholder and shouldn't be used in the actual keyword query. I will remove these from the documentation as they are confusing.

**Comment by razvan-b** [comment]
Hi Mark,

I have opened a case with support because the search was not working 
without <> at the begging and at the end of the folderID. Please check 
the attachment for more details.

Can you give me the email of your contact in engineering who provided 
the info ? If not, can you ask them to contact me on Teams using 
razvanb@microsoft.com


Thanks,
Razvan
