### ISSUE TITLE
Teams resiliency info

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#444]
Hello, do you plan to include info about data resiliency in Teams? On similar detail level like for EXO and SPO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20e9936-697a-fd79-ec14-f56e89fa29e9
* Version Independent ID: e4e4ed6b-8501-3124-9d41-81cb3a5fd39f
* Content: [Data Resiliency in Office 365](https://docs.microsoft.com/en-us/Office365/securitycompliance/office-365-data-resiliency-overview)
* Content Source: [SecurityCompliance/office-365-data-resiliency-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-data-resiliency-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
Hello @Larryngolog, and thank you for the feedback. We are looking into this. My teammate who owns this article is out this week, but he'll look at this and a couple of others when he's back in the office.

**Comment by robmazz** [comment]
@Larryngolog  - thanks so much for the feedback! Yes, we are looking into possibly expanding coverage to include Teams, though it is currently at a low priority in our current work backlog. Your feedback helps with our ongoing evaluation and I'll keep this issue on my radar and reach back out to you when our work status on this topic changes. Thanks!
