### ISSUE TITLE
Isolation for Teams

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#445]
Hello, do you plan to include info about isolation and data control in Teams? On similar detail level like for EXO, S4BO and SPO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e51655-ce8e-dee6-ef1b-942101084208
* Version Independent ID: 23b4c0cc-8420-a790-eeae-6332eff530eb
* Content: [Office 365 Isolation and Access Control in Office 365](https://docs.microsoft.com/en-us/Office365/securitycompliance/office-365-isolation-in-office-365)
* Content Source: [SecurityCompliance/office-365-isolation-in-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-isolation-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
Hello @Larryngolog and thank you for the feedback! We are looking into this.

**Comment by robmazz** [comment]
@Larryngolog - thanks so much for the feedback! As I also mentioned in your other request about Data Resiliency and the inclusion of Teams information, this has been considered and is also in our work backlog to look into these updates. I'll continue to investigate and update you on the status of this request as we review this work in our upcoming sprints. Thanks!
