### ISSUE TITLE
Encryption in Teams

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#446]
Hello, do you plan to include info about data encyrption in Teams? On similar detail level like for EXO and SPO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52a31b5-6ba4-c837-52a2-4938b615baec
* Version Independent ID: f8820fb3-c3bd-8804-5033-fbc6f0759d82
* Content: [Office 365 Encryption for Skype, OneDrive, SharePoint, and Exchange](https://docs.microsoft.com/en-us/Office365/securitycompliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange)
* Content Source: [SecurityCompliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @Larryngolog, and thank you for raising this question. We are looking into this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Larryngolog Thanks for your feedback, the author will consider including this in the future. Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
