### ISSUE TITLE
Contradiction

### ISSUE THREAD

**Issue by AaronDinnage** [MicrosoftDocs/OfficeDocs-o365seccomp#448]
"when a user uploads a file to SharePoint Online, that file is disassembled and translated into application code and stored in multiple tables across multiple databases"
contradicts with:
"SharePoint Online stores file binary blobs (e.g., the file streams) in Microsoft Azure"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e51655-ce8e-dee6-ef1b-942101084208
* Version Independent ID: 23b4c0cc-8420-a790-eeae-6332eff530eb
* Content: [Office 365 Isolation and Access Control in Office 365](https://docs.microsoft.com/en-au/office365/securitycompliance/office-365-isolation-in-office-365#feedback)
* Content Source: [SecurityCompliance/office-365-isolation-in-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-isolation-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
Hello @AaronDinnage. Thank you for letting us know about this. We are looking into it.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by robmazz** [comment]
@AaronDinnage - thanks for the feedback! SharePoint Online stores document metadata in SQL and the actual encrypted file content in stored in Azure blob storage. I've updated the topic with these clarifications.
