### ISSUE TITLE
Some updates needed

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-o365seccomp#449]
Hi folks, can you please make sure you're using the latest "terms" in the documentation. Few examples:

 - When describing the new dashboard, the "Supervision" tab is mentioned. However, in the actual dashboard, the tab is named "Review"
 - When detailing the PowerShell cmdlets, you are using the "old" ones. Nowadays, only the "V2" cmdlets exist, such as New-SupervisoryReviewPolicyV2. The exception being the Get-* cmdlets, which are still available for backwards compatibility.
 - The PowerShell example in the Auditing section uses variables that are undefined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0793ffc7-f4ef-691a-acbd-fd614e91b0f3
* Version Independent ID: e6be5b46-744f-3757-b92f-46d8816a9e2b
* Content: [Supervision Policies in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/supervision-policies)
* Content Source: [SecurityCompliance/supervision-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/supervision-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
Hello @michevnew, and thank you for the feedback. We are looking into this, and we will post an update here soon.

**Comment by robmazz** [comment]
@michevnew - thanks so much for your comments! I've updated the topic to address these issues and you should see them live soon at https://docs.microsoft.com/office365/securitycompliance/supervision-policies#auditing.
