### ISSUE TITLE
Left hand side menu, grammar error: Get Started > Security "Dashbord" Should be Dashboard.

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-o365seccomp#45]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 113e14a6-61b3-6764-1b95-7c021ab7bb0a
* Version Independent ID: 69ee3e8d-7115-09c9-1e2d-abf35fbdff6d
* Content: [Security dashboard overview](https://docs.microsoft.com/en-us/office365/securitycompliance/security-dashboard#feedback)
* Content Source: [SecurityCompliance/security-dashboard.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/security-dashboard.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you for the feedback. This is now fixed.
