### ISSUE TITLE
TFN keywords list 

### ISSUE THREAD

**Issue by jonathonashfield** [MicrosoftDocs/OfficeDocs-o365seccomp#460]
Please can you modify the default keywords list to include the abbreviation 'TFN'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd170f21-e0d6-4bd0-ee70-df9fc165f9fe
* Version Independent ID: 31c72b93-a444-90ad-508e-c43fa522f8fc
* Content: [Create, test, and tune a DLP policy](https://docs.microsoft.com/en-us/office365/securitycompliance/create-test-tune-dlp-policy#feedback)
* Content Source: [SecurityCompliance/create-test-tune-dlp-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
Hello @jonathonashfield and thank you for the feedback. We are looking into this.

**Comment by stephow-MSFT** [comment]
Hey, we can fwd your request to the engineering team.

In the meantime, you can modify any of the built-in sensitive information types -- you can include 'TFN' in the keyword list by following the steps here -

https://docs.microsoft.com/en-us/office365/securitycompliance/customize-a-built-in-sensitive-information-type
