### ISSUE TITLE
Add reference to new Compliance Center

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#466]
The SCC is getting separated into 2 centers, this documentation should mention how to use this tool from the new Compliance Center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 456c69b0-7745-6eef-8818-c80396de3281
* Version Independent ID: ab8a17f7-ec7f-1a16-b585-807749350b52
* Content: [Release notes for Advanced eDiscovery (Preview)](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/compliance20/release-notes-ediscovery20)
* Content Source: [SecurityCompliance/compliance20/release-notes-ediscovery20.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/compliance20/release-notes-ediscovery20.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
We're in the process of doing this for **all** topics in the security and compliance TOC on docs.microsoft.com (to be completed by the end of March)  to learn more about the new admin experience, see: https://docs.microsoft.com/en-us/office365/securitycompliance/microsoft-security-and-compliance
