### ISSUE TITLE
Holding data in other apps/services

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#467]
Please add some information about the ability/plans to place holds on content that is all of the other O365 services, e.g. Forms, Stream, Yammer, ToDo, etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f9cc1ad-1edc-b956-3121-fd22bf69c201
* Version Independent ID: 2b8ba1ea-e514-e454-63a3-b58c5aca8445
* Content: [Manage holds in Advanced eDiscovery (Preview)](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/compliance20/managing-holds)
* Content Source: [SecurityCompliance/compliance20/managing-holds.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/compliance20/managing-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
Hello @DeanGross, and thank you for the feedback. We are looking into this.

**Comment by markjjo** [comment]
@DeanGross We published a new topic about the Office 365 apps that store data in an EXO mailbox: https://docs.microsoft.com/en-us/Office365/SecurityCompliance/what-is-stored-in-exo-mailbox 

Article cites that Forms and Planner data isn't preserved when hold is placed on mailbox. As more Office 365 app store data in a mailbox, topic will be updated.

Here's some info about retention in Yammer: https://docs.microsoft.com/en-us/yammer/manage-security-and-compliance/manage-data-compliance
