### ISSUE TITLE
Jumpy text size

### ISSUE THREAD

**Issue by kepacek** [MicrosoftDocs/OfficeDocs-o365seccomp#468]
Hi, it seems that the text size in this article is somewhat exaggerated at some points. Please check out the paragraphs and text formatting in order to make this more readable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73681216-32f3-f9a2-51b1-690e4b7c4c38
* Version Independent ID: c3213d50-3e63-4324-7a74-651d4c2b0492
* Content: [Get started with Office 365 Threat Investigation and Response](https://docs.microsoft.com/en-us/office365/securitycompliance/get-started-with-ti)
* Content Source: [SecurityCompliance/get-started-with-ti.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/get-started-with-ti.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@kepacek thank you so much for pointing this out. We did have some formatting issues in there. It's fixed now, and the update will be live within a few moments. Thank you so much for letting us know about this.
