### ISSUE TITLE
Dynamic Delivery Unsupported Conditions

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/OfficeDocs-o365seccomp#469]
Please can the documentation be updated to detail the end state of messages that meet the unsupport Dynamic Delivery criteria. Are these not scanned? Or are they applicable to Replace, Block, Monitor etc.

**Comment by denisebmsft** [comment]
Hello @scottclarke1! Thank you for posting your question here. Just so I'm clear on what you are asking, are you asking about what happens to email messages when Dyamic Delivery is selected but the email messages or environment doesn't meet the requirements for Dynamic Delivey? https://docs.microsoft.com/en-us/office365/securitycompliance/dynamic-delivery-and-previewing#are-there-scenarios-for-which-dynamic-delivery-is-not-available

**Comment by scottclarke1** [comment]
Hi Denise
That’s right. :-)

**Comment by denisebmsft** [comment]
@scottclarke1 in those cases, the messages are not scanned. However, if there are URLs in those email messages, the URLs would be scanned, assuming Safe Links protection is in place. And yes, i will update the documentation accordingly. Thank you again for the feedback!!

**Comment by denisebmsft** [comment]
@scottclarke1 I have updated the documentation. Thank you for the feedback--it helps us improve the documentation!
