### ISSUE TITLE
What's correct?

### ISSUE THREAD

**Issue by DougPlumley** [MicrosoftDocs/OfficeDocs-o365seccomp#47]
In this article "It's important to remember, however, that Exchange role groups and Security & Compliance Center role groups don't share membership or permissions."

But in the Exchange Online admin portal, looking at the out of the box "Compliance Management" role group I see this in the description "Membership in this role group is synchronized across services and managed centrally. This role group is not manageable through Microsoft Exchange. Members of this role group may include cross-service helpdesk or password administrators, as well as external partner groups and Microsoft Support. By default, this group is not assigned any roles. However, it will be a member of the View-Only Organization Management role group and will inherit the rights of that group."

I also see another role group "ComplianceAdmins_11406#####" in Exchange, what is that?

Why is this so confusing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
Thank you for the feedback, @DougPlumley. We will look into this.

**Comment by AndreaBarr** [comment]
@DougPlumley Thank you for this feedback

I am adding this to the o365seccomp team for investigation and updating. For expiated answers please open a support ticket. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
