### ISSUE TITLE
Some minor corrections needed on this page, please

### ISSUE THREAD

**Issue by cyberswimmer** [MicrosoftDocs/OfficeDocs-o365seccomp#471]
My name is Eric Wolff and I am a Senior Product Marketing Manager at Thales eSecurity. Some feedback on the page:  

1. Thales is in the process of divesting the nShield product line to a company called "nCipher". Can you change the occurrences of "Thales nShield" to "nCipher nShield" and the various "Thales" references below to nCipher". I have made the changes in the text proposed below.

2. You are welcome to verify this next request with Sumedh Bard or anyone on the Azure Key Vault team. Thales eSecurity has a relatively new product that manages Azure Key Vault keys using AKV Bring Your Own Key (BYOK) APIs. It is called CipherTrust Cloud Key Manager and it is available on the Azure Marketplace and also for Azure Stack, and is selected by Microsoft as a "Microsoft Preferred Product".  Therefore, I am proposing this new text for the area of this page that begins with, "To import a key directly into your key vault..."

To import a key directly into your key vault, you need to use the CipherTrust Cloud Key Manager from Thales eSecurity or have an nCipher nShield Hardware Security Module.

Some organizations prefer a "Bring Your Own Key" approach to establish the provenance of their keys, and these methods also provides the following:

&gt; CipherTrust Cloud Key Manager from Thales, available on the Microsoft Azure Marketplace and for Azure Stack, offers you Web- or API-driven full encryption key life cycle management for Azure keys. The key source for CipherTrust Cloud Key Manager encryption keys for Azure Key Vault can be either a Vormetric Data Security Manager, available in the Azure Marketplace with FIPS 140-2 Level 1 certification, or as an on-premises appliance with up to FIPS 140-2 Level 3 certification) or an nCipher nShield HSM.

&gt; nCipher nShield Hardware Security Modules (HSM)
The toolset used for key import includes attestation from nCipher that the Key Exchange Key (KEK) that is used to encrypt the key you generate is not exportable and is generated inside a genuine HSM that was manufactured by nCipher.

The toolset includes attestation from nCipher that the Azure Key Vault security world was also generated on a genuine HSM manufactured by nCipher. This attestation proves to you that Microsoft is also using genuine nCipher hardware.

Check with your security group to determine if the above attestations are required. For detailed steps to create a key on-premises and import it into your key vault, see How to generate and transfer HSM-protected keys for Azure Key Vault. Use the Azure instructions to create a key in each key vault.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e55fe21-a628-4ad9-b250-82fc24714fce
* Version Independent ID: ce31506e-5a7b-47dc-6ea7-87633e07a379
* Content: [Controlling your data in Office 365 using Customer Key](https://docs.microsoft.com/en-us/office365/securitycompliance/controlling-your-data-using-customer-key#feedback)
* Content Source: [SecurityCompliance/controlling-your-data-using-customer-key.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/controlling-your-data-using-customer-key.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@cyberswimmer thank you very much for the feedback. We are looking into this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by KCCross** [comment]
This has been taken on by the product team. Thanks again for the information.
