### ISSUE TITLE
Retroactive?

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/OfficeDocs-o365seccomp#474]
I am having trouble understanding the difference between Automatic Labeling, Automatic labeling through Cloud App Security, and Automatic labeling with the AIP scanner. Does this automatic labeling only apply to SharePoint/OneDrive? Does it apply retroactively to documents already created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a51b92d-11ce-5c5d-bbd0-0229aba04784
* Version Independent ID: 3cdddabc-fa4e-9210-0b09-ef7cb98b4b3e
* Content: [Apply a sensitivity label to content automatically](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/apply_sensitivity_label_automatically)
* Content Source: [SecurityCompliance/apply_sensitivity_label_automatically.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/apply_sensitivity_label_automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
Sensitivity labels and AIP labels are completely interoperable. For your other questions, this info from the article might help - 

Automatic labeling applies to Word, Excel, and PowerPoint when documents are saved, and to Outlook when emails are sent. These conditions detect sensitive information in the body text in documents and emails, and to headers and footers -- but not in the subject line or attachments of email.

So no, no retroactive labels.
