### ISSUE TITLE
Unable to change Litigation Hold Duration on Inactive Mailbox for Deleted User

### ISSUE THREAD

**Issue by tjlogue4** [MicrosoftDocs/OfficeDocs-o365seccomp#475]
Hi,

I am trying to change the LitigationHoldDuration on an  InactiveMailbox, for a user that was deleted about 6 months ago. The duration is currently "Unlimited" but I need it to be "4500". I receive an error regarding licensing stating "Your Microsoft Exchange Online license doesn't permit you to put a litigation hold on this mailbox." I am not able to assign a license given there is no user in O365 associated with this mailbox.

Is it possible to change the duration of the hold.

Thank you,

Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e28d8d2-861e-ac51-af16-d60d3b044668
* Version Independent ID: 1a4b8d24-a96a-7334-a9cb-9c7d6526a738
* Content: [Change the hold duration for an inactive mailbox in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/change-the-hold-duration-for-an-inactive-mailbox#feedback)
* Content Source: [SecurityCompliance/change-the-hold-duration-for-an-inactive-mailbox.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/change-the-hold-duration-for-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@tjlogue4 What command did you run? In EXO PowerShell, I ran **Set-Mailbox -InactiveMailbox -Identity <identity of inactive mailbox> -LitigationHoldDuration 4500** and it worked. Did you run Get-Mailbox -InactiveMailboxOnly | FL *litigation*? to get info about the inactive mailbox? Did that command return the inactive mailbox that you want to change the hold duration for? Did you verify that there is a LitHold on that mailbox? The message that you got sounds like there isn't a lithold on that mailbox. You could ping me offline or I suggest that you open a ticket with MS support.

**Comment by tjlogue4** [comment]
@markjjo I ran: **Get-Mailbox -InactiveMailboxOnly | FL DisplayName,Name,IsInactiveMailbox,LitigationHoldEnabled,LitigationHoldDuration,InPlaceHolds,ExchangeGuid**

It returned several users but the specific user I am changed has the following:
DisplayName            : A***** R*****
Name                   : A***** R*****
IsInactiveMailbox      : True
LitigationHoldEnabled  : True
LitigationHoldDuration : Unlimited
InPlaceHolds           : {}
ExchangeGuid           : _ExchangeGUID_

Then I ran the following: **Set-Mailbox -InactiveMailbox -Identity _ExchangeGUID_ -LitigationHoldDuration 4500**

The following Error was returned:
The action 'Set-Mailbox', 'LitigationHoldDuration', can't be performed on the user '_ExchangeGUID_'. Your
Microsoft Exchange Online license doesn't permit you to put a litigation hold on this mailbox.
    + CategoryInfo          : NotSpecified: _ExchangeGUID_:MailboxIdParameter) [Set-Mailbox], RecipientTaskEx
   ception
    + FullyQualifiedErrorId : [Server=******** ,RequestId=**************,TimeStamp=3/11/2019 10:27:35 PM
   ] [FailureCategory=Cmdlet-RecipientTaskException] 60E38B9D,Microsoft.Exchange.Management.RecipientTasks.SetMailbox
    + PSComputerName        : outlook.office365.com

Thanks, 

Tom

**Comment by markjjo** [comment]
@tjlogue4 Sorry but I have to ask: in the Set-Mailbox command, you're using the actual ExchangeGUID value, correct? (the one returned by Get-Mailbox? Did you try to run Set-Mailbox using a different identity value? Like DN? The error messages makes it sound like the mailbox you're trying to change isn't on Litigation Hold. You might try:

$InactiveMailbox = Get-Mailbox -InactiveMailboxOnly -Identity "A***** R*****"
Set-Mailbox -InactiveMailbox -Identity $InactiveMailbox.DistinguishedName -LitigationHoldDuration 4500

Of use $InactiveMailbox.ExchangeGuid or another identity value as long as you're sure it's unique?

As I said, I can't repo your problem; I'm able to change the duration of a litigation hold an inactive mailbox that has been inactive for more than 2 years.

**Comment by tjlogue4** [comment]
Just double checked, it's the proper ID, also tried your method and got the same error (seen below).

The action 'Set-Mailbox', 'LitigationHoldDuration', can't be performed on the user '***** .PROD.OUTLOOK.COM/Microsoft Exchange
Hosted Organizations/*our_domain*.onmicrosoft.com/Soft Deleted Objects/A***** R****'. Your Microsoft Exchange Online license doesn't
permit you to put a litigation hold on this mailbox.
    + CategoryInfo          : NotSpecified: (NAMPR18A004.PRO...ts/A**** R****:MailboxIdParameter) [Set-Mailbox], RecipientTaskExcep
   tion
    + FullyQualifiedErrorId : [Server=***** ,RequestId=***** ,TimeStamp=3/11/2019 11:59:41 PM
   ] [FailureCategory=Cmdlet-RecipientTaskException] 64F2FFAC,Microsoft.Exchange.Management.RecipientTasks.SetMailbox
    + PSComputerName        : outlook.office365.com

I think the issue may have to do with the fact that the user no longer exists and does not have a license assigned to it. When you run this, does the user still exist  in O365, and does that user have a license assigned to it?

**Comment by markjjo** [comment]
@tjlogue4 Curious, when was the lithold originally created (Get-Mailbox -InactiveMailboxOnly | FL LitigationHoldDate)?

By definition, an inactive mailbox is no longer associated with a user; the supported way to make a mailbox inactive is to place a hold on it and then delete the corresponding O365 user account. But it seems that the Set-Mailbox cmdlet is enforcing licensing. One guess is that the mailbox didn't have an EXO Plan 2 license when the lithold was initially created, but the hold was still created (before licensing was enforced by the cmdlet,  licensing compliance was per the EULA). Then the mailbox was made inactive and now Set-Mailbox is enforcing the licensing when you try to change the duration. Just a guess.

Here's one possible workaround. Consider documenting what you do, particularly info/properties about previous inactive mailbox mapped to the new one (e.g. old and new ExchangeGuid, old and new DN, old and new principal SMTP address, etc).

1. "Back up" the existing inactive mailbox by running a Content Search; use a search query that returns all items (e.g. a blank keyword query). Then export the search results to a PST file and download it.
2. Recover the inactive mailbox. See this topic: https://docs.microsoft.com/en-us/office365/securitycompliance/recover-an-inactive-mailbox Be sure to read all of the More info section about the description of what happens, guidance for naming the new mailbox, and especially the bit about the old inactive mailbox being converted to an active mailbox. If you plan to recover the inactive mailbox, determine beforehand what value to use for the -MicrosoftOnlineServicesID parameter. This parameter will used as the SMTP address for the new active mailbox (with new ExchangeGUID and DN), you can use the SMTP from inactive mailbox if it's still unique in your org.
3. In the M365 admin center, assign an EXO Plan 2 (E3 or E5) license to the new user account that is created as a result of step 2.
4. In EXO, place the new mailbox on Litigation Hold with a duration of 4500 days (or whatever your requirement is).
5. Wait at least 60 minutes (or even 24 hours) and then verify that the Litigation Hold is created on the mailbox.
6. Delete the corresponding user account in the M365/O365 admin center.
7. Verify that the mailbox was made inactive (IsInactiveMailbox = True)

Hope this makes sense and can resolve your issue.

Mark

**Comment by markjjo** [comment]
@tjlogue4 Additionally, for compliance reasons, after you verify the "new" inactive mailbox is in place with the 4500 day lithold duration, you might want to delete the PST backup file and delete the content search that you created in step 1 above.

**Comment by markjjo** [comment]
@tjlogue4 I checked with MS Support and here's more that sounds relevant to your situation: 

"This happens when the customer downgrades the license while the mailbox is on litigation hold – Persisted capabilities is changed from BPOS_S_Enterprise to some other license, typically P1 which is BPOS_S_Standard. Archive add on license is also another license that allows hold (BPOS_S_ArchiveAddOn).

They can see what is set by  running:

Get-mailbox [-InactiveMailboxOnly] <user> | fl Persist*

With the current implementation the system won’t remove the hold when it is downgraded but it won’t allow them to make changes to litigation hold other than remove it. If they transition the mailbox to inactive with a license that does not support hold (eg: P1) then the mailbox retains the P1 capability when transitioned to inactive as opposed to the P2 if it was not downgraded. This will cause this error if the customer tries to set the duration, since it does not have the appropriate capability set on the mailbox."

**Comment by tjlogue4** [comment]
@markjjo This is the issue. After we set the litigation hold, we later downgraded license when the employee no longer worked here.

Thank you very much for the help and information.

Tom
