### ISSUE TITLE
Phishing and Scam Emails in Outlook.

### ISSUE THREAD

**Issue by RicardoEva** [MicrosoftDocs/OfficeDocs-o365seccomp#476]
My email account was, and has been, hacked for a very long time. No matter how much, or how often, I mark emails as either junk, spam, phishing and even ask outlook to "block" the senders yet I still get the same scam mails from the same sender over and over and over again! I spoke to a myriad of "CS reps" to no avail, I have eliminated a whole lot of "suspicious" (to Microsoft) software, I have clean my PC using a myriad of paid and "unpaid" security software, I have wiped my hard drives and done a number of "clean installs" just to have the spam emails come back within an hour! I have even recurred to trying to close my Microsoft account altogether, an account which I HAVE HAD SINCE HOTMAIL LAUNCHED (and even before that if you want to count when Bill Gates launched his first Windows back then when we had to have a floppy with the OS - DOS - and ANOTHER with WORDPERFECT and yet a third one with LOTUS 1-2-3! ah, don´t forget HAVARD GRAPHICS!! but I digress) only to find out that if I were to close my Microsoft account I would LOOSE ALL OF THE WORK I'D COMPILED FOR SO MANY YEARS! so, you tell me, is YOUR "answer" of any help? I'd rather say NOT!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13dd34ae-60cf-db1d-0dbd-5b9bc8cdc6bf
* Version Independent ID: 5a430055-9b49-69c6-46f1-e55d0c06457d
* Content: [Report junk email and phishing scams in Outlook on the web ](https://docs.microsoft.com/en-us/office365/securitycompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop#feedback)
* Content Source: [SecurityCompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @RicardoEva, we are very sorry to hear that this has happened to you. And you are correct; this article can't help with your situation.
