### ISSUE TITLE
Integration direction is unclear

### ISSUE THREAD

**Issue by chooko** [MicrosoftDocs/OfficeDocs-o365seccomp#477]
Hello,

As a SIEM Engineer, I've been asked if this particular integration will work with the SIEM we use. Generally in SIEM theory, we're looking at data flows from a device -------&gt; (into) the SIEM. 

Is this integration designed for the SIEM to be a data source -------&gt; (into) Office 365 Cloud App Security? Or is it designed to be an additional data source fed -------&gt; (into) the SIEM?

It's a bit hard to tell in this documentation...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e348a89-eba5-4b74-d64d-76d6f923610b
* Version Independent ID: f8523776-9be1-f349-70ef-9f93f5479efa
* Content: [Integrate your SIEM server with Office 365 Cloud App Security](https://docs.microsoft.com/en-us/office365/securitycompliance/integrate-your-siem-server-with-office-365-cas#feedback)
* Content Source: [SecurityCompliance/integrate-your-siem-server-with-office-365-cas.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/integrate-your-siem-server-with-office-365-cas.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @chooko and thank you for the feedback. The integration is designed to be a data source for your SIEM server. It'll stream activities and alerts from Cloud App Security to your SIEM server. I hope this helps! I will update the overview to make this more clear.

**Comment by chooko** [comment]
Yes, thank you!
