### ISSUE TITLE
Activate Users Link Issue

### ISSUE THREAD

**Issue by jdotto02** [MicrosoftDocs/OfficeDocs-o365seccomp#478]
In step #4 in the "To synchronize user directories" section the "Activate synced users" link doesn't appear to be pointing to the correct website. The "What is hybrid identity?" website it points to doesn't mention anything about activating users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d99a1fa-e2de-8032-1599-8b3307bd8035
* Version Independent ID: 59c8bdec-85cd-d0de-3580-eed3aaec4822
* Content: [Manage mail users in EOP](https://docs.microsoft.com/en-us/office365/securitycompliance/eop/manage-mail-users-in-eop)
* Content Source: [SecurityCompliance/eop/manage-mail-users-in-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/manage-mail-users-in-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @jdotto02. I took a look at this and I see what you're describing. We are looking into this, and we will post an update here soon. Thank you for posting your feedback here.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msbemba** [comment]
@jdotto02 Thank you for the feedback. The doc was outdated. We have removed the activation part as the mail users show up in Exchange online as soon as the synchronization is complete and there is no activation needed. The changes can be tracked via PR https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/pull/833

**Comment by scanum** [comment]
@jdotto02 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
