### ISSUE TITLE
Content update

### ISSUE THREAD

**Issue by nisinghMS** [MicrosoftDocs/OfficeDocs-o365seccomp#479]
Customer has raised some questions regarding already available Microsoft documentation on Partially-Indexed items. 

“As previously explained, the partially indexed items in the content locations that are searched are automatically included with the estimated search results. You have the option to include these partially indexed items when you export search results or prepare the search results for Advanced eDiscovery. To include partially indexed items when you're exporting search results or preparing them for Advanced eDiscovery, select one of the options to include items that have an unrecognized format, are encrypted, or weren't indexed for other reasons.”

•	When you run a content search, the total number and size of partially indexed items (returned by the search query) are displayed in search statistics in the details pane, as labeled as “unindexed items".

•	When you export search results and include partially indexed items, partially indexed Exchange items are exported to a separate PST file for each mailbox in which they are located, or as individual messages if you select the option to download Exchange items as messages.

https://docs.microsoft.com/en-us/office365/securitycompliance/partially-indexed-items-in-content-search#partially-indexed-items-included-in-the-search-results 

The highlighted/bold lines appear to contradict our findings, as well as the matrix we have provided. Customer wants us to address these discrepancies.

Is it possible to update the documentation accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f583844-0cbb-c87e-a096-ebf59ae57e11
* Version Independent ID: e707abbe-ff3b-6625-8284-b55c104c22d3
* Content: [Partially indexed items in Content Search in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/partially-indexed-items-in-content-search#feedback)
* Content Source: [SecurityCompliance/partially-indexed-items-in-content-search.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/partially-indexed-items-in-content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@nisinghMS Please update the topic directly by clicking Edit and then submit a pull request.
