### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by richardb52** [MicrosoftDocs/OfficeDocs-o365seccomp#480]
Does the Disposition Reviewer user only see the disposition for items they were notified about, or will they see items awaiting disposition for all content across the tenant? 
I'm trying to understand if its possible to segregate disposition review duties across departments for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d6bbdc-15c0-1f90-85c3-eb950d3a4837
* Version Independent ID: f4810537-30d6-0451-f9fa-62da1af72f2b
* Content: [Overview of disposition reviews](https://docs.microsoft.com/en-us/office365/securitycompliance/disposition-reviews)
* Content Source: [SecurityCompliance/disposition-reviews.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
Every reviewer sees all items awaiting disposition. But in the disposition view, items are aggregated by retention label, so you could possibly assign different labels to different reviewers.
