### ISSUE TITLE
Searching for Special characters

### ISSUE THREAD

**Issue by junterpfe** [MicrosoftDocs/OfficeDocs-o365seccomp#482]
I have recently been asked by a customer if there is a way to perform searches for the following special characters
! @ # % ^ & ; : ’ - = + _ / ? \
From what i have seen some break search, some act like they aren't there, it would be good to know which characters are not indexed so that we know they will not be available to search for.
for example searching for "Case #" breaks search (and eDiscovery) but that would help them find specific documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b84ade-fa24-3ca7-adb8-1a3398faa0a0
* Version Independent ID: b601bd4d-aa7e-63aa-0404-4cd84d817a9d
* Content: [Keyword queries and search conditions for Content Search](https://docs.microsoft.com/en-us/office365/securitycompliance/keyword-queries-and-search-conditions)
* Content Source: [SecurityCompliance/keyword-queries-and-search-conditions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
Hello @junterpfe. This is a good question, and we are looking into this. Stay tuned!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by markjjo** [comment]
@junterpfe As per your pull request, a note about this has added to the tips and tricks section in the following topic: https://docs.microsoft.com/en-us/office365/securitycompliance/keyword-queries-and-search-conditions#search-tips-and-tricks
