### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mramnet** [MicrosoftDocs/OfficeDocs-o365seccomp#483]
"Investigaiton"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2431ea89-86b7-5af7-a528-a9b3c31d21a9
* Version Independent ID: 8ade760a-f092-8d93-9f3d-485be3a1ecd7
* Content: [Office 365 Threat Investigation and Response](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-ti?redirectSourcePath=%252fen-us%252farticle%252foffice-365-threat-intelligence-32405da5-bee1-4a4b-82e5-8399df94c512)
* Content Source: [SecurityCompliance/office-365-ti.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-ti.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thanks @mramnet for catching this. There was a second typo as well. Both are fixed. Hope you have a good day!!
