### ISSUE TITLE
Retention label location

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#485]
Why are Retention labels in the Security Center? those are typically implemented to fulfill compliance requirements. I would expect to see them in the Compliance Center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f727c85-8525-613e-6b41-3278a6a10986
* Version Independent ID: 2c6f9456-d06a-7af8-d952-f6025563362b
* Content: [Get ready for Microsoft 365 security and compliance](https://docs.microsoft.com/en-us/office365/securitycompliance/microsoft-security-and-compliance)
* Content Source: [SecurityCompliance/microsoft-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/microsoft-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @DeanGross! Are you not seeing retention labels in the Microsoft 365 compliance center? That is where they're supposed to be, and we do mention retention labels in the Microsoft 365 compliance center section.

**Comment by DeanGross** [comment]
I do see them in the Compliance Center, I was not expecting to see them in the Security Center

**Comment by denisebmsft** [comment]
@DeanGross I did not know they were showing up in the security center, too. THANK YOU for bringing this up. I will look into it.
