### ISSUE TITLE
Alerts in 2 places

### ISSUE THREAD

**Issue by cvanelli-ducks** [MicrosoftDocs/OfficeDocs-o365seccomp#494]
alerts still show in office 365 security & compliance center&gt;Alerts  after resolving in cloud app security&gt;Alerts. Do I have to resolve them in both places? 
chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b700f46-ec5d-f0cb-d7cb-1d1032de75be
* Version Independent ID: 0d350765-4eed-8786-992b-cc1d330ceb17
* Content: [Review and take action on alerts in Office 365 Cloud App Security](https://docs.microsoft.com/en-us/office365/securitycompliance/review-office-365-cas-alerts#feedback)
* Content Source: [SecurityCompliance/review-office-365-cas-alerts.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/review-office-365-cas-alerts.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @cvanelli-ducks. Thank you for raising this question. I am looking into this.

**Comment by cvanelli-ducks** [comment]
Thank you! 

Chris

**Comment by denisebmsft** [comment]
@cvanelli-ducks the answer is, YES, you do need to update alerts in both places. Unfortunately, when you resolve a Cloud App Security alert in the Cloud App Security portal, it doesn't automatically reflect that in the Security & Compliance Center, and vice versa. I will make sure the content mentions this.

**Comment by cvanelli-ducks** [comment]
Thank you for following up on that for me. How do we get this turned into a feature request? We shouldn’t have to triage alerts twice. That just makes it more likely it won’t get done.

Thanks again for the help

Chris

**Comment by denisebmsft** [comment]
Hello again @cvanelli-ducks. I agree, and our product team is looking into this. I've updated the content, and changes should be live very soon. My teammate has also documented this, here: https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies#viewing-cloud-app-security-alerts 

I'm going to close this issue for now, but please reach out if you have further questions.

Thanks again!!
