### ISSUE TITLE
Outlook 2019

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-o365seccomp#495]
It is a lot of time from Outlook 2013 to Outlook 2019 in Office 365 ProPlus. Does something changed in support of DLP Policy Tips there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12efdace-f4c6-fbc5-47f5-d945b2479de1
* Version Independent ID: f792284f-6b6f-f75c-60ec-7848c89c9bf8
* Content: [Send email notifications and show policy tips for DLP policies](https://docs.microsoft.com/en-us/office365/securitycompliance/use-notifications-and-policy-tips)
* Content Source: [SecurityCompliance/use-notifications-and-policy-tips.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@Kazzan, good point. Thank you for catching this. I'm working on several content updates for DLP, and will make sure to address this as well.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by denisebmsft** [comment]
@Kazzan, thank you again for the feedback. And @scanum thank you for your help. The article has been updated with more current information, so I am closing this issue at this time. Please let us know if there are any other questions.
