### ISSUE TITLE
Once removed, will it return? 

### ISSUE THREAD

**Issue by MrOCanada** [MicrosoftDocs/OfficeDocs-o365seccomp#496]
I have a user who is being added to the restricted Users list.  It is a false positive.  If I remove the user will it be added back to the Restricted Users List if the user's actions remains the same?  Or once you remove the name it will not come back on the list?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baecd02e-eaff-0822-1cf2-dc7f02e4a218
* Version Independent ID: f97b946a-3306-6cfa-d26a-90e425d5789b
* Content: [Removing a user from the restricted users portal after sending spam email](https://docs.microsoft.com/en-ca/office365/securitycompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email#feedback)
* Content Source: [SecurityCompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/removing-a-user-domain-or-ip-address-from-a-block-list-after-sending-spam-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by robmazz** [comment]
@MrOCanada - thanks for the feedback, I'll get this over to the Enterprise content team for clarification.

**Comment by CxGD1Qrb** [comment]
We have the same situation at a large organisation. currently we are not confident that the user will not get blocked again in the near future.

**Comment by MrOCanada** [comment]
I just had another false positive.  Unblocked as well but not sure if this will impact the user again.

**Comment by MrOCanada** [comment]
Different user I meant, sorry.

**Comment by Dan-Newton** [comment]
Yes, users can be restricted again even if they have been removed from the restricted users list. We have seen this a number of times with mailboxes being identified as a false positive, that are subsequently repeatedly restricted again and again. There needs to be a better mechanism in place for dealing with this scenario otherwise you end up with genuine use cases being repeatedly restricted causing numerous delivery failures.

**Comment by MrOCanada** [comment]
Thanks for the information.  We rolled out the Outbound Spam by adding users to a group and expanding the membership until all users were members, excluding some service mailboxes \ automation mailboxes. 
I suppose I could remove the false positive user from the group but that's not a perfect solution obviously.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by DJREIT** [comment]
I am experiencing a similar issue on a shared mailbox. We use it as an autoresponder for incoming enquirers. It sends out maybe 10 emails per hour. But it got blocked by our Office365. I have already unblocked it a number of times even created a Mail Flow rule for thet mailbox to be Bypassed in SPAM filtering. Still it gets blocked. 

What else can I do?

**Comment by davejonnes** [comment]
Nothing you can do, you cannot divert messages from being checked by spam filtering even with a rule. O365 is not a good tool for bulk emailing, since it is a "shared service" with multiple other tenants using this service.

**Comment by scanum** [comment]
@MrOCanada thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jacobyoby** [comment]
Why was this closed? I am getting false positives also and there's little/no information of correcting this or whitelisting users.

**Comment by MSFTTracyP** [comment]
@jacobyoby, have you gone to Support with your issue in an effort to find out what the root cause is?

**Comment by MSFTTracyP** [comment]
@jacobyoby I'm not able to find a means of whitelisting a user addy like this during an outbound analysis. I would strongly suggest that you investigate this further with Support (https://docs.microsoft.com/office365/admin/contact-support-for-business-products or https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75), and, please, feel free to summarize their answer (or ask for a summary of the answer to be written up) which you can post here. It very well could help other people experiencing this!

**Comment by MSFTTracyP** [comment]
@Jacobyoby - If this thread closes, please reopen if you have to for an ans to this problem from Support. Also, thanks for checking back on this thread!
