### ISSUE TITLE
Actions - 'Block Sender' not just 'Block'

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/OfficeDocs-o365seccomp#497]
The Actions Column in the Enhanced ESNs released this week is 'Block Sender' not just 'Block'
Update to: Block Sender if you want Office 365 to add the sender to your blocked senders list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ff95c3-b69f-ae49-03ab-994c6fb97f3c
* Version Independent ID: 788c6b03-ce4a-73e3-0e1a-07a7c5fa127d
* Content: [Configure end-user spam notifications in EOP](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-end-user-spam-notifications-in-eop)
* Content Source: [SecurityCompliance/configure-end-user-spam-notifications-in-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-end-user-spam-notifications-in-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by robmazz** [comment]
@DavidTaig - thanks for the feedback, I'll get this over to the Enterprise content team for review.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@DavidTaig Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@OFFICEDOCSBOT CLOSE

**Comment by scanum** [comment]
@officedocsbot close
