### ISSUE TITLE
Actions - 'Block Sender' not just 'Block'

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/OfficeDocs-o365seccomp#498]
The Actions Column in the Enhanced ESNs released this week is 'Block Sender' not just 'Block'
Update to: Block Sender if you want Office 365 to add the sender to your blocked senders list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6abf8b-ab18-1185-f53d-9c6aef9e3c3c
* Version Independent ID: cf94f179-0ce3-fe16-f903-a68cdbb7cf65
* Content: [Use user spam notifications to release and report quarantined messages in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-spam-notifications-to-release-and-report-quarantined-messages)
* Content Source: [SecurityCompliance/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by robmazz** [comment]
@DavidTaig - thanks for the feedback, I'll get this over to the Enterprise content team for review.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by MSFTTracyP** [comment]
Updating.

**Comment by MSFTTracyP** [comment]
Thanks for this feedback! I'll close out this request now.
