### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by zmottie** [MicrosoftDocs/OfficeDocs-o365seccomp#503]
talks about the legacy version of OME.

"For example, you can't use it to stop a recipient from forwarding"

needs to be updated as this chart is very useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6a3d683-95ba-2f2b-251f-fe9f8ae75180
* Version Independent ID: 16d2230a-cd21-856d-c153-3b985c2e0ee9
* Content: [Email encryption in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/email-encryption#feedback)
* Content Source: [SecurityCompliance/email-encryption.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/email-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @zmottie and thank you for the feedback. We are looking into this, and we will post an update here soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@zmottie thank you for reaching out and helping improve MS Docs.  Please let me know if the issue has been solved in the interim, or if not, if you have any suggestions to improve the article.

**Comment by scanum** [comment]
@zmottie  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
