### ISSUE TITLE
I am unable to block users email if he any user share the credit card information with external domain.

### ISSUE THREAD

**Issue by pkvk14** [MicrosoftDocs/OfficeDocs-o365seccomp#505]
Hi ,

i have create one DLP rule to if any one want to share credit card information with outside domain then it must be blocked and admin get the notification. i have log a case with support team and he said it is not possible. Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd170f21-e0d6-4bd0-ee70-df9fc165f9fe
* Version Independent ID: 31c72b93-a444-90ad-508e-c43fa522f8fc
* Content: [Create, test, and tune a DLP policy](https://docs.microsoft.com/en-us/office365/securitycompliance/create-test-tune-dlp-policy#feedback)
* Content Source: [SecurityCompliance/create-test-tune-dlp-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @pkvk14. Sorry you are having difficulty with this. Just to clarify the issue, are you saying that you have created a DLP rule to prevent people from sharing credit card information outside your domain, and that it's not working? Is the issue that the rule is not working, or that what you want to do is not possible? I just want to make sure I understand the issue.

I'm looking into this issue and will follow up here soon. Opening a case with the support team is your best course of action here; however, I will make sure the documentation is correct.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@pkvk14  - thank you for submitting feedback.

As @denisebmsft  mentioned, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by pkvk14** [comment]
Hi Support,

This case is not close because engineer not provide any solution.

Thanks & Regard
Pradeep Misha
+919717139117

________________________________

**Comment by pkvk14** [comment]
Hi Support,

Case in not close.

Thanks & Regard
Pradeep Misha
+919717139117

________________________________
