### ISSUE TITLE
Deleting mail

### ISSUE THREAD

**Issue by anthonyofume** [MicrosoftDocs/OfficeDocs-o365seccomp#506]
Please i want to confirm.
Will this feature allow a domain admin to delete message that was sent to users from a different person outside the domain? 
For example: a hacker send a phishing mail to some users in a domain.. can the admin of that domain delete the phishing mail using this product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00591b3a-0e82-b0e1-fa3b-350c689eefee
* Version Independent ID: 397f05c8-7dc6-5935-f973-5146fc647808
* Content: [Find and investigate malicious email that was delivered (Office 365 Threat investigation and response](https://docs.microsoft.com/en-us/office365/securitycompliance/investigate-malicious-email-that-was-delivered#feedback)
* Content Source: [SecurityCompliance/investigate-malicious-email-that-was-delivered.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/investigate-malicious-email-that-was-delivered.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @anthonyofume. Thank you for your question. Yes, this feature is designed to work that way. Assuming you have the necessary licenses and permissions, and policies are defined, you can use Threat Explorer to find and delete phishing email that was sent (and delivered) to users.
