### ISSUE TITLE
Apply to free shared mailboxes?

### ISSUE THREAD

**Issue by TymWongPSNinja** [MicrosoftDocs/OfficeDocs-o365seccomp#508]
Does the ability to ensure data is retained for a certain period of time, i.e. cannot be permanently deleted apply to free Shared mailboxes in Exchange Online or does this require the shared mailbox to have an Exchange Online P2 license applied?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-gb/office365/securitycompliance/retention-policies?redirectSourcePath=%252farticle%252f5e377752-700d-4870-9b6d-12bfc12d2423)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
According to the licensing info here -

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

"Retention policies applied to mailboxes require Office 365 Enterprise E3 or E5."
