### ISSUE TITLE
Message Count limitations

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/OfficeDocs-o365seccomp#509]
It would be helpful to know if there is a limitation around the amount of messages that can be returned. It appears to be 50k. It's also interesting to note that in the console, when running a very large query, I can see the message count stops at 50k, but if I look at the same report with the Get-HistoricalSearch cmdlet, I see a message count of over 240k. It's a discrepancy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89002086-f4a5-145f-1a65-b47566eecb1f
* Version Independent ID: a36a7664-1de1-c4c9-9caf-2caadbf1d138
* Content: [Message trace in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/message-trace-scc)
* Content Source: [SecurityCompliance/message-trace-scc.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/message-trace-scc.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@terrogin Thank you for reaching out and helping improve MS Docs.  Just for clarification are you suggesting adding a note along these lines: "The limit for the amount of messages that can be returned is 50 000. In the console, when running a very large query, the Get-HistoricalSearch cmdlet report message count exceeds 240 000."?

**Comment by TokyoScarab** [comment]
Hi @terrogin thank you for posting this issue!  I will be examining your question and seeing how it can be used to update the documentation.

**Comment by scanum** [comment]
@terrogin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by terrogin** [comment]
Apologies but the new note is still inaccurate. What's really happening is that in the console, the message count will stop at 50k and the report will also only show 50k. However, the PowerShell cmdlet Get-HistoricalSearch cmdlet will show the actual message count. In my case it was 240,000+ but this count could be anything. 

My thoughts were that we could add a note calling out the 50k message limitation for the report and the console since those were missing from the article before. Then also call out that the cmdlets will show the true message count. 

When I was initially running my report and using this article as a reference, I was only interesting in knowing the message count, which was only obtainable through the cmdlet.

**Comment by scanum** [comment]
@officedocsbot reopen

**Comment by chrisda** [comment]
OK. Fixed again:

Only the first 50000 messages are displayed in the results. The [Get-HistoricalSearch](https://docs.microsoft.com/powershell/module/exchange/reporting/get-historicalsearch) cmdlet in Exchange Online PowerShell or Exchange Online Protection PowerShell returns all messages in the results.

Closing again.
