### ISSUE TITLE
 The Fast Track - section of this article should be changed - to Fast Track Audit of configuration process.  

### ISSUE THREAD

**Issue by Ramonin** [MicrosoftDocs/OfficeDocs-o365seccomp#51]
Fast Track will not setup BYOK/ what fast track is doing is auditing the setup to ensure that there is redundancy in the Azure Subscriptions and policies. This is misleading to customers and should be correctly stated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e55fe21-a628-4ad9-b250-82fc24714fce
* Version Independent ID: ce31506e-5a7b-47dc-6ea7-87633e07a379
* Content: [Controlling your data in Office 365 using Customer Key](https://docs.microsoft.com/en-us/office365/securitycompliance/controlling-your-data-using-customer-key?redirectSourcePath=%252fen-us%252farticle%252fControlling-your-data-in-Office-365-using-Customer-Key-f2cd475a-e592-46cf-80a3-1bfb0fa17697)
* Content Source: [SecurityCompliance/controlling-your-data-using-customer-key.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/controlling-your-data-using-customer-key.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Thank you for the feedback, @Ramonin. We will look into this.

**Comment by AndreaBarr** [comment]
@Ramonin Thank you for this feedback

I will get this to the o365seccomp team for investigation and updating. 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by Ramonin** [comment]
Great thank you

Ramon Infante
Principal Program Manager Office 365 CXP
Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>




[http://mysignature.azureedge.net/files/L_Microsoft.png]
[CHANGE  PRACTITIONER  Prosci]

**Comment by AndreaBarr** [comment]
Closing this issue until we have an update for it.
