### ISSUE TITLE
Japanese title for this article is not appropriate.

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/OfficeDocs-o365seccomp#511]
Japanese title for this article is not appropriate.

Current(Current Japanese title does not make sense to us...)
Office 2010 での無制限アーカイブの概要 (機械翻訳) 365

Expected
Office365 無制限アーカイブの概要

**Comment by denisebmsft** [comment]
Hello @AkikoTsukahara. Thank you for raising this issue. We are working on this.

**Comment by MollyMalone** [comment]
@OfficeGlobal please fix this issue.
https://docs.microsoft.com/ja-jp/office365/securitycompliance/unlimited-archiving 

According to Hideatsu the fix should be:
Office365 の無制限アーカイブの概要

The string in the “Expected” section above works but with “の” is better.

**Comment by OfficeGlobal** [comment]
@MollyMalone We're working on a fix (Bug 3251607)

**Comment by OfficeGlobal** [comment]
@MollyMalone , @AkikoTsukahara The article has been HumanTranslated and published live. The issue is fixed

**Comment by scanum** [comment]
@AkikoTsukahara  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
