### ISSUE TITLE
Add Get-UrlTrace reference to "Additional Reports to view" section

### ISSUE THREAD

**Issue by laughingman42** [MicrosoftDocs/OfficeDocs-o365seccomp#512]
Get-UrlTrace is a useful powershell report that should get mentioned here as it relates to detailed report for ATP SafeLinks. It's also not referenced in other places making it a little bit obscure. 
https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/get-urltrace?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1416056e-b387-df7e-1999-093815262aab
* Version Independent ID: c45f1a99-3dd1-3209-27e5-59c028e31fc3
* Content: [View reports for Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/view-reports-for-atp#feedback)
* Content Source: [SecurityCompliance/view-reports-for-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/view-reports-for-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @laughingman42 and thank you for the feedback. I will definitely update the content to include this. Thank you for pointing this out.

**Comment by denisebmsft** [comment]
Hello @laughingman42. I wanted to let you know I added the URL trace report to the article. Thank you so much for your helpful feedback!
