### ISSUE TITLE
Tested a Statement

### ISSUE THREAD

**Issue by bellomu** [MicrosoftDocs/OfficeDocs-o365seccomp#515]
We tested this by adding a member in AAD but it did not show up in SCC.  Did we understand the statement below correctly?  Maybe it needs further clarification. 

If you edit this role group in the Security & Compliance Center, those changes apply only to the Security & Compliance Center and not any other services, whereas changes made in the Azure Active Directory admin center affect all services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center?redirectSourcePath=%252fen-us%252farticle%252fPermissions-in-the-Office-365-Security-Compliance-Center-d10608af-7934-490a-818e-e68f17d0e9c1#feedback)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
That info applies to the new AAD-based roles that will appear in the Microsoft 365 security center and Microsoft 365 compliance centers, and those features are still being rolled out.

So the para you reference is a bit early, wait until the new Microsoft 365 centers are available.
