### ISSUE TITLE
Dimmed Options under Quarantined Message

### ISSUE THREAD

**Issue by anelshaer** [MicrosoftDocs/OfficeDocs-o365seccomp#518]
i have a Full Access Permissions and still cant download an email or release. All the options are dimmed for me.
![Screenshot 2019-03-28 at 16 06 42](https://user-images.githubusercontent.com/4087461/55168756-b4ec8880-5173-11e9-8871-efcc233c54b2.png)

**Comment by denisebmsft** [comment]
Hello @anelshaer. You might want to open a case with support for this. Are you seeing this in the Security & Compliance Center?

**Comment by anelshaer** [comment]
yes in 
> Office 365 Security & Compliance

**Comment by denisebmsft** [comment]
@anelshaer, did you file a support ticket on this? We are not able to reproduce what you are seeing, and our technical support staff should be able to help you with this.

**Comment by anelshaer** [comment]
i couldnot open a ticket because idont have the full admin right. but the permissions i have is set on a group of users all of them able to see these options but not my account. 
is there other way than admin to open ticket!
