### ISSUE TITLE
Incorrect Scenario

### ISSUE THREAD

**Issue by SweetmanD** [MicrosoftDocs/OfficeDocs-o365seccomp#519]
There are 31 days in July.

"You can configure the retention hold so that it's turned off on some date in the future. You do this by running the Set-Mailbox -EndDateForRetentionHold date command. For example, assuming that today's date is July 1, 2016 and you want the retention hold turned off in 30 days, you would run the following command: Set-Mailbox -EndDateForRetentionHold 8/1/2016. In this scenario, you would leave the RetentionHoldEnabled property set to True. For more information, see Set-Mailbox."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a65de3-b878-b20a-3823-11a9dbc3e37c
* Version Independent ID: 28499237-e103-b204-12b2-11d72f685370
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files#step-6-filter-data-and-start-the-pst-import-job)
* Content Source: [SecurityCompliance/use-network-upload-to-import-pst-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@SweetmanD Thanks for pointing this out
