### ISSUE TITLE
"when it was labeled" doesn't apply to Exchange Online

### ISSUE THREAD

**Issue by rodsorbara** [MicrosoftDocs/OfficeDocs-o365seccomp#520]
This article is missing a mention that the option "when it was labeled" doesn't apply to Exchange. Historically, email retention policies have always been based on when the email was sent or received and according to my lab tests results, this is also true (for Exchange items) even though selecting this option lead us to think otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
Hello @rodsorbara, and thank you for the feedback. We are looking into this, and a response will be posted here soon.

**Comment by lindspea** [comment]
@rodsorbara Thank you for reaching out and helping improve MS Docs.  It looks like this issue has be solved in the interim.  Please can you confirm, or advise if you have any further suggestions to improve the article.

**Comment by scanum** [comment]
@rodsorbara  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
