### ISSUE TITLE
Need ability to turn this off for users

### ISSUE THREAD

**Issue by alanraylloyd** [MicrosoftDocs/OfficeDocs-o365seccomp#521]
Is there some way to turn this off so that my users cannot release their own messages? Ideally, I'd like users to have the ability to *see* what's in quarantine, and even request that it be released, but I'd still like to approve things before they're released.

Barring that option, there should at least be a way to turn off end-user management of quarantine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e487b445-a3ef-ec1e-43b6-bd9f7afa3f62
* Version Independent ID: 34d5e5a4-4bdc-47bd-3638-bcf80ee935d6
* Content: [Find and release quarantined messages as a user in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/find-and-release-quarantined-messages-as-a-user#feedback)
* Content Source: [SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @alanraylloyd, and thank you for the feedback. We are looking into this from a documentation perspective, and we will follow up on this soon. In the meantime, you do have a way to give this good feedback to our product team here: [https://office365.uservoice.com/forums/289138-office-365-security-compliance](https://office365.uservoice.com/forums/289138-office-365-security-compliance). Please do tell them, and we'll share your feedback internally as well.

**Comment by alanraylloyd** [comment]
> 
> 
> Hello @alanraylloyd, and thank you for the feedback. We are looking into this from a documentation perspective, and we will follow up on this soon. In the meantime, you do have a way to give this good feedback to our product team here: https://office365.uservoice.com/forums/289138-office-365-security-compliance. Please do tell them, and we'll share your feedback internally as well.

Thanks @denisebmsft There is a uservoice request for the exact thing I'm talking about... it's been open for over three years with no response from MSFT: https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/12556947-quarantine-notifications-but-no-release-functiona

**Comment by denisebmsft** [comment]
@alanraylloyd - wow. I'll mention that, too, when we share your feedback internally. Thank you!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@alanraylloyd thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
