### ISSUE TITLE
Ambiguous FIPS 140-2 Certified Components

### ISSUE THREAD

**Issue by pfdeaver** [MicrosoftDocs/OfficeDocs-o365seccomp#522]
The link to NIST is bad.  Search of NIST for Microsoft (vendor) and Azure (keyword) returns 4 certificates related to WS2012 R2, none related to storage, not "under test", not "in process".  I presume "cng.sys" as with BitLocker, but none of the "cng.sys" certificates call out Azure as a tested platform.

My auditor requires Microsoft assertion and certificate number to assert compliance if Azure is to be used.  Please point me where to look.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02bbaaca-a299-8772-1fac-1d865f8cc53e
* Version Independent ID: 24f0699c-77c2-c985-e8d8-65f73f857152
* Content: [Encryption in the Microsoft Cloud](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-encryption-in-the-microsoft-cloud-overview#feedback)
* Content Source: [SecurityCompliance/office-365-encryption-in-the-microsoft-cloud-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-encryption-in-the-microsoft-cloud-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @pfdeaver. Thank you so much for reaching out to us about this. We are looking into this issue, and an update will be posted here soon.

**Comment by pfdeaver** [comment]
The FBI allows 14 days to respond to compliance queries.  Pardon me if I push.

The Azure Storage Service for Encryption at Rest doc (https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption) FAQ states: Storage Service Encryption is FIPS 140-2 compliant. For more information about the cryptographic modules underlying Storage Service Encryption, see Cryptography API: Next Generation.

This is OK for now.  Please respond with new/updated Trust Center links as soon as they become available.  DOC is much better than a FAQ responses.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by pfdeaver** [comment]
I was able to document FIPS certificate numbers for Storage via an Azure support request.  The response related to certificates not used by a current Windows OS.  I requested that these are documented with Microsoft's compliance Web pages.
I am awaiting a reply to FIPS certificate numbers for HTTPS via a separate Azure support request.

**Comment by scanum** [comment]
@pfdeaver Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
