### ISSUE TITLE
Searching Audit Log

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#524]
What happened to the Audit Log search functionality that was in the original Security and Compliance Center? I don't see it in the new Compliance Center or in the new Security Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87cb65d2-5233-61bb-dfd4-f9b0dc3ab41c
* Version Independent ID: 970ee1f2-7ec5-6ad6-15a8-b03f565e1be6
* Content: [Welcome to your all-new new Microsoft 365 compliance center](https://docs.microsoft.com/en-us/office365/securitycompliance/microsoft-365-compliance-center)
* Content Source: [SecurityCompliance/microsoft-365-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/microsoft-365-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @DeanGross! Thanks for this question. I'm working on this, and I'll follow up as soon as possible.

**Comment by denisebmsft** [comment]
Hi @DeanGross. Not all compliance features are hooked up to the new Microsoft 365 compliance center just yet. More features and solutions are being added over the coming months. In the meantime, if there is something you can't find, such as audit log search, you can use the existing Office 365 Security & Compliance Center (https://protection.office.com). I've added an FAQ about this to the article. Thank you so much for raising this question, and for helping me improve our documentation.
