### ISSUE TITLE
Malware should "Quarantine" instead of "Deleted"

### ISSUE THREAD

**Issue by masamig** [MicrosoftDocs/OfficeDocs-o365seccomp#529]
The image "How EOP works" shows [Anti-Malware] ---> [Deleted] (trash bin), but currently malware goes Quarantine. Quarantine is the only option for Anti-Malware. This image mislead users there might be deletion option for malware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f54a0b9a-a1a6-3f33-46f7-8f21989189fb
* Version Independent ID: 36ef546f-93c7-68e0-2330-07a658a17150
* Content: [Exchange Online Protection overview](https://docs.microsoft.com/en-us/office365/securitycompliance/eop/exchange-online-protection-overview)
* Content Source: [SecurityCompliance/eop/exchange-online-protection-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/exchange-online-protection-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @masamig and thank you so much for the feedback. We are looking into this, and an update will be posted here soon.

**Comment by andypunt** [comment]
Yes, this needs to be updated as Malware goes to Quarantine now. Although, I don't have any good graphics updating tools, so I will not be able to do this update of the .PNG.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@masamig Thank you for reaching out and helping improve MS Docs.  Please confirm if the issue has been resolved in the interim.  It seems to be reading correctly now.

**Comment by FrankCarius** [comment]
And "connection Filtrer" will also not "delete" the message. It does a "reject", which is a important difference. "Delete" means nor the sender or receiver gets an information. Rejecting the Message with a Message like "550 5.7.1 Service unavailable, Client host [87.150.155.4] blocked using Spamhaus."  tells the sending MTA to generate a NDR to the sender, which is fine.

**Comment by lindspea** [comment]
@denisebmsft any update yet?

**Comment by lindspea** [comment]
Thanks @FrankCarius we are still investigating.

**Comment by MSFTTracyP** [comment]
Updated!
