### ISSUE TITLE
Email Quarantine and Mail Flow: where?

### ISSUE THREAD

**Issue by rcooke-cc** [MicrosoftDocs/OfficeDocs-o365seccomp#530]
How does one navigate to email quarantine and mail flow from the new admin interfaces?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f727c85-8525-613e-6b41-3278a6a10986
* Version Independent ID: 2c6f9456-d06a-7af8-d952-f6025563362b
* Content: [The new Microsoft 365 security center and Microsoft 365 compliance center are now generally available](https://docs.microsoft.com/en-us/office365/securitycompliance/microsoft-security-and-compliance)
* Content Source: [SecurityCompliance/microsoft-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/microsoft-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @rcooke-cc and thank you for the feedback. Try using [https://protection.office.com](https://protection.office.com) for the features you are not seeing in the new Microsoft 365 security center and Microsoft 365 compliance center. Our product team is still adding features/functionality to the two new centers. In the meantime, the existing features/functionality are still available in the Office 365 Security & Compliance Center ([https://protection.office.com](https://protection.office.com)). I hope this helps! And I will be updating this article soon!
