### ISSUE TITLE
Mailbox not getting automatically deleted after we remove the hold.

### ISSUE THREAD

**Issue by sdesai79** [MicrosoftDocs/OfficeDocs-o365seccomp#531]
I work for Microsoft Support (CSS) as an SEE. We have known issue where if customer remove the hold after 30 days from mailbox which is part of SoftDeletedMailbox container, mailbox will be not removed automatically. Customer admin need to remove it manually using "Remove-Mailbox -PermanentlyDelete".
I recommend we add a Note in the article (under more information section)

Reach out to me directly if you need official link where product group is tracking the behavior - sdesai@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4055cac1-948f-ee07-fb2f-49cd4fe6e5b5
* Version Independent ID: 7bb78099-50a0-f765-5510-9bffa2b508f6
* Content: [Delete an inactive mailbox in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/delete-an-inactive-mailbox#feedback)
* Content Source: [SecurityCompliance/delete-an-inactive-mailbox.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/delete-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@sdesai79 Because you are internal Microsoft, let's take this offline, and then we will update the article accordingly.
