### ISSUE TITLE
DLP Policy - Client Error

### ISSUE THREAD

**Issue by sudeepku** [MicrosoftDocs/OfficeDocs-o365seccomp#532]
Question reported by @yoer1 at https://github.com/MicrosoftDocs/feedback/issues/1316 
--------------------------------------
Can anyone please help me with this kind of error in DLP.. I can't edit the policy settings and I also tried to do this in 3 different tenant. Same result, is this a bug? Please see error below. Thank You in advance.

1. Go to 'https://protection.office.com/?rfr=AdminCenter#/datalossprevention'
2. Click on 'Exisiting DLP Policy'
3. Click on 'Edit'
4. Once editing is done, please see error below

Client Error
Your request couldn't be completed. Please try again, and if the problem persists, contact your administrator.

Request: /api/policy?policyType=Dlp
Status code: 500
Exception message: {"Message":"The DlpComplianceManagementRule type entity does not have the following type command: Update.\r\nParameter name: entityMetadata","DiagnosticContext":"{Version:16.00.2927.001,Environment:EASPROD,DeploymentId:3c31d0adf8964fe5bc51a71de288012e,InstanceId:WebRole_IN_1,SID:63636797-82c2-423f-aa42-fff6e66f129c,CID:99dc3b0e-764a-40bd-9823-ab0da631dcd1}","Time":"2019-03-22T02:42:08.1987091Z","ExceptionType":"System.ArgumentException"}
Diagnostic information: **{Version:16.00.2927.001,Environment:EASPROD,DeploymentId:3c31d0adf8964fe5bc51a71de288012e,InstanceId:WebRole_IN_0,SID:63636797-82c2-423f-aa42-fff6e66f129c,CID:1080593c-9894-4202-b6f9-d11fd0b2abc8}
Time: 2019-03-22T02:42:06.618Z
![Error Msg](https://user-images.githubusercontent.com/48461407/54797523-70eb1680-4c8f-11e9-8f04-97a51d0e92c9.JPG)
![Error Msg](https://user-images.githubusercontent.com/48461407/54797533-7a747e80-4c8f-11e9-81f2-3fb39fa1de02.JPG)

**Comment by denisebmsft** [comment]
Hello @sudeepku, I am looking into this on my side, but I also wanted to recommend that you open a ticket with Technical Support.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@sudeepku  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
