### ISSUE TITLE
Alternate/more reliable way to get DKIM Selector CNAME

### ISSUE THREAD

**Issue by mhendric** [MicrosoftDocs/OfficeDocs-o365seccomp#533]
Rather than having people construct their own Selector CNAME's which is error prone, it may be easier to just get this information from Get-DkimSigningConfig. I.e.

New-DkimSigningConfig -DomainName domain -Enabled $false
Get-DkimSigningConfig -DomainName domain | fl Selector1CNAME, Selector2CNAME

…Create CNAMEs referenced in Get-DkimSigningConfig output...

Set-DkimSigningConfig -DomainName domain -Enabled $true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM for email in your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dkim-to-validate-outbound-email#feedback)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @mhendric, and thank you for the feedback. We are looking into this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@mhendric Thank you for reaching out and helping improve MS Docs.  Please confirm where you suggest adding/changing this command in the article?

**Comment by mhendric** [comment]
HI @lindspea, I suggest putting it in the 'Publish two CNAME records for your custom domain in DNS' section. Currently that section shows how you're supposed to construct the CNAME record on your own, but the instructions don't always work, especially for domains with non-alpha characters in them. Creating the DkimSigningConfig, and then getting the CNAME records directly from Get-DkimSigningConfig as O365 expects them, is a far more reliable way to get the values.

**Comment by pbuffolino** [comment]
Using this method takes the guesswork out of it.  Well done!

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@mhendric @officedocsbot close
