### ISSUE TITLE
Inconsistency between this article and the SCC Bulk compliance policy

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/OfficeDocs-o365seccomp#534]
The "Treat Bulk Email as Spam" option in the Security and Compliance policy directly contradicts this article.

From the S&CC, it shows that the default BCL is 7. If you set to 9, it will allow more bulk email. This article suggests that if you have it set to 9, less bulk email will get delivered.

This suggests that either this article is incorrect, or the BCL config in SCC is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e237cb-493d-fd86-b9cd-8a1cfa80b896
* Version Independent ID: 74ebdf34-8da1-e241-3b06-4c47adb55474
* Content: [Bulk Complaint Level values](https://docs.microsoft.com/en-us/office365/SecurityCompliance/bulk-complaint-level-values)
* Content Source: [SecurityCompliance/bulk-complaint-level-values.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/bulk-complaint-level-values.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @vboyev-MSFT and thank you for the feedback. We are looking into this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@vboyev-MSFT Thank you for reaching out and helping improve MS Docs. It seems the article has been fixed in the interim.  Please can you check and confirm, or advise if you have any further suggestions to improve the article.

**Comment by scanum** [comment]
@vboyev-MSFT  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by MSFTTracyP** [comment]
The documentation has been updated. Thank you.

**Comment by MSFTTracyP** [comment]
Clarified in the article. Closing. Thank you to all!
