### ISSUE TITLE
Ability to remove user actions

### ISSUE THREAD

**Issue by tmaguire** [MicrosoftDocs/OfficeDocs-o365seccomp#537]
Is there a plan to remove the option for allowing users to release emails to their mailbox and instead notify administrators?

Concerned about allowing users to just release any email they feel like without an administrator double checking it to make sure that it's not a phishing attempt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8252ddfb-8d51-29d8-0e8a-01c70c07db45
* Version Independent ID: ddc36cea-faf5-78b0-5542-e4ef41692083
* Content: [Configure end-user spam notifications in Exchange Online](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-end-user-spam-notifications-in-exchange-online#feedback)
* Content Source: [SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-end-user-spam-notifications-in-exchange-online.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @tmaguire and thank you for the feedback. We are looking into this, and will be reaching out to our product team. Stay tuned for an update to be posted here.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by kking3106** [comment]
Also curious to see if there is an update on this @denisebmsft @scanum I would like to turn on notifications but would like to restrict the access of releasing any email they want

**Comment by scanum** [comment]
@tmaguire @kking3106 @jmrita Since this is not related to the documentation and more to features of the products, I would recommend following up on that user voice that @jmrita suggested. Other than this, we really appreciate your feedback.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
