### ISSUE TITLE
Exact version of OME seems to be important, please be more precise?

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-o365seccomp#538]
Hi
We have issues with IRM/AIP/Encryption. I was told by Microsoft it depends which version of OME we are using. See actual message below. So I started looking for information about OME versions, and found this one. But this one did not refer to version numbers. Can you please provide specific version numbers so that "legacy" and "new" become defined.

From James Craddock AIP technical manager:
"The issue with 'Try again in 5 minutes' on Mobile devices is caused by the version of OME you have configured. Ensure you are ONLY running OME Version 2, not 1 or 1 and 2.. 
https://www.yammer.com/askipteam/threads/56146450137088
We have also seen issues when overly cautious users use s/mime as well as AIP, which means Exchange does get access to apply the wrapper."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efa2f7c1-8703-b46d-870f-8bf83e48888d
* Version Independent ID: 3f4219fa-e443-31a5-a767-5450438173ff
* Content: [Office 365 Message Encryption version comparison](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-version-comparison#feedback)
* Content Source: [SecurityCompliance/ome-version-comparison.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-version-comparison.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @blouwagie. Thank you so much for the feedback. We are looking into this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by KCCross** [comment]
I will definitely pass on the feedback about the versions to the folks that control branding. Right now, there are only two versions and they are the previous or legacy version of OME and the new OME capabilities. That's how I'm able to differentiate between them in the docs. I've requested more clarification from the brand team.

**Comment by scanum** [comment]
@blouwagie thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by blouwagie** [comment]
I have done the service tickets and fully understand a lot of the
differences between the versions.. is just hard for other readers to have
to second guess documentation because the version that is documented is not
well defined. I don't need it, just trying to help others. Next time.


Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)

http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call is needed)
