### ISSUE TITLE
Update guidance

### ISSUE THREAD

**Issue by modangsr2** [MicrosoftDocs/OfficeDocs-o365seccomp#541]
There was a more recent version of public guidance available on the Terry Zink blog on the topic: "How to securely add a sender to an allow list in Office 365". Can we make sure we update this content to align with it? (or give more up-to date recommendations if things are changed since 2015?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0785746b-cad9-9f3f-20f9-1fb3552abf6f
* Version Independent ID: e34bbfea-0bbe-4f21-e49a-2cee9d3860af
* Content: [Create organization-wide safe sender or blocked sender lists in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365#feedback)
* Content Source: [SecurityCompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
Hello @modangsr2, we are looking into this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@modangsr2, we're in the process of revamping the anti-spam/threat guidance, and this topic is part of that greater effort. I'm going to close this issue, but rest assured that it's being looked at in light of Terry's blog and the current threat landscape.

Thanks for the feedback.
