### ISSUE TITLE
Data Loss Prevention notifications

### ISSUE THREAD

**Issue by CarlosTabera** [MicrosoftDocs/OfficeDocs-o365seccomp#542]
As stated in the documentation on this page, when a Data Loss Prevention Policy is configured to send a notification email in SharePoint or OneDrive, this email notification will only be triggered with the new content and not with the already existing. 
I think that it can be a problem if you create a new Policy for a long stablished SharePoint enviroment. There is any chance to include the trigger for the already existing content?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12efdace-f4c6-fbc5-47f5-d945b2479de1
* Version Independent ID: f792284f-6b6f-f75c-60ec-7848c89c9bf8
* Content: [Send email notifications and show policy tips for DLP policies](https://docs.microsoft.com/en-us/office365/securitycompliance/use-notifications-and-policy-tips#feedback)
* Content Source: [SecurityCompliance/use-notifications-and-policy-tips.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@CarlosTabera thank you so much for the feedback. Good question! I will find out.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by denisebmsft** [comment]
Hello @CarlosTabera and @scanum. I have an answer to your question:

DLP policies apply to all documents that match the policy, whether those documents are new or existing. However, the email notification is only generated when new content matches an existing DLP policy. Existing content is protected, but will not generate a user notification via email. 

I will add this information to this article to make it more clear.

And thank you again for raising this question.

**Comment by denisebmsft** [comment]
@CarlosTabera and @scanum I am closing this issue now because I've updated the content. If you don't see the update yet, you will see it very soon. Thank you @CarlosTabera for the feedback.
