### ISSUE TITLE
Outdated? 

### ISSUE THREAD

**Issue by SPGabe** [MicrosoftDocs/OfficeDocs-o365seccomp#543]
Seems like some of these instructions are a little outdated considering the changes that were recently made. Also, can you call out specifically whether or not Global Administrators should automatically have access to the Audit Log Search? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#feedback)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@SPGabe Thanks for reaching out. What specifically is outdated? What recent changes are you referring to? We can add a bit about the fact that Office 365 global admins are added by default to the Organization Management role group in EXO, which gives them the necessary permissions to search the audit log, which is documented here: https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center#permissions-needed-to-use-features-in-the-security--compliance-center

**Comment by markjjo** [comment]
@SPGabe I went ahead and added info about global admins being added to OrgManagement in EXO.
https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#before-you-begin
