### ISSUE TITLE
The Backscatterer.org IP list link is broken

### ISSUE THREAD

**Issue by birop** [MicrosoftDocs/OfficeDocs-o365seccomp#546]
The link The Backscatterer.org IP list (https://blogs.msdn.com/b/tzink/archive/2012/08/22/the-backscatterer-org-ip-list.aspx) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8b18da-a962-85b2-97df-2492342c53aa
* Version Independent ID: e9245f31-a3bb-1875-f338-643f0b7193cd
* Content: [Backscatter messages and EOP](https://docs.microsoft.com/en-us/office365/securitycompliance/backscatter-messages-and-eop)
* Content Source: [SecurityCompliance/backscatter-messages-and-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/backscatter-messages-and-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@birop Thank you for reaching out.  I'll investigate further and revert soonest.

**Comment by scanum** [comment]
@birop Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
