### ISSUE TITLE
Searching by IP and header's tags

### ISSUE THREAD

**Issue by jm15502** [MicrosoftDocs/OfficeDocs-o365seccomp#547]
How to search emails by IP or by header tags like X-Source-IP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b84ade-fa24-3ca7-adb8-1a3398faa0a0
* Version Independent ID: b601bd4d-aa7e-63aa-0404-4cd84d817a9d
* Content: [Keyword queries and search conditions for Content Search](https://docs.microsoft.com/en-us/office365/securitycompliance/keyword-queries-and-search-conditions#feedback)
* Content Source: [SecurityCompliance/keyword-queries-and-search-conditions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jm15502 Unfortunately, neither of these is possible.
