### ISSUE TITLE
File Plan Descriptors

### ISSUE THREAD

**Issue by RobBath** [MicrosoftDocs/OfficeDocs-o365seccomp#548]
I know this page is already rather lengthy, but it probably needs to have some information about the new File plan descriptors added to it. I'd love to know precisely how File plan descriptors work with retention labels; how we can remove descriptors etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels#feedback)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@RobBath Thank you for reaching out and helping improve MS Docs.  I'll investigate further and revert soonest.

**Comment by scanum** [comment]
@RobBath Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
