### ISSUE TITLE
Cmdlet syntax invalid

### ISSUE THREAD

**Issue by eric-lavalley** [MicrosoftDocs/OfficeDocs-o365seccomp#549]
In several sections of this document the instructions say to use "Set-DlpSensitiveInformationTypeRulePackage -Identity "NameOfYourPackage". However, Identity is not a valid parameter for the Set-DlpSensitiveInformationTypeRulePackage cmdlet. When running this cmdlet with the Identity parameter you receive an error stating "A parameter cannot be found that matches parameter name 'Identity'". Dropping the Identity parameter works. This documentation should be updated to reflect the functionality of the cmdlet defined here: https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-dlp/set-dlpsensitiveinformationtyperulepackage?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78840565-da03-9f42-b333-892c30e751e8
* Version Independent ID: 366d5a9f-2ba9-1291-8676-2a6575ee28cd
* Content: [Create a custom sensitive information type in Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/office365/securitycompliance/create-a-custom-sensitive-information-type-in-scc-powershell#modify-a-custom-sensitive-information-type)
* Content Source: [SecurityCompliance/create-a-custom-sensitive-information-type-in-scc-powershell.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-a-custom-sensitive-information-type-in-scc-powershell.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by denisebmsft** [comment]
Hello @eric-lavalley and thank you so much for the feedback. I have updated this article accordingly. Thank you for helping us improve the documentation!
