### ISSUE TITLE
Clarification re: mailbox policies 

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-o365seccomp#550]
Please specify that individual mailbox policies (OWA/ActiveSync) override these settings (i.e. if -IRMEnabled is set to False within the respective OWA Mailbox policy or ActiveSync Mailbox policy, then these configurations would not apply).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0688888b-5379-009a-d325-49709fe8f4a8
* Version Independent ID: 2234c4fd-9423-8e63-7544-c2c8a654cf29
* Content: [Manage Office 365 Message Encryption](https://docs.microsoft.com/en-us/office365/securitycompliance/manage-office-365-message-encryption)
* Content Source: [SecurityCompliance/manage-office-365-message-encryption.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/manage-office-365-message-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@hudish. Thank you for the suggestion. I have added the suggested note to be approved. Your help is greatly appreciated.

**Comment by scanum** [comment]
@hudish Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
