### ISSUE TITLE
DLP Incorrect Statement?

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/OfficeDocs-o365seccomp#552]
"Data Loss Prevention (DLP) policies can only work with the metadata (including Office 365 labels) but not the contents of these files (such as credit card numbers within files)."

Isn't this statment incorrect, because Microsoft DLP and Microsoft Cloud App Security can inspect AIP protected files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 118d7f90-b599-baac-9c6e-51f35221cd64
* Version Independent ID: a525ac7f-7603-4050-02ad-5132e008e1aa
* Content: [Protect SharePoint Online files with Azure Information Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/protect-sharepoint-online-files-with-azure-information-protection)
* Content Source: [SecurityCompliance/protect-sharepoint-online-files-with-azure-information-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/protect-sharepoint-online-files-with-azure-information-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Mark7even Thank you for reaching out.  This statement is correct within the context of the entire paragraph:
"When Azure Information Protection encryption is applied to files stored in Office 365, the service cannot process the contents of these files. Co-authoring, eDiscovery, search, Delve, and other collaborative features do not work. Data Loss Prevention (DLP) policies can only work with the metadata (including Office 365 labels) but not the contents of these files (such as credit card numbers within files)."
At this time, DLP cannot process files encrypted with Azure Information Protection.

**Comment by scanum** [comment]
@Mark7even We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
