### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by oguzhanf** [MicrosoftDocs/OfficeDocs-o365seccomp#553]
Mail flow settings section, dead link - https://blogs.technet.microsoft.com/office365security/how-to-deal-with-ransomware/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 270b3972-f1bb-c979-e670-8b4195b8aa51
* Version Independent ID: 4a98a0bf-3f91-c895-28c0-04a24bc18041
* Content: [Configure your Office 365 tenant for increased security](https://docs.microsoft.com/en-us/office365/securitycompliance/tenant-wide-setup-for-increased-security)
* Content Source: [SecurityCompliance/tenant-wide-setup-for-increased-security.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/tenant-wide-setup-for-increased-security.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@oguzhanf Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
