### ISSUE TITLE
Video durations

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#554]
Please add info about the video length's so that we know what to expect and can figure out when to squeeze these into our schedules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c445a4a-62bc-3085-8b11-4edd8011b6ba
* Version Independent ID: 26eed08e-978d-9fa9-b080-ab81287cb4c4
* Content: [Chief Information Security Officer (CISO) Workshop](https://docs.microsoft.com/en-us/office365/securitycompliance/ciso-workshop?_lrsc=0439bab7-dd14-4221-a574-e3bbdb13d43f)
* Content Source: [SecurityCompliance/ciso-workshop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ciso-workshop.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by robmazz** [comment]
@DeanGross - thanks so much for the feedback, I've updated each of the video sections to show the video duration times. We've also updated the structure and organized the modules into separate topics today.
