### ISSUE TITLE
Custom RBAC role groups

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/OfficeDocs-o365seccomp#555]
Has the ability to create custom role groups been eliminated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f727c85-8525-613e-6b41-3278a6a10986
* Version Independent ID: 2c6f9456-d06a-7af8-d952-f6025563362b
* Content: [The new Microsoft 365 security center and Microsoft 365 compliance center are now generally available](https://docs.microsoft.com/en-us/office365/securitycompliance/microsoft-security-and-compliance#feedback)
* Content Source: [SecurityCompliance/microsoft-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/microsoft-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@mrkeiths Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
