### ISSUE TITLE
Option to apply sensitivty label not appearing

### ISSUE THREAD

**Issue by DavidWood139** [MicrosoftDocs/OfficeDocs-o365seccomp#556]
Hi All, 

I have created a basic sensitivity label and published it to all users and groups.  The sensitivity button does not appear in apps on Office 365 such as Word.  Could someone advise what step has been missed?

Thanks,
David

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@DavidWood139  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
