### ISSUE TITLE
reflect changes to audit log search

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-o365seccomp#559]
consent to application is no longer available...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9df7e735-5c53-aa7c-59d5-44dabea53523
* Version Independent ID: 6018d9ad-0eb1-22af-789c-8934de357d4d
* Content: [Detect and Remediate Illicit Consent Grants in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/detect-and-remediate-illicit-consent-grants)
* Content Source: [SecurityCompliance/detect-and-remediate-illicit-consent-grants.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/detect-and-remediate-illicit-consent-grants.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by bakerm00** [comment]
it can be found in the azure ad audit log

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@bakerm00 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
