### ISSUE TITLE
SMIME signed?

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-o365seccomp#561]
What happens with S/MIME signed messages? Does it work or not?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a4e2d7-73c3-464a-75a6-bb3bc54442a7
* Version Independent ID: 629cc24e-c828-41f8-dc47-89ce5dc2e7fa
* Content: [Dynamic Delivery and previewing with Office 365 ATP Safe Attachments](https://docs.microsoft.com/en-us/office365/securitycompliance/dynamic-delivery-and-previewing#additional-considerations)
* Content Source: [SecurityCompliance/dynamic-delivery-and-previewing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/dynamic-delivery-and-previewing.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@trudolf-msft Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
