### ISSUE TITLE
How does Microsoft determine if a user is inactive for thirty (30) days

### ISSUE THREAD

**Issue by lmusicofztech** [MicrosoftDocs/OfficeDocs-o365seccomp#563]
We are using Microsoft Secure Score for our clients. I was asked by one of our account managers how Microsoft determines a user account has not been used for thirty (30) days.

One of our clients has the majority of their employees listed in the "inactive users" report in Secure Score and I was asked how this is possible.

Any advice is greatly appreciated!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by kenwith** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@lmusicofztech  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
