### ISSUE TITLE
Could not find "Retention" on office365 webpage

### ISSUE THREAD

**Issue by atul898** [MicrosoftDocs/OfficeDocs-o365seccomp#565]
"Retention" is available at https://protection.microsoft.com and not at https://compliance.microsoft.com like this page describes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac2ead82-c764-16a8-2850-a313ecabc44a
* Version Independent ID: 26baec04-9492-6030-e39f-060243939cec
* Content: [Create and manage inactive mailboxes in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/create-and-manage-inactive-mailboxes#feedback)
* Content Source: [SecurityCompliance/create-and-manage-inactive-mailboxes.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by markjjo** [comment]
@atul898 Thanks for the feedback. I can't repro your experience; for me, https://compliance.microsoft.com redirects to https://protection.office.com, which is URL for Security & Compliance Center. The URL https://compliance.microsoft.com is for the new M365 compliance center; but for existing Office 365 tenants, it should redirect to the Security & Compliance Center. But obviously it's not working that way. I will update this topic and revert back to https://protection.office.com which should resolved the issue you're seeing. Thanks for your time and sorry for the hassle.
