### ISSUE TITLE
Keep up (MS Changing their dashboards too fast)

### ISSUE THREAD

**Issue by Coldry** [MicrosoftDocs/OfficeDocs-o365seccomp#567]
The document above reads:

"Create an activity alert

Go to https://compliance.microsoft.com/#/managealerts.

Sign in to Office 365 using your work or school account.

On the Activity alerts page, click Add on New...."

Firstly the link mentioned redirects to "https://compliance.microsoft.com/homepage"

And there is no "Activity Alerts" page at tha link. I'm sure there was at some point but how do I make my search look only for help in current docs!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb61519-dd23-0fc2-f91a-4c9db668875c
* Version Independent ID: 618e4a73-a59e-39e1-13d2-3d1ad7ebb9b5
* Content: [Create activity alerts in the Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/create-activity-alerts#feedback)
* Content Source: [SecurityCompliance/create-activity-alerts.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-activity-alerts.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Coldry Thanks for the feedback. I can't repro your experience; for me, https://compliance.microsoft.com/#/managealerts redirects to https://protection.office.com/managealerts
, which is URL for Activity alerts page. 

Please try this: https://protection.office.com/managealerts

The URL https://compliance.microsoft.com is for the new M365 compliance center; but for existing Office 365 tenants, it should redirect to the Security & Compliance Center. But obviously it's not working that way for you. I will update this topic and revert back to https://protection.office.com/managealerts which should fix the issue you're seeing. 

I agree that this dashboards are changing fast. We're trying to continually improve, but there are glitches. Thanks for your time and sorry for the hassle.

**Comment by Coldry** [comment]
Thanks. You're right, if i go to "https://protection.off..." its fine. So there's a separate issue here. Why am I being redirected to the wrong place? Do you know the team I should be posting that question to?
