### ISSUE TITLE
Not Junk reporting does not work when mailbox is not en-us

### ISSUE THREAD

**Issue by jmrita** [MicrosoftDocs/OfficeDocs-o365seccomp#568]
Not Junk reporting does not work when mailbox is not en-us. If folder is called 'E-Mail de lixo' ( portuguese for Junk E-Mail ), we get message stating that not junk reporting only works for messages in Junk folder. Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62304805-117a-0e04-038b-a42a89e12162
* Version Independent ID: 7c12ba44-3c56-7607-7e63-84b0073a25df
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in#feedback)
* Content Source: [SecurityCompliance/enable-the-report-message-add-in.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@jmrita  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
