### ISSUE TITLE
Your, not You're

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/OfficeDocs-o365seccomp#569]
In step two, is the following text:
Step 2: Create a new case
The next step is to create a new eDiscovery case. You must be a member of the eDiscovery Managers role group to create eDiscovery cases. As previously explained, after you create a new case in the Security & Compliance Center, you (and other case members) will be able to access that same case in Advanced eDiscovery if you're organization has an Office 365 E5 subscription.

The "you're" in that paragraph should be "your".
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98d1f72-c381-3056-c1c4-7e54a9ab05af
* Version Independent ID: f5771dac-209a-433b-1967-a6ef3118eec6
* Content: [eDiscovery cases in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/ediscovery-cases?redirectSourcePath=%252fen-US%252farticle%252feDiscovery-FAQ-9d1a29ae-b7b4-4a27-9c8c-84289023dcae)
* Content Source: [SecurityCompliance/ediscovery-cases.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ediscovery-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@WillMartin58 Thanks for catching this; I have fixed and revised topic should be live later today.

**Comment by WillMartin58** [comment]
Thanks, Mark.  This type of typo bugs me – my daughter is a proofreader, so you can imagine.
