### ISSUE TITLE
Typo in the default policies section

### ISSUE THREAD

**Issue by danielharkerdp** [MicrosoftDocs/OfficeDocs-o365seccomp#571]
"Unusual external user file activity 
Generates an alert when an usually large number of activities are performed on files "

Surely that should be "...an UNusually large number..."

That same table has the same error a few times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e607177-4e5b-69af-5408-caa6337bbd0e
* Version Independent ID: c82bbeaa-9df1-c070-644b-a666406464b5
* Content: [Alert policies in the security and compliance center](https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies)
* Content Source: [SecurityCompliance/alert-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@danielharkerdp Thanks for the heads up. Will fix. Note that you can also fix by clicking the Edit icon on the article page, making edit, and then submitting a pull request.

**Comment by danielharkerdp** [comment]
I did not realise I could do that. Change submitted
