### ISSUE TITLE
Email Body property is undocumented

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/OfficeDocs-o365seccomp#576]
I seem to be able to search for Body:Keyword in the same way that Subject:Keyword works within exchange however this doesn't appear to be documented anywhere.  Is this a deliberate omission?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b84ade-fa24-3ca7-adb8-1a3398faa0a0
* Version Independent ID: b601bd4d-aa7e-63aa-0404-4cd84d817a9d
* Content: [Keyword queries and search conditions for Content Search](https://docs.microsoft.com/en-us/office365/securitycompliance/keyword-queries-and-search-conditions#feedback)
* Content Source: [SecurityCompliance/keyword-queries-and-search-conditions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ld0614 Thanks for the question. Using body:<keyword> in a search query will return the same results as using <keyword>. So it's not really a searchable email property; it's just ignored, which is why it doesn't return an error as an "unsupported property."
