### ISSUE TITLE
Sending an email back using O365 encryption

### ISSUE THREAD

**Issue by ScottGroner** [MicrosoftDocs/OfficeDocs-o365seccomp#577]
Is there a way to have a customer click a link in my signature line that would initiate an encrypted email back to me?  We have this feature currently using Citrix ShareFile where a customer can click the "Upload" button in our signature line.  When the customer clicks on the upload button, it takes the user to the ShareFile FileDrop page where a client can securely upload a file with PII.

**Comment by scanum** [comment]
@ScottGroner  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
