### ISSUE TITLE
Names of some cmdlets are wrong in ja-jp version.

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/OfficeDocs-o365seccomp#579]
https://docs.microsoft.com/ja-jp/office365/securitycompliance/permissions-filtering-for-content-search?redirectSourcePath=%252fja-jp%252farticle%252f-1adffc35-38e5-4f7d-8495-8e0e8721f377

Some names of Cmdlets are wrong in ja-jp version.(In en-us version, these information is correct.)
It would be appreciated if you could modify this information as follows.
*All the cmdlets names are "new-compliancesecurity filter" in ja-jp version.

<Current>
Search permissions filtering is supported by the Content Search feature in the Security & Compliance Center. These four cmdlets let you configure and manage search permisisons filters:
new-compliancesecurityfilter
new-compliancesecurityfilter
new-compliancesecurityfilter
new-compliancesecurityfilter
<Expected>
Search permissions filtering is supported by the Content Search feature in the Security & Compliance Center. These four cmdlets let you configure and manage search permisisons filters:
New-ComplianceSecurityFilter
Get-ComplianceSecurityFilter
Set-ComplianceSecurityFilter
Remove-ComplianceSecurityFilter

**Comment by denisebmsft** [comment]
@AkikoTsukahara thank you for letting us know. We are looking into this.

**Comment by MollyMalone** [comment]
@OfficeGlobal please take care of this.  The topic is currently machine translated, please uplift it to human translation.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@AkikoTsukahara , @MollyMalone article has been HumanTranslated. The issue is fixed.

**Comment by scanum** [comment]
@officedocsbot close
