### ISSUE TITLE
Microsoft 365 Audit Logs retention for Microsoft 365 Enteprise

### ISSUE THREAD

**Issue by JordyBlommaert** [MicrosoftDocs/OfficeDocs-o365seccomp#581]
This article described following retention policy's:
Office 365 E3 - Audit records are retained for 90 days.

Office 365 E5 - Audit records are retained for 365 days (one year). Retaining audit records for one year is also available for organizations that have an E3 subscription and an Office 365 Advanced Compliance add-on subscription.

What about Microsoft 365 E3 licenses I assume this is also 90 days because it contains an Office 365 E3 packet and doesn't have Advanced Compliance in the packet.
Or does it also haves a retention policy of 1 year?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#feedback)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@JordyBlommaert You are correct; retention period for unified audit log records is 90 days for M365 E3. In summary, retention periods for any E3 subscriptions without add-in subscriptions (M365, O365, government) is 90 days. Likewise, retention periods for any E5 subscriptions is 1 year.
