### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by mikeld24** [MicrosoftDocs/OfficeDocs-o365seccomp#583]
The link for the text below goes to a 404 not found page.
Block email spam with the Office 365 spam filter to prevent false negative issues

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78678fe5-0473-27f2-1600-122267386c3d
* Version Independent ID: ab96b413-3d71-a9ae-5887-e80696b30f3f
* Content: [Submit spam, non-spam, and phishing scam messages to Microsoft for analysis](https://docs.microsoft.com/en-us/office365/SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis#feedback)
* Content Source: [SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @mikeld24, and thank you for the feedback. Links are fixed.
