### ISSUE TITLE
I'm locked out of my BitLocker

### ISSUE THREAD

**Issue by Pivoted** [MicrosoftDocs/OfficeDocs-o365seccomp#584]
I've spent the past 4 days trying to find recovery keys so that I can get help with my laptop that isn't booting properly. As someone who doesn't understand this stuff, I find incomprehensible pages like this one, and I find deadends. I've called Microsoft and they tell me to call the manufacturer of my computer. The manufacturer then says I have to talk to Microsoft ... who tells me again to call the manufacturer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ee2a5a-25b6-b153-725d-c29a7f08e873
* Version Independent ID: 215dfb0e-65cb-9868-f78c-12458f7707d2
* Content: [Office 365 BitLocker for Encryption](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-bitlocker-and-distributed-key-manager-for-encryption#feedback)
* Content Source: [SecurityCompliance/office-365-bitlocker-and-distributed-key-manager-for-encryption.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-bitlocker-and-distributed-key-manager-for-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Pivoted  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Pivoted** [comment]
I did a lot of research and gave up. I found so many people in forums and on Twitter who were in a jam like I was, never heard of Bitlocker and had no idea where this key is. I couldn't even restore the laptop to factory settings without the Bitlocker key.

I paid Best Buy to do a clean install of Windows--without Bitlocker encryption.
