### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by JanBakker88** [MicrosoftDocs/OfficeDocs-o365seccomp#587]
In step 1 the URL points to https://compliance.microsoft.com/ 
This is not the right location to Import PST files. 
https://compliance.microsoft.com/ only points to the Compliance Center.

This should be: https://protection.office.com/. This points to the Security & Compliance Center where you can import the PST files. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a65de3-b878-b20a-3823-11a9dbc3e37c
* Version Independent ID: 28499237-e103-b204-12b2-11d72f685370
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files)
* Content Source: [SecurityCompliance/use-network-upload-to-import-pst-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@JanBakker88 Thanks for the heads up; I will fix URL
