### ISSUE TITLE
Where is the Chrome extension?

### ISSUE THREAD

**Issue by NoSubstitute** [MicrosoftDocs/OfficeDocs-o365seccomp#589]
It's mentioned here and in other places, but there is NO real reference to it, so I'm still not able to follow the instructions! We need an exact URL, or a proper extension ID, that actually exists in the Chrome Web Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f128898d-48f8-c45f-2230-957195b4ab9f
* Version Independent ID: d3c2b975-fafe-510b-d64d-a65db2ed8b98
* Content: [Configure S/MIME settings in Exchange Online for Outlook on the web](https://docs.microsoft.com/en-us/office365/SecurityCompliance/configure-s-mime-settings-for-outlook-web-app#feedback)
* Content Source: [SecurityCompliance/configure-s-mime-settings-for-outlook-web-app.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-s-mime-settings-for-outlook-web-app.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@NoSubstitute Thank you for reaching out and helping improve MS Docs.  I'll investigate further and revert soonest.

**Comment by chrisda** [comment]
@NoSubstitute, I've updated the topic with new information. The extention 'example' in the topic isn't an example; it's the real value you need to use. Users are prompted in OWA to install the S/MIME control the first time the do anything S/MIME related, or they can go to S/MIME in their OWA settings to get the download link for the control.

**Comment by NoSubstitute** [comment]
Well, that's not my experience.
The "example" extension didn't exist when I tried to use it.

Did you update the code/link to something that actually works now?

**Comment by chrisda** [comment]
@NoSubstitute, I've been told on good authority that the value `maafgiompdekodanheihhgilkjchcakm;https://outlook.office.com/owa/SmimeCrxUpdate.ashx` is the correct value for everyone to use in Office 365. That's what the topic says now. Are you saying that value doesn't work?

**Comment by scanum** [comment]
@NoSubstitute  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by NoSubstitute** [comment]
**Thank you.**
I have also verified that the current forced installation information now works.
I haven't been able to verify all of the actual S/MIME capability, since there are still a bunch of requirements (settings in O365 Admin, and getting user certificates online) before the first S/MIME signed or encrypted email can be sent.

It does however show a certificate icon for incoming signed emails.

Sadly, it does so only in the "old" version of Outlook, and not in the _New Outlook_ UI. Opening a signed email in the new/beta/coming web UI clearly states that S/MIME isn't supported.

I must say that it is much easier using Hosted S/MIME in G Suite.
There you only enable the feature in the admin console, and the user can immediately upload their own certificate, or I can bulk-upload them.

**Comment by NoSubstitute** [comment]
This is what it looks like when you try to use S/MIME, using only the addon.
This is with the old UI, since S/MIME doesn't work at all with the new UI.

![20190519-1558-O365_SMIME-Incoming_signed_email-Notification_of_signature](https://user-images.githubusercontent.com/12572734/57983302-77f49200-7a50-11e9-8a2c-5e8adb47d026.png)

![20190519-1601-O365_SMIME-Incoming_signed_email-Verification_not_possible_in_view](https://user-images.githubusercontent.com/12572734/57983309-7c20af80-7a50-11e9-8ef0-84542c0cc675.png)

![20190519-1602-O365_SMIME-Incoming_signed_email-New_window-Still_cant_view](https://user-images.githubusercontent.com/12572734/57983312-804ccd00-7a50-11e9-8378-de8531fd1ee0.png)
