### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#591]
When i click on the links below the videos to Download, nothing gets downloaded. I was hoping to be able to do this so that I could view them off-line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce9b8aa-323c-eb83-d8c2-5297cfdcdd37
* Version Independent ID: c349edcb-3b19-64db-2c7f-5ae75a59aa64
* Content: [Chief Information Security Officer (CISO) Workshop, Module 1: Microsoft Cybersecurity Briefing](https://docs.microsoft.com/en-us/office365/securitycompliance/ciso-workshop-module-1)
* Content Source: [SecurityCompliance/ciso-workshop-module-1.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ciso-workshop-module-1.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by robmazz** [comment]
@DeanGross - thanks for the feedback, I'm looking into this with our video hosting team.

**Comment by robmazz** [comment]
@DeanGross  - unfortunately, downloading the videos is not available due to licensing restrictions. However, you can download transcripts for the videos. You can also download the lesson PDF or PPT file. Thanks again for the feedback!
