### ISSUE TITLE
Note required Outlook License

### ISSUE THREAD

**Issue by MorshuBombs** [MicrosoftDocs/OfficeDocs-o365seccomp#592]
Certain Outlook licenses are required to access an in-place archive mailbox. Please note this somewhere on this page. See this page for more info on the licenses that support this feature: https://support.office.com/en-ie/article/outlook-license-requirements-for-exchange-features-46b6b7c5-c3ca-43e5-8424-1e2807917c99

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90155d71-7541-cf11-f769-97239f69ee2c
* Version Independent ID: 3c709c8c-460a-a075-067e-70907a97a015
* Content: [Enable archive mailboxes in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-archive-mailboxes#feedback)
* Content Source: [SecurityCompliance/enable-archive-mailboxes.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@MorshuBombs Thanks for the suggestion. We'll add a link to the support.office.com topic about supported clients.
