### ISSUE TITLE
"Data Investigator" role is missing

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/OfficeDocs-o365seccomp#593]
The current O365 Sercurity & Compliance center has "Data Investigator" as a role. Please add this role to this page.
Role Group: Data Invertigator
Description: Perform searches on mailboxes, SharePoint Online sites, and OneDrive for Business locations.
Assigned Roles: 
Export
RMS Decrypt
Custodian
Communication
Review
Preview
Compliance Search
Data Investigation Management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center#feedback)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@UKayo Thank you for reaching out and helping improve MS Docs.  I'll have the team look into this soonest.

**Comment by scanum** [comment]
@UKayo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
