### ISSUE TITLE
A few is ok but I don't like the release all option... too risky

### ISSUE THREAD

**Issue by jm15502** [MicrosoftDocs/OfficeDocs-o365seccomp#594]
The release all option could be a too easy way for lazy or careless people to disregard all the security criteria that put those emails on quarantine. I believe this should be limited to reduce the risk of damage while users are still allowed to release some messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e487b445-a3ef-ec1e-43b6-bd9f7afa3f62
* Version Independent ID: 34d5e5a4-4bdc-47bd-3638-bcf80ee935d6
* Content: [Find and release quarantined messages as a user in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/find-and-release-quarantined-messages-as-a-user)
* Content Source: [SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@jm15502  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make o365seccomp better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://office365.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
