### ISSUE TITLE
bad links

### ISSUE THREAD

**Issue by lpullenMEA** [MicrosoftDocs/OfficeDocs-o365seccomp#595]
Your Connect to Security & Compliance Center PowerShell links are both dead including the one I need  Connect to Security & Compliance Center PowerShell using multi-factor authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61322e04-93a6-100c-4fba-43366e2e3dfc
* Version Independent ID: 0c03b380-5b46-8ef5-6cc2-1545031e5645
* Content: [Search for and delete email messages in your Office 365 organization - Admin Help](https://docs.microsoft.com/en-us/office365/securitycompliance/search-for-and-delete-messages-in-your-organization#feedback)
* Content Source: [SecurityCompliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@lpullenMEA Thanks for the heads up and sorry for the hassle. The links to the SCC powershell topics are working again.

MFA: https://docs.microsoft.com/powershell/exchange/office-365-scc/connect-to-scc-powershell/mfa-connect-to-scc-powershell?view=exchange-ps
