### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by Drtrider** [MicrosoftDocs/OfficeDocs-o365seccomp#596]
- Page in question: https://docs.microsoft.com/en-us/office365/securitycompliance/search-for-and-delete-messages-in-your-organization
- Broken Link: https://docs.microsoft.com/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell

Under "Step 2: Connect to Security & Compliance Center PowerShell" the "Connect to Security & Compliance Center PowerShell." is broken and returns a 404.

**Comment by denisebmsft** [comment]
Hello @Drtrider, I've run into the same problem with that link today, and I've written the documentation team about this. Stay tuned - they'll get that link fixed very soon. Sorry for the inconvenience!

**Comment by denisebmsft** [comment]
@Drtrider i heard back from the article owner, and they're resolving this. Link should be fixed pretty soon.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by markjjo** [comment]
@Drtrider @denisebmsft @scanum These links have been fixed and are now working.
