### ISSUE TITLE
Missing permission for import

### ISSUE THREAD

**Issue by MCFHTAGENTS** [MicrosoftDocs/OfficeDocs-o365seccomp#597]
The instruction
'You have to be assigned the appropriate permissions to access the Import page in the Security & Compliance Center. See the Before you begin section for more information.' is not covered in the before you begin - it covers assigning an exchange permission - where do we go for the import permission? Please consider adding links to all the myriad of pages

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a65de3-b878-b20a-3823-11a9dbc3e37c
* Version Independent ID: 28499237-e103-b204-12b2-11d72f685370
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-gb/office365/securitycompliance/use-network-upload-to-import-pst-files#feedback)
* Content Source: [SecurityCompliance/use-network-upload-to-import-pst-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@MCFHTAGENTS Thanks for the heads up. It seems that the minimal permissions (as documented) required to create import jobs in the Security & Compliance Center (SCC) has changed. Please try this: In addition to assigning the Mailbox Import Export and Mail Recipients roles in Exchange, assign the View-Only Recipients role in the Security & Compliance Center. One wayto do this is to create a custom role group in the SCC and assign the View-Only Recipients role to this group and then add the person who will create the import jobs (make sure this same person is assigned the required roles in Exchange). After you done that, have the person go to https://protection.office.com and sign in. They should be able to go to Data governance > Import and create import jobs. It would be great if you can follow up on this same issue and let us know if that worked for you. I was able to repo it. Thanks again.

**Comment by MCFHTAGENTS** [comment]
The page where you do the import actually said it was that single permission. Note having to set this and 'wait 24 hours' does not provide a great migration experience.

Also you should state that mapping file name must be PSTImportMappingFile.csv

**Comment by MCFHTAGENTS** [comment]
and also needs to state the users mailboxes must be setup first

**Comment by markjjo** [comment]
@MCFHTAGENTS I assume that assigning the View-Only Recipients role in the SCC unblocked your issue. Documentation will be updated accordingly.
