### ISSUE TITLE
Removing or deleting a retention label 

### ISSUE THREAD

**Issue by ernelso** [MicrosoftDocs/OfficeDocs-o365seccomp#598]
We should add the appropriate documentation in this article as we explain for EXO retention tags... and illustrate the similarity in how labels operate and are managed like tags by the MFA in EXO.
https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/retention-tags-and-policies
Removing or deleting a retention tag from a retention policy
When a retention tag is removed from the retention policy applied to a mailbox, the tag is no longer available to the user and can't be applied to items in the mailbox.
Existing items that have been stamped with that tag continue to be processed by the Managed Folder Assistant based on those settings and any retention action specified in the tag is applied to those messages.
However, if you delete the tag, the tag definition stored in Active Directory is removed. This causes the Managed Folder Assistant to process all items in a mailbox and restamp the ones that have the removed tag applied. Depending on the number of mailboxes and messages, this process may significantly consume resources on all Mailbox servers that contain mailboxes with retention policies that include the removed tag.
Important
If a retention tag is removed from a retention policy, any existing mailbox items with the tag applied will continue to expire based on the tag's settings. To prevent the tag's settings from being applied to any items, you should delete the tag. Deleting a tag removes it from any retention policies in which it's included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ernelso Thanks Eric for this information. Are you suggesting adding your wording above, to the article - "removing or deleting a retention tag...?" Let me know and I can have it implemented soonest.

**Comment by scanum** [comment]
@ernelso  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by ernelso** [comment]
@lindspea - Yes that is my suggestion. However, we need adjust the verbiage from tags (which are used in EXO MRM) and Labels which are used in O365 Security & Compliance Retention Policies.
