### ISSUE TITLE
import csv file template fails

### ISSUE THREAD

**Issue by beigewell** [MicrosoftDocs/OfficeDocs-o365seccomp#599]
you cannot import this csv export template as the fields are not possible to import without some of these fields already pre populated in your tenant

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@ - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jamtur01** [comment]
@scanum I think you might have @'ed the wrong person?

**Comment by scanum** [comment]
@jamtur01 Apologies!
