### ISSUE TITLE
Data Handling Standards

### ISSUE THREAD

**Issue by chharts** [MicrosoftDocs/OfficeDocs-o365seccomp#6]
It would be great to know more about data handling standards, and what happens to messages sent to junk@office365.microsoft.com and phish@office365.microsoft.com, and how long they are held for. Can we create a section or link to an article that covers this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c57b5515-12f8-2221-aa94-7883cc58fe1b
* Version Independent ID: 44327e0a-c461-013c-cb20-a0427d74f4f0
* Content: [Submitting malware and non-malware to Microsoft for analysis](https://docs.microsoft.com/en-us/office365/SecurityCompliance/submitting-malware-and-non-malware-to-microsoft-for-analysis)
* Content Source: [SecurityCompliance/submitting-malware-and-non-malware-to-microsoft-for-analysis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/submitting-malware-and-non-malware-to-microsoft-for-analysis.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
Hi Chris! Thanks for your interest. Those are great suggestions. I've forwarded your request on to the team.
