### ISSUE TITLE
Lack of information about powershell commandlets permission changes

### ISSUE THREAD

**Issue by samrajcse** [MicrosoftDocs/OfficeDocs-o365seccomp#600]
Hi Team,

What changes we need to do to for powershell commandlets to work without breaking the existing functionality? Any new role to be added or existing role is enough?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@samrajcse - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
