### ISSUE TITLE
Reference to obsolete center

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#601]
The instructions refer to the Security & Compliance Center which is being split into 2 separate centers. This documentation should be updated to refer to the new Security Center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efdde62-0d69-bc5f-3833-d402bb1aa24f
* Version Independent ID: 3feeadc7-1848-b77b-a29f-e9b91c20e9c5
* Content: [Automated Investigation and Response (AIR) with Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/automated-investigation-response-office)
* Content Source: [SecurityCompliance/automated-investigation-response-office.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/automated-investigation-response-office.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @DeanGross and thank you for the feedback. Not everything in the Office 365 Security & Compliance Center is in the two new centers just yet, and the former hasn't been completely deprecated. That said, I will make sure the content gets updated soon. Thank you for helping us improve our documentation! We appreciate the feedback!

**Comment by DeanGross** [comment]
Ok, that should be helpful, it is currently tremendously difficult to keep track of the changes, the new centers keep showing up and disappearing, functionality is changing frequently . The announcement that they were GA was premature.
