### ISSUE TITLE
SKU naming on Info barriers page 

### ISSUE THREAD

**Issue by MarkBratton** [MicrosoftDocs/OfficeDocs-o365seccomp#602]
At https://docs.microsoft.com/en-us/Office365/SecurityCompliance/information-barriers this list should be updated with correct naming. Notes below. 

Microsoft 365 Enterprise E5 <--Remove "Enterprise" as we no longer use that in plan names
Office 365 Enterprise E5 <---Remove "Enterprise" 
Office 365 Advanced Compliance
Information Protection & Compliance <---change to new name "Microsoft 365 E5 Compliance"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ddb4a04-f1de-180f-5f98-4f8d6893ce42
* Version Independent ID: 6b6fb7da-b919-f35a-5a86-d6d21a5dc193
* Content: [Information barriers overview](https://review.docs.microsoft.com/en-us/Office365/SecurityCompliance/information-barriers?branch=infobarriers-working)
* Content Source: [SecurityCompliance/information-barriers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
HI @MarkBratton, and thanks. This content isn't live yet, but I'll take these suggestions into account.

**Comment by MarkBratton** [comment]
Thanks!

**Comment by MarkBratton** [comment]
To remove any ambiguity, can we please change the 3 instances of "E5" to "E5/A5/G5" and remove the "such as:"? With this change, the list is subscriptions that include info barriers is complete. Thanks!
