### ISSUE TITLE
The private preview program for increasing the Audit Log retention to 365 days was suspended

### ISSUE THREAD

**Issue by marcelkatz** [MicrosoftDocs/OfficeDocs-o365seccomp#603]
I've just been informed by our product management team for Auditing that the private preview program for increasing the Audit Log retention to 365 days was suspended, and we don't have an estimated time of when it will be re-activated. The Documentation Team should update the paragraph below accordingly.

 "Note

The one-year retention period for audit records for E5 organizations (or E3 organizations that have Advanced Compliance add-on licenses) is currently available only as part of a private preview program. To enroll in this preview program, please file a request with Microsoft Support and include the following as the description of what you need help with: "Long-term Office 365 audit log private preview""

Thanks,
-Marcel Katz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance?redirectSourcePath=%252fen-us%252farticle%252fSearch-the-audit-log-in-the-Office-365-Security-Compliance-Center-0d4d0f35-390b-4518-800e-0c7ec95e946c#feedback)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@marcelkatz Thank you for reaching out and helping improve MS Docs.  I'll have this updated soonest.

**Comment by markjjo** [comment]
The documentation has been updated to state that the private preview program is closed to new enrollment.
