### ISSUE TITLE
Office 365 ATP Plan 2 in M365B?

### ISSUE THREAD

**Issue by scottabbotts** [MicrosoftDocs/OfficeDocs-o365seccomp#605]
"Office 365 Advanced Threat Protection and Threat Investigation and Response (previously known as Office 365 Threat Intelligence) are now Office 365 Advanced Threat Protection Plan 2, along with additional threat protection capabilities included in in certain subscriptions, such as Microsoft 365 Enterprise, Microsoft 365 Business, Office 365 Enterprise E5, Office 365 Education A5, etc."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2431ea89-86b7-5af7-a528-a9b3c31d21a9
* Version Independent ID: 8ade760a-f092-8d93-9f3d-485be3a1ecd7
* Content: [Office 365 threat investigation and response](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-ti?fbclid=IwAR0nimnOXo1t2yIXXX4Ow9g7tHycqqrKbtglgOOxxOi1pe0H0kHaiUJWz6A#feedback)
* Content Source: [SecurityCompliance/office-365-ti.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-ti.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@scottabbotts Thanks for reaching out and helping improve MS Docs.  Please can you clarify what you are asking or requesting to be changed in the Doc?

**Comment by scottabbotts** [comment]
@Lindsay<mailto:notifications@github.com> I quoted a sentence in my original post that includes Microsoft 365 Business as one of the plans that includes Office 365 ATP Plans 2, however, I think this is an error. I’d love it if were true, but please consider other documentation from Microsoft:

[cid:image001.png@01D4FF48.382C69F0]

Scott Abbotts
(727) 300-4940 voice
(727) 203-6959 text
https://resolute-it.com
support@resolute-it.com<mailto:support@resolute-it.com?subject=New%20ticket:>
Schedule an Appointment<https://outlook.office365.com/owa/calendar/ResoluteIT@scottabbotts.com/bookings/>

**Comment by scanum** [comment]
@scottabbotts Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
