### ISSUE TITLE
DMARC action p=none

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#606]
I think it might be prudent to add something around how we treat mails that fail DMARC were the action is none, as it can still end up being marked as spam due to other factors (which most recipients/customers are unaware of)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df985369-7b10-20c3-c09e-651e7e216d93
* Version Independent ID: 3336ab94-64b0-a2a9-a9e9-e8a56d15941d
* Content: [Use DMARC to validate email in Office 365](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dmarc-to-validate-email)
* Content Source: [SecurityCompliance/use-dmarc-to-validate-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@aldoug  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by aldoug** [comment]
Hi Manuela

I work for Microsoft support, it’s more to get the documentation updated for our customers☺

Alisdair Douglas

Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support

Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 09:00 - 18:00

[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG
