### ISSUE TITLE
DKIM Selectors & O365/Exchange

### ISSUE THREAD

**Issue by vkswaminathan** [MicrosoftDocs/OfficeDocs-o365seccomp#608]
Can O365/Exchange have DKIM selectors other/additional than "Selector1" & "Selector2"? Can there be more than 2/3/4/5 selectors used to rotate. If yes, what might happen if Selector1 & Selector2 fail simultaneously?

**Comment by scanum** [comment]
@vkswaminathan  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
