### ISSUE TITLE
Clarify "Content in mailboxes and public folders"

### ISSUE THREAD

**Issue by fitzgeezy** [MicrosoftDocs/OfficeDocs-o365seccomp#609]
This section mentions "After a retention policy is assigned to a mailbox or public folder, content can follow one of two paths:", however it does not differentiate when or how it is decided which path would be followed for mailbox content. I believe path #1 is followed when the retention policy is created without a delete action, and path #2 is followed if the retention policy has a delete action.

Without clarification, I found it hard to understand if mailbox content that is not in the Recoverable Items folder would also be deleted at the end of the retention period, even if there is no delete action in the retention policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies#feedback)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@fitzgeezy - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedcosbot assign @scanum

**Comment by svenghyselinck** [comment]
"Content in mailboxes and public folders"
This section mentions "When a person attempts to change certain properties of a mailbox item — such as the subject, body, attachments, senders and recipients, or date sent or received for a message — a copy of the original item is saved to the Recoverable Items folder before the change is committed. This happens for each subsequent change. At the end of the retention period, copies in the Recoverable Items folder are permanently deleted."

Please clarify this paragraph. At the beginning of this paragraph you should clarify if concerns a situation with or without a retention policy.

**Comment by lindspea** [comment]
@fitzgeezy @svenghyselinck thank you for pointing out these findings.  I'll work on having some clarity added to the article.

**Comment by scanum** [comment]
@fitzgeezy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
