### ISSUE TITLE
Weaker than what?

### ISSUE THREAD

**Issue by beb-bang** [MicrosoftDocs/OfficeDocs-o365seccomp#610]
In this paragraph:

"001 means the message failed implicit email authentication. This means that the sending domain did not have email authentication records published, or if they did, they had a weaker failure policy (SPF soft fail or neutral, DMARC policy of p=none). "

Where it states "they had a weaker failure policy", what is that related to? Weaker than what? Perhaps my own policy?

Many Thanks!
Bryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab02396-69f6-5a83-fc27-7a2ba9ab78eb
* Version Independent ID: 63266ff4-ef2a-84b3-f1b9-c7b3e4d8a1b7
* Content: [Anti-spoofing protection in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/anti-spoofing-protection#feedback)
* Content Source: [SecurityCompliance/anti-spoofing-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spoofing-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@beb-bang - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedcosbot assign @scanum

**Comment by lindspea** [comment]
@beb-bang Thank you for reaching out and helping improve MS Docs. For DMARC, 'p' stands for policy and you can have different settings. The same for Sender Policy Framework (SPF), soft fail being the "weakest'.

**Comment by scanum** [comment]
@beb-bang Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
