### ISSUE TITLE
 Protection > Content filter

### ISSUE THREAD

**Issue by Wallace4444** [MicrosoftDocs/OfficeDocs-o365seccomp#611]
The page suggests to enable user notifications on  Protection &gt; Content filter page. Shouldn't it be  Protection &gt; Spam Filter page?

There is no user notification option on Content Filtering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ff95c3-b69f-ae49-03ab-994c6fb97f3c
* Version Independent ID: 788c6b03-ce4a-73e3-0e1a-07a7c5fa127d
* Content: [Configure end-user spam notifications in EOP](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-end-user-spam-notifications-in-eop#feedback)
* Content Source: [SecurityCompliance/configure-end-user-spam-notifications-in-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-end-user-spam-notifications-in-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@Wallace4444 - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedcosbot assign @scanum

**Comment by scanum** [comment]
@Wallace4444 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
