### ISSUE TITLE
delegated mailboxes 

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/OfficeDocs-o365seccomp#614]
can users with delegated mailbox permission retrieve emails from the delegated mailbox? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e487b445-a3ef-ec1e-43b6-bd9f7afa3f62
* Version Independent ID: 34d5e5a4-4bdc-47bd-3638-bcf80ee935d6
* Content: [Find and release quarantined messages as a user in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/find-and-release-quarantined-messages-as-a-user)
* Content Source: [SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@netaneladar - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedcosbot assign @scanum

**Comment by lindspea** [comment]
@netaneladar thank you for reaching out.  Please have a look at this article and let me know if it answers your question. https://docs.microsoft.com/office365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide

**Comment by netaneladar** [comment]
Hi there,  
Thank you but it does not answer my question regarding end user quarantine access to a user who has been delegated permission to another mailbox.  
Thanks,Netanel  
    	
    	

    	Get Outlook for iOS
    
  




On Fri, May 10, 2019 at 4:19 AM -0400, "Lindsay" <notifications@github.com> wrote:












@netaneladar thank you for reaching out.  Please have a look at this article and let me know if it answers your question. https://docs.microsoft.com/office365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide

**Comment by lindspea** [comment]
@netaneladar it seems that is only for the mailbox of the user, not the delegated one. Please see here: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/36308347-delegated-permissions-for-managing-spam-quarantine.

**Comment by scanum** [comment]
@netaneladar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
