### ISSUE TITLE
Update needed to reflect Teams

### ISSUE THREAD

**Issue by pistolbrazil** [MicrosoftDocs/OfficeDocs-o365seccomp#615]
Not sure if this is the correct place to post this, but this content needs to be updated with Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd170f21-e0d6-4bd0-ee70-df9fc165f9fe
* Version Independent ID: 31c72b93-a444-90ad-508e-c43fa522f8fc
* Content: [Create, test, and tune a DLP policy](https://docs.microsoft.com/en-us/office365/securitycompliance/create-test-tune-dlp-policy#feedback)
* Content Source: [SecurityCompliance/create-test-tune-dlp-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@pistolbrazil- Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@pistolbrazil Thank you for reaching out and helping improve MS Docs.  Please could you specify where you think 'Teams' needs to be added to the article.  Could you elaborate please.

**Comment by scanum** [comment]
@pistolbrazil Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
