### ISSUE TITLE
License pack references

### ISSUE THREAD

**Issue by Spaatz965** [MicrosoftDocs/OfficeDocs-o365seccomp#616]
This is the Additional information link for the M365 Message Center announcement for General Availability. Skimming through, this looks wonderful. But the first and key bit of info I need - does it relate to the licenses in the tenant I'm administering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b11f2c-cd30-c35c-352f-744e5878ca04
* Version Independent ID: f440c56f-2943-c559-0d67-bc5ff93426a0
* Content: [Overview of the Advanced eDiscovery solution in Microsoft 365](https://docs.microsoft.com/en-us/office365/securitycompliance/compliance20/overview-ediscovery-20#feedback)
* Content Source: [SecurityCompliance/compliance20/overview-ediscovery-20.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/compliance20/overview-ediscovery-20.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Spaatz965 Thanks for the question. For a user to be added as a custodian in an Advanced eDiscovery case, that user must be licensed in one of the following ways:

-  E3 with the Advanced Compliance add-on
- Office 365 E5
- Microsoft 365 E5 Compliance
- Miicrosoft 365 E5

An IT admin or lawyer or paralegal who manages Advanced eDiscovery cases (e.g. adding custodian, running searches, adding to data to review sets, running Analytics, exporting data) don't require the above licensing (e.g. E3 or  EXO Plan 2 license)
