### ISSUE TITLE
8. International Spam false advertisement

### ISSUE THREAD

**Issue by ichkoj** [MicrosoftDocs/OfficeDocs-o365seccomp#617]
Does anyone actually testing these products..?! we got bombarded with phishing email from countries that are blocked and sending IP is matching the IP pattern for the originating country, on top we have ATP and still international spam is bypassing all that. This is false advertisement delete it from the article! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b37016-da2f-6e2a-c3e7-360c3e9ec5ed
* Version Independent ID: 395a4420-1d14-5b0a-0be8-8f2b36fdb081
* Content: [Configure your spam filter policies](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-your-spam-filter-policies)
* Content Source: [SecurityCompliance/configure-your-spam-filter-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-your-spam-filter-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@ichkoj - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@ichkoj  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
