### ISSUE TITLE
Web bugs in HTML - false advertisement

### ISSUE THREAD

**Issue by ichkoj** [MicrosoftDocs/OfficeDocs-o365seccomp#618]
This feature doesn't work and there is no prooff that ever worked, neither Microsoft themselves understand it. I've been testing it multiple times with different tracking platforms and it never works. Below is a list of some of the platforms we tested.
Please delete it this is false advertisement! 
salesforceiq.com/t.png
cirrusinsight
deepsynapse.com
sidekickopen 
google analytics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1851022e-16b2-345d-7b88-82576f7fe41d
* Version Independent ID: ba06c46e-fece-e686-b6aa-8b33d31b246f
* Content: [Advanced spam filtering options](https://docs.microsoft.com/en-us/office365/securitycompliance/advanced-spam-filtering-asf-options)
* Content Source: [SecurityCompliance/advanced-spam-filtering-asf-options.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/advanced-spam-filtering-asf-options.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@ichkoj - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@ichkoj  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make our products better . They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://office365.uservoice.com/

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close

**Comment by ichkoj** [comment]
Why you're closing this since its not resovled - please remove this feature since its not working your support confirmed that 
Please dont close without resolving it

**Comment by ichkoj** [comment]
In US false advertisment is illegal
