### ISSUE TITLE
Can't clean up outside / external data

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-o365seccomp#619]
Re "You're informed of a data spillage incident where an employee unknowingly shared a highly-confidential document with multiple people through email. You want to quickly assess who received this document, both inside and outside of your organization. After you've investigate the incident, you plan to share your findings with other investigators to review, and then permanently remove the spilled data from Office 365. After the investigation is complete, you want to remove all evidence." 

I agree that the data may have been spilled outside the organisation, but the capabilities above cannot touch this data. Perhaps it would be good to call this out in a blue / important box to make the scope clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 167bf112-857f-0343-e73b-4c6d9d5ace9b
* Version Independent ID: 80a5b61f-60bb-828b-bfc0-5bbeb967fbc3
* Content: [Manage a data spillage incident in Microsoft 365](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/datainvestigations/manage-data-spillage-incidents)
* Content Source: [SecurityCompliance/datainvestigations/manage-data-spillage-incidents.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/datainvestigations/manage-data-spillage-incidents.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@michael-sampson 
Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Michael-Sampson Thank you for reaching out and helping improve MS Docs.  I'll have this added to the article.  Could you perhaps give your suggestion to make it clearer.  Perhaps: "IMPORTANT - although data may have spilled outside the organization, the capabilities above cannot touch this data."?

**Comment by Michael-Sampson** [comment]
@lindspea Yes, that looks fine. Or "IMPORTANT - while you will be able to permanently remove the spilled data within your own organization, any data spilled outside your organization cannot be removed with these capabilities." And I guess the reality is that may require a data breach notification.

**Comment by markjjo** [comment]
@Michael-Sampson @lindspea Revise topic has been published.
