### ISSUE TITLE
Safelinks and Safe Attachments

### ISSUE THREAD

**Issue by erikwfraser** [MicrosoftDocs/OfficeDocs-o365seccomp#620]
Does OME reduce functionality of Safe links and Safe Attachments? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ad427d-d869-2ab6-3d2c-f846efc99256
* Version Independent ID: 606eaa37-2713-8087-015f-012ae9c90090
* Content: [Office 365 Message Encryption FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-faq#feedback)
* Content Source: [SecurityCompliance/ome-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@erikwfraser -
Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by erikwfraser** [comment]
@scanum How long does an investigation normally take?

**Comment by lindspea** [comment]
@erikwfraser Thank you for reaching out and helping improve MS Docs.  Please have a look at the link and let me know if this answers your questions. https://docs.microsoft.com/office365/securitycompliance/email-encryption.

**Comment by erikwfraser** [comment]
@lindspea Not really. There is no reference to Safelinks, SafeAttachments or ATP anywhere on this page

**Comment by lindspea** [comment]
@erikwfraser As far as I know OME does not reduce functionality, but I'm just waiting for confirmation from the team.

**Comment by lindspea** [comment]
@SSalahAhmed

**Comment by scanum** [comment]
@erikwfraser Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
