### ISSUE TITLE
Inconsistency in time to resolution

### ISSUE THREAD

**Issue by jasontenpenny** [MicrosoftDocs/OfficeDocs-o365seccomp#621]
On this page, it says it can take up to 30 minutes to remove restrictions. But when I performed this action today, inside the portal it said it could take up to an hour. Can we make this consistent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baecd02e-eaff-0822-1cf2-dc7f02e4a218
* Version Independent ID: f97b946a-3306-6cfa-d26a-90e425d5789b
* Content: [Removing a user from the Restricted Users portal after sending spam email](https://docs.microsoft.com/en-us/office365/SecurityCompliance/removing-user-from-restricted-users-portal-after-spam#feedback)
* Content Source: [SecurityCompliance/removing-user-from-restricted-users-portal-after-spam.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/removing-user-from-restricted-users-portal-after-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@jasontenpenny
Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@jasontenpenny thank you for reaching out and helping improve MS Docs.  I have changed the wording in the article slightly.

**Comment by scanum** [comment]
@jasontenpenny Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
