### ISSUE TITLE
Requesting to update the Article

### ISSUE THREAD

**Issue by BeginnersMindzet** [MicrosoftDocs/OfficeDocs-o365seccomp#622]
Requesting to update the Article because the Second bullet point for Admins specifically the PowerShell cmdlet is no longer working/is not working whether the condition is true or false:
 "Get-MailboxJunkEmailConfiguration -Identity * | Where {$_.Enabled -eq $false}"

============ Recommended Script  =============

&lt;#
.SYNOPSIS
    A script to help admins Enable Junk Mail Rule for users who has it turned off. Admins must connect or create a session for Exchange Online to PowerShell first.
.DESCRIPTION
    ALL Users with mailbox whose Junk mail rule was disabled will be enabled after running the script.
.NOTES
    File Name    : SetJunkMailRule.ps1
    Author         : C.D. (cdonnes11@gmail.com)
    Prerequisite : PowerShell V2 over Vista and upper.
    © Copyright 2019 - Glenn Magistrado's Apprentice 
#&gt;
$allMailBoxUser = Get-Mailbox;
Foreach ($values in $allMailBoxUser)
{
$NewValues = Get-MailboxJunkEmailConfiguration -Identity $values.UserPrincipalName;
IF($NewValues.Enabled -eq $false) 
{ 
Set-MailboxJunkEmailConfiguration -Identity $values.UserPrincipalName $true;
echo $NewValues | Select Identity, Enabled; 
} #End-Of-IfStatement
 } #End-Of-ForeachStatement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f3ca65b-a23e-bae6-ba7e-c18f4f1991b0
* Version Independent ID: e544ddb9-f665-b435-450a-f16d01930260
* Content: [How to reduce spam email in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/reduce-spam-email#feedback)
* Content Source: [SecurityCompliance/reduce-spam-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/reduce-spam-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by BeginnersMindzet** [comment]
**NOTE**
Set-MailboxJunkEmailConfiguration -Identity $values.UserPrincipalName $true SHOULD BE : 

Set-MailboxJunkEmailConfiguration -Identity $values.UserPrincipalName -Enabled $true;

**Comment by scanum** [comment]
@officedocsbot assign @scanum 

@BeginnersMindzet Thanks for submitting feedback, will get this investigated.

**Comment by BeginnersMindzet** [comment]
Thanks!

**Comment by lindspea** [comment]
@BeginnersMindzet Thank you for reaching out and helping improve MS Docs.  Are you suggesting just changing the wording as per your note above?

**Comment by scanum** [comment]
@BeginnersMindzet Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
