### ISSUE TITLE
Mailbox intelligence based impersonation protection

### ISSUE THREAD

**Issue by AzureGuineaPig** [MicrosoftDocs/OfficeDocs-o365seccomp#623]
A new option called "Enable mailbox intelligence based impersonation protection?" is now available in the Mailbox Intelligence &gt; Impersonation Policy settings.  Additionally, there is a new setting within Mailbox Intelligence to apply an action "If email is sent by an impersonated user" Can you you share some details about these new features, and how this action relates to already existing "If email is sent by an impersonated user" setting in the Actions section? It seems these policy settings are similar, it would be good to understand the precedence of each and when these actions would apply.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies#feedback)
* Content Source: [SecurityCompliance/set-up-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@officedocsbot assign @scanum 
@AzureGuineaPig Hi, thanks for submitting feedback. I will get this investigated.

**Comment by PHITDept** [comment]
what did you find when you investigated?

**Comment by lindspea** [comment]
@PHITDept @AzureGuineaPig this issue is still under investigation. Thank you for your patience. I'll revert soonest with some clarifications. @MSFTTracyP

**Comment by scanum** [comment]
@AzureGuineaPig Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocbot close

**Comment by AzureGuineaPig** [comment]
@lindspea @scanum, thank you for sharing the link, however it doesn't appear to be updated to reflect the mailbox intelligence "impersonation protection" feature and has no mention of this new functionality, so my question still remains valid.  I'll pose the question on the forum on that page and include some screenshots, and hopefully someone can chime in there.
