### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Toasterlabs** [MicrosoftDocs/OfficeDocs-o365seccomp#624]
https://ome-advanced-message-encryption.md/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e8c7180-4b5f-37eb-32b8-c87512ce0820
* Version Independent ID: 33c43b5c-b035-8c8b-7e59-a38492924cf3
* Content: [Office 365 Message Encryption](https://docs.microsoft.com/en-us/office365/securitycompliance/ome#feedback)
* Content Source: [SecurityCompliance/ome.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@officedocsbot assign @scanum 

@Toasterlabs Thank you for submitting feedback. We are currently investigating this.

**Comment by Reeced40** [comment]
@Toasterlabs Thanks for reaching out, I'll replace the link soonest.

**Comment by KCCross** [comment]
Fixed. Thanks!
