### ISSUE TITLE
User reported message report

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#626]
This needs some clarification on expectations and what it should indicate, initial response from end users suggest it is unclear as to what to expect from it

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcff63fb-157a-4657-2123-15ce646cd0a8
* Version Independent ID: 2f037070-e3d5-f765-fb7a-b125ff0da981
* Content: [View email security reports in the Security & Compliance Center](https://docs.microsoft.com/en-gb/office365/securitycompliance/view-email-security-reports?redirectSourcePath=%252farticle%252f3a137e28-1174-42d5-99af-f18868b43e86#user-reported-messages-report)
* Content Source: [SecurityCompliance/view-email-security-reports.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/view-email-security-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@aldoug Thanks for submitting feedback. We are investigating this.

@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @aldoug how are you? Hope you are doing great.
Thanks for your feedback, could you kindly clarify your comment? Do you expect a change in product behavior or this documentation? If you need to suggest a change in the product, I would encourage you to visit here https://office365.uservoice.com/
But if you think that a change in documentation is needed, please clarify me what you expect.

Thank you

**Comment by aldoug** [comment]
Can you give me a link as to which request it was? Got a fair few open…

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 09:00 - 18:00
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by get-itips** [comment]
@aldoug  You should have the link in all github's notifications about this, but, here it is https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/626

**Comment by aldoug** [comment]
I see, it was in response to this

"Details are available for each message, including the delivery reason, such a spam policy exception or mail flow rule configured for your organization. To view details, select an item in the user-reports list, and then view the information on the Summary and Details tabs."

It feels we should list the possible values, and what they indicate

**Comment by denisebmsft** [comment]
@aldoug thank you very much for the feedback. I have added this as a work item in my queue, but the content update is a few weeks out. I am going to close this issue for now, but I won't lose track of the work for this. Thanks again!
