### ISSUE TITLE
Turning off user notifications generates

### ISSUE THREAD

**Issue by parabolic123** [MicrosoftDocs/OfficeDocs-o365seccomp#627]
Not sure if this is an isolated incidence or not, but creating a DLP email policy to block sensitive information being sent externally consistently generates an error similar to below if you have the user notifications set to disabled (data annonymised).

Request: /api/policy?policyType=Dlp Status code: 500 Exception message: {"Message":"Missing parameter: \u0027NotifyUser\u0027. Use of \u0027BlockAccessScope PerUser\u0027 requires -BlockAccess $true -AccessScope NotInOrganization -NotifyUser -NotifyAllowOverride parameters.","DiagnosticContext":"{Version:17.00.3024.002,Environment:WEUPROD,DeploymentId:ee708620397741d999472a4b622e9d84,InstanceId:WebRole_IN_1,SID:928a109a-0f25-4ddc-ad85-b6d9357604a8,CID:819aac95-bd53-421c-ae4a-6c9ea6be8761}","Time":"2019-05-07T11:02:53.9340604Z","ExceptionType":"Microsoft.Exchange.PswsClient.PswsException"} Diagnostic information: **{Version:17.00.3024.002,Environment:WEUPROD,DeploymentId:ee608620397741d999472a4b622e9d84,InstanceId:WebRole_IN_1,SID:858a109a-0f25-4ddc-ad85-b6d9357604a8,CID:d8c4d369-96b0-4413-9397-454b666a9c80} Time: 2019-05-07T11:02:53.768Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12efdace-f4c6-fbc5-47f5-d945b2479de1
* Version Independent ID: f792284f-6b6f-f75c-60ec-7848c89c9bf8
* Content: [Send email notifications and show policy tips for DLP policies](https://docs.microsoft.com/en-us/office365/securitycompliance/use-notifications-and-policy-tips)
* Content Source: [SecurityCompliance/use-notifications-and-policy-tips.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@parabolic123 Thanks for submitting feedback. We are investigating this.

@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @parabolic123 
Thanks for your feedback.
I could reproduce, based on your input, the error you receive. I did not receive an error when enabling notifications to the end user. Although this issue resource is specifically for issues in documentation, it seems that this might be temporary or the portal is having some trouble, so I please encourage you to visit https://support.office.com/home/contact to raise the issue there.
Thank You!

**Comment by scanum** [comment]
@parabolic123 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
