### ISSUE TITLE
DLP Policy configuration blocking share of a document with Highly confidential label

### ISSUE THREAD

**Issue by kapilmehtagit** [MicrosoftDocs/OfficeDocs-o365seccomp#630]
The DLP policy configuration in the page does not address the blocking of share configuration for Highly Confidential label. It is almost identical to that for the Sensitive label, which only shows a warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fce61-99c1-279d-9978-7e59e445fb84
* Version Independent ID: 77c05a43-ff13-c240-4de7-a5d5d47ed2cb
* Content: [Protect SharePoint Online files with retention labels and DLP](https://docs.microsoft.com/en-us/office365/securitycompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp#feedback)
* Content Source: [SecurityCompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by scanum** [comment]
@kapilmehtagit Thanks for submitting feedback. We are investigating this.

@officedocsbot assign @scanum

**Comment by JoeDavies-MSFT** [comment]
@kapilmehtagit This has been corrected for the highly-sensitive DLP policy. Thanks for letting us know.
