### ISSUE TITLE
Unable to setup new OME based on this documentation

### ISSUE THREAD

**Issue by Eric-VF** [MicrosoftDocs/OfficeDocs-o365seccomp#631]
i just setup a tenant to use OME from scratch and by following this documentation did not really help me. Enabling AzureRMSLicensingEnabled is not enough. I had to add the licensing location manually and to do that it takes more couple of steps. After that, i then had to enable InternalLicensingEnabled and ClientAccessServerEnabled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12629dc8-4ce5-f4f9-dc32-8356eb357f33
* Version Independent ID: 877bf185-bd2f-c546-933e-a69b660737a9
* Content: [Set up new Office 365 Message Encryption capabilities](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-new-message-encryption-capabilities#feedback)
* Content Source: [SecurityCompliance/set-up-new-message-encryption-capabilities.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-new-message-encryption-capabilities.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@Eric-VF  Thank you for submitting feedback. We are currently investigating this.

 @officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
@Eric-VF Hello and thank you for bringing this issue up.  Would you be able to describe your set up and describe in detail the steps you took.  This would help not only help me better understand the process you took but also what necessary steps could be taken to update the documentation accordingly.  Thanks!

**Comment by scanum** [comment]
@Eric-VF Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
