### ISSUE TITLE
The video misses a key point

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#635]
Messages that are Bcc'd as outbound spam should be submitted as false-positives in order for any action to be taken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb11c0e-64ba-029f-5090-37523f41073a
* Version Independent ID: f5bde7e6-5a26-b73f-fbbd-c9ed460d843d
* Content: [Configure the outbound spam policy](https://docs.microsoft.com/en-us/office365/SecurityCompliance/configure-the-outbound-spam-policy)
* Content Source: [SecurityCompliance/configure-the-outbound-spam-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by aldoug** [comment]
If the video cannot be changed, this action should be added to the page

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
