### ISSUE TITLE
O365 E3 Subscriptions

### ISSUE THREAD

**Issue by Archehandoro** [MicrosoftDocs/OfficeDocs-o365seccomp#636]
According to our portal in protection.office.com E3 subscriptions are also entitled to use 365 Cloud App Security at not extra cost. Can you confirm if that's the case and update the article if necessary, please?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a128057-1ddd-f0f4-f8f4-87c1bcd382fe
* Version Independent ID: 57fe6ac3-b5e2-f491-33a4-65055f940e84
* Content: [Overview of Office 365 Cloud App Security](https://docs.microsoft.com/en-gb/office365/securitycompliance/office-365-cas-overview?redirectSourcePath=%252farticle%252f81f0ee9a-9645-45ab-ba56-de9cbccab475)
* Content Source: [SecurityCompliance/office-365-cas-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-cas-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@Archehandoro Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by denisebmsft** [comment]
Hello @Archehandoro and @scanum. I have doublechecked this and can confirm that Office 365 E5 is required. I'm not sure why it's showing up in your Office 365 E3 subscription, @Archehandoro, as it's supposed to be included in Office 365 E5. You might need to reach out to support to confirm your plan offerings.

For reference, here's a page that describes the differences between E3 and E5: [https://www.microsoft.com/microsoft-365/business/compare-more-office-365-for-business-plans](https://www.microsoft.com/microsoft-365/business/compare-more-office-365-for-business-plans).

Thank you so much for raising this question. I'm going to close this issue out, but please let us know if you have further questions.
