### ISSUE TITLE
Minimum permissions

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#637]
Permissions required to work with emails of other users and files are not only Global Administrator but also Security Administrator granted in SCC. Please correct the article and check if there are no other SCC roles that grant access to Quarantine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de340d87-f658-2c76-c99a-c7a87be7755a
* Version Independent ID: 1ceac9b2-1e6f-7f13-0d32-0fcc92d87244
* Content: [Manage quarantined messages and files as an administrator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/manage-quarantined-messages-and-files#feedback)
* Content Source: [SecurityCompliance/manage-quarantined-messages-and-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by weigh2tall** [comment]
Any chance you could create a permission level that allows non-GA's the ability to release for another person?

**Comment by mohan1921** [comment]
it is not security admin. it is the Transport-Hygiene role that is required for managing quarantine. please update this as this is confusing customers.

**Comment by scanum** [comment]
@TokyoScarab Could this also be updated?

**Comment by chrisda** [comment]
OK. Done.

Closing
