### ISSUE TITLE
No documentation on finer query details for the management log

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/OfficeDocs-o365seccomp#639]
I'm working on a solution to import and run analytics/notifications on certain events in the office 365 management activity log.  The linked api reference documentation only seems to cover searching for all audit events by date range, leading to very long and expensive recursive requests to get all audit data from the entire date range even when it contains no desired events.  How can I perform a query filtered by date, type, operation, and/or user with the office 365 management activity API?  Something similar to the functionality exposed by search-unifiedauditlog, but which can be performed by a registered application or flow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jordanmills Unfortunately, what you want to do isn't possible. From  
[Troubleshooting the Office 365 Management Activity API](https://docs.microsoft.com/en-us/office/office-365-management-api/troubleshooting-the-office-365-management-activity-api):

**Can I query the Management Activity API for a particular event ID or RecordType or other properties in the content blob?**

No. Don’t think of the data available through the Management Activity API as being a “log” in the traditional sense. Rather, think of it as a dump of event details. It’s up to you to gather all those event details, store and index them locally, and then implement your own query logic, by using either a custom application or a third-party tool.
