### ISSUE TITLE
Incorrect Area assigned in "Beyond" section

### ISSUE THREAD

**Issue by weeyeh** [MicrosoftDocs/OfficeDocs-o365seccomp#640]
"Information Protection" and "Identity and Access Management" assignment in "Beyond" section is reversed

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e904dc-936d-dcf4-3601-69889493a612
* Version Independent ID: 86d60d59-0217-7ff1-851f-694247236054
* Content: [Office 365 security roadmap - Top priorities for the first 30 days, 90 days, and beyond](https://docs.microsoft.com/en-sg/office365/securitycompliance/security-roadmap?redirectSourcePath=%252fen-us%252farticle%252foffice-365-security-roadmap-top-priorities-for-the-first-30-days-90-days-and-beyond-28c86a1c-e4dd-4aad-a2a6-c768a21cb352#feedback)
* Content Source: [SecurityCompliance/security-roadmap.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/security-roadmap.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by scanum** [comment]
@weeyeh Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by BrendaCarter** [comment]
This is fixed. Thank you for letting us know!
