### ISSUE TITLE
Quarantine differences

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#642]
Should be updated to note that Phish messages and Transport Rule quarantined messages are sent to admin quarantine as opposed to end user quarantine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bbdbf77-5e6c-7629-d38f-9bb66e69230e
* Version Independent ID: e9285790-bd63-a512-2223-e411d9d51c99
* Content: [Quarantine email messages in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/quarantine-email-messages)
* Content Source: [SecurityCompliance/quarantine-email-messages.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/quarantine-email-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
Updated topic as described. Closing
