### ISSUE TITLE
'Bad outbound sender' cannot send emails internally

### ISSUE THREAD

**Issue by mildh** [MicrosoftDocs/OfficeDocs-o365seccomp#643]
If a user continuously sends emails from Office 365 that are classified as spam, they will be restricted from sending any more messages outbound.
Your message couldn't be delivered because you weren't recognized as a valid sender. The most common reason for this is that your email address is suspected of sending spam and it's no longer allowed to send messages outside of your organization. Contact your email admin for assistance. Remote Server returned '550 5.1.8 Access denied, bad outbound sender'

However, user capabilities to send emails are completely restricted and they cannot send both internal and external emails.
NDR verbiage is also misleading, it should specify that users emails capabilities are completely restricted rather than incorrect "it's no longer allowed to send messages outside of your organization."

**Comment by scanum** [comment]
@mildh Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@mildh thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
