### ISSUE TITLE
Exaples are not useful.  Need something besides basic auth.

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/OfficeDocs-o365seccomp#644]
Per MS recommendation and general good sense, basic auth is disabled on many (most?) tenants.  Examples should include an oauth2 token request and required resource/activity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b234b20-917f-643d-f9d4-621a41738169
* Version Independent ID: e983bbcf-0b53-4d60-0aae-2f8a9a558a2e
* Content: [Automate event-driven retention](https://docs.microsoft.com/en-us/office365/securitycompliance/automate-event-driven-retention)
* Content Source: [SecurityCompliance/automate-event-driven-retention.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/automate-event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@jordanmills - Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by stephow-MSFT** [comment]
@Manisha Advani<mailto:manishac@microsoft.com>

Hi Manisha, your article received this comment below via GitHub.

Is this something you should/can update in the article?

Thanks,
Stephen

**Comment by robertoyg** [comment]
At this time there is no option other than basic auth for these APIs for non-interactive applications, I think the MS team is working on new APIs that will allow OAuth authentication to these APIs.
