### ISSUE TITLE
Isn't Threat Explorer included in ATP P1 as well?

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#645]
Isn't Threat Explorer included in ATP P1 as well but without "All email" view and URL filters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7a592b-f888-32e7-8226-484ddc20acc4
* Version Independent ID: d97a1c36-5d8d-53f9-262b-b715d96dc330
* Content: [Use Threat Explorer in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/use-explorer-in-security-and-compliance)
* Content Source: [SecurityCompliance/use-explorer-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-explorer-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by denisebmsft** [comment]
Hello @scanum, @pawp81, and all! We have updated the content about Threat Explorer to include information about real-time reports (which is turning into real-time detections) and details about Explorer for ATP Plan 2 and real-time reports for ATP Plan 1. I hope this answers your questions.

**Comment by pawp81** [comment]
I checked the article but I don't see any mention in it about ATP P1. Could you please check if article got updated?
