### ISSUE TITLE
How to identify the type of hold placed on an Exchange Online mailbox

### ISSUE THREAD

**Issue by StaceyLC** [MicrosoftDocs/OfficeDocs-o365seccomp#647]
Hi team - does it make sense to add a link to "How to identify the type of hold placed on an Exchange Online mailbox" (https://docs.microsoft.com/en-us/office365/securitycompliance/identify-a-hold-on-an-exchange-online-mailbox) to this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
I don’t think so – seems a little random and very specific to Exchange.

**Comment by StaceyLC** [comment]
The Overview article mentions retention, eDiscovery, and litigation holds, and we get the occasional question about how to determine what kind of hold is applied. I'll bookmark both articles for my reference. Thanks for reviewing!

**Comment by scanum** [comment]
@StaceyLC Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by michevnew** [comment]
The link is useful, and the same type of documentation should be added to this article for other resources (Groups, Teams, SPO sites, etc). Not to mention you need to describe the full lifecycle of policies, including deleting them.

**Comment by stephow-MSFT** [comment]
We've added a section on releasing a hold -

https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies#releasing-a-retention-policy

The  other link is very specific to Exchange and I'm not sure there are parallel features for other resources.
