### ISSUE TITLE
Several URLs/URI is outdated

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftDocs/OfficeDocs-o365seccomp#649]
Several URLs/URI is outdated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 627e8aea-9d5d-aef0-08d1-a7965fc26521
* Version Independent ID: 656a6bef-af83-36af-73d3-358afcb8843c
* Content: [Overview of Office 365 Information Protection for GDPR](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-info-protection-for-gdpr-overview#feedback)
* Content Source: [SecurityCompliance/office-365-info-protection-for-gdpr-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-info-protection-for-gdpr-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by scanum** [comment]
@rramoscabral Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@rramoscabral Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
