### ISSUE TITLE
Conditional Access MFA Support

### ISSUE THREAD

**Issue by philkloose** [MicrosoftDocs/OfficeDocs-o365seccomp#651]
Is there a timeline for when we'll be able to access this tool using Conditional Access MFA instead of the Office 365 MFA?  I just spoke with support and they claimed that according to internal documentation (that they weren't allowed to share with me) that I could fearlessly enable Office 365 MFA on my account (which already has Conditional Access MFA enabled/configured) just to access the tool and then disable it if I wanted.  This sounds reckless as well as a great way to possibly lock myself out of my account or at the very least break my Conditional Access configuration, so I shall wait.

When might we see this Conditional Access MFA support for the Attack Simulator tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@philkloose Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by VLG17** [comment]
@philkloose What do you mean with "Conditional Access MFA instead of the Office 365 MFA"? Do you mean creating a conditional access policy requiring one to have MFA enabled? That will work and the article states that:

"Multi-factor authentication/Conditional Access is turned on, for at least the Office 365 global administrator account and security administrators. (Ideally, multi-factor authentication/conditional access is turned on for all users in your organization.)"

**Comment by antrevino** [comment]
@VLG17 I suspect that @philkloose may be referring to triggering MFA using a Custom Control (Third-party MFA - not Azure MFA) which can *ONLY* be done by setting up a conditional access policy to trigger a custom control that'll direct the MFA prompt to the third-party provider. I have this set up on my lab tenant and do not have the ability to use the attack simulator. I also need to know when conditional access will *actually* be supported for the Attack Simulator. This appears to be a growing trend is the new enterprise security features -- they only work with Azure MFA. Can Microsoft provide clarification?

**Comment by scanum** [comment]
@VLG17

**Comment by denisebmsft** [comment]
Hello! Just FYI that I am looking into this and will post an update here soon.

**Comment by denisebmsft** [comment]
Hello, everyone! Although I am going to close this issue out, I have a work item in my queue to update the Attack Simulator content. The updates will address your questions about MFA. So please know that even though I'm closing the issue, this isn't off my radar.
