### ISSUE TITLE
Max value for AuditLogAgeLimit

### ISSUE THREAD

**Issue by dgorgone** [MicrosoftDocs/OfficeDocs-o365seccomp#652]
What is the maximum value for AuditLogAgeLimit?  How many days can audit logs for a mailbox be stored?

**Comment by scanum** [comment]
@dgorgone thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
