### ISSUE TITLE
Preservation Hold library

### ISSUE THREAD

**Issue by siladas** [MicrosoftDocs/OfficeDocs-o365seccomp#653]
Hi all
Just working on creating retention labels and grouping them by different policies, though I wonder if the documentation is right
I'm using this  doc: https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies

It says
"
After a retention policy is assigned to a OneDrive account or SharePoint site, content can follow one of two paths:

If the content is modified or deleted during the retention period, **a copy of the original content as it existed when the retention policy was assigned is created in the Preservation Hold library**. There, a timer job runs periodically and identifies items whose retention period has expired, and these items are permanently deleted within seven days of the end of the retention period.
" 
Although, once the **document is labelled, it can no longer be deleted**. I wonder if the document is right.
I have searched everywhere and have found no clear explanation of why that happens. unless the document is wrong and the UI on SCC is wrong too, there must be something that I'm missing in my configuration

Appreciate the help

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies#feedback)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
The distinction is, once a doc is labeled, it cannot be *permanently* deleted. Retention is invisible to the end user. They can delete a doc and it disappears from their view, but it's still retained in the Preservation Hold library.

**Comment by siladas** [comment]
Hi Stephen
thanks for replying on this
Maybe I didn't explain it right - I understand and expect that a labelled document with retention time set to 6 years will not be permanently deleted.
Although, when you say "Retention is invisible to the end user. They can delete a doc and it disappears from their view, but it's still retained in the Preservation Hold library" I don't see that working on SharePoint Online and OneDrive

you can check the screenshot here [https://1drv.ms/f/s!Atx6QAHPaDkGhfs1lxuu3A8j3AiRjQ](url)

**Comment by stephow-MSFT** [comment]
If a retention label includes the option to mark the content as a record, the file can't be deleted at all in SharePoint and OneDrive -

https://docs.microsoft.com/en-us/office365/securitycompliance/labels#records-cant-be-deleted

Does your label use that option?

**Comment by siladas** [comment]
No, it does not.
I've uploaded a new screenshot that shows the retention 
https://1drv.ms/f/s!Atx6QAHPaDkGhfs1lxuu3A8j3AiRjQ

**Comment by stephow-MSFT** [comment]
This screenshot suggests the label marks the content as a record -

https://onedrive.live.com/?authkey=%21AJcbrtwPI9wIkY0&cid=063968CF01407ADC&id=63968CF01407ADC%2197718&parId=63968CF01407ADC%2197717&o=OneUp

Instead of checking settings in File Plan, go up to the Labels page > Retention labels tab, find the label, and check the settings there.

**Comment by siladas** [comment]
Yeah, I worked with labels last year and that was the warning I would get when the document was set as a record
Although, this retention label I've created now does not set it as a record 

Here's the link of the settings on the Labels page
https://onedrive.live.com/?authkey=%21AJcbrtwPI9wIkY0&cid=063968CF01407ADC&id=63968CF01407ADC%2197722&parId=63968CF01407ADC%2197717&o=OneUp

**Comment by siladas** [comment]
Just one thing I didn't mention
This tenant where I am testing the policies is a tenant created from demos.mocrosoft.com, using my MPN subscription - wonder if this type of tenant would make a difference ?

**Comment by stephow-MSFT** [comment]
At this point, I can say the documentation you quote above is accurate. I'm not able to troubleshoot your scenario - suggest you open a support ticket. But I welcome any other feedback on the documentation, if there's some gotcha we should make more clear.

**Comment by siladas** [comment]
Sure, no problem. I'm raising a ticket with the support team to understand what's happening 
Thanks for your comments - very appreciated
