### ISSUE TITLE
SharePoint Malware Detection - Inaccurate information

### ISSUE THREAD

**Issue by eBentl** [MicrosoftDocs/OfficeDocs-o365seccomp#654]
Article states that SharePoint Online and OneDrive for Business prohibit the upload of certain files types, this is no longer the case as indicated in the linked page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2db4e9b-cd96-96b5-08b8-d2f61db73f75
* Version Independent ID: 6b41374b-20d5-614c-9e33-b2ff87234796
* Content: [Office 365 Malware and Ransomware Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-malware-and-ransomware-protection#feedback)
* Content Source: [SecurityCompliance/office-365-malware-and-ransomware-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-malware-and-ransomware-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@eBentl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@eBentl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
