### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by PascalRascal7** [MicrosoftDocs/OfficeDocs-o365seccomp#658]
The link on this page for "Plan for Office 365 security and information protection capabilities" leads to a page that says "Sorry, the page you’re looking for can’t be found."  The link is https://support.office.com/article/3d4ac4a1-3920-4ff9-918f-011f3ce60408  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a77f761-18fd-6f44-462b-31a65bb31840
* Version Independent ID: fa2614d7-94a6-ecac-44d6-266c356c3e0c
* Content: [Encryption in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/encryption#encryption-for-data-at-rest-and-data-in-transit)
* Content Source: [SecurityCompliance/encryption.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@PascalRascal7 - Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@PascalRascal7 Thank you for your feedback and helping improve MS Docs. I'll have the link fixed shortly.

**Comment by scanum** [comment]
@PascalRascal7 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
