### ISSUE TITLE
Document Missing Key Component

### ISSUE THREAD

**Issue by chgary1219** [MicrosoftDocs/OfficeDocs-o365seccomp#66]
A policy with specific inclusions or exclusions 

You can also apply a DLP policy to specific users. To do so, toggle the Status of that location on, and then use the links to include or exclude specific users or locations.

However, note that the following limits exist for a DLP policy that includes or excludes over 1,000 specific users:

Such a DLP policy can contain no more than 1,000 mailboxes and 100 sites.A tenant can contain no more than 1,000 such DLP policies.Although these limits exist, understand that you can get over these limits by applying either an org-wide policy or a policy that applies to entire locations.

Please reference counterpart article https://support.office.com/en-gb/article/create-a-dlp-policy-from-a-template-59414438-99f5-488b-975c-5023f2254369 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39476d87-2474-330d-22f0-3328d3e4302c
* Version Independent ID: 021a74bd-d060-38ce-e99a-af9693aa3867
* Content: [Create a DLP policy from a template](https://docs.microsoft.com/en-gb/office365/securitycompliance/create-a-dlp-policy-from-a-template)
* Content Source: [SecurityCompliance/create-a-dlp-policy-from-a-template.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-a-dlp-policy-from-a-template.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by denisebmsft** [comment]
Thank you for the feedback, @chgary1219. We will look into this.

**Comment by AndreaBarr** [comment]
@chgary1219 Thank you for this feedback

I will get this over to the o365seccomp team for investigation and updating. 

I was able to get this into the backlog for the O365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by denisebmsft** [comment]
Hello @chgary1219 and @scanum. Thank you for the feedback (and help!). I think the original issue is addressed in the content, especially in the section pasted below, so I am going to close this for now. Please let me know if you still have questions.

"To include or exclude an entire location such as all Exchange email or all OneDrive accounts, switch the Status of that location on or off.
To include only specific SharePoint sites or OneDrive for Business accounts, switch the Status to on, and then click the links under Include to choose specific sites or accounts. When you apply a policy to a site, the rules configured in that policy are automatically applied to all subsites of that site."
