### ISSUE TITLE
Default Alert Policies

### ISSUE THREAD

**Issue by ernelso** [MicrosoftDocs/OfficeDocs-o365seccomp#661]
The list and descriptions for default alert policies is missing some and needs updating. (for example: The alert policy "Suspicious email sending patterns detected" is missing, etc...) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e607177-4e5b-69af-5408-caa6337bbd0e
* Version Independent ID: c82bbeaa-9df1-c070-644b-a666406464b5
* Content: [Alert policies in the security and compliance center](https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies#feedback)
* Content Source: [SecurityCompliance/alert-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@ernelso Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by markjjo** [comment]
@ernelso @scanum A description for "Suspicious email sending patterns detected" has been added to the topic. The other alert policies that aren't yet documented are in preview; descriptions for these will be added when the product group releases them to GA. @ernelso as you are internal MSFT, in the future, please contact me (or other writers) directly about documentation issues.

https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies#default-alert-policies
