### ISSUE TITLE
Delivery fails on reporting email address

### ISSUE THREAD

**Issue by DeanHougen** [MicrosoftDocs/OfficeDocs-o365seccomp#666]
The email address for reporting apparently fails regularly.

"----- The following addresses had permanent fatal errors ----- <abuse@messaging.microsoft.com>

   ----- Transcript of session follows ----- <abuse@messaging.microsoft.com>... Deferred: Connection timed out with messaging.microsoft.com.
Message could not be delivered for 5 days Message will be deleted from queue"

**Comment by scanum** [comment]
@DeanHougen thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot close
