### ISSUE TITLE
Protect button in OWA

### ISSUE THREAD

**Issue by ernelso** [MicrosoftDocs/OfficeDocs-o365seccomp#668]
This verbiage (see below) is no longer accurate and up to date, since we rolled out the Encrypt buttons in OWA and Outlook "The Protect button in Outlook on the web is disabled when you set up OME."  The Protect button is now the Encrypt button and it doesn't appear to be disabled by default...(at a minimum, not when you already had the prior OME v1 enabled).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0688888b-5379-009a-d325-49709fe8f4a8
* Version Independent ID: 2234c4fd-9423-8e63-7544-c2c8a654cf29
* Content: [Manage Office 365 Message Encryption](https://docs.microsoft.com/en-us/office365/securitycompliance/manage-office-365-message-encryption#enable-service-side-decryption-of-email-messages-for-ios-mail-app-users)
* Content Source: [SecurityCompliance/manage-office-365-message-encryption.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/manage-office-365-message-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@ernelso Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@ernelso Thank you for your feedback. We have made the necessary changes to the Doc via PR https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/pull/694

**Comment by scanum** [comment]
@ernelso Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
