### ISSUE TITLE
Role title repeated

### ISSUE THREAD

**Issue by sqlsolver** [MicrosoftDocs/OfficeDocs-o365seccomp#670]
In this section:
https://docs.microsoft.com/en-us/office365/securitycompliance/ediscovery-cases#step-1-assign-ediscovery-permissions-to-potential-case-members the eDiscovery Manager role is listed twice with different permissions under each description. Clarify secondary role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98d1f72-c381-3056-c1c4-7e54a9ab05af
* Version Independent ID: f5771dac-209a-433b-1967-a6ef3118eec6
* Content: [eDiscovery cases in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/ediscovery-cases)
* Content Source: [SecurityCompliance/ediscovery-cases.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ediscovery-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@sqlsolver Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by markjjo** [comment]
@sqlsolver @scanum - Unfortunately, it is confusing to have the same name for the role group and for the sub-group. As per the documentation, the "eDiscovery Manager" and "eDiscovery Administrator" are sub-groups of the role group. The primary different between these two subgroups is that members of the eDiscovery Manager subgroup can only access cases they are a member of. Members of the eDiscovery Administrator subgroup can access all cases in the organization. Note on the eDiscovery Manager **role group** flyout page in UI that you can't add members to the "role group" - you can only add members to one of the subgroups.

![image](https://user-images.githubusercontent.com/36746813/58502948-7b68d700-813c-11e9-8dea-5965dee83a6a.png)

**Comment by sqlsolver** [comment]
Yes, thank you Mark. Still - I think the difference should be called out in
the manner you've just explained it in the documentation.

*Please visit www.sqlsolver.com <http://www.sqlsolver.com/>*
* <http://www.sqlsolver.com/>530-237-4SQL*
