### ISSUE TITLE
ListItemRecycled activity

### ISSUE THREAD

**Issue by yoinuma** [MicrosoftDocs/OfficeDocs-o365seccomp#671]
Audit log in the Security & Compliance Center now has a activity type of "ListItemRecycled" but it is not listed.
Please update the document.

**Comment by scanum** [comment]
@yoinuma Please reference document. Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@yoinuma We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
