### ISSUE TITLE
Feature not yet generally available

### ISSUE THREAD

**Issue by Justfyn** [MicrosoftDocs/OfficeDocs-o365seccomp#672]
Please add a note that the feature is still in roll out for general availability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b48decb0-39eb-38f5-9708-883fe6b4dc6f
* Version Independent ID: c474dfc8-d061-c4d5-31d1-45d8bb6c2f8e
* Content: [Unverified Sender](https://docs.microsoft.com/en-us/office365/securitycompliance/unverified-sender-feature)
* Content Source: [SecurityCompliance/unverified-sender-feature.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/unverified-sender-feature.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@Justfyn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@Justfyn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
