### ISSUE TITLE
Include more information about what URLs are allowed in the example for "contoso.com"

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/OfficeDocs-o365seccomp#673]
In the example, it lists "*contoso.com*" and indicates some sample URLs that would be exempt for it.  Please also clarify/include whether that would also exempt something like:
1. https://malware.com/contoso.com/login.php.  
2. https://badcontoso.com

If these workarounds are protected against, and these exemptions only look at the main URL only, please indicate this on the page somewhere for clarity.  If these workarounds are not protected against, please indicate on the page how you would only exempt URLs that are for contoso.com but not allow for the variances listed above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f466441b-e9f7-f7ce-ade9-ec78b879699c
* Version Independent ID: 57d4a26b-0f05-cb76-5e05-6077e88c9495
* Content: [Set up a custom do-not-rewrite URLs list using Office 365 ATP Safe Links](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp)
* Content Source: [SecurityCompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@aakash-shah Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @aakash-shah 
I did some tests and when I entered, for example "contoso.com" to the list of "do not rewrite", it was not the same as using 

` *contoso.com*`

so if I sent an email with http://badcontoso.com it was actually rewrited.

and if I used 
` *contoso.com*`
all urls that included contoso.com were actually not rewrited.

So I am calling @denisebmsft now to confirm this behavior, because I think we should correct the wording on this article.

**Comment by aakash-shah** [comment]
Thanks - that's what I've observed to date too.

**Comment by get-itips** [comment]
Hello @denisebmsft did  you have time to review this? thank you

**Comment by denisebmsft** [comment]
Hello @aakash-shah, @get-itips, and @scanum. I have updated the article to clarify the behavior. Thank you so much for raising these questions. We appreciate your feedback, as it helps us improve the documentation.

**Comment by aakash-shah** [comment]
Hello!  Thanks for posting that update!  We ended up not using ATP Safe Links, but I recall a different behavior when we tested this a few months ago:
In our case, whitelisting just "contoso.com" correctly allowed anything under contoso.com/subpath (I don't recall if I tested subdomains), but it correctly denied items like:
https://malware.com/contoso.com/login.php.
https://badcontoso.com

However based on the update to the page, it says that "contoso.com" "Allows recipients to visit a site like http://contoso.com but not subdomains or paths".  Unless something has changed since I last used it, can you please confirm whether this is still the case?  I still have a video I took documenting this as well as the configuration we used if that would help (it has private data so I can't post it publicly, but feel free to reach out and I can email/send it to you).
