### ISSUE TITLE
Inconsistent content on this page

### ISSUE THREAD

**Issue by dennisxu2019** [MicrosoftDocs/OfficeDocs-o365seccomp#674]
In the last paragraph of "Customer Key" section it mentioned Customer Key can be setup for Skype for Business. In the first paragraph it says customer key is currently available for Exchange Online, SharePoint Online, One Drive without mentioning Skype for Business. IF customer key do support skype for business then 1st paragraph need to be updated. Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f061b93c-1509-b989-754d-e41c9fd1be08
* Version Independent ID: ff3cce33-19a4-59f6-b7f4-7adeabaa8914
* Content: [Office 365 Service Encryption](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-service-encryption)
* Content Source: [SecurityCompliance/office-365-service-encryption.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-service-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@dennisxu2019 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @KCCross how are you? can you help us confirm is Customer Key was indeed released for SfB ? Could not find any news about that.
Thank you

**Comment by KCCross** [comment]
Customer Key covers everything in the Exchange mailbox, including Skype for Business messages. If it's missing from the opening paragraph, that's an oversight. It's mentioned throughout the rest of the document and in the FAQ.

**Comment by KCCross** [comment]
I can’t find the instance to which you refer. Customer Key covers everything in the Exchange mailbox which includes SfB messages.
