### ISSUE TITLE
how do I subscribe to future content update on this page? 

### ISSUE THREAD

**Issue by dennisxu2019** [MicrosoftDocs/OfficeDocs-o365seccomp#675]
Hello, is there a way to "watch" or "subscribe" to this page so if there is any future content update I can get an email notification? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a63ecb36-3201-687e-78cd-1f5453889644
* Version Independent ID: 54559940-a2fe-7dac-0b92-4a4ac569141b
* Content: [Office 365 Advanced Message Encryption](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-advanced-message-encryption)
* Content Source: [SecurityCompliance/ome-advanced-message-encryption.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-advanced-message-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@dennisxu2019 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@dennisxu2019 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
