### ISSUE TITLE
Connection Filtering and Connectors

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#676]
This should be referenced https://internal.support.services.microsoft.com/en-us/help/4052852/cannot-bypass-spam-filtering

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3368430-e303-8e6f-65d9-22b7e6c6c6b7
* Version Independent ID: 94dddc16-eb0a-b5c3-262b-c1712566e68e
* Content: [Configure the connection filter policy](https://docs.microsoft.com/en-us/office365/SecurityCompliance/configure-the-connection-filter-policy)
* Content Source: [SecurityCompliance/configure-the-connection-filter-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-the-connection-filter-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @aldoug how are you?
Can you kindly paste here the info you want to be included so I can review it?
The link is not working for me.
Thank you

**Comment by aldoug** [comment]
Mail can't bypass spam filtering when the sender's IP is added to the Client Allow List
Applies to: Exchange Online Protection
________________________________
Symptoms
________________________________
In Microsoft Exchange Online, you can add an IP address to the Client Allow List (based on the guidance in Configure the connection filter policy<https://technet.microsoft.com/en-us/library/jj200718(v=exchg.150).aspx>) so that email from that IP address assigned a Spam Confidence Level (SCL) rating of -1 and therefore not subject to spam filtering. However, in some circumstances, mail from that IP address is still filtered.
Microsoft Internal Support Information
Cause
________________________________
This issue can occur for the following reasons:
·         If the email message hits EOP front door server where connecting IP is in an on-premises IP based receive connector of any tenant within the same forest, IPV:CAL will be visible in the message headers based on Anti-spam message headers<https://technet.microsoft.com/en-us/library/dn205071(v=exchg.150).aspx>. However, the SCL:-1 verdict will not be applied, and the email message will be subject to spam scoring by the EOP Content Filter.
·         If the email message hits an EOP front door server that is not in the same forest as the tenant in which the IP address  was added to the Client Allow List, the IPV:CAL verdict will not be visible, and the email message will be subject to spam scoring by the EOP Content Filter.
Resolution
________________________________
Administrators can use an Exchange transport rule to set the spam confidence level to Bypass Spam Score by using the Sender's IP address is in the range condition. For more information, refer to Use mail flow rules to set the spam confidence level (SCL) in messages<https://technet.microsoft.com/en-us/library/dn798345(v=exchg.150).aspx>.


Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 09:00 - 18:00
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by get-itips** [comment]
Hello @MSFTTracyP I will rely on your call on this one, to decide if we, somehow, add this info from support services to the article.
thank you

**Comment by get-itips** [comment]
Hello @MSFTTracyP please we need your call on this as article author

**Comment by chrisda** [comment]
OK. Added.

Closing
