### ISSUE TITLE
Location of functionality

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#677]
Please add some information about where we go to use this functionality. I'm guessing its the new Compliance Center, but that is not stated anywhere so I'm not totally sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74f3656b-2967-4b91-86a0-fbecdcfb4169
* Version Independent ID: 60777b5f-c54e-3fc8-9dc6-12d6a218087a
* Content: [Records management in Microsoft 365](https://docs.microsoft.com/en-us/office365/securitycompliance/records-management)
* Content Source: [SecurityCompliance/records-management.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/records-management.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by cjkn** [comment]
So for each of the above, E5 is needed by all users in a tenant?

**Comment by get-itips** [comment]
Hello @deangross 
Thanks for your feedback.
As the article says, records management solutions supports several elements, if you follow the link for each one, you will find documented, where each of these elements are.
Thank you

**Comment by get-itips** [comment]
Hello @scanum I think we can close this one.

**Comment by stephow-MSFT** [comment]
Records management is a top-level node in the left nav of the Office 365 Security and Compliance Center. We are in the process of adding it to the Microsoft 365 compliance center, probably by end of year.
