### ISSUE TITLE
Third Party state reflects Score?

### ISSUE THREAD

**Issue by msandbu** [MicrosoftDocs/OfficeDocs-o365seccomp#679]
I've recently changes controlstateprofiles for all security scores to Third-Party but still after 48 hours the score is not updated on my tenant.  

According to the documentation "The score can also reflect when third-party solutions have addressed recommended improvement actions." is this still applicable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f13e79-166c-a063-ef70-dd4bd45ecc67
* Version Independent ID: d66d3771-8820-2a01-2757-400effef3dc1
* Content: [Microsoft Secure Score](https://docs.microsoft.com/en-us/office365/securitycompliance/microsoft-secure-score#feedback)
* Content Source: [SecurityCompliance/microsoft-secure-score.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/microsoft-secure-score.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by scanum** [comment]
@msandbuthank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
