### ISSUE TITLE
How to ensure that destructive process of virtual data has success.

### ISSUE THREAD

**Issue by angelionix99** [MicrosoftDocs/OfficeDocs-o365seccomp#683]
I wonder how MS office 365 ensure my personal files have been deleted and can not recover again.

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 78e4adce-0939-cea7-d5e5-51628d2712de
* Version Independent ID: e7a6ef98-26be-c9b9-e7d9-e82995650b6f
* Content: [Office 365 Data Destruction](https://docs.microsoft.com/th-th/office365/SecurityCompliance/office-365-data-destruction#feedback)
* Content Source: [SecurityCompliance/office-365-data-destruction.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-data-destruction.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@angelionix99 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
