### ISSUE TITLE
When does MS add, update, or remove Sensitive info types?

### ISSUE THREAD

**Issue by ryanwga** [MicrosoftDocs/OfficeDocs-o365seccomp#684]
Where do we as admins get notification when MS adds, updates, or removes "Sensitive info types"?  Also how often are they reviewed and updated?

Thanks,
Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401c22ca-51e6-82c5-6500-7320a6bb99a6
* Version Independent ID: 6c7dba02-0f25-9db2-742f-d12a60e32b26
* Content: [What the sensitive information types look for](https://docs.microsoft.com/en-us/office365/securitycompliance/what-the-sensitive-information-types-look-for#feedback)
* Content Source: [SecurityCompliance/what-the-sensitive-information-types-look-for.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@ryanwga thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
