### ISSUE TITLE
Link between service request and lockbox access request

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#687]
Is there any way for approver to identify which service request given lockbox access request is related with. Let's say that in the example in this article person who approves lockbox request would like to review the service request from step 2. Is there any easy way to identify such request from the lockbox access request? Is the lockbox request # (called reference number on request list) related to the service request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be441956-3ac9-2f3e-aa00-e97a194fe875
* Version Independent ID: 5006f4fd-0ac4-ac2a-2c8a-2c34988fe654
* Content: [Office 365 Customer Lockbox Requests](https://docs.microsoft.com/en-us/office365/securitycompliance/customer-lockbox-requests#auditing-customer-lockbox-requests)
* Content Source: [SecurityCompliance/customer-lockbox-requests.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@Larryngolog thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
