### ISSUE TITLE
Mail Flow Quarantine Notifications

### ISSUE THREAD

**Issue by msywulak** [MicrosoftDocs/OfficeDocs-o365seccomp#688]
From this doc: https://docs.microsoft.com/en-us/office365/securitycompliance/use-spam-notifications-to-release-and-report-quarantined-messages
"Messages that are quarantined because they matched a mail flow rule are not included in user quarantined messages. Only spam-quarantined messages are listed."

This doesn't really make sense functionality wise at all. Why can users see messages that Microsoft chooses to quarantine but not from admins using transport rules? Admins have the ability to quarantine for a reason why not have notifications just work for everything in it?

**Comment by scanum** [comment]
@msywulak Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @msywulak how are you?
This issue resource is specific to address issues in documentation, for feature requests, I need to kindly redirect you to https://office365.uservoice.com/
Thank you

**Comment by get-itips** [comment]
Hello @scanum please close this one. thanks

**Comment by scanum** [comment]
@msywulak Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
