### ISSUE TITLE
Permission question

### ISSUE THREAD

**Issue by c9777777** [MicrosoftDocs/OfficeDocs-o365seccomp#689]
Hi on here 

https://docs.microsoft.com/en-us/office365/securitycompliance/threat-explorer

On the permissions section it says “for the security and compliance center must have one of the following roles and in exchange online must have one of the following roles”

Is this saying a user needs both security reader role and view only recipients role in exchange online also? 

Do they need both a role in exchange online and the security and compliance center or only one in either or? 

So if a user is only assigned view only recipients in exchange online but no roles in the security and compliance center then they can’t access threat explorer, correct?

**Comment by scanum** [comment]
@c9777777 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@c9777777 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
