### ISSUE TITLE
DLP Policy not being enforced

### ISSUE THREAD

**Issue by angarcia30** [MicrosoftDocs/OfficeDocs-o365seccomp#692]
If previously created a transport rule utilizing DLP Policy then removed and re-created through O365 Security & Compliance, how long before I can see the new policy being enforced?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12efdace-f4c6-fbc5-47f5-d945b2479de1
* Version Independent ID: f792284f-6b6f-f75c-60ec-7848c89c9bf8
* Content: [Send email notifications and show policy tips for DLP policies](https://docs.microsoft.com/en-us/office365/securitycompliance/use-notifications-and-policy-tips#feedback)
* Content Source: [SecurityCompliance/use-notifications-and-policy-tips.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@angarcia30 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
