### ISSUE TITLE
 showing policy tips for only some conditions

### ISSUE THREAD

**Issue by johntchoi** [MicrosoftDocs/OfficeDocs-o365seccomp#699]
According to [this](https://docs.microsoft.com/en-us/office365/securitycompliance/use-notifications-and-policy-tips#outlook-2013-and-later-supports-showing-policy-tips-for-only-some-conditions) documentation Policy Tips are not supported if an email attachment could not be scanned or the scan did not complete.  In this circumstance is there a way for the end user to over ride the the policy?

**Comment by scanum** [comment]
@johntchoi thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
