### ISSUE TITLE
Even if you assign the Exchange Role Management role to the Exchange Administrators, it doesn't work

### ISSUE THREAD

**Issue by cmanuel83** [MicrosoftDocs/OfficeDocs-o365seccomp#700]
https://docs.microsoft.com/en-us/office365/securitycompliance/privileged-access-management-overview

If you are a different administrator than the global admin, then it doesn't work. Only Global admins can request access. I would like to apply this functionality to Exchange Administrators but it doesn't work because if you don't have Global Admin permission you cannot access the "Security & privacy" blade and therefore cannot access the Privileged Access section. Even if you assign the Exchange Role Management role to the Exchange Administrators, it doesn't work.
Regards.

**Comment by scanum** [comment]
@cmanuel83 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @cmanuel83 
Thanks for your feedback.
Currently there is a limitation to make the request by using the Admin UI, so you will have to make the administrator make the request using Powershell thru the New-ElevatedAccessRequest cmdlet using 
and the Exchange Online PowerShell Module .

More info https://docs.microsoft.com/es-es/office365/securitycompliance/privileged-access-management-configuration#step4

![image](https://user-images.githubusercontent.com/36666927/60749959-e76e0480-9f5e-11e9-8b33-0afe325ffc1f.png)

**Comment by cmanuel83** [comment]
Hello Andres

Thank you so much for the workaround.

Regards.

________________________________

**Comment by cmanuel83** [comment]
Thank you, Andres, for the information.
The workaround is requesting permission via PowerShell.
