### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by KimmoBergius** [MicrosoftDocs/OfficeDocs-o365seccomp#703]
This page leaves a lot of pre-defined functions undocumented, would it be possible to document them as well? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e152ecb-29cd-522c-9fed-5ecfa80099b6
* Version Independent ID: dd3c71b6-fdea-b49f-16e2-c81f8dc3a8d8
* Content: [What the DLP functions look for](https://docs.microsoft.com/en-us/office365/securitycompliance/what-the-dlp-functions-look-for#feedback)
* Content Source: [SecurityCompliance/what-the-dlp-functions-look-for.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/what-the-dlp-functions-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@KimmoBergius Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @KimmoBergius 
Thanks for your feedback, we appreciate it.
This page lists the **internal functions only**, for other type of functions, you have to see the link in the article [What the sensitive information types look for](https://docs.microsoft.com/en-us/office365/securitycompliance/what-the-sensitive-information-types-look-for)

Or are you referring to other internal functions? If so, can you name them so we can get this information from product team?

Thank you

**Comment by get-itips** [comment]
Hell @KimmoBergius did you have chance to see my comment?

**Comment by chrfox** [comment]
closing this thread, no responses from originator for over 90 days
