### ISSUE TITLE
Who needs ATP1/P2 license?

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#704]
It is not clear from the article who needs the ATP P1/P2 license. Is it protected user only, protected user+administrator or administrator only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7a592b-f888-32e7-8226-484ddc20acc4
* Version Independent ID: d97a1c36-5d8d-53f9-262b-b715d96dc330
* Content: [Threat Explorer (and real-time detections)](https://docs.microsoft.com/en-us/office365/securitycompliance/threat-explorer#required-licenses-and-permissions)
* Content Source: [SecurityCompliance/threat-explorer.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/threat-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @pawp81 

Thank you for reaching out!

Office 365 global administrators or security administrators can access Office 365 ATP features in the Security & Compliance Center at Threat Management > Policy.

So these administrators can define recipients or domains in your organization to be part of these policies. 

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by pawp81** [comment]
Thank you for the answer, but it doesn't address my concern. The article says that ATP P1/P2 license is needed, which is fine, but who needs it?  Is it protected user only, protected user+administrator or administrator only?

**Comment by sowjanya365** [comment]
Hi @pawp81 

Yes, It is only Administrators who needs it. Thank you.

**Comment by pawp81** [comment]
OK so maybe we can update the article approriately

**Comment by sowjanya365** [comment]
Hi @pawp81 

Kindly help us to understand where do you want us to update the article? Do you want us to correct anything which is incorrect?

Thank you.

**Comment by pawp81** [comment]
I would added to the "Required licenses and permissions" chapter. 
However, I am not sure if it is correct statement that only Administrator needs ATP P1/P2 to work with Threat Explorer.

**Comment by sowjanya365** [comment]
Hi @pawp81 

Thank you for sharing your views. We really appreciate it.

Required permissions and roles already listed on the article. And this article only relates to "Threat Explorer (and real-time detections)".

"To view and use Explorer or real-time detections, you must have appropriate permissions, such as those granted to a security administrator or security reader."

So we don't think it is necessary to add any additional statement to it. Thank you very much your contribution. Really appreciate it.

**Comment by pawp81** [comment]
I would like to disagree :-)
If only admins require ATP license, then in my opinion it is worth mentioning it, because it is not typical situation.

**Comment by sowjanya365** [comment]
Hi @pawp81 

I think there is some confusion around this article. Let me clarify. :)

ATP has policies and these policies can be assigned to any users. It can be done via admin portal > Security & Compliance Center at Threat Management > Policy.

And this can be done by either Office 365 Global Administrator OR Security Administrator OR Exchange Online Organization Management. By default these roles are entitled to assign policies to users.

For more information on roles and Where/how assigned, please see https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by pawp81** [comment]
Are we discussing the same article: https://docs.microsoft.com/en-us/office365/securitycompliance/threat-explorer. My feedback was related to the article describing Threat Explorer

**Comment by denisebmsft** [comment]
Hello @pawp81, @sowjanya365, @scanum, and everyone else. Threat Explorer shows information for all users who are licensed for ATP Plan 2. (Similarly, the real-time detections report shows information for all users who are licensed for ATP Plan 1.) Even though the permissions model requires a user to be global admin or security admin (as spelled out in the article), users need to be assigned licenses as well. The licenses ensure that users are protected by ATP policies and that detections for those users are included in the reports. I'll get an update in for this article ASAP to help clarify this.

**Comment by sowjanya365** [comment]
Thanks for the information, @denisebmsft ! Much appreciated!!! :)

**Comment by denisebmsft** [comment]
@sowjanya365 you are most welcome. I've updated the article, and the changes should be live now (or within moments). I'm closing this issue but please let us know if you have any other questions.
