### ISSUE TITLE
Enabling procedure for the organization has been changed

### ISSUE THREAD

**Issue by svetp** [MicrosoftDocs/OfficeDocs-o365seccomp#71]
I went through the step-by-step procedure to enable the add-in for my organization but it looks like it has been changed after step 10. Instead of going to EAC to enabled it, the add-in appears in Services & add-ins of Microsoft 365 admin center where it can be enabled for everyone or a specific group as shown in step 14. 

It does not appear in the add-ins of EAC. And, it is not available in the users' Outlook

Thanks,

Svet 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62304805-117a-0e04-038b-a42a89e12162
* Version Independent ID: 7c12ba44-3c56-7607-7e63-84b0073a25df
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-the-report-message-add-in)
* Content Source: [SecurityCompliance/enable-the-report-message-add-in.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-the-report-message-add-in.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AndreaBarr** [comment]
@svetp Thank you for this feedback

I agree this should be updated in the article. 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by weigh2tall** [comment]
I think it would be helpful to include the old method for historical record.  I think I enabled it using the old workflow, and even though the add in is visible for our employees, it is not listed under the "Services & Add-ins" pane.
