### ISSUE TITLE
Name too long on created Incidents

### ISSUE THREAD

**Issue by dajdin** [MicrosoftDocs/OfficeDocs-o365seccomp#712]
Incidents that are created after a delete action is approved have names that are too long. Trying to edit status of an incident throws an error "Please complete all required fields" which has nothing to do with the length of the Incident name.

**Comment by scanum** [comment]
@dajdin thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
