### ISSUE TITLE
How long it takes to remove data from database copies, including lagged ones

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#716]
Can you please include information how long it takes for the deletion to be replicated to the passive copies of the database, also the lagged copy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4770b4e9-06d9-2dc6-1c82-06f3434076e1
* Version Independent ID: e30e0525-c4c0-a553-3985-97ff7b799e84
* Content: [Office 365 Exchange Online Data Deletion](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-exchange-online-data-deletion)
* Content Source: [SecurityCompliance/office-365-exchange-online-data-deletion.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-exchange-online-data-deletion.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @robmazz can you help us with this? thanks

**Comment by get-itips** [comment]
Hello @robmazz can you kindly help us with this info? thanks

**Comment by robmazz** [comment]
@Larryngolog - thanks for your feedback. Same comment for this - we're currently looking at more comprehensive reviews and updates to the Service Assurance topics and we'll likely address this in our upcoming updates. I don't have an answer I can give you yet, but I've logged this as an open question and will try to incorporate. Thanks!
