### ISSUE TITLE
Backup period duration

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#718]
Hello, what is length of the backup period? It is important from the regulatory perspective to know how long the data will be stored in backups after deletion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4522f966-a190-4582-f168-a1c72c6fc858
* Version Independent ID: a285bcae-0adf-9625-beb1-5e190aded751
* Content: [Office 365 SharePoint Online Data Deletion](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-sharepoint-online-data-deletion)
* Content Source: [SecurityCompliance/office-365-sharepoint-online-data-deletion.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-sharepoint-online-data-deletion.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @robmazz can you help us with this information? thanks

**Comment by get-itips** [comment]
Hello @robmazz can you kindly help us with this information? thanks

**Comment by robmazz** [comment]
@Larryngolog - thanks for your feedback, We're currently looking at more comprehensive reviews and updates to the Service Assurance topics and we'll likely address this in our upcoming updates. I don't have an answer I can give you yet, but I've logged this as an open question and will try to incorporate. Thanks!
