### ISSUE TITLE
Missleading statement

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#719]
Section

"Default behavior for DKIM and Office 365
If you do not enable DKIM, Office 365 automatically creates a 1024-bit DKIM public key for your custom domain "

Should read

"Default behavior for DKIM and Office 365
If you do not enable DKIM, Office 365 automatically creates a 1024-bit DKIM public key for your DEFAULT domain "

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM for email in your custom domain in Office 365](https://docs.microsoft.com/en-gb/office365/SecurityCompliance/use-dkim-to-validate-outbound-email)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @aldoug 
Thanks for your feedback.
I could verify, so I'll create a pull request to modify the article.
Thank you

**Comment by get-itips** [comment]
@scanum please close this one. Thanks

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
