### ISSUE TITLE
MFA requirement is not fulfilled when your office IP is whitelisted

### ISSUE THREAD

**Issue by gandoge** [MicrosoftDocs/OfficeDocs-o365seccomp#723]
This feature "Requires MFA". If your office IP is white listed from MFA, this feature will not work. You can do every other thing in office 365 as a global admin (delete every single user and document from the tenant) from your office IP but you can not use this feature. When ever I want to click the "Launch Attack" button, I have to go to starbucks or my house to click the button because it forces MFA. Great Job!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@gandogethank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by gandoge** [comment]
@scanum I did open a ticket Premier Partner Support and the "very smart person" on the other end told me this was intended. Which makes no sense when you can do every other thing as a global admin, but if you want to click this button I have to go to starbucks open wifi and then get an MFA prompt to be able to click that button. I came here because this is obviously wrong.

Here is the ticket number if you have any escalation paths ping them this. Ticket #14730053
