### ISSUE TITLE
SMIME digital signing breaks O365 Message Encryption

### ISSUE THREAD

**Issue by enadmin** [MicrosoftDocs/OfficeDocs-o365seccomp#724]
We sign emails using Outlook desktop client and we noticed when we use our SMIME certificates for digital signatures, it breaks our ability to send O365 Encrypted messages and the message that we intended to encrypt in fact goes out as plain text.

Is this a known issue and is there any efforts being done to address this?  Thanks!

**Comment by scanum** [comment]
@enadmin thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
