### ISSUE TITLE
Error in PowerShell example

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/OfficeDocs-o365seccomp#726]
Get-RoleGroupMember -Identity "OrganizationManagement"
This example should be 
Get-RoleGroupMember -Identity "Organization Management"
It shows that way in our environment and this is a built in group so I'm guessing just a mistype.

**Comment by scanum** [comment]
@JohnGGeo Please reference the documentation. Thanks

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by JohnGGeo** [comment]
@scanum the documentation is incorrect due to a misspelling.
`Add-RoleGroupMember -Identity "OrganizationManagement" -Member MatildaS`
Should be:
`Add-RoleGroupMember -Identity "Organization Management" -Member MatildaS`

Thanks,

**Comment by get-itips** [comment]
Hello @JohnGGeo thanks for your feedback.
Your issue report is missing the reference article where you found that example, as in the article Get-RoleGroupMember isn't present.
Can you please reference it here? Thanks

**Comment by JohnGGeo** [comment]
https://docs.microsoft.com/en-us/office365/securitycompliance/grant-access-to-the-security-and-compliance-center?redirectSourcePath=%252farticle%252f2cfce2c8-20c5-47f9-afc4-24b059c1bd76

**Comment by get-itips** [comment]
Hello @JohnGGeo 
I see that you created a pull request, I've just analyzed this and I could verify that the current example works, and your proposal too:

![image](https://user-images.githubusercontent.com/36666927/61094347-10cddb00-a40c-11e9-980f-4ba1fc52ee44.png)
![image](https://user-images.githubusercontent.com/36666927/61094382-30650380-a40c-11e9-9017-0bada081262e.png)

![image](https://user-images.githubusercontent.com/36666927/61094322-f3007600-a40b-11e9-8350-b555e747fbf5.png)

**Comment by chrisda** [comment]
The example is correct as written. In Security & Compliance Center, all but one of the role group Name values have no spaces in them:

```
Get-RoleGroup | Format-Table Name,DisplayName

Name                        DisplayName
----                        -----------
Reviewer                    Reviewer
Device security admin       Device security admin
RecordsManagement           Records Management
ComplianceDataAdministrator Compliance Data Administrator
SecurityOperator            Security Operator
TenantAdmins                Company Administrator
SecurityAdministrator       Security Administrator
OrganizationManagement      Organization Management
ExchangeServiceAdmins       Exchange Service Administrator
SupervisoryReview           Supervisory Review
ComplianceAdministrator     Compliance Administrator
SecurityReader              Security Reader
eDiscoveryManager           eDiscovery Manager
ServiceAssuranceUser        Service Assurance User
DataInvestigator            Data Investigator
HelpdeskAdmins              Helpdesk Administrator
MailFlowAdministrator       MailFlow Administrator
GlobalReader                Global Reader
```

It's unusual that the DisplayName property works as an Identity value, because the DisplayName property of an object often doesn't have uniqueness requirements. But it works in this case.

I can see the confusion as the Security & Compliance Center UI appears to favor the role group DisplayName instead of the Name

![image](https://user-images.githubusercontent.com/33166947/61143315-b1f97780-a486-11e9-9ad7-4de2e51f8f6e.png)

So, it appears the smart move is to update the examples (all of them) to use the role group DisplayName values instead of Name.

Closing
