### ISSUE TITLE
UpdateCalendarDelegation in Exchange section is duplicated

### ISSUE THREAD

**Issue by mmascolino** [MicrosoftDocs/OfficeDocs-o365seccomp#729]
The UpdateCalendarDelegation item in the Exchange section is duplicated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#before-you-begin)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@mmascolino Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by markjjo** [comment]
@mmascolino Thanks for heads up; Duplicated activity deleted. https://docs.microsoft.com/en-us/Office365/SecurityCompliance/search-the-audit-log-in-security-and-compliance#exchange-mailbox-activities
