### ISSUE TITLE
No Archive option 

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/OfficeDocs-o365seccomp#73]
At the section "Enable an archive mailbox" (https://docs.microsoft.com/en-us/office365/securitycompliance/enable-archive-mailboxes#enable-an-archive-mailbox)
there is a misleading info: there is no Archive option in the left pane of the Security & Compliance Center -&gt; Data governance 
I have tested this as a global administrator of the tenant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90155d71-7541-cf11-f769-97239f69ee2c
* Version Independent ID: 3c709c8c-460a-a075-067e-70907a97a015
* Content: [Enable archive mailboxes in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-archive-mailboxes)
* Content Source: [SecurityCompliance/enable-archive-mailboxes.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-archive-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Michal-Ziemba -- Can't repro; in multiple tenants, the Data governance > Archive is available in the SCC. As per the help topic, you have to be assigned the Mail recipients role in Exchange Online. Verify that the global admin in O365 is a member of Organzation Management role group in Exchange Online (or that the global admin is assigned to an Exchange Online role group that is assigned the Mail recipients role. You could also try to enable archive mailbox in Exchange Online; see this topic (which is for Exchange server but is also applicable to Exchange Online as long as you use the Exchange Online admin center or Exchange Online powershell: https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/in-place-archiving/manage-archives

**Comment by markjjo** [comment]
Forgot to attach this screenshot

![sccarchive](https://user-images.githubusercontent.com/36746813/45833931-c7fd3800-bcba-11e8-8d47-3b0f0d0b8845.png)

**Comment by Michal-Ziemba** [comment]
Thx. I will check and gdy back to you



Best regards/Pozdrawiam
Michał Ziemba

Sent from mobile phone

Wiadomość napisana przez Mark Johnson <notifications@github.com<mailto:notifications@github.com>> w dniu 20.09.2018, o godz. 18:40:


@Michal-Ziemba<https://github.com/Michal-Ziemba> -- Can't repro; in multiple tenants, the Data governance > Archive is available in the SCC. As per the help topic, you have to be assigned the Mail recipients role in Exchange Online. Verify that the global admin in O365 is a member of Organzation Management role group in Exchange Online (or that the global admin is assigned to an Exchange Online role group that is assigned the Mail recipients role. You could also try to enable archive mailbox in Exchange Online; see this topic (which is for Exchange server but is also applicable to Exchange Online as long as you use the Exchange Online admin center or Exchange Online powershell: https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/in-place-archiving/manage-archives

**Comment by AndreaBarr** [comment]
@Michal-Ziemba Thank you for this feedback

It appears that Mark has given you a resolution. I am going to close this issue. If the issue is not resolve please reopen the issue.

**Comment by cmakas** [comment]
Is it possible to activate archive via powershell?
Thx

**Comment by markjjo** [comment]
@cmakas Yes
1. Connect to Exchange Online PowerShell: https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell?view=exchange-ps

2. Run this command: Enable-Mailbox <user identity> -Archive

3. To enable the archive mailbox for all users whose archive is disabled, run this command: Get-Mailbox –Filter {ArchiveStatus –Eq "None" –AND RecipientTypeDetails –eq "UserMailbox"} | Enable-Mailbox -Archive

**Comment by markjjo** [comment]
@cmakas Step 2 should be Enable-Mailbox usermailbox -Archive

**Comment by cmakas** [comment]
@markjjo Thank you for your answer. Because of hybrid configuration I had to do it on premises with Enable-RemoteMailbox ... -Archive.
