### ISSUE TITLE
Category CAT:PHSH and others

### ISSUE THREAD

**Issue by javirivas80** [MicrosoftDocs/OfficeDocs-o365seccomp#735]
Can you please update the article explaining more in detail the difference between the available Advanced phishing thresholds and how ATP identifies emails in each category ?
for example CAT:PHSH  https://docs.microsoft.com/en-us/office365/securitycompliance/how-policies-and-protections-are-combined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies)
* Content Source: [SecurityCompliance/set-up-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@javirivas80 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Solving this issue with PR #746

**Comment by scanum** [comment]
@javirivas80 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
