### ISSUE TITLE
False Positives or Dismissing events for Machine Learning

### ISSUE THREAD

**Issue by SweetmanD** [MicrosoftDocs/OfficeDocs-o365seccomp#738]
Hello, 

Thank you for the great content. One thing it'd be nice to see is how to report false positives or what dismissing an alert does for machine learning, Similar to AADIP.  Right now we are getting spammed with alerts for legitimate emails/URLs. We've turned off email alerts for now hoping that Microsoft can provide some guidance to these features.

thanks!
-dan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efdde62-0d69-bc5f-3833-d402bb1aa24f
* Version Independent ID: 3feeadc7-1848-b77b-a29f-e9b91c20e9c5
* Content: [Automated Investigation and Response (AIR) with Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/automated-investigation-response-office)
* Content Source: [SecurityCompliance/automated-investigation-response-office.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/automated-investigation-response-office.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@SweetmanD Thank you for submitting feedback and contributing to the docs. We appreciate your suggestion and we will take it into consideration when updating the docs in the future.

**Comment by scanum** [comment]
@officedocsbot close
