### ISSUE TITLE
Script output for site folders incomplete

### ISSUE THREAD

**Issue by marleyjaffe** [MicrosoftDocs/OfficeDocs-o365seccomp#739]
I have noticed that the script provided does not provide a full listing of Sharepoint Site folders. It seemingly only provides the first 200 folder paths, with no indication that there may be more that are not being returned. I have been unsuccessful with fixing the script to return an accurate report. I believe this is due to a Content Search Limitation. I suggest either removing this limitation or alerting to this limitation either in the script or in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9162d31-5514-df46-aff8-679814ed5060
* Version Independent ID: a6ffc7a8-ffe0-9f72-9371-27b6ee51e8e5
* Content: [Use Content Search in Office 365 for targeted collections](https://docs.microsoft.com/en-us/office365/securitycompliance/use-content-search-for-targeted-collections#feedback)
* Content Source: [SecurityCompliance/use-content-search-for-targeted-collections.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-content-search-for-targeted-collections.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@marleyjaffe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @marleyjaffe thanks for your feedback.
I tested this in my lab, and I could verify that results are limited to 200 objects, but limitations are documented [here](https://docs.microsoft.com/en-us/office365/securitycompliance/limits-for-content-search) 
I will propose with a Pull Request adding a note including this link.

Thank you

**Comment by get-itips** [comment]
Hello @scanum please close this issue. thanks

**Comment by scanum** [comment]
@marleyjaffe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
