### ISSUE TITLE
Updates license requirement under "Before you begin" 

### ISSUE THREAD

**Issue by MarkBratton** [MicrosoftDocs/OfficeDocs-o365seccomp#740]
Please change the text of the first 2 bullets under the section "Before you begin" to:

•	To make a mailbox inactive, it must be assigned an Exchange Online Plan 2 license so that a Litigation Hold or an Office 365 retention policy can be applied to the mailbox before it's deleted. Exchange Online Plan 2 licenses are part of an Office 365 Enterprise E3 and E5 subscriptions. If a mailbox is assigned an Exchange Online Plan 1 or Exchange Online Kiosk license (which are part of an Office 365 E1 and F1 subscriptions respectively), you would have to assign it a separate Exchange Online Archiving license so that a hold can be applied to the mailbox before it's deleted. For more information, see Exchange Online Archiving.
•	The licenses associated with the deleted Exchange Online mailbox will be available after you delete the corresponding Office 365 user account. You can then Assign licenses to users in Office 365 for business to another user.

These updates reflect recent licensing policy decisions from business planning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac2ead82-c764-16a8-2850-a313ecabc44a
* Version Independent ID: 26baec04-9492-6030-e39f-060243939cec
* Content: [Create and manage inactive mailboxes in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/create-and-manage-inactive-mailboxes)
* Content Source: [SecurityCompliance/create-and-manage-inactive-mailboxes.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@MarkBratton Thanks for heads up; topic has been updated with these fixes and republished. Next time, you can contact me (or other writers) directly via MSFT corp email.
