### ISSUE TITLE
What to do steps order

### ISSUE THREAD

**Issue by bradrush** [MicrosoftDocs/OfficeDocs-o365seccomp#741]
I think it would be more logical under 'What to do' for step '3: Learn about Safe Attachments policy' to proceed 'step 2: Set up an ATP Safe Attachments policy'
Thanks,

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721eb3a3-eb0d-77a8-0c74-1b9ddb8e963a
* Version Independent ID: 9b8b98f1-2b65-9c11-3fbc-09dcd1c2ed84
* Content: [Set up Office 365 ATP Safe Attachments policies](https://docs.microsoft.com/en-nz/office365/securitycompliance/set-up-atp-safe-attachments-policies?redirectSourcePath=%252fen-us%252farticle%252fSet-up-Safe-Attachments-policies-in-Office-365-078eb946-819a-4e13-8673-fe0c0ad3a775#feedback)
* Content Source: [SecurityCompliance/set-up-atp-safe-attachments-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-safe-attachments-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@bradrush Thank you for submitting feedback and contributing to the docs. We appreciate your suggestion and will consider it when the docs are updated in the future.

**Comment by scanum** [comment]
@officedocsbot close
