### ISSUE TITLE
Messages in deferral

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-o365seccomp#742]
Message deferral time has been reduced to 24 hours recently instead of 48 hours. It would nice if this article could get updated.
Source: https://lynx.office.net/#/messagecenter/MC173908

Many thanks
Jeroen Dronkers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afba520e-06bd-30d9-3bd0-0117e343d249
* Version Independent ID: 2a2cbdb9-5a6f-474e-624f-e83708c9f021
* Content: [EOP queued, deferred, and bounced messages FAQ](https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/eop-queued-deferred-and-bounced-messages-faq)
* Content Source: [SecurityCompliance/eop/eop-queued-deferred-and-bounced-messages-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/eop-queued-deferred-and-bounced-messages-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@JeroenDronkers Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @JeroenDronkers 
Thanks for your feedback, could you please paste the information on the referenced url here?
Thank you

**Comment by JeroenDronkers** [comment]
Hello

It is the link mentioned under "Content": https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/eop-queued-deferred-and-bounced-messages-faq

Thanks

**Comment by get-itips** [comment]
Hello, I am referring to the link you provided as "source" thanks.

**Comment by JeroenDronkers** [comment]
Hello,

These are the original details of the posting

Details
Update June 13, 2019:

This roll out has taken longer than originally planned and we will now complete the roll out by the end of June.

Beginning on March 20, 2019, if after multiple attempts we’re unable to send or deliver a message sent by one of your users, we’ll send them a bounce message about it within 24 hours instead of 48 hours.

[How does this affect me?]
Currently, when a temporary routing error occurs, we repeatedly attempt to send the message for 48 hours before the system returns a bounce message (or non-delivery report (NDR)) to the sender.
This change reduces the Office 365 message expiration timeout interval from 48 hours to 24 hours. By reducing the message expiration timeout interval to 24 hours, senders will know sooner if we were unable to deliver their message, and can respond to the error in a more timely fashion.

Note that this will only affect messages queued on Office 365 servers. The message expiration times for messages queued on servers outside of Office 365 are not affected by this change. We will begin rolling this change out on March 20, 2019, and we anticipate worldwide rollout completion by the end of April.

[What do I need to do to prepare for this change?] There is nothing you need to do to prepare for this change. Please click Additional Information to learn more about non-delivery reports in Office 365.





Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>
[Microsoft Logo]
Backup | Alisdair Douglas (Alisdair Douglas (aldoug@microsoft.com)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

**Comment by get-itips** [comment]
Ok I have just noticed that the article has been already updated to match that information.
We will close this now.
Thank you

**Comment by get-itips** [comment]
@scanum can you close this one? Thank you ;)

**Comment by scanum** [comment]
@JeroenDronkers Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
