### ISSUE TITLE
Missing X-Forefront-Antispam-Report fields

### ISSUE THREAD

**Issue by pauldurham** [MicrosoftDocs/OfficeDocs-o365seccomp#743]
As of 2019-6-13 there are still at least 6 fields in the X-Forefront-Antispam-Report entry that are not documented.  Can these please be added to your documentation?
EFV:NLI
SFS:
DIR:INB
SFP:
MX:
CAT:SPM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0c22e-ec20-d8dc-bbc5-cfbb9e98350e
* Version Independent ID: d9a1bac2-69ef-5fa7-23f1-417d7454c4cc
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-za/office365/SecurityCompliance/anti-spam-message-headers#feedback)
* Content Source: [SecurityCompliance/anti-spam-message-headers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@pauldurham Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by pauldurham** [comment]
Thank you @scanum.

**Comment by jjtitos** [comment]
Please update this!

Also, need an update on this, please! We have no idea what these anti-spam message headers mean!

https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-spam-message-headers

22	X-Microsoft-Antispam-Mailbox-Delivery	ucf:0;jmr:0;ex:0;auth:0;dest:I;ENG:(20160514016)(750119)(520011016)(944506303)(944626516);

**Comment by get-itips** [comment]
Hello @KCCross can you help us with getting the missing info?
Thank you

**Comment by get-itips** [comment]
Hello @KCCross can you kindly help us with this information? Thank you

**Comment by MooseTheCoder** [comment]
I have looked through an old issue about EFV:NLI and have landed here. Some info on that would be awesome!

**Comment by Luspin** [comment]
EFV:NLI is in no way related to deliveries to the Junk folder.
If these are occurring in an Exchange Online environment, I suggest opening a support ticket via the Office 365 portal.
If we're talking about Outlook.com, that team can be reached too.

**Comment by MSFTTracyP** [comment]
So, since not all of these X-Forefront-Antispam-Report entries are defined, if you receive a response that is troublesome, or inexplicable, and find it's not documented anywhere, please do feel free to submit a ticket here:

https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone

**Comment by MSFTTracyP** [comment]
Hello everyone. I have a final answer regarding this article, and I'd like to apologize for any confusion before we set out. Parts of the header information are exposed for customers to read in documents like this one, but parts are never going to be exposed and are not destined or meant for documentation. One analogy for this is that asking after certain of the codes would be like as asking after the contents of encrypted text in headers. The codes that _are_ available are published as guidance at this time. Other codes will not be published and there are no plans to publish them.

At this point, I _strongly_ suggest that if you run into a problem and/or work-stoppage associated with an undocumented header, you go to Support _immediately_ for further investigation, and to avoid headaches. There is no other way that I know of to interpret, except through raising the issue there, for the purpose of investigation.

Apologizes for any inconveniences or confusions this causes. I appreciate your feedback and questions about this and thank you for your time and concern.
