### ISSUE TITLE
Missing Reference to powershell cmdlets

### ISSUE THREAD

**Issue by john-louden** [MicrosoftDocs/OfficeDocs-o365seccomp#745]
Wondering if it would be possible to have a link to the powershell commands that can be run to manage the alert policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e607177-4e5b-69af-5408-caa6337bbd0e
* Version Independent ID: c82bbeaa-9df1-c070-644b-a666406464b5
* Content: [Alert policies in the security and compliance center](https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies#feedback)
* Content Source: [SecurityCompliance/alert-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@john-louden Thank you for submitting feedback and contributing to the docs. We appreciate your suggestion and will take it into consideration in the future when updating this doc.

**Comment by scanum** [comment]
@officedocsbot close
