### ISSUE TITLE
Power Query Formatting

### ISSUE THREAD

**Issue by jameseccles** [MicrosoftDocs/OfficeDocs-o365seccomp#747]
Rather than use the "split by delimiter" function in Power Query, it would be more effective to transform the column to JSON and then expand the records. This will separate the property title from the value and ensure the correct headers in the Excel sheet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d2f21cd-9175-e409-e5ef-a614bfe8b774
* Version Independent ID: a2b1fcb5-3a60-676c-e3e4-7d25d7c3e756
* Content: [Use sharing auditing in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/use-sharing-auditing#feedback)
* Content Source: [SecurityCompliance/use-sharing-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-sharing-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by SergePoint** [comment]
In my environment the columns for the exported results are not named "Time, User, Action, and Detail", but "CreationDate, Userids, Operations and AuditData". The article was published in 2018.  Did the column name changed and the article was not updated?  Also I have shared content with an external/Guestuser and in the log I do not find "TargetUserOrGroupType:Guest" did this change too?  Thanks

**Comment by markjjo** [comment]
@jameseccles Will you please send me instructions to my MSFT corp account about how to "transform the column to JSON" and I will see if this can be added to topic. Thanks.
