### ISSUE TITLE
Reviewer Role

### ISSUE THREAD

**Issue by Breaker119** [MicrosoftDocs/OfficeDocs-o365seccomp#750]
The reviewer role states that it is specifically for eDiscovery "Use a limited set of the analysis features in Office 365 Advanced eDiscovery. Members of this group can see only the documents that are assigned to them."

By this statement the Reviewer Role (with Review permissions) should only see eDiscovery cases assigned to them.

However, when I assign the Reviewer Role to a user the following items are enabled that should not be per the documentation:

- Alerts (Dashboard and Individual Alerts)
- Records Management
- Data Governance (Dashboard)
- Mailflow (Dashboard)
- Data Privacy (GDPR Dashboard and Data Subject Requests)
- Search (Content Search)
- Service Assurance

**Comment by scanum** [comment]
@Breaker119thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
