### ISSUE TITLE
Office 365 Groups Retention

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/OfficeDocs-o365seccomp#751]
Please clarify what services are included with a retention policy applied to Office 365 Group location. Does this include Teams document libraries? There is a statement that you need a retention policy applied to SPO to retain Teams document libraries. Does the Office 365 Group location overlap with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@toddjohnson39 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@toddjohnson39 Thank you for reaching out and helping improve docs.  Please have a look at this link and let me know if it answers any of your questions and I can have the necessary information added to the article. https://techcommunity.microsoft.com/t5/Office-365-Groups/Using-Office-365-retention-policies-with-Office-365-Groups/td-p/62004

**Comment by toddjohnson39** [comment]
Here are the statements I think need clarification with my notes.

"Office 365 groups (applies to content in the group's mailbox, site, and documents. Support for content in Planner, Yammer, and CRM is coming soon.)"

*Please list exactly what is included as well (e.g. Teams, PowerBI, Stream, Exchange, SharePoint Team Sites).

"Therefore, to retain or delete files in a Team, you need to create a retention policy that applies to the SharePoint and OneDrive locations."

*This sounds like a Retention Policy applied to Office 365 Groups location would not cover the resources created by a Team. We would need to use a Retention Policy that targets SharePoint and OneDrive specifically. Or is this just another option?

"A retention policy applied to an Office 365 group includes both the group mailbox and site."

*This sounds like a Retention Policy applied to an Office 365 group will protect the resources created by an Office 365 group, which would include Teams.

**Comment by toddjohnson39** [comment]
Any update on this?

**Comment by lindspea** [comment]
@toddjohnson39 I have submitted a PR. It will take a few days to reflect once the author has approved it.

**Comment by lindspea** [comment]
@stephow-MSFT

**Comment by scanum** [comment]
@toddjohnson39 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
