### ISSUE TITLE
Advanced phishing thresholds

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/OfficeDocs-o365seccomp#752]
I think the section for "Advanced phishing thresholds" should be reworded a bit.  You have "For example, messages with a very high probability of being phish will have the most aggressive actions taken on them while messages with a low probability have less aggressive actions taken on them." in the right column  But the middle column has it all listed as being "... handled by the system in the same way."
So, it isn't really different actions taken, it is essentially setting how probable the mail is phishing as to whether or not you take the (same) designated action on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies)
* Content Source: [SecurityCompliance/set-up-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@J-Fedor Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@J-Fedor thanks for reaching out.  I'll change the wording as per your suggestion.

**Comment by scanum** [comment]
@J-Fedor Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
