### ISSUE TITLE
Document sets and retention in SharePoint

### ISSUE THREAD

**Issue by hermansolberg** [MicrosoftDocs/OfficeDocs-o365seccomp#753]
Scenario: Apply retention label on Document Set in a document library.
Expectation: Documents in the labeled Document Set will be deleted according to the rules of the label. Document Set will also be deleted according to the same rules once it is empty.
Result: Documents are deleted, but Document Set remains.
Question: Are Document Sets not affected by the retention and disposal rules?

**Comment by scanum** [comment]
@hermansolberg thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by hermansolberg** [comment]
Thanks for the response @scanum. And sorry, I could have been clearer in my intentions with raising this issue.

A customer I'm working with has already raised a case to get a yes/no answer whether this is by design. The tests they have performed point in the direction that this is by design. If this is the case, it would be useful to update the documentation to reflect this. I know several customer who expected Document Set to be disposed according to the label rules. So clearly stating that it is not the case, would remove any misconceptions of how things work.

**Comment by hermansolberg** [comment]
@scanum - The support ticket has come back with the expected verdict. The product does not support retention and disposal on Document Sets at the moment. I think it would be a good idea to make that clear in the documentation so that customers know what to expect.
