### ISSUE TITLE
How to verify DKIM records ?

### ISSUE THREAD

**Issue by ManlyElectronics** [MicrosoftDocs/OfficeDocs-o365seccomp#754]
There is a tool for Google Suite allowing to verify DKIM etc domain records easy, without any logins.
Is that possible to test domain setup with Microsoft 365 Business suite ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0c22e-ec20-d8dc-bbc5-cfbb9e98350e
* Version Independent ID: d9a1bac2-69ef-5fa7-23f1-417d7454c4cc
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/office365/securitycompliance/anti-spam-message-headers#feedback)
* Content Source: [SecurityCompliance/anti-spam-message-headers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@ManlyElectronics thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by ManlyElectronics** [comment]
I do not see who you are, scanum, hence I cannot trust your answer and follow your instructions blindly. But assuming I trust, the answer you tried to avoid is No, there is no way people can verify Microsoft 365 business Suite installation without login, hence Microsoft 365 business Suite is inherently vulnerable to spam and hacking attacks.
