### ISSUE TITLE
ATP Safe Links Policies Question

### ISSUE THREAD

**Issue by jakob-leonard** [MicrosoftDocs/OfficeDocs-o365seccomp#755]
Hi! Reaching out because I work at an Email Service Provider. Trying to diagnose a problem we are seeing with Office 365 Advanced Thread Protection and could not find any documentation on. 

The issue is for links in emails that we wrap for tracking purposes. We have heard from customers that these inboxes generate a warning on those links that look like this:
![0365-atp](https://user-images.githubusercontent.com/39770762/59782902-ef565500-928c-11e9-8f79-632233be1330.png)

The question is if there is an ATP Safe Link Policy for URL length that we might be tripping? (Our wrapped links are rather long ~600 characters)

**Comment by scanum** [comment]
@jakob-leonard thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
