### ISSUE TITLE
Puzzled

### ISSUE THREAD

**Issue by gbc46** [MicrosoftDocs/OfficeDocs-o365seccomp#759]
I was directed to this page by an email from Microsoft telling me about some wonderful new facilities which would allow me to encrypt any emails I send from Office 365 (for which I have an end-user subscription). However on reading this I'm finding it very difficult to make sense of it because when I click on links (like the one to see the size limits of encrypted emails with attachments) it seems to only apply to enterprise levels of Office and not to one that an end-user may have bought? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e8c7180-4b5f-37eb-32b8-c87512ce0820
* Version Independent ID: 33c43b5c-b035-8c8b-7e59-a38492924cf3
* Content: [Office 365 Message Encryption](https://docs.microsoft.com/en-gb/office365/securitycompliance/ome?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-Message-Encryption-OME-F87CB016-7876-4317-AE3C-9169B311FF8A#feedback)
* Content Source: [SecurityCompliance/ome.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@gbc46 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
