### ISSUE TITLE
Clarify "Deleting content that's older than a specific age"

### ISSUE THREAD

**Issue by jcallaghan** [MicrosoftDocs/OfficeDocs-o365seccomp#761]
**Deleting content that's older than a specific age**
Please,** could you clarify when content is deleted i.e. deletion policy (Deleting content that's older than a specific age) where it goes? Does the file get moved to the sites Recycle Bin?

**Comment by scanum** [comment]
@jcallaghan Hello, thanks for submitting feedback. Could you please link the document that you are referring to? Thanks.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@jcallaghan We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
