### ISSUE TITLE
Document might need to be updated with new column names

### ISSUE THREAD

**Issue by SergePoint** [MicrosoftDocs/OfficeDocs-o365seccomp#763]
In my environment the columns for the exported results are not named "Time, User, Action, and Detail", but are named "CreationDate, Userids, Operations and AuditData". The article was published in 2018. Did the column name changed and the article was not updated? Also I have shared content with an external/Guestuser and in the log I do not find "TargetUserOrGroupType:Guest" did this change too? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d2f21cd-9175-e409-e5ef-a614bfe8b774
* Version Independent ID: a2b1fcb5-3a60-676c-e3e4-7d25d7c3e756
* Content: [Use sharing auditing in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/use-sharing-auditing#feedback)
* Content Source: [SecurityCompliance/use-sharing-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-sharing-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@SergePoint Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @SergePoint 
The columns you see in the screenshot are a result of what is stated in the article:

> The next step is to filter the CSV for the SharingSet and SharingInvitationCreated events, and to display those events where the TargetUserOrGroupType property is Guest. You use the Power Query Editor tool in Excel to do this. For step-by-step instructions, see Export, configure, and view audit log records.

https://docs.microsoft.com/en-us/office365/securitycompliance/export-view-audit-log-records

Thank you

**Comment by get-itips** [comment]
Hello @scanum please close this one. Thank you

**Comment by scanum** [comment]
@SergePoint Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
