### ISSUE TITLE
Can not see Apply Label

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/OfficeDocs-o365seccomp#765]
Based on section "Onedrive and Sharepoint" section, it says that user can apply label to a document but I can not see the "Apply label" label and text box to select one. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels?redirectSourcePath=%252fen-us%252farticle%252fOverview-of-labels-af398293-c69d-465e-a249-d74561552d30#where-published-retention-labels-can-appear-to-end-users)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by ravick4u** [comment]
![ApplyLabelMissing](https://user-images.githubusercontent.com/11890407/59931656-7f260b80-9413-11e9-8314-1050326917d6.png)

**Comment by stephow-MSFT** [comment]
The info above is correct. Lots of possible reasons why you're not seeing this -- scroll down to see more properties in your screenshot, maybe labels haven't been deployed to this site yet (may take up to a day for SharePoint), maybe this site is not included in the retention policy, etc.

**Comment by ravick4u** [comment]
Thanks @stephow-MSFT
