### ISSUE TITLE
Events Option is missing from navigation

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/OfficeDocs-o365seccomp#766]
I do not see Event in left navigation. Is this something still being rolled out ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa8bea84-e38c-1780-59a7-261e0112208b
* Version Independent ID: 7a9cb33b-cb67-5c77-14b0-36123c3c12c8
* Content: [Overview of event-driven retention](https://docs.microsoft.com/en-us/office365/securitycompliance/event-driven-retention?redirectSourcePath=%252fen-us%252farticle%252fOverview-of-event-driven-retention-dd851332-747b-45b9-82de-e3cd7d01c8a7)
* Content Source: [SecurityCompliance/event-driven-retention.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by ravick4u** [comment]
![EventsOptionIsMissing](https://user-images.githubusercontent.com/11890407/59936317-ada8e400-941d-11e9-948c-138b6d47ef47.png)

**Comment by stephow-MSFT** [comment]
It looks like we moved Events under Records Management in the left nav of the Security and Compliance Center. I'll update the topic.
