### ISSUE TITLE
1000 user specific Limit

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/OfficeDocs-o365seccomp#767]
The document says that each group has a 1000 mailbox limit.  So if my customer wants:

- 10,000 of their users in a 2 year retention policy
- 1500 in a 5 year 
- 100 in a 10 year
- The rest have no retention policy

What is the best way to apply to the 10000?  Do we really need to ask our customers to create 27 policies in the Security and Compliance center??

**Comment by scanum** [comment]
@sinnamingrrl thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
