### ISSUE TITLE
Need to add details about MS Teams

### ISSUE THREAD

**Issue by scossio** [MicrosoftDocs/OfficeDocs-o365seccomp#768]
Need details for using Customer Key with MS Teams, if not additional steps are needed, that should also be documented. Customers are pointing out the lack of details for Teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e55fe21-a628-4ad9-b250-82fc24714fce
* Version Independent ID: ce31506e-5a7b-47dc-6ea7-87633e07a379
* Content: [Controlling your data in Office 365 using Customer Key](https://docs.microsoft.com/en-us/office365/securitycompliance/controlling-your-data-using-customer-key#feedback)
* Content Source: [SecurityCompliance/controlling-your-data-using-customer-key.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/controlling-your-data-using-customer-key.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@scossio Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Substituted PR #828 for #829 @scanum

**Comment by KCCross** [comment]
All guidance pertaining to Microsoft Teams will be incorporated separately as a single update. the PT is not yet ready to deliver this guidance.
