### ISSUE TITLE
Recipient policies are a requirement, not a choice

### ISSUE THREAD

**Issue by nivdolgin** [MicrosoftDocs/OfficeDocs-o365seccomp#77]
Consider (pun intended) revising the language used in the first sentence in this section: https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-safe-links-policies#add-a-policy-for-specific-email-recipients

It reads: "...consider defining additional policies for specific groups of email recipients."
But if recipient policies are not defined, link re-write doesn't work at all with only an Org-wide policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5375df5a-9955-47d9-5ef4-8adbd219f77b
* Version Independent ID: 5b191c2a-bfde-a531-9c3b-4b295efea56c
* Content: [Set up Office 365 ATP Safe Links policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-safe-links-policies#add-a-policy-for-specific-email-recipients)
* Content Source: [SecurityCompliance/set-up-atp-safe-links-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-safe-links-policies.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AndreaBarr** [comment]
@nivdolgin Thank you for this feedback

I agree the verbiage needs to change if it's not a choice. 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
