### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Dynowarz90** [MicrosoftDocs/OfficeDocs-o365seccomp#770]
There's an extra space in "OneDrive" in the first paragraph. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1333d56b-1895-3836-6ea9-aae2501ec5a4
* Version Independent ID: 485be486-3c4e-2de2-3d7e-327932b0f93f
* Content: [Use Content Search to search the mailbox and OneDrive for Business site for a list of users](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users)
* Content Source: [SecurityCompliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Dynowarz90 Thanks for heads up. We will fix this. Note that you can also fix issues like these by clicking the Edit link at the topic of the browser (when you're signed in to your GitHub account) editing the topic and then submitting a pull request.
