### ISSUE TITLE
Philippine DPA 2012 Template

### ISSUE THREAD

**Issue by jaysonvelasco** [MicrosoftDocs/OfficeDocs-o365seccomp#772]
Hello MS365 team - Do you guys have a template for the 2012 Philippine DPA for DLP in Office 365?

When I checked Qualys, they do have a template for the Philippine DPA. I hope you could come up with one. 

Plus this isn't updated - https://www.microsoft.com/en-ph/TrustCenter/Privacy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25120ecd-d708-786f-b361-5baf5169e766
* Version Independent ID: d38b34f4-db27-fcd8-e5e3-f927a9f850a5
* Content: [What the DLP policy templates include](https://docs.microsoft.com/en-us/office365/securitycompliance/what-the-dlp-policy-templates-include?redirectSourcePath=%252farticle%252fc2e588d3-8f4f-4937-a286-8c399f28953a#feedback)
* Content Source: [SecurityCompliance/what-the-dlp-policy-templates-include.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/what-the-dlp-policy-templates-include.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@jaysonvelasco Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hello @jaysonvelasco  you can either post your idea here:
https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/18957937-dlp-report

Or create a support ticket to support so they can have you informed if there's already something there that you can back up or create a new idea.

**Comment by scanum** [comment]
@officedocsbot close
