### ISSUE TITLE
Blocking of ODB files - WebOnly?

### ISSUE THREAD

**Issue by Tower7Bro** [MicrosoftDocs/OfficeDocs-o365seccomp#775]
The screenshot of ODB on desktop only shows the web view.  Does this same red shield icon and ATP features also work for the built in ODB client on Windows 10?  I don't know many users that use and manage files day to day in the webview for ODB.  Thanks.

**Comment by denisebmsft** [comment]
Hello @Tower7Bro. I think you are referring to [this article](https://docs.microsoft.com/en-us/office365/securitycompliance/atp-for-spo-odb-and-teams#how-it-works), yes?

Although ATP features apply to files in SharePoint, OneDrive, and Teams, the visual cue of the red shield is only visible in the browser (Modern Experience view). Classic view in SharePoint won't show the red shield, and neither in Windows Explorer. Protection is still in place, however, for all licensed users, assuming a security administrator has turned on protection.

I hope this helps! Please let us know if you have any other questions.

**Comment by Tower7Bro** [comment]
Thank you. Yes im referring to that link. Im new to this and clicked on the open comment on that link. Not sure what im doing wrong it doesnt show in the open section.
