### ISSUE TITLE
Changes to ZAP action

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#776]
There were changes to ZAP Spam action.
No unread messages will be moved to junk email folder when spam policy action is:Redirect. Delete, Quarantine, MoveToJmf
The same applies to ZAP phish. Please verify internally and update the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c88a1bea-b981-89e7-57db-14b7887618a8
* Version Independent ID: 16dc4701-b3f9-3d6a-f699-418d1201840c
* Content: [Zero-hour auto purge - protection against spam and malware](https://docs.microsoft.com/en-us/office365/securitycompliance/zero-hour-auto-purge)
* Content Source: [SecurityCompliance/zero-hour-auto-purge.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/zero-hour-auto-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by MSFTTracyP** [comment]
Hi @paw81, I have verified that the section (below) which is already live, addresses when actions will be taken, and includes info re. behaviours if the message is read/unread re. the policy actions taken.

![GitHub_776](https://user-images.githubusercontent.com/33558605/63981773-273ffc80-ca75-11e9-9d17-7a00a42731c8.png)
