### ISSUE TITLE
RecordType

### ISSUE THREAD

**Issue by shyamjiniranjan** [MicrosoftDocs/OfficeDocs-o365seccomp#777]
I am trying to call audit.general and in response for the workload "SecurityComplianceCenter" is getting RecordType 52 which is not listed in this page and also not getting detected malware counts, spoofing counts etc in response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2748572-d1b7-6bb3-a4ed-c58da8a232bb
* Version Independent ID: 6f16b647-f313-9ec9-c26a-934aac9c3c00
* Content: [Detailed properties in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log#feedback)
* Content Source: [SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@shyamjiniranjan RecordType 52 = DataInsightsRestApiAudit; I will add this to the topic and to the [Office 365 Management Activity API schema topic](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema).   Here is the schema for DataInsightsRestApiAudit:

  <?xml version="1.0" encoding="utf-8" ?> 
- <edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
- <edmx:Reference Uri="http://schema.audit.exchange.microsoft.com">
  <edmx:Include Alias="Common" Namespace="Microsoft.Office.Audit.Schema" /> 
  </edmx:Reference>
- <edmx:DataServices>
- <Schema Namespace="Microsoft.Office.Audit.Schema.DataInsightsRestApiAudit" xmlns="http://docs.oasis-open.org/odata/ns/edm">
- <EntityType Name="DataInsightsRestApiAuditRecord" BaseType="AuditRecord">
  <Annotation Term="Microsoft.Office.Audit.Schema.WorkloadType" EnumMember="Microsoft.Office.Audit.Schema.WorkloadType/SecurityComplianceCenter" /> 
  <Annotation Term="Microsoft.Office.Audit.Schema.RecordType" EnumMember="Microsoft.Office.Audit.Schema.AuditLogRecordType/DataInsightsRestApiAudit" /> 
  <Property Name="ResponseCode" Type="Edm.String" /> 
  <Property Name="Exception" Type="Edm.String" /> 
  <Property Name="DataType" Type="Edm.String" /> 
  <Property Name="StoreType" Type="Edm.String" /> 
  <Property Name="Debug" Type="Edm.String" /> 
  <Property Name="FieldsQueried" Type="Edm.String" /> 
  </EntityType>
  </Schema>
  </edmx:DataServices>
  </edmx:Edmx>

Also, here is info about the ATP auditing schema: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#office-365-advanced-threat-protection-and-threat-investigation-and-response-schema

**Comment by shyamjiniranjan** [comment]
Thanks Sir,
no issue with schema, i am looking for the api end point which will return the ATP auditing schema in response.
