### ISSUE TITLE
ServiceType

### ISSUE THREAD

**Issue by shyamjiniranjan** [MicrosoftDocs/OfficeDocs-o365seccomp#778]
There is mentioned office 365 service named "Security & Compliance Center" in the page but not  mentioned content type for the management activity api which will return security and compliance threat management reporting data. There is mentioned only Audit.General, Audit.SharePoint, Audit.Exchange, Audit.AzureActiveDirectory & DLP.All and none of these returns advance threat protection (ATP) reporting data. Please reply. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2748572-d1b7-6bb3-a4ed-c58da8a232bb
* Version Independent ID: 6f16b647-f313-9ec9-c26a-934aac9c3c00
* Content: [Detailed properties in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log#feedback)
* Content Source: [SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@shyamjiniranjan Not sure what your question is. As per my previous answer to the other issue you opened, see here for info about ATP schema: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#office-365-advanced-threat-protection-and-threat-investigation-and-response-schema

**Comment by shyamjiniranjan** [comment]
Thanks Sir,
I am looking for the management activity api endpoint which will return "advanced threat protection" data in response so that i would use that data for reporting purpose in user interface.
