### ISSUE TITLE
SharingInvitationCreated operation not logged anymore?

### ISSUE THREAD

**Issue by markusmiet** [MicrosoftDocs/OfficeDocs-o365seccomp#779]
Either the documentation is outdated or something is wrong with external share logging. I shared document from sharepoint to external user and I cannot get SharingInvitationCreated operation as document claims it should occur. Instead I see only SecureLinkCreated, AddedToSecureLink, GroupAdded and SharingSet. Seems that log behavior is changed somehow? Could you please update the document or provide optional information to recognize external share event from the operations I listed above.

Example share event is shared outside the my tenant and it seems it creates a secure link, adds a user to secure link and adds the secure link to the sharepoint group. Is that correct? According the documentation (https://docs.microsoft.com/en-us/office365/securitycompliance/use-sharing-auditing) SharingInvitationCreated  should occur when sharing outside your organization.

Thank you!

**Comment by markjjo** [comment]
@markusmiet The article is out of date. We're evaluating whether to update the topic or remove it. Here are the events related to sharing in SharePoint and OneDrive.

SharingInvitationCreated: A user tried to share an object (likely a site) with an external user resulting in an external sharing invitation being sent. No access is granted at this time.

SharingInvitationAccepted: The external guest has accepted the above invitation and now has access.

AnonymousLinkCreated: An anonymous link was created to this item. As a link can be created & then copied, it is reasonable to consider any document with an anonymous link as being shared.

AnonymousLinkUsed: You can use this event to confirm that a link has been used.

SecureLinkCreated: A user has created a “specific people link” (which may be someone who is external).

AddedToSecureLink: A user has been added onto a specific people link (which may be an external person)

Re: "Example share event is shared outside the my tenant and it seems it creates a secure link, adds a user to secure link and adds the secure link to the sharepoint group. Is that correct? "

Yes, when I share a document with a guest user outside of my org, those are the related events that are logged; also SharingSet. The TargetUserOrGroupType = Guest property appears for the related AddedToGroup event, indicating the resource was shared with guest user.

Tip: Export the audit log by downloading all results. Then use Power Query Editor to transform the JSON object, which will spilt each field in the AuditData column to a separate column. Then you can filter on those columns to drill down the sharing related events. So open audit csv file in Power Query, right-click AuditData column title, click Transform > JSON

**Comment by markjjo** [comment]
@markusmiet Note that AddedToSecureLink event also has TargetUserOrGroupType property, which will have a value of Guest when guest user is added to link. The value of TargetUserOrGroupName will be the guest user.
