### ISSUE TITLE
Minor grammar error

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-o365seccomp#78]
enable the report message add-in for you users.  &gt;&gt; should be "your" users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b6674e7-d943-db79-4cca-410299a36837
* Version Independent ID: c2da9b51-7a0c-7e4e-a932-5d9fb241ffca
* Content: [How to prevent real email from being marked as spam in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/prevent-email-from-being-marked-as-spam?redirectSourcePath=%252farticle%252fhow-to-prevent-real-email-from-being-marked-as-spam-in-office-365-34823bbc-a3e3-4949-ba42-97c73997eeed)
* Content Source: [SecurityCompliance/prevent-email-from-being-marked-as-spam.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@hudish Thank you for this feedback.

We apricate you catching this, I will make sure this gets updated. 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
This is fixed. Thank you @hudish and @AndreaBarr for the feedback.
