### ISSUE TITLE
Creating Custom Queue Alerts

### ISSUE THREAD

**Issue by xkcd350** [MicrosoftDocs/OfficeDocs-o365seccomp#780]
I know that I am able to update the threshold and recipients for this alert through the GUI, however when I view the Alert via Powershell I don't see that the change was made, and because this is a system default I believe that's why I get an error when attempting to Set-ProtectionAlert -identity "GUID/Object" -Threshold 200? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ac8cdad-09bd-cf36-8fe1-4effda8baa03
* Version Independent ID: 3cffbbdd-5ab7-3f0f-6636-fcdf50ba0691
* Content: [Queue alerts and Queues](https://docs.microsoft.com/en-us/office365/securitycompliance/mfi-queue-alerts-and-queues#customize-queue-alerts)
* Content Source: [SecurityCompliance/mfi-queue-alerts-and-queues.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/mfi-queue-alerts-and-queues.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@xkcd350 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
I think that to create alerts the cmdlet should be "[New-ProtectionAlert](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/new-protectionalert?view=exchange-ps)" not set.

Please proceed to post the error you're getting, so we can actually troubleshoot it

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
