### ISSUE TITLE
qualification on the E5 license type

### ISSUE THREAD

**Issue by john-louden** [MicrosoftDocs/OfficeDocs-o365seccomp#784]
Hi,

Just noticed our "Office 365 E5 without Audio" licenses don't have Office 365 Advanced Threat Protection Plan 2. as an option while our M365 E5 licenses do have the option. Is this to be expected?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73681216-32f3-f9a2-51b1-690e4b7c4c38
* Version Independent ID: c3213d50-3e63-4324-7a74-651d4c2b0492
* Content: [Get started with Office 365 Threat Investigation and Response](https://docs.microsoft.com/en-gb/office365/securitycompliance/get-started-with-ti)
* Content Source: [SecurityCompliance/get-started-with-ti.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/get-started-with-ti.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@john-louden Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Honestly, I don't think that's normal @john-louden, please open a ticket to support and update us back to update the documents if it's true or false. I mean at the end it's an E5 license and audio conferencing is not related to ATP.

**Comment by scanum** [comment]
@john-louden Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
