### ISSUE TITLE
Licensing requirements

### ISSUE THREAD

**Issue by garypronych** [MicrosoftDocs/OfficeDocs-o365seccomp#787]
Based on the below lines in this document, does a Teams and EXO license need to be assigned to the user to create the mailbox for online storage? 

The user accounts in your on-premises directory service (such as Active Directory) must be synchronized with Azure Active Directory, the directory service in Office 365. This means that a **mail user account is created in Office 365** and is associated with a user whose primary mailbox is located in the on-premises organization.

**Comment by scanum** [comment]
@garypronych could you please link the document you are referring to? Thanks

**Comment by garypronych** [comment]
@scanum the comments of the article redirected me to this forum, here is the link
https://docs.microsoft.com/en-us/office365/securitycompliance/search-cloud-based-mailboxes-for-on-premises-users

**Comment by scanum** [comment]
Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by markjjo** [comment]
@garypronych FAQ added to topic that answers this licensing question. https://docs.microsoft.com/en-us/office365/securitycompliance/search-cloud-based-mailboxes-for-on-premises-users#frequently-asked-questions
