### ISSUE TITLE
"Phish delivered due to tenant or user override" policy was working too well and is now no longer available

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-o365seccomp#789]
If you, like us got a bunch of alerts from the "Phish delivered due to tenant or user override" policy and then the next day the policy was just gone from the tenant you are not alone.

The implementation of this policy has been revoked and put on hold for now. We will hopefully get an update to the public documentation soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e607177-4e5b-69af-5408-caa6337bbd0e
* Version Independent ID: c82bbeaa-9df1-c070-644b-a666406464b5
* Content: [Alert policies in the security and compliance center](https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies)
* Content Source: [SecurityCompliance/alert-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by jonwbstr** [comment]
For reference, MS Ticket #:14952297

**Comment by markjjo** [comment]
@jonwbstr Thanks for the heads up. We've added footnotes about this and guidance on how to create custom alert policies that recreate the functionality of these alert policies.

https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies#default-alert-policies
