### ISSUE TITLE
eDiscovery and OME

### ISSUE THREAD

**Issue by imnota** [MicrosoftDocs/OfficeDocs-o365seccomp#79]
While the FAQ States that message encryption can be used with eDiscovery, in my experience (and various support calls with Microsoft) this does not appear to be accurate.

If someone external replies to an encrypted email then eDiscovery cannot search within the encrypted email/documents. In fact, other documentation suggests encryption is not compatible with gdpr due to the inability of eDiscovery to search within encrypted messages ( https://docs.microsoft.com/en-gb/Office365/SecurityCompliance/apply-labels-to-personal-data-in-office-365 ).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ad427d-d869-2ab6-3d2c-f846efc99256
* Version Independent ID: 606eaa37-2713-8087-015f-012ae9c90090
* Content: [Office 365 Message Encryption FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/ome-faq#can-i-use-message-encryption-with-compliance-features-such-as-ediscovery)
* Content Source: [SecurityCompliance/ome-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ome-faq.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@imnota Thank you for this feedback

I agree this should be investigated and the article updated. 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by imnota** [comment]
We're 3 months on and the FAQ is still incorrect, is there an expected timescale for correction?
