### ISSUE TITLE
Group enabled team sites

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#790]
Please provide instructions for doing this with Office Group enabled SPO team sites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7fcb1e4-31c8-fb5b-739e-23782d2b4683
* Version Independent ID: ba9d4130-df22-bd93-2138-f04faa09765b
* Content: [Deploy SharePoint Online sites for three tiers of protection](https://docs.microsoft.com/en-us/office365/securitycompliance/deploy-sharepoint-online-sites-for-three-tiers-of-protection)
* Content Source: [SecurityCompliance/deploy-sharepoint-online-sites-for-three-tiers-of-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/deploy-sharepoint-online-sites-for-three-tiers-of-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by DeanGross** [comment]
If we follow these instructions, we won't be able to use Teams with the sites which contain sensitive content, which seem overly restrictive and won't support many business scenarios. Is there any official guidance from MSFT about how to best configure Teams with SPO sites that contain sensitive and/or highly confidential content?

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hello @DeanGross 

Here's the balance between being restrictive (because is sensitive information) and being allowed to share data with people inside and outside organization (MS Teams).

Certainly, there are specifics scenarios where this is required like in your case, but most of the people won't use it in that manner. Another way to help is to do a formal request to Microsoft thru the [Users voice Security and Compliance](https://www.uservoice.com/security-compliance/)

Thank you very much in advance.

**Comment by DeanGross** [comment]
Sorry, but I disagree. Microsoft is demonstrating the use of Teams in the Healthcare industry in which sensitive information is going to be discussed and shared. The documentation should provide guidance for these type of scenarios. 

The link you provided is to the Security and Compliance information for the UserVoice service, and has nothing to do with securing SPO

**Comment by j0rt3g4** [comment]
@DeanGross It's good to disagree, I'd just ask @scanum  to link the authors of the article and see if they can add a more "specifics" article to your answer or if there is anything else that I'm not seeing.

**Comment by dariomws306** [comment]
Hi @DeanGross, thank you for your feedback.

I think at the moment there isn't a similar feature on Microsoft Teams, but Private Channels are coming in August and you will have the ability to create private/confidential Teams:
https://support.office.com/en-us/article/create-a-private-channel-in-teams-60ef929a-4d68-418b-bf4f-5784db184ec9
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16911079-support-for-private-channels?utm_source=t.co&utm_medium=referral
https://www.microsoft.com/en-us/microsoft-365/blog/2019/03/19/microsoft-teams-experiences-intelligent-workplace/#privatechannels
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=50588

Hope that helps.

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
