### ISSUE TITLE
Making notes on Improvement Actions

### ISSUE THREAD

**Issue by whysyn** [MicrosoftDocs/OfficeDocs-o365seccomp#791]
In the security portal, when reviewing Improvement Actions, there is an area to make notes on each action, but no obvious button to save the notes.  They also don't seem to save if there are notes entered when the review button is clicked.  Am I missing something or is the page not working properly?  It would be especially helpful to make notes on the "[Not Scored]" items confirming they are complete, as well as making notes on implementation for any item for audit purposes (date applied, who did it, etc.).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f13e79-166c-a063-ef70-dd4bd45ecc67
* Version Independent ID: d66d3771-8820-2a01-2757-400effef3dc1
* Content: [Microsoft Secure Score](https://docs.microsoft.com/en-us/office365/securitycompliance/microsoft-secure-score#feedback)
* Content Source: [SecurityCompliance/microsoft-secure-score.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/microsoft-secure-score.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by scanum** [comment]
@whysyn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hello @whysyn since we don't have access to any tenant from the documentation perpective we can't say if it's working or not, so please go ahead and proceed with the creation of a ticket using your o365 portal.

https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by dariomws306** [comment]
Hi @whysyn, thank you for your feedback.

Did you test it again?

I can see that there is a Save button and it works:
![image](https://user-images.githubusercontent.com/33589238/61647386-a1fe4680-ac83-11e9-86e1-7580605e2f6c.png)

**Comment by whysyn** [comment]
The save button is now appearing for me.  Thank you!

**Comment by scanum** [comment]
@whysyn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
