### ISSUE TITLE
Add guidance for SPO, ODfB, Teams

### ISSUE THREAD

**Issue by scossio** [MicrosoftDocs/OfficeDocs-o365seccomp#794]
This article is excellent but it is very mailbox-centric. Now that eDiscovery covers all of O365 it would be great to extend the guidance for the other services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cc953eb-258b-03d3-6fdd-03a7d57699ed
* Version Independent ID: b8a1c7cf-0b8a-cb5c-b16a-c1bb4d4ed5e7
* Content: [eDiscovery solution series Data spillage scenario - Search and purge](https://docs.microsoft.com/en-us/office365/securitycompliance/data-spillage-scenariosearch-and-purge)
* Content Source: [SecurityCompliance/data-spillage-scenariosearch-and-purge.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/data-spillage-scenariosearch-and-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@scossio Thanks for the question. At this time, you can only "search and purge" items located in mailboxes (which would include mailboxes corresponding to Teams and Office 365 Groups). Here's some information about deleting items found in sites:

https://docs.microsoft.com/en-us/office365/securitycompliance/datainvestigations/manage-data-spillage-incidents#step-4-delete-the-spilled-data

https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-dsr-office365#deleting-documents-in-sharepoint-online-and-onedrive-for-business
