### ISSUE TITLE
Replace method

### ISSUE THREAD

**Issue by javirivas80** [MicrosoftDocs/OfficeDocs-o365seccomp#795]
Hello, I need some information regarding the Replace method:
-What’s the text description that a user receives when malware or a malicious file is detected? 
-What´s the language, is it a setting that can be modified?
-Can I customize the description? If that’s the case, how do I do that?

Thanks in advance for your response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721eb3a3-eb0d-77a8-0c74-1b9ddb8e963a
* Version Independent ID: 9b8b98f1-2b65-9c11-3fbc-09dcd1c2ed84
* Content: [Set up Office 365 ATP Safe Attachments policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-safe-attachments-policies)
* Content Source: [SecurityCompliance/set-up-atp-safe-attachments-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-safe-attachments-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@javirivas80 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by javirivas80** [comment]
Hello Manuela, I opened a service ticket [Ticket #:15142399] before posting and they couldn’t resolve it. I believe it’s essential that the information I’m requesting is included in the documentation, since it’s important to know beforehand what kind of message the user receives when ATP process the attachments and finds something malicious, so that he, as well as our IT team, can be aware of the expected message. If the user doesn´t know the message, someone could maliciously send an email with a txt attachment asking the user to download a file or enter credentials, which can be rapidly discarded if he knows the ATP message.

**Comment by javirivas80** [comment]
@scanum Hello Manuela, I opened a service ticket [Ticket #:15142399] before posting and they couldn’t resolve it. I believe it’s essential that the information I’m requesting is included in the documentation, since it’s important to know beforehand what kind of message the user receives when ATP process the attachments and finds something malicious, so that he, as well as our IT team, can be aware of the expected message. If the user doesn´t know the message, someone could maliciously send an email with a txt attachment asking the user to download a file or enter credentials, which can be rapidly discarded if he knows the ATP message.
