### ISSUE TITLE
unique count in spam

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#796]
Can we clarify if we show aggregated count of unique email messages in Spam Detection report?
Meaning if the same message has multiple recipients we count it as one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcff63fb-157a-4657-2123-15ce646cd0a8
* Version Independent ID: 2f037070-e3d5-f765-fb7a-b125ff0da981
* Content: [View email security reports in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/view-email-security-reports)
* Content Source: [SecurityCompliance/view-email-security-reports.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/view-email-security-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@pawp81  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by jkubikng** [comment]
I would also like clarification on this point.

**Comment by denisebmsft** [comment]
Hello @pawp81, @jkubikng, and @scanum. I have confirmed that for the Spam Detections report, message counts are per message. So one message sent to multiple recipients counts as one message. I have updated the article accordingly. Changes will be live very soon. Thank you for your feedback!
