### ISSUE TITLE
Need to update as changes now made in SCC portal, not Exchange admin centre

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-o365seccomp#797]
Now indicates that the controls referenced are being removed when trying to follow these instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb11c0e-64ba-029f-5090-37523f41073a
* Version Independent ID: f5bde7e6-5a26-b73f-fbbd-c9ed460d843d
* Content: [Configure the outbound spam policy](https://docs.microsoft.com/en-us/office365/SecurityCompliance/configure-the-outbound-spam-policy)
* Content Source: [SecurityCompliance/configure-the-outbound-spam-policy.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@aldoug  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
Confirmed. When you try to edit the Default policy in the EAC at **Protection** \> **Outbound spam**, you now get the following notification:

![image](https://user-images.githubusercontent.com/33166947/64056867-68a2db80-cb4b-11e9-9fae-b23cbb51f547.png)

Will refactor the topic for SCC.

**Comment by chrisda** [comment]
OK. Done. Thanks for the feedback.
