### ISSUE TITLE
Incorrect selector hostname documentation

### ISSUE THREAD

**Issue by jonarmstrong** [MicrosoftDocs/OfficeDocs-o365seccomp#80]
The documentation for the host name of the selector cname record indicates that it should be in the form: selector1._domainkey.&lt;domain&gt;

However; I've been unable to get it to work with that syntax, I've had to omit .&lt;domain&gt; from the end of the selector1 and selector 2 records to get DKIM to enable successfully on exchange online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM to validate outbound email sent from your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dkim-to-validate-outbound-email)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@jonarmstrong Thank you for this feedback

I agree this should be updated. 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jessicagray** [comment]
I was coming here to post this exact thing. Glad to see there is a fix planned.

**Comment by AndreaBarr** [comment]
@jonarmstrong I am going to close this again until we have an update

**Comment by garciacrew** [comment]
> I am trying the above with CloudFlare and do not seem to have any luck. If I try to put the full domain selector1._domainkey. the . portion is removed and only selector1._domainkey remains. However, it does not verify.

I figured it out.  I removed the "." from the domain and entered it as one expression.  See example below.

`selector1._domainkey.customdomaincom`

**Comment by KCCross** [comment]
Update: We have a team testing the various ISPs we support. Thanks for your patience on this one. Same as the previous comment for GoDaddy.

**Comment by student-forever** [comment]
Just following up to check if there are any updates on this thread?

Need to confirm if the format needs to be the following:

Host name:			selector1._domainkey.cohovineyard.com
Points to address or value:	selector1-cohovineyard-com._domainkey.cohovineyardandwinery.onmicrosoft.com
TTL:				3600

Host name:			selector2._domainkey.cohovineyard.com
Points to address or value:	selector2-cohovineyard-com._domainkey.cohovineyardandwinery.onmicrosoft.com
TTL:				3600

**Comment by student-forever** [comment]
Just to add, I was referring to the article below for the syntax info:

https://social.technet.microsoft.com/wiki/contents/articles/36796.office-365-enabling-dkim-for-custom-domains.aspx?Redirected=true

**Comment by Absoblogginlutely** [comment]
Looks like the extra period at the end of the hostname has been removed from the documentation. 

@student-forever , yes the hostname you mentioned is correct.

I think the confusion lies in how various dns web forms require the hostname to be filled out. Some require a trailing period - others don't.
However as long as your nslookup resolves correctly, that is the test as to whether it's working or not.
As the trailing period no longer shows up and the examples look correct I would therefore recommend this issue be closed.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
