### ISSUE TITLE
10 DNS queries for an SPF record lookup

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-o365seccomp#803]
The error mentioned in this article has nothing to do with DNS queries for spf records:
the sender may receive a message that states that the  "maximum hop count for the message has been exceeded".
Maximum hop count exceeded will only trigger if an email loop is detected. It has nothing to do with SPF records.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32b69213-5d1c-52d3-cd3b-08eb807e0bae
* Version Independent ID: 9452e9e5-d824-7950-84de-309f45f65fcd
* Content: [How Office 365 uses Sender Policy Framework (SPF) to prevent spoofing](https://docs.microsoft.com/en-us/office365/securitycompliance/how-office-365-uses-spf-to-prevent-spoofing)
* Content Source: [SecurityCompliance/how-office-365-uses-spf-to-prevent-spoofing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/how-office-365-uses-spf-to-prevent-spoofing.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@JeroenDronkers  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by MSFTTracyP** [comment]
Investigating this issue.

**Comment by MSFTTracyP** [comment]
When the look-up is exhausting the DNS timeout due to being in a loop this error message can show up for people. A common cause is a cached address which is somehow incorrect (though it can also be missing, and this error message won’t actually detail that). This error may also occur for other reasons, something to keep in mind during troubleshooting.
