### ISSUE TITLE
Issue when uploading a rule package

### ISSUE THREAD

**Issue by williamhimself** [MicrosoftDocs/OfficeDocs-o365seccomp#808]
After attempting to upload a rule package I get this error:

The classification rules collection load failed to be validated against the target schema. The following error was found on line number 1, position 1, on load: The namespace document  "http://schemas.microsoft.com/office/2018/mce" it is incorrect. The namespace document expected is "http://schemas.microsoft.com/office/2011/mce".
    + CategoryInfo          : InvalidData: (:) [New-DlpSensitiv...TypeRulePackage], ClassificationR...dationException
    + FullyQualifiedErrorId : [Server=BN3NAM01WS028,RequestId=476d95dc-ddca-4101-85fe-8bbd2059755e,TimeStamp=09/07/2019 17:21:52] [F
   ailureCategory=Cmdlet-ClassificationRuleCollectionSchemaValidationException] EB9C06D7,Microsoft.Office.CompliancePolicy.Tasks.Ne
  wDlpSensitiveInformationTypeRulePackage
    + PSComputerName        : nam01b.ps.compliance.protection.outlook.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573f2126-d59c-0db8-8540-7fade663caf8
* Version Independent ID: 52031680-fb4e-23b2-4bad-6cd1ea31a15e
* Content: [Create custom sensitive information types with Exact Data Match](https://docs.microsoft.com/en-us/office365/securitycompliance/create-custom-sensitive-info-type-edm#feedback)
* Content Source: [SecurityCompliance/create-custom-sensitive-info-type-edm.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-custom-sensitive-info-type-edm.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@williamhimself Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum
