### ISSUE TITLE
Please update this article to reflect that E3 can have DLP for Teams

### ISSUE THREAD

**Issue by MarcusCKLee** [MicrosoftDocs/OfficeDocs-o365seccomp#812]
Please update this article to reflect that E3 can have DLP for Teams

**Comment by scanum** [comment]
@MarcusCKLee Hi Marcus, please link the article you are referring to. Thanks.

**Comment by MarcusCKLee** [comment]
Hi Manuela,

Apologise for the late reply, I have uploaded my comment and the article
link.

**Comment by scanum** [comment]
@MarcusCKLee I still don't see it. Please update as soon as possible. Thanks.

**Comment by MarcusCKLee** [comment]
Hi Manuela,

Please find below the info:
A paragraph in the article ( https://docs.microsoft.com/en-us/office365/securitycompliance/dlp-microsoft-teams ) stated that E3 license offers DLP for Teams and it does not require the Advanced Compliance Add-on. It provided an example of defining a DLP policy in SharePoint and OneDrive that can prevent sensitive information from being shared in Teams chat of channel conversations.

Excerpt from the article:
Example 2: Protecting sensitive information in documents. Suppose that someone attempts to share a document with guests in a Microsoft Teams channel or chat, and the document contains sensitive information. If you have a DLP policy defined to prevent this, the document won't open for those users. Note that in this case, your DLP policy must include SharePoint and OneDrive in order for protection to be in place. (This is an example of DLP for SharePoint that shows up in Microsoft Teams, and therefore requires that users are licensed for Office 365 DLP (included in Office 365 E3), but does not require users to be licensed for Office 365 Advanced Compliance.)

However its title itself does not state about E3 can offer DLP for Teams.
Header Note from the article:
Data loss prevention capabilities were recently added to Microsoft Teams chat and channel messages for users licensed for for Office 365 Advanced Compliance, which is available as a standalone option and is included in Office 365 E5 and Microsoft 365 E5 Compliance. To learn more about licensing requirements, see Microsoft 365 Tenant-Level Services Licensing Guidance.

In my opinion, this article must be clearly stating
[E3 can enable DLP for Teams with expected result.pdf](https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/files/3418133/E3.can.enable.DLP.for.Teams.with.expected.result.pdf)
 about E3 does offer DLP for Teams by elaborating with more examples when defining policies for SharePoint and OneDrive that will offer DLP for Teams.

At the moment, one of my customers is reluctant to transition to Teams due to the lack of 'clear' official document from Microsoft.

We have also confirmed by defining DLP for Teams and tested with expected result: sensitive information will be blocked by the defined policies. However, the customer need a clear official document that states E3 does offer DLP for Teams from Microsoft.

Please find attached the screenshot of the customer tenant that illustrates the policies that have been defined in Teams that tested with expected result.

Looking forward to your reply.

Thanks.

**Comment by MarcusCKLee** [comment]
Hi Manuela,

I have commented it.

**Comment by chrfox** [comment]
Hi, Thanks for your question.  I am investigating internally to see if Microsoft 365 E3 includes DLP.

**Comment by MarcusCKLee** [comment]
Hi Chris,

Thanks for following up.
Looking forward to your update.

**Comment by chrfox** [comment]
published update
