### ISSUE TITLE
Wait for URL scanning to complete before delivering the message Doesnt Exist in Options

### ISSUE THREAD

**Issue by tepperj** [MicrosoftDocs/OfficeDocs-o365seccomp#813]
This option isn't show up in configuration of SafeLinks.
**Wait for URL scanning to complete before delivering the message** 
I originally put it in our testing plan and now its gone.

**Comment by scanum** [comment]
@tepperj thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
