### ISSUE TITLE
What is the difference between real-time detection and Threat Explorer

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#817]
I think it would be good to point out what are the differences between real-time detection and Threat Explorer apart from the fact the one comes with ATP P1 and the other with ATP P2.
The differences I am aware of are: "All mail" view, URL filters...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7a592b-f888-32e7-8226-484ddc20acc4
* Version Independent ID: d97a1c36-5d8d-53f9-262b-b715d96dc330
* Content: [Threat Explorer (and real-time detections)](https://docs.microsoft.com/en-us/office365/securitycompliance/threat-explorer)
* Content Source: [SecurityCompliance/threat-explorer.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/threat-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
#Solving Issue #818 by adding 3 differences, if this can be checked by author and team :) please let me know @scanum #865

**Comment by j0rt3g4** [comment]
PR #866 Added 3 differences please check.

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by pawp81** [comment]
No the issue is not closed. I mentioned that I would recommend more precisely documenting what the differences between Threat Explorer and real-time detections.  This sentence is not very helpful: "The real-time detections report allows you to view detections in real-time. Threat Explorer does this as well, but also allows you to view additional details for a given attack." I would recommend adding that Threat Explorer provides: "All mail" view, "URL" filtering and Machine information (when integration with MDATP is enabled).
