### ISSUE TITLE
Enable mailbox intelligence based impersonation protection

### ISSUE THREAD

**Issue by antede** [MicrosoftDocs/OfficeDocs-o365seccomp#818]
Can you please further clarify what the recenty added "Enable mailbox intelligence based impersonation protection" option in the Mailbox Intelligence section does? What is the exact difference between "Enable mailbox intelligence" and "Enable mailbox intelligence based impersonation protection" ? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies#phishpolicyoptions)
* Content Source: [SecurityCompliance/set-up-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@antede Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by pawp81** [comment]
Any progress on documenting "mailbox intelligence based impersonation protection"?

**Comment by denisebmsft** [comment]
Hello! We have updated this article to include more information about mailbox intelligence. I'm going to close this issue at this time, but please let us know if you have any further questions.

**Comment by MSFTTracyP** [comment]
![image](https://user-images.githubusercontent.com/33558605/63975785-a5e06e00-ca64-11e9-9eb2-fc8cb21746a3.png)

**Comment by MSFTTracyP** [comment]
Ah! The second option is about applying Mailbox Intel to impersonation issues rather than just spoofing situations. You can also think of this as what Exchange Online Protection does, versus the part available through ATP.
