### ISSUE TITLE
How can I restore a deleted mail item with -PurgeType HardDelete?

### ISSUE THREAD

**Issue by jaehungim31** [MicrosoftDocs/OfficeDocs-o365seccomp#819]
In the text, it is written as follows.
A message that's deleted with the New-ComplianceSearchAction -Purge -PurgeType HardDelete command is moved to the Purges folder and can not be accessed by the user. After the message is moved to the Purges folder, the message is retained for the duration of the deleted item.

However, you can not find the Purges folder to which you want to restore mail, nor can you find deleted mail items in your Purges folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61322e04-93a6-100c-4fba-43366e2e3dfc
* Version Independent ID: 0c03b380-5b46-8ef5-6cc2-1545031e5645
* Content: [Search for and delete email messages in your Office 365 organization - Admin Help](https://docs.microsoft.com/en-us/office365/securitycompliance/search-for-and-delete-messages-in-your-organization#feedback)
* Content Source: [SecurityCompliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jaehungim31 You are correct that a user can't access the Purges folder. But if single item recovery is enabled for a mailbox and if the deleted item retention period for the hard-deleted item has not expired, then an admin can use the Content Search tool in the Security & Compliance Center to search for items in the Purges folder. If the mailbox is on hold, hard-deleted items will be preserved and an admin can search for them.
