### ISSUE TITLE
Able to create alert for external user

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#82]
The Before you Begin section above states that " You can't use this page to create alerts for activity performed by external users." However, I am able to create an alert for an external guest user that I have enabled through Azure B2B. Can you please explain why I can do this or clarify the text above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb61519-dd23-0fc2-f91a-4c9db668875c
* Version Independent ID: 618e4a73-a59e-39e1-13d2-3d1ad7ebb9b5
* Content: [Create activity alerts in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/create-activity-alerts#more-information)
* Content Source: [SecurityCompliance/create-activity-alerts.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-activity-alerts.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

I agree this needs to get investigated and the article updated. 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@DeanGross The Before You Begin section specifically says you can "...create alerts only for activity **performed by users who are listed in your organization's address book**. You can't use this page to create alerts for activity performed by external users **who aren't listed in the address book**. In other words, you can create activity alert for anyone who has been sync'd to Azure Active Directory. So guest users have a AAD identity and would be available in the address book. I can clarify this in the topic.
