### ISSUE TITLE
reason=904?

### ISSUE THREAD

**Issue by vgabriel-rutgers** [MicrosoftDocs/OfficeDocs-o365seccomp#822]
It would be good if all the reasons were published. I am trying to figure out what reason=904 actually means. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab02396-69f6-5a83-fc27-7a2ba9ab78eb
* Version Independent ID: 63266ff4-ef2a-84b3-f1b9-c7b3e4d8a1b7
* Content: [Anti-spoofing protection in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/anti-spoofing-protection)
* Content Source: [SecurityCompliance/anti-spoofing-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spoofing-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@vgabriel-rutgers Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
The exact reason it's here:
https://answers.microsoft.com/en-us/msoffice/forum/all/mail-marked-as-spam/116d2a00-673e-4eba-ab38-0aadf7466982

Also, you can use a support ticket for O365 to know exactly what's going on.

**Comment by vgabriel-rutgers** [comment]
I don't see 904 anywhere in that thread, documentation shouldn't be in random threads, nor should it require a support call.

**Comment by scanum** [comment]
@vgabriel-rutgers Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
