### ISSUE TITLE
Is the limit on the number of simultaneous exports per user configurable?

### ISSUE THREAD

**Issue by michaelblumenthal** [MicrosoftDocs/OfficeDocs-o365seccomp#823]
Is there a way to configure this limit? Our eDiscovery Manager sometimes needs to do more than three exports at a time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdb113e3-c0e8-79c0-4cdb-a085e0eaffdb
* Version Independent ID: a26fcb1e-907d-13d4-c13f-a7883b4138e3
* Content: [Export Content Search results](https://docs.microsoft.com/en-us/office365/securitycompliance/export-search-results#feedback)
* Content Source: [SecurityCompliance/export-search-results.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/export-search-results.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@michaelblumenthal Unfortunately, this is not configurable. As you probably know, there is an organizational limit of 10 simultaneous exports. So you could enable other eDiscovery Managers to export search results to get beyond the 3 exports per user limit.
