### ISSUE TITLE
authenticated senders still marked 'unverified'

### ISSUE THREAD

**Issue by ChrissieBrownWEC** [MicrosoftDocs/OfficeDocs-o365seccomp#840]
Even when the sender is ourselves (eg. online form from our own website), and our Admin has listed ourselves as a trusted sender, the Outlook O365 app still marks the emails as 'We could not verify the identity of the sender'. This is SO frustrating.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b48decb0-39eb-38f5-9708-883fe6b4dc6f
* Version Independent ID: c474dfc8-d061-c4d5-31d1-45d8bb6c2f8e
* Content: [Unverified Sender](https://docs.microsoft.com/en-gb/office365/securitycompliance/unverified-sender-feature#feedback)
* Content Source: [SecurityCompliance/unverified-sender-feature.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/unverified-sender-feature.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@ChrissieBrownWEC  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by MSFTTracyP** [comment]
@ChrissieBrownWEC - That's got to be annoying. Okay, so to short-circuit this issue I'll tell you that you have to take this one to support so they can untangle what's happening to you.

https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone

Thank you!
