### ISSUE TITLE
Please indicate where to find those screens that you show in this article

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-o365seccomp#841]
It may be clear to the author what Microsoft portal this refers to, but it is not explained to the reader. I thus have not found where to find this, even after reading the whole article. Please repeat, throughout the article, where one has to go/click to find the equivalents screens/settings as the ones you are talking about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by blouwagie** [comment]
I since found the URL, it is  https://protection.office.com/retention , please sprinkle this in a few relevant places.

**Comment by scanum** [comment]
@blouwagie  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dplotnikov** [comment]
@stephow-MSFT please merge the PR and feel free to close this issue
