### ISSUE TITLE
Principles of retention graphic enchancement

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-o365seccomp#842]
The graph with the four blue blocks indicating the principles of retention also need to include a fifth box "the legal hold" box.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@blouwagie  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dplotnikov** [comment]
@stephow-MSFT please merge the PR and feel free to close this issue

**Comment by dplotnikov** [comment]
@stephow-MSFT please note that I've created 2 PRs - one with a text change and the 2nd one is to update image

**Comment by stephow-MSFT** [comment]
I commented on this in the related pull request - legal hold is really a separate scenario from retention. It's mentioned here as a related footnote.
