### ISSUE TITLE
Time frame

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/OfficeDocs-o365seccomp#846]
How long will launched scenarios last when you simulate a spear-phishing attack?  Do they expire?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator#new-features-in-attack-simulator)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@HarrisburgUSysAdmin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by denisebmsft** [comment]
Hello! I am looking into this, and I'll post an update here soon.

**Comment by denisebmsft** [comment]
Hello, everyone! Although I am going to close this issue out, I have a work item in my queue to update the Attack Simulator content. The updates will address your questions about the duration of a launched simulated attack. So please know that even though I'm closing the issue, this isn't off my radar.
