### ISSUE TITLE
Shortlink in encrypted mail goes to the wrong page.

### ISSUE THREAD

**Issue by SjorsKrebbeks** [MicrosoftDocs/OfficeDocs-o365seccomp#848]
When you send an encrypted mail people get the following message if they don't have the software to open it. 
=========================
This message is protected with Microsoft Information Protection. You can open it using Microsoft Outlook, which is available for iOS, Android, Windows, and Mac OS. Get Outlook for your device here: https://aka.ms/protectedmessage.

Microsoft Information Protection allows you to ensure your emails can't be copied or forwarded without your permission. Learn more at https://microsoft.com/rms.
==========================

The URL in it (https://aka.ms/protectedmessage) isn't exactly suitable for end users. Probably a good idea to forward that URL to a download page to allow people to read encrypted mail.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 12629dc8-4ce5-f4f9-dc32-8356eb357f33
* Version Independent ID: 877bf185-bd2f-c546-933e-a69b660737a9
* Content: [Set up new Office 365 Message Encryption capabilities](https://docs.microsoft.com/nl-nl/office365/securitycompliance/set-up-new-message-encryption-capabilities?redirectSourcePath=%252fen-us%252farticle%252fSet-up-new-Office-365-Message-Encryption-capabilities-built-on-top-of-Azure-Information-Protection-7ff0c040-b25c-4378-9904-b1b50210d00e#feedback)
* Content Source: [SecurityCompliance/set-up-new-message-encryption-capabilities.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-new-message-encryption-capabilities.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@SjorsKrebbeks  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by jbalcorn** [comment]
I just received a message from my bank and have no reasonable way to read it.  The links included automatically in the email take me to configuration page for Azure Rights Management and a page all about Azure Rights Management, not to a place where I can download outlook for windows.

**Comment by SjorsKrebbeks** [comment]
@jbalcorn You can find the clients here:
https://portal.azurerms.com/#/download

It's not outlook but it will help 👍

**Comment by KCCross** [comment]
This has been taken on by the product team. Thanks for flagging it!
