### ISSUE TITLE
This vs Exchange Online Retention Tags/Policies - what wins?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-o365seccomp#85]
It needs to be nice and clear which system wins if both are configured.  That is, if I configure and apply retention tags and policies in Exchange Online, and then also configure and apply a retention policy via Security and Compliance Center - which one takes precedence if there are conflicts?

I'm comparing this page with this other page - https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mrm/retention-tags-and-retention-policies?view=exchserver-2019

Please comment so there is official confirmation.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc3ec331-b731-119d-35f8-3838c77ddc71
* Version Independent ID: f371ba68-36b0-51eb-19bd-1dc4dce89abd
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies?redirectSourcePath=%252farticle%252f5e377752-700d-4870-9b6d-12bfc12d2423#use-a-retention-policy-instead-of-these-features)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@JeremyTBradshaw Thank you for this feedback

Chris was able to answer this by updating on the other issue you opened https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/130 . We appreciate you catching this so we can get it updated.

**Comment by JeremyTBradshaw** [comment]
Thanks @AndreaBarr.  I'm reopening this issue as well.  Ideally, both this article and the other one should have the answer stated within.  That will ensure that each article standing on its own is clear about this.

Once the other article gets it, I can do the pull request / merge request to get the same info into this article.

I use these pages throughout the year over and over for customer projects and it's really nice to be able to state that things work a certain way, and then point to official documentation to confirm the statement.

**Comment by JeremyTBradshaw** [comment]
FYI that MS Support has gone silent and the question remains unanswered.  I think there's actually a chance that nobody knows and Mr. Office 365 Retention Policy has never even met Mr. Exchange Retention Policy, or had any discussions about what should be published in regards to what happens when customers decide to use them both.  The inability to see O365 policies from the EXO perspective, while the EXO policies are still fully visible and functional in EXO is, at least to me, very confusing.  It's not that I have a learning disability, it's a huge undocumented gap that is seemingly being ignored with intent.

Every article on the internet just glazes over the whole in-between topic, and either touches one or the other, but not both at the same time or transitioning from one to the other.

> [Ticket #:11573061]
> <name removed> (Microsoft)
> Thursday, October 4, 2018 2:09 AM GMT
> 
> Hello Jeremy,
> 
> Greetings of the day. Hope you are doing well.
> First and foremost, I would like to apologize for the delay in contacting you as promised. I sincerely look forward assisting you on your issue. This case is under discussion. I will once I get update on this.
> Thank you for choosing Microsoft Professional Support and for your continued trust on our products and services.
> Thank you for being a part of Microsoft Family. Thank you for choosing Microsoft.
> 
> Thanks and Regards
> <name removed> |  Support Engineer | M365

**Comment by AndreaBarr** [comment]
@JeremyTBradshaw We are sorry that you are having this experience. I am going to get this issue escalated for you. Thank you for reaching out to us to let us know what was going on.

**Comment by JeremyTBradshaw** [comment]
I apologize for the nastiness.  I've heard back from MS support and am told it is still being discussed in house.  I'll update back here with the resolution once it is found.
