### ISSUE TITLE
Update to AzCopy v10

### ISSUE THREAD

**Issue by ilantz** [MicrosoftDocs/OfficeDocs-o365seccomp#850]
The link on the wizard redirects to https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy so you would use the new version and not v8.1

The new version is working as long as you'll use the right parameters.. for example:

AzCopy.exe copy "C:\nonO365data" "https://speur01salinkexternal003.blob.core.windows.net/7a6b766d-04fc-4840-91bc-xxxxxxx-xxxxxx-externalstore/?sv=2017-07-29&sr=c&si=ExternalStore63%7C1&sig=QK%xxxxXXXXXxxx%2FLDk%3D" --recursive

Believe we should update both the docs and the wizard in the product itself.

_Originally posted by @ilantz in https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/324#issuecomment-513547736_

**Comment by scanum** [comment]
@ilantz  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ilantz Thank you for reaching out and helping improve MS Docs.  Which article are you referring to?  Could you please be a bit more specific about what changes need to be made in which articles and I can have it done soonest.

**Comment by ilantz** [comment]
This about AzCopy and importing non office 365 data into Advanced eDisocvery, one affected article is this - https://docs.microsoft.com/en-us/office365/securitycompliance/compliance20/troubleshooting-azcopy

**Comment by lindspea** [comment]
@ilantz Thank you for this, but what needs to be changed in the document you mention above?  Please could you be a bit more specific. The article you reference above is showing the link to v 10.

**Comment by ilantz** [comment]
Yes, that's exactly the problem. the link within the product is pointing to the latest version while the highlighted command that the wizard is constructing won't work. 

so that's why i believe we should align to v10, currently the docs are for the 8.1 old version while the link on the wizard is pointing to v10...

**Comment by lindspea** [comment]
@ilantz Okay, I'm with you now.  Thanks for that.  I'll make the changes soonest.

**Comment by markjjo** [comment]
@ilantz Updated topic has been published.
