### ISSUE TITLE
Order of the rules

### ISSUE THREAD

**Issue by ccadenasa** [MicrosoftDocs/OfficeDocs-o365seccomp#853]
In this article, about DLP policies, the rule for high volume has priority over the low volume rule. Is this correct? When the policy is created, the default is on the other way round. Can you please confirm?

**Comment by scanum** [comment]
@ccadenasa Please reference the article you are mentioning, thanks.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ccadenasa thank you for reaching out, but please can you let me know which article you are referring to and I can investigate to get the answer for you.

**Comment by scanum** [comment]
@ccadenasa We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
