### ISSUE TITLE
Unlimited Archives 

### ISSUE THREAD

**Issue by simarino** [MicrosoftDocs/OfficeDocs-o365seccomp#854]
Please clarify somewhere in our documentation that the number of AUX archives which is forming the so called 'unlimited archives' for EXO Plan 2 based mailboxes is actually 20 AUX Archives. This can't be increased at the moment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9058ce15-b039-ca90-821d-01edf4d86bdf
* Version Independent ID: b30e615e-0405-ec16-e931-c3bfed196b63
* Content: [Overview of unlimited archiving in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/unlimited-archiving?redirectSourcePath=%252farticle%252fOverview-of-unlimited-archiving-in-Office-365-37cdbb02-a24a-4093-8bdb-2a7f0b3a19ee#feedback)
* Content Source: [SecurityCompliance/unlimited-archiving.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@simarino Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@simarino Thank you for reaching out and helping improve MS Docs.  I'll have the information added soonest.

**Comment by simarino** [comment]
Hi,

Did you confirm this with engineering?
Also could you tell me if you checked if it's checked with licensing?
If this will be putting sells at risk i want to cancel the change.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lindspea** [comment]
@markjjo please can you confirm if this change is allowed to be made to the doc and I'll do the PR?

**Comment by lindspea** [comment]
@markjjo

**Comment by scanum** [comment]
@markjjo  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
