### ISSUE TITLE
Search permission filter count

### ISSUE THREAD

**Issue by Allaen** [MicrosoftDocs/OfficeDocs-o365seccomp#855]
I am working mostly for global corporations with several legal entities. There is a need to setup compliance boundaries for each legal entity combined with country as e.g. on legal entity could operate in several countries and data can't leave the country through an eDiscovery search. This fact alone leads to more than 100 filters that are necessary even when combining Exchange, OneDrive & SharePoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f37089-3459-9e8e-f336-cb3bd236601f
* Version Independent ID: 3e595e12-d834-fb8d-a7c0-efb2931cd82e
* Content: [Set up compliance boundaries for eDiscovery investigations in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-compliance-boundaries#feedback)
* Content Source: [SecurityCompliance/set-up-compliance-boundaries.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-compliance-boundaries.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@Allaen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Allaen Thank you for reaching out and helping improve MS Docs.  Are you suggesting adding a note about this in the article?

**Comment by lindspea** [comment]
@markjjo

**Comment by markjjo** [comment]
@allaen Please feel free to give feedback about this at https://office365.uservoice.com/forums/289138-office-365-security-compliance

Though it sounds like you're already doing this, using a filters list in the fileter as documented here (see note in step 4) may help reduce the number of filters: https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-compliance-boundaries#step-4-create-a-search-permissions-filter-to-enforce-the-compliance-boundary
