### ISSUE TITLE
Delete limit?

### ISSUE THREAD

**Issue by greg4168** [MicrosoftDocs/OfficeDocs-o365seccomp#858]
If I use Threat Explorer to search on an non-threatening email that was mistakenly sent to the entire company with the goal of deleting it, the search brings up 50 messages per page.  Would using Select All include all messages or just the ones displayed?  Is this a recommended method of doing a mass message delete?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2002ebb1-c4b0-5832-8732-d71a78ababe7
* Version Independent ID: 125916be-6793-932f-c71f-6e87434f7180
* Content: [Views in Threat Explorer and real-time detections](https://docs.microsoft.com/en-us/office365/securitycompliance/threat-explorer-views#feedback)
* Content Source: [SecurityCompliance/threat-explorer-views.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/threat-explorer-views.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@greg4168 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@greg4168 Thank you for reaching out. I'll investigate further and have an answer for you soonest.

**Comment by lindspea** [comment]
@greg4168 'Select All' would delete the messages displayed on the page.  This is recommended for mass message deletion.  Let me know if you have any further questions.

**Comment by greg4168** [comment]
> 
> 
> @greg4168 'Select All' would delete the messages displayed on the page. This is recommended for mass message deletion. Let me know if you have any further questions.

Hi Lindsay - so that would just delete messages on the one page.  What if I want to delete all rather than just the first page?

**Comment by lindspea** [comment]
@greg4168 As far as I know there should be an option to increase the number of items displayed on the page, so you would be able to delete more at one time, but let me investigate further and get back to you on that one.

**Comment by denisebmsft** [comment]
Hello, all! I've reached out to our product team and have an answer for you on this.

Threat Explorer is designed to hunt/find malicious email messages that somehow made it through antiphishing, antimalware, and antispam features in Office 365. When you want to delete a non-threatening email message, your best bet is to go to the user's inbox from where the email message was sent, and recall that message. 

Another option is to use zero-hour auto purge [(Zero-hour auto purge)](https://docs.microsoft.com/office365/securitycompliance/zero-hour-auto-purge) to accomplish this task. 

If you do use Threat Explorer to delete a non-threatening message, Threat Explorer will add all the messages you select to an incident, which you can then review before taking action. 

We do recommend adding all email messages that you want to take action on to an incident, and then review the incident before taking action.

I hope this helps!
