### ISSUE TITLE
Commands are wrong

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/OfficeDocs-o365seccomp#859]
### Problem

In _**To enable DKIM signing for your custom domain by using PowerShell**_ section, you have following statement:

> 2. Run the following command:
> ```
> New-DkimSigningConfig -DomainName <domain> -Enabled $true
> ```
> Where domain is the name of the custom domain that you want to enable DKIM signing for.
> 
> For example, for the domain contoso.com:
> ```
> New-DkimSigningConfig -DomainName contoso.com -Enabled $true
> ```

However, it fails since we already have **DkimSigningConfig** object of our custom domains. In the previous section, _**To enable DKIM signing for your custom domain through the admin center**_, you have the following statement since we already have the target object.

> 5. Select the domain for which you want to enable DKIM and then...

### Proposal

Replace the command with **Set-DkimSigningConfig**.

```
Set-DkimSigningConfig -DomainName <domain> -Enabled $true
```

Same as above, the example should be like following.

```
Set-DkimSigningConfig -DomainName contoso.com -Enabled $true
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM for email in your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dkim-to-validate-outbound-email)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@hishikitetsuya Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@hishikitetsuya Thank you for pointing this out and helping improve MS Docs. I'll investigate further and make the necessary changes.

**Comment by scanum** [comment]
@hishikitetsuya Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by hishikitetsuya** [comment]
@scanum  I am happy with the PR. thanks.
