### ISSUE TITLE
Link to SharePoint Data resiliency is broken

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#860]
When I click on the "SharePoint Data resiliency" link it takes me to the same page - Data Resiliency in Office 365. SP Data resiliency page is also missing from the left menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20e9936-697a-fd79-ec14-f56e89fa29e9
* Version Independent ID: e4e4ed6b-8501-3124-9d41-81cb3a5fd39f
* Content: [Data Resiliency in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-data-resiliency-overview)
* Content Source: [SecurityCompliance/office-365-data-resiliency-overview.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-data-resiliency-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Larryngolog Thank you for reaching out and helping improve MS Docs.  Would this link suffice? https://docs.microsoft.com/office365/securitycompliance/office-365-exchange-data-resiliency. Please let me know and I can have it added to the article.

**Comment by lindspea** [comment]
@Larryngolog have you had a chance to review the link above?

**Comment by Larryngolog** [comment]
@lindspea there used to be an article for SPO, you can still see it in the april branch https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/blob/origin/April-CustomerKey-updatesTOC/SecurityCompliance/office-365-sharepoint-data-resiliency.md

**Comment by lindspea** [comment]
@robmazz Just to confirm this link is still relevant and I can have it added in a PR?

**Comment by robmazz** [comment]
@Larryngolog and @lindspea  - Thanks for the feedback. The SharePoint data resiliency topic was removed, it was very outdated and we're discussing ideas for an updated replacement. I removed the link to the topic from the main Office 365 data resiliency topic. Thanks!
