### ISSUE TITLE
Routing and Export for Canada Geo region confusing

### ISSUE THREAD

**Issue by Allaen** [MicrosoftDocs/OfficeDocs-o365seccomp#861]
Searching and exporting content in Multi-Geo environments section refers to the region parameter and which datacenter will be used to route searches to and export data. The two tables don't match for Canada (CAN). Please clarify when Canada data centers will be used if region parameter CAN is set and when USA data centers are used even if CAN region parameter is set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f37089-3459-9e8e-f336-cb3bd236601f
* Version Independent ID: 3e595e12-d834-fb8d-a7c0-efb2931cd82e
* Content: [Set up compliance boundaries for eDiscovery investigations in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-compliance-boundaries)
* Content Source: [SecurityCompliance/set-up-compliance-boundaries.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-compliance-boundaries.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@Allaen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by markjjo** [comment]
@allaen Thanks for pointing this out. We have updated the topic and tried to clarify. https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-compliance-boundaries#searching-and-exporting-content-in-multi-geo-environments

Specifically, IF the Region parameter is set to CAN, THEN content searches of SP and OD sites will go through US datacenters AND exports of content search results will go through CAN datacenters.
