### ISSUE TITLE
Documents hanging forever?

### ISSUE THREAD

**Issue by marekkis** [MicrosoftDocs/OfficeDocs-o365seccomp#862]
Content awaiting a disposition review is deleted only after a reviewer chooses to permanently delete the content. - If a reviewer takes no action, for how long the document will be available for a reviewer to take action and for a user? Let´s say that a document test1.docx is after a 2 years of retention (Policy1) now awaiting a disposition review (Policy1) and there is a second policy (Policy2) applied to test1.docx which is set to delete a document after 2 years but a reviewer takes no action. What happens with test1.docx? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d6bbdc-15c0-1f90-85c3-eb950d3a4837
* Version Independent ID: f4810537-30d6-0451-f9fa-62da1af72f2b
* Content: [Overview of disposition reviews](https://docs.microsoft.com/en-us/office365/securitycompliance/disposition-reviews#feedback)
* Content Source: [SecurityCompliance/disposition-reviews.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@marekkis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@marekkis Thank you for reaching out and helping improve MS Docs.  Some information from the doc that might have been recently updated: 
   - Content in a document library will be moved to the first-stage Recycle Bin within 7 days of disposition, and then permanently deleted 93 days after that. The Recycle Bin is not indexed by search and therefore its contents are not available to an eDiscovery hold.
   - Content in the Preservation Hold library will be permanently deleted within 7 days of disposition.
   - Items in an Exchange mailbox will be permanently deleted within 14 days of disposition. (Note that 14 days is the default setting but it can be configured up to 30 days.)
Please let me know if that answers your questions.

**Comment by scanum** [comment]
@marekkis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
