### ISSUE TITLE
Transport rules predicates

### ISSUE THREAD

**Issue by Dottn** [MicrosoftDocs/OfficeDocs-o365seccomp#87]
>For more information about mail flow rule conditions in Exchange Online Protection, see Mail flow rule conditions and exceptions (predicates) in Exchange Online Protection.

That paragraph links to the parent page, Mail flow in EOP, which doesn't contain any information on the predicates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36425a1e-3618-c089-b143-8c1a191adf64
* Version Independent ID: 9cbd390d-9813-c7bc-2957-8c2be4a50949
* Content: [Mail flow rules (transport rules) in Exchange Online Protection](https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/mail-flow-rules-transport-rules-0)
* Content Source: [SecurityCompliance/eop/mail-flow-rules-transport-rules-0.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eop/mail-flow-rules-transport-rules-0.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@Dottn Thank you for this feedback

I will make sure this gets investigated and updated. 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
