### ISSUE TITLE
example script "Releasing a retention policy" errors

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/OfficeDocs-o365seccomp#870]
The commands used in the example script in section "Releasing a retention policy":
- refers to cmdlets not available in the mentioned 'Office 365 Security & Compliance Center PowerShell.'
- refers to commands not applicable to Office 365: ie. command 'Get-SPSiteSubscription' is only available for On On Premises SharePoint: https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spsitesubscription?view=sharepoint-ps
- refer to variables not declared earlier in the script
- has incorrect syntax as lines end with 'equal' signs

Please add, correct and rewrite this section on how to adjust the grace period for retention policies in SharePoint On Premises AND Office 365.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@SjoerdV Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by stephow-MSFT** [comment]
@SjoerdV @scanum I'm following up with product team to verify accuracy of script.

**Comment by stephow-MSFT** [comment]
@SjoerdV @scanum Customer is correct, script is not accurate. I'm going to pull that section of the article while we research and then republish.

**Comment by stephow-MSFT** [comment]
@SjoerdV The product team has said the grace period is *not* configurable via powershell. If you have a requirement to change it, you can open a Support request and they can change it for you. I've updated the article to remove the mention of using powershell.

**Comment by SjoerdV** [comment]
Ok Great, good to know.

Sent from my iPhone
________________________________
