### ISSUE TITLE
Exporting Filter on direction does not work

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/OfficeDocs-o365seccomp#871]
When you filter on sent messages only during the export creation, the exported file contains both sent and received.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03d93a3-027c-3b21-5f51-76206df72143
* Version Independent ID: 7794adae-d872-2465-1172-89b9e53de406
* Content: [Outbound and inbound mail flow](https://docs.microsoft.com/en-us/office365/securitycompliance/mfi-outbound-and-inbound-mail-flow?redirectSourcePath=%252farticle%252ff2738dec-41b0-43c4-b814-84c0a4e45c6d)
* Content Source: [SecurityCompliance/mfi-outbound-and-inbound-mail-flow.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/mfi-outbound-and-inbound-mail-flow.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@MarcLaf Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@MarcLaf  thank you for pointing this out. Are you suggesting adding a note stipulating this, or is there something that needs to be changed in the article?

**Comment by MarcLaf** [comment]
I was trying to submit feedback on the behaviour of the feature, not the documentation, and that the feature is not working as advertised. If the export feature gives you the option to filter on sent or received, I would think that it would respect the selection made.

**Comment by scanum** [comment]
@MarcLaf thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
