### ISSUE TITLE
Explanations for the File Plan descriptors

### ISSUE THREAD

**Issue by v-olduch** [MicrosoftDocs/OfficeDocs-o365seccomp#872]
We would need to have more information on the new File Plan descriptors, what they do, how they work, usage and how it interacts with the file plan.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-ca/office365/securitycompliance/labels)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@v-olduch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@v-olduch Thank you for reaching out and helping improve MS Docs. I'll investigate further to find the necessary information to be added to the article.  If you have any suggestions or helpful links that could be added please let me know. Thanks so much.

**Comment by v-olduch** [comment]
Not sure there is any documentation yet. Will see if I can get something together for end of week.

**Comment by lindspea** [comment]
@v-olduch would this link help - https://docs.microsoft.com/office365/securitycompliance/file-plan-manager. Let me know and I can have it added to the article.

**Comment by stephow-MSFT** [comment]
Does this article help with file plan?

https://docs.microsoft.com/en-us/office365/securitycompliance/file-plan-manager

If it's missing info, pls let us know

**Comment by v-olduch** [comment]
Sorry about the delay in response!

The issue was about the File Plan descriptor you can add in a retention label. There is no details as to how these fields are used, if they interact with other entities and how you can use them in conjunction with the file plan. There are five descriptors and each of these should have at least a general mention of what it does and how it can be used in the File Plan Manager. This is especially true for the Provision/citation field, as it can be used to cite authoritative documentation like HIPAA and ultimately ISO norms. The process to add a citation or provision is not explained elsewhere.

**_Proposition:_**

File Plan descriptors:
These descriptors allows administrators to create custom reference attributes for internal classification. These attributes will appear in the File Plan Manager to better organize the different labels that exist throughout the tenant.

Reference ID:
Specify a customer reference ID for tracking and/or identification
Business function/department:
Specify the relevant business function or department to which this label refers
Category
Specify a custom category for this retention label
Authority type
Specify a custom type of authority to which this label refers
Provision/citation
Specify an external or internal provision or citation to which this label refers and/or complies to

![File Plan Descriptors](https://user-images.githubusercontent.com/47566750/64613803-0a74c480-d3a5-11e9-9ee0-c3c4242e20c2.jpg)
Thanks,
