### ISSUE TITLE
Step 3 issue

### ISSUE THREAD

**Issue by mymebenha** [MicrosoftDocs/OfficeDocs-o365seccomp#875]
I see storage explorer preview but there is no connect button and it doesn't look like the screenshot.  Tried storage accounts classic as well but there is only an Add button, no connect button. More information is needed, documentation is incomplete or inaccurate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae492dc9-f3b6-084b-6b40-21262938ec8d
* Version Independent ID: 18aceca4-de0b-4306-fe19-9a9d125d0ebd
* Content: [Download export jobs](https://docs.microsoft.com/en-us/office365/securitycompliance/compliance20/download-export-jobs#feedback)
* Content Source: [SecurityCompliance/compliance20/download-export-jobs.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/compliance20/download-export-jobs.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mymebenha** [comment]
Found the link at the top of the page with more info.  Storage Explorer is referring to an app that needs to be installed, not Storage Explorer in the Azure portal.

**Comment by markjjo** [comment]
@mymebenha Thanks for following up. I'll look into updating this topic. Maybe the best thing is to make the installation of the Storage Explorer app step 1 in the workflow. e.g. 1. Install Storage Explorer app. 2. Go to Export tab in the AeD case and select the export job. 3. Copy the Locations URL. etc.
