### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by geordietech** [MicrosoftDocs/OfficeDocs-o365seccomp#876]
Hi,

The link for "Manage your security - ATP post-setup" under https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-atp is not configured correctly.  It points to "https://docs.microsoft.com/en-us/"

**Comment by scanum** [comment]
@geordietech Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@geordietech Thank you for reaching out and helping improve MS Docs.  Please can you let me know which article you are referring to so I can investigate further.  I cannot find the link in question in the above article you provided.

**Comment by lindspea** [comment]
@geordietech Please see related issue, link was removed - https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/879 @denisebmsft
