### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#879]
The Manage your security - ATP Post setup link on the left side navigation does not point to that content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f6ebd5-e0c1-978a-8d8d-415510b09a48
* Version Independent ID: 18b839e1-f53d-90a3-d97a-7249b54d762b
* Content: [Office 365 ATP for SharePoint, OneDrive, and Microsoft Teams](https://docs.microsoft.com/en-us/office365/securitycompliance/atp-for-spo-odb-and-teams)
* Content Source: [SecurityCompliance/atp-for-spo-odb-and-teams.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/atp-for-spo-odb-and-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@DeanGross Thanks Dean. I'm currently investigating this from another issue raiser as well.  I'll have the link added as soon as I find the document related.  If you have found it please let me know. Thanks for helping improve MS Docs.

**Comment by denisebmsft** [comment]
Hello, all! We have removed the link. Thank you so much for raising this issue. Your feedback helps us improve the quality of our content.
