### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#88]
In the For More information section, the "Find sensitive data stored in SharePoint Online sites" is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deff2463-655e-f984-8d32-6b8f1eac6283
* Version Independent ID: 8bd62a52-dc23-8b62-d358-9a8f0e3d237c
* Content: [Form a query to find sensitive data stored on sites](https://docs.microsoft.com/en-us/office365/securitycompliance/form-a-query-to-find-sensitive-data-stored-on-sites)
* Content Source: [SecurityCompliance/form-a-query-to-find-sensitive-data-stored-on-sites.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/form-a-query-to-find-sensitive-data-stored-on-sites.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

I will make sure this link gets fixed. 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
