### ISSUE TITLE
SPO, versions and Preservation Library

### ISSUE THREAD

**Issue by ATJSM** [MicrosoftDocs/OfficeDocs-o365seccomp#881]
In this page, there is a statement that reads: "Each time a document subject to a retention policy is edited or deleted, a version is copied to the Preservation Hold library". I am testing this behavior and I am not seeing this. 

The behavior I am seeing is the following:
-  Whenever I edit a document, nothing is created in the Preservation library (unlike what the article states)
-  Whenever I try to delete a version (major or minor), I get an error: "Versions of this item cannot be deleted because it is on hold or retention policy"
-  Only when I delete the whole document, I can see the document with all the versions as separate items in the preservation library

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies#how-a-retention-policy-works-with-document-versions-in-a-site-collection)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@ATJSM Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by DTGitRepository** [comment]
Please consider voting on this UserVoice entry: https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/34687639-office-365-labels-allow-deletion-of-documents-wi

**Comment by ATJSM** [comment]
Thanks, regardless of the user voice, the documentation still needs better wording: "Each time a document subject to a retention policy is edited or deleted, a version is copied to the Preservation Hold library"

Again, I am not seeing that in my tenant. When I edit a document that is subject to a retention policy and nothing gets created in the Preservation Hold Library (as opposed to what's stated in the article). Only when I delete the entire document I can see the versions in the Preservation Hold library.

Another issue, but this is from a functionality perspective and not documentation issue, is that I don't understand why users cannot delete a version of a document that has a retention hold but they can delete the entire document.....(but that's another discussion :))

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
