### ISSUE TITLE
What is the point of Quarantine, if it doesn't work?

### ISSUE THREAD

**Issue by GlenCG** [MicrosoftDocs/OfficeDocs-o365seccomp#884]
The Quarantine just started with our Outlook.  I have been blocking the same email address and domain just about every day and yet Quarantine will not just block it and keep it blocked.  It has been manually input to block even before the Quarantine program started, then I put it in again manually and it still pops up in the daily message. It blocks and quarantines all the others I have blocked but not this one, "MPP@em.home.dell.com."  I mean, this word, "blocked" I don't think it means what you think it means.  "Quarantine" as well... I expect that once I click "Block Sender" that the program would do that, BLOCK SENDER, not just keep reporting it to me, over, and over, and over, and over, and over, and over, and over, and over... you get what I mean.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
