### ISSUE TITLE
Date of New Features

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#888]
Please add a Date to the New Features section so that we tell how new they are. I'm guessing that these are several/many months old by now and may no longer be "new", if this is the case, then having a separate "Change Log/Version History" page would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator#new-features-in-attack-simulator)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@DeanGross thank you for reaching out.  I'll investigate with the team and see if the dates are released yet and can be added to the article. @denisebmsft could you please assist?

**Comment by denisebmsft** [comment]
Hello, all! Thank you for the feedback. I have a work item in my queue to update the Attack Simulator content, and I am taking this feedback into account.
