### ISSUE TITLE
Include Yammer conversations

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#89]
When will Yammer be included?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9665969-72ad-2a1e-5c5b-3e8cde4a307d
* Version Independent ID: 6aabb1a5-f38f-cf6d-408c-14e90c496d40
* Content: [Run a Content Search in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/run-a-content-search-in-the-security-and-compliance-center#teams)
* Content Source: [SecurityCompliance/run-a-content-search-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/run-a-content-search-in-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

I do not know when Yammer will be included but support might. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
