### ISSUE TITLE
No Track Revoke capability even with valid licenses

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-o365seccomp#890]
Need to add that if you have EMS E3 or EMS E5 administrators cannot see track and revoke for files shared via this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c2558b-57f8-54ce-6ebd-336b5572d2a5
* Version Independent ID: 3a5d3e54-c48f-874d-83a4-c8b26835723e
* Content: [Set up Information Rights Management (IRM) in SharePoint admin center](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-irm-in-sp-admin-center#feedback)
* Content Source: [SecurityCompliance/set-up-irm-in-sp-admin-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-irm-in-sp-admin-center.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by scanum** [comment]
@bakerm00 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by KCCross** [comment]
Sent to Team for review. Moving content to new repo in the meantime.
