### ISSUE TITLE
Secure Readers not seeing information

### ISSUE THREAD

**Issue by Exnav29** [MicrosoftDocs/OfficeDocs-o365seccomp#892]
Have noticed that people with only the "Security Reader" role are not able to access the Secure Score Information. The Overview tab shows a blank screen. The Improvement and History tabs show a client error "Auth token does not contain valid permissions or user does not have valid roles." Details are as follows:
Request: /api/m365/securescore/SecureScoreAction/GetAll
Status code: 500
Exception: Microsoft.Data.OData.ODataErrorException
Diagnostic information: {Version:17.00.3275.003,Environment:EUSPROD,DeploymentId:d2288b27111b4d5798d1312be6ea37df,InstanceId:WebRole_IN_2,SID:a028fd47-28f0-419a-a9a1-aedf577a3b1b,CID:56bd2445-e574-4351-b152-eeb197d8a531}
Time: 2019-08-02T21:42:17.8971365Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f13e79-166c-a063-ef70-dd4bd45ecc67
* Version Independent ID: d66d3771-8820-2a01-2757-400effef3dc1
* Content: [Microsoft Secure Score](https://docs.microsoft.com/en-us/office365/securitycompliance/microsoft-secure-score)
* Content Source: [SecurityCompliance/microsoft-secure-score.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/microsoft-secure-score.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by scanum** [comment]
@Exnav29 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Exnav29 Thank you for reaching out and helping improve MS Docs.  Is there anything you could suggest adding to the article to help other users?  Please let me know and I can have it added soonest.

**Comment by scanum** [comment]
@Exnav29 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
