### ISSUE TITLE
Retention with Keywords not working?

### ISSUE THREAD

**Issue by jemsjose** [MicrosoftDocs/OfficeDocs-o365seccomp#893]
The document states "Apply a policy to all content or just content meeting certain conditions, such as content containing specific keywords". I may be missing something. But followed below steps with no luck:

1. Created the Retention Policy (not Label) on Security & Compliance Center with a keyword value "Test" and retention period of 7 years
2. Location for the Retention Policy was set to a specific SharePoint site
3. Created a document in the location site and waited for the search to pickup the document with the keyword
4. Waited for the policy to be On (Success)

Expected the automatic creation of Preservation library on deletion of this document but instead the document is sent to Recycle bin as if no Retention has been applied. If no keyword is mentioned on the policy, it works as expected and creates the Preservation Library on document delete.

Don't see any additional steps in this document to set this up. Please point us to the right direction is above steps missing something? Thank you.

**Comment by scanum** [comment]
@jemsjose Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
