### ISSUE TITLE
Any documents to implement MFA with Hybrid

### ISSUE THREAD

**Issue by Narulans** [MicrosoftDocs/OfficeDocs-o365seccomp#894]
Any documents to implement MFA with Hybrid (w/ exchange 2010) for OWA only.. .all users and shared mailboxes are on O365 but applications mailboxes are still on exchange 2010 which will be later migrated to exchange 2016 box.. Mfa not required on outlook and active sync

**Comment by scanum** [comment]
@Narulans thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
