### ISSUE TITLE
Cannot solve Captcha

### ISSUE THREAD

**Issue by overrider** [MicrosoftDocs/OfficeDocs-o365seccomp#895]
I have tried to solve the captcha for delisting now for over one hours i think. Tried also from different IP addresses/Networks, different provided E-Mail, different Browser and OS. I believe the system must be broken. I cannot be that dull that i can't solve it. I tried the Audio Challenge too. Can someone please help me to delist my Server.

**Comment by overrider** [comment]
<img width="859" alt="Screen Shot 2019-16-05 11:16:15" src="https://user-images.githubusercontent.com/2169790/62436510-78104e00-b772-11e9-9ea9-6ca685141196.png">
Like every dozen or two captchas i get a simple one like that. Still can't solve it, this can't be.

**Comment by overrider** [comment]
<img width="859" alt="Screen Shot 2019-16-05 11:16:15" src="https://user-images.githubusercontent.com/2169790/62436568-a7bf5600-b772-11e9-9f2c-a3661bf476ee.png">
Every dozen or two captchas i get a simple one like that. Still unable to solve it. This can't be right!!

**Comment by scanum** [comment]
@overrider 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
