### ISSUE TITLE
DAMN!!!

### ISSUE THREAD

**Issue by BUG-reporter** [MicrosoftDocs/OfficeDocs-o365seccomp#896]
I tried to delist my e-mail but I can't pass your FUCKING captcha! I tried 10 times and all the times it says incorrect! Fuck your captcha! Fuck you, Microsoft!

---
#### Відомості про документ

⚠ *Не змінюйте цей розділ. Він необхідний для зв’язування питань на платформах docs.microsoft.com ➟ GitHub.*

* ID: 63192844-fbfe-bd5a-45b7-84ac6c1bbb2c
* Version Independent ID: a02659bc-0cfd-e145-8dd4-6c55877e4ff3
* Content: [Use the delist portal to remove yourself from the Office 365 blocked senders list](https://docs.microsoft.com/uk-ua/office365/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis#feedback)
* Content Source: [SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by Faeringen** [comment]
Same, even tried the sound option, no luck

**Comment by KeerlITServices** [comment]
I have been trying to delist one mail server over the last two days for hours and hours, using linux desktops, microsoft servers, laptops and pcs from several different IP addresses.
Neither sound nor captcha works.

I am so fed up with you guys... @microsoft!

**Comment by Ylacat** [comment]
The problem: captcha
Solution: Make global phone support delist IP’s

**Comment by andrelopes1705** [comment]
Total waste of time. Nice way to treat your customers. 
Fix it.

**Comment by noblebluelion** [comment]
Unfortunately, the Delist Captcha is still inoperable. It is affecting my entire department. I believe this issue to be effecting multiple networks and customers. Please look into this further.

**Comment by Faeringen** [comment]
I succesfully used the captcha today, waiting to see if the delist went through

**Comment by Faeringen** [comment]
It works again.

**Comment by overrider** [comment]
Sweet Jesus i have tried for hours...both text and audio. Today it worked.

**Comment by troyrollo** [comment]
The email that gets sent breaches RFC5322 and RFC2822 and is rejected by complying mail servers with messages such as the following:

2019-08-06 15:42:59 1husFP-0006DV-PI H=mail-bgr052100135046.outbound.protection.outlook.com (NAM03-CO1-obe.outbound.protection.outlook.com) [52.100.135.46] X=TLS1.2:ECDHE_RSA_AES_256_CBC_SHA1:256 CV=no F=<no-reply@microsoft.com> rejected after DATA: maximum allowed line length is 998 octets, got 3172

If you cannot design a mail system that complies with this basic requirement which is literally the first mandatory requirement for implementors in the applicable RFCs, you have no business offering any service to the public, let alone implementing such an aggressive block list system.

**Comment by G2G2G2G** [comment]
Microsoft can't get standards correct, which is why they bully others and make their own. It's hilarious watching google bully them like they did everyone else for decades.

**Comment by scanum** [comment]
@BUG-reporter 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
