### ISSUE TITLE
What does Block Sender do?

### ISSUE THREAD

**Issue by RobertSpokane** [MicrosoftDocs/OfficeDocs-o365seccomp#897]
Our users are getting annoyed because they choose "Block Sender" but their block lists just means any future mails will still go to quarantine. Why isn't BLOCK and actual BLOCK?

**Comment by scanum** [comment]
@RobertSpokane 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
