### ISSUE TITLE
IP Delist information policies 

### ISSUE THREAD

**Issue by KeerlITServices** [MicrosoftDocs/OfficeDocs-o365seccomp#898]
So, after MS fixed the Captcha issue on the https://sender.office.com/Delist/ site, I now am looking at the next atrocity:
MS is telling me, the IP cannot be mitigated.
Then they refer me to https://sendersupport.olc.protection.outlook.com/pm/postmaster.aspx where one could find some tools and info.
I have enlisted in both JMRP and SNDS - Both tools fail to give me any info regarding the blocked IP address. SNDS even says, status is normal!

My guess, that this might have been caused by the previous owner of the IP, is discarded as "we cannot give you any info". This mail server was set up last friday and went productive yesterday -where we were IMMEDIATELY blocked.

So, apparently, as MS says, something is wrong with the server (SPF, DKIM and DMARC are all in place, as are AntiSpam and AntiVirus) - but MS will not tell me, what could be wrong!

Thanks - my customer is now -rightly so - p*ssed off, as this mail migration went t*** up*, which of course yours truly has to answer for.
*No, all went fine - until people started sending e-mails to their business partners, hosted on O365. I now know exactly why I neither offer nor support this.

**Comment by scanum** [comment]
@KeerlITServices 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
