### ISSUE TITLE
Error with \<img height\="?1"? width\="?1"? sr\c=.?http\://

### ISSUE THREAD

**Issue by Navoxctr** [MicrosoftDocs/OfficeDocs-o365seccomp#901]
I am using o365 and setting up a mail rule using the instructions here. 

Under the section: Create a mail flow rule to filter bulk email messages based on text patterns

This line:     \&lt;img height\="?1"? width\="?1"? sr\c=.?http\://  

Produces the following error - "The pattern contains incorrect characters,operators, or constructs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e97743da-8e83-7fbd-45aa-945dd38899fc
* Version Independent ID: 2c7484e5-81ca-19fb-2646-c241782fd897
* Content: [Use mail flow rules to configure bulk email filtering in Exchange Online Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/use-transport-rules-to-configure-bulk-email-filtering#feedback)
* Content Source: [SecurityCompliance/use-transport-rules-to-configure-bulk-email-filtering.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-transport-rules-to-configure-bulk-email-filtering.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@Navoxctr 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
