### ISSUE TITLE
PLace a mailbox in Litigation Hold link goes to a 404 page

### ISSUE THREAD

**Issue by DocJelly** [MicrosoftDocs/OfficeDocs-o365seccomp#902]
For step-by-step procedures for placing a mailbox on Litigation Hold or applying an Office 365 retention policy, see:

Place a mailbox on Litigation Hold
^^ this link in step 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac2ead82-c764-16a8-2850-a313ecabc44a
* Version Independent ID: 26baec04-9492-6030-e39f-060243939cec
* Content: [Create and manage inactive mailboxes in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/create-and-manage-inactive-mailboxes)
* Content Source: [SecurityCompliance/create-and-manage-inactive-mailboxes.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@DocJelly Thanks for the heads up. This link is fixed and now points to https://go.microsoft.com/fwlink/?linkid=856286
