### ISSUE TITLE
"To" vs. "Recipient"

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-o365seccomp#903]
Hi,
At first your table says:

**Recipients**: All recipient fields in an email message; these fields are To, CC, and BCC.
**To**: The To field of an email message.

Then a bit later you wrote:

**Recipients**: The person an email message was sent to. **This is the same property as the To** email property.
**To**: The recipient of an email message.

Correct me if I'm wrong, but isn't those give a bit different message? At first "Recipients" covers all recipient fields and "To" only "to"-field. And then you turn out and say, they are the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b84ade-fa24-3ca7-adb8-1a3398faa0a0
* Version Independent ID: b601bd4d-aa7e-63aa-0404-4cd84d817a9d
* Content: [Keyword queries and search conditions for Content Search](https://docs.microsoft.com/en-us/office365/securitycompliance/keyword-queries-and-search-conditions)
* Content Source: [SecurityCompliance/keyword-queries-and-search-conditions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Petri-X Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
