### ISSUE TITLE
SPF and DKIM all valid, yet MS Choosed to block.

### ISSUE THREAD

**Issue by harqen** [MicrosoftDocs/OfficeDocs-o365seccomp#906]
How do I determine why the IP was blocked. Do we need to exclude office 365 from our supported technology list like Internet Explorer.

David
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63192844-fbfe-bd5a-45b7-84ac6c1bbb2c
* Version Independent ID: a02659bc-0cfd-e145-8dd4-6c55877e4ff3
* Content: [Use the delist portal to remove yourself from the Office 365 blocked senders list](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis)
* Content Source: [SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by G2G2G2G** [comment]
It doesn't say at all why stuff is blocked. They probably don't even know themselves.

**Comment by scanum** [comment]
@harqen 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by harqen** [comment]
I see the primary issue is that our product uses email to communicate with our clients and their clients. As a client they only know the email never arrives, and they consider it a product failure. I can suggest they get a more reliable email handler, but the decision to use onmicrosoft is not mine or my company's to make. Onmicrosoft is failing to deliver email the client wants and does not even let them know that it is happening. I would certainly run it through our legal team, but it seems that onmicrosoft is obstructing the contract the client signed with us because we require the client to accept email our system delivers.
