### ISSUE TITLE
Same thing but for OneDrive

### ISSUE THREAD

**Issue by michaeak** [MicrosoftDocs/OfficeDocs-o365seccomp#907]
How do you tell which sites are on hold - by site URL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11cfda8-7ca5-8f14-afef-c16deda5db50
* Version Independent ID: dfb762aa-615e-93b9-f042-9fa347463152
* Content: [How to identify the type of hold placed on an Exchange Online mailbox](https://docs.microsoft.com/en-us/office365/securitycompliance/identify-a-hold-on-an-exchange-online-mailbox#feedback)
* Content Source: [SecurityCompliance/identify-a-hold-on-an-exchange-online-mailbox.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/identify-a-hold-on-an-exchange-online-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
