### ISSUE TITLE
Internet Explorer (or Edge) required to "Download Results" (i.e. Downloading "eDiscovery Export Tool")

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-o365seccomp#908]
I think this is just like every other ClickOnce installer (Exchange Online's Hybrid Configuration Wizard, and EXO PowerShell Module, the O365 SARA tool) - is there a particular reason Microsoft keeps using this approach since other browsers can't deal with them?

I see the warning (now, not originally):

>  Warning: You must use Microsoft Edge or Internet Explorer to download search results or reports. Please switch to one of these browsers to download the content.

But what gives, why not make this work for any browser?  It seems strange because this is a hosted service and not every subscribing company's security / discovery admin is going to be (or going to want to have to be) running Windows.  At the very least, Edge based on Chromium should somehow get looped into the list of working browsers.

It is nearing foul play.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdb113e3-c0e8-79c0-4cdb-a085e0eaffdb
* Version Independent ID: a26fcb1e-907d-13d4-c13f-a7883b4138e3
* Content: [Export Content Search results](https://docs.microsoft.com/en-us/office365/securitycompliance/export-search-results)
* Content Source: [SecurityCompliance/export-search-results.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/export-search-results.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@JeremyTBradshaw  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by markjjo** [comment]
@jeremyTBradshaw You can provide product feedback on the eDiscovery Export tool at https://office365.uservoice.com/forums/289138-office-365-security-compliance

Also, you might check out Advanced eDiscovery, which uses a different method for downloading exported content.
