### ISSUE TITLE
\*contoso.com\* does not work

### ISSUE THREAD

**Issue by billshieh** [MicrosoftDocs/OfficeDocs-o365seccomp#91]
this new wild card syntax for do not rewrite list does not appear to be working.  is there anything else that needs to be done to enable this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f466441b-e9f7-f7ce-ade9-ec78b879699c
* Version Independent ID: 57d4a26b-0f05-cb76-5e05-6077e88c9495
* Content: [Set up a custom do-not-rewrite URLs list using Office 365 ATP Safe Links](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp?redirectSourcePath=%252farticle%252f35dbfd99-da5a-422b-9b0e-c6caf3b645fa)
* Content Source: [SecurityCompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@billshieh thank you for letting us know about this. I'll look into it and get back to you ASAP.

**Comment by denisebmsft** [comment]
@billshieh please remove the "\" from the URLs you're entering. So instead of \*contoso.com\* just enter *contoso.com*

I have updated the article and republished. Changes should be live within a few minutes. Apologies for the inconvenience, and thank you again for letting me know.
