### ISSUE TITLE
Cleaning up the definition of what constitutes a "phish"

### ISSUE THREAD

**Issue by jmvalente** [MicrosoftDocs/OfficeDocs-o365seccomp#912]
The way Microsoft defines "phishing" in the security & compliance center is way too vague of a definition.  The vast majority of items that will come up in the Threat Explorer under "phish" or under AIR are various forms of spam (usually with a spoofed sender, which I assume is triggering the phish), such as links to knock off goods, generic meds, etc. 

When you ask any one working in information security, or even IT in general, the definition of phishing you will almost always get will be that it is a social engineering based attack with the intent of tricking someone into giving up sensitive info (username/password, W2 forms, PII, etc).  When 90% of the alerts being raised are not this type of phishing and are essentially the standard form of spam, actually concerning phishing attacks are drowned out and it is difficult for an analyst to sift through the alerts.  Even using things like CloudAppSecurity ends up not being helpful as the alert for suspicious email will trigger on this spam. I've tried to play with AIR but I end up looking through 100+ daily investigations to try and determine which are something more troubling than an a diet pill email hitting a user's junk box and being tagged as a phish.  

The security and compliance center needs MS to either tighten up the definition of what a "phish" is or enable admins tighter control of what is classified as what. The current setup makes many of the alerts and search filters unusable due to nearly every result being absolutely useless.

**Comment by scanum** [comment]
@paratz Please link documentation you are referring to. Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by jmvalente** [comment]
Now that I'm back in, here's a few examples from the threat explorer.

![image](https://user-images.githubusercontent.com/55451/62870003-e4e19600-bce6-11e9-9a46-e5bd29f0a6ab.png)

This was marked as a phish because of domain spoofing, but the subject alone makes it obvious that this was some type of spam 

And here's an example of a listserv (running mailman, I think) also being categorized as a phish because of the anti-spoofing

![image](https://user-images.githubusercontent.com/55451/62870167-24a87d80-bce7-11e9-80dc-385dcab0abee.png)
![image](https://user-images.githubusercontent.com/55451/62870248-4dc90e00-bce7-11e9-938f-9a86034b951a.png)

The latter example is also very troublesome as when I raised this issue with MS Premier their solution was to whitelist every listserv that our users are subscribed to in our transport rule (essentially bypassing any spam/phishing filtering that would be applied to actually malicious messages applied to these messages). As a university with ~10k active students, another 10-20k active alumni users, and 1000+ faculty and staff, this is an insane requirement to expect admins to manually add every possible mailing list a person may be using.  Even if only 1% of users are using a unique mailing list, that's over 100 items we'd need to manually add and document.  These ones in particular are being flagged because the sender doesn't match the sender-from --something done by mailing lists to address issues with SPF failures, and not a new concept (i.e. mailing lists have existed for decades).

I understand_why_ EOP/ATP thinks this might be a phish (the spoofing of the sender) but for a solution that costs hundreds of thousands of dollars per year, some intelligence in how these messages are categorized is absolutely necessary.  If I filter through just today's results for messages marked as a phish, I'm having difficulty finding any "actual" phish among the results that've been returned.  Even trying to further refine the results by filtering on the detection technology doesn't fare much better.

**Comment by lindspea** [comment]
@jmvalente Thank you for reaching out and helping improve MS Docs. Please could you specify which article you are referring to that needs to be edited. I work on the editing/writing side of the MS Docs in helping improve content for all users.

**Comment by scanum** [comment]
@jmvalente We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
