### ISSUE TITLE
Messages sent to Distribution List not expanded.

### ISSUE THREAD

**Issue by labanex** [MicrosoftDocs/OfficeDocs-o365seccomp#915]
If a message is sent to a distribution list and gets quarantined, not expanded, if released or removed, it will delete the message entirely for everyone who is associated with the distribution list. If released, it will release to everyone. If removed, it will remove for everyone. This or other articles does not explain how distribution list is handed. Would love to see this updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 461aa2f7-3082-31fc-d9c8-8bc92b4ee9a6
* Version Independent ID: c2279790-fe0e-61e6-85e7-735ee9fa2043
* Content: [Quarantine FAQ](https://docs.microsoft.com/en-us/office365/securitycompliance/quarantine-faq)
* Content Source: [SecurityCompliance/quarantine-faq.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/quarantine-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@labanex Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @labanex, thank you for your feedback. We really appreciate it.

However, we think this behavior is standard for most of the market spam solutions and there is no need to explain further.
Each email object is managed as a single object.

**Comment by MSFTTracyP** [comment]
@Labanex - Thank you for bringing this information to my attention! I've taken note of it for future edits. I really appreciate your input from experience. Thank you.
