### ISSUE TITLE
Get-DkimSigningConfig parametername wrong

### ISSUE THREAD

**Issue by smartwombat** [MicrosoftDocs/OfficeDocs-o365seccomp#916]
Get-DkimSigningConfig -DomainName domain | fl Selector1CNAME, Selector2CNAME
Fails, with an error that DomainName is not a valid parameter.

Documentation at at https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/get-dkimsigningconfig?view=exchange-ps)
Gives the parameter name as -Identity

And this command works:
Get-DkimSigningConfig -Identity &lt;customdomain&gt; | fl Selector1CNAME, Selector2CNAME

And for us was identical to the description for GCC High customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM for email in your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dkim-to-validate-outbound-email)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@smartwombat Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @smartwombat, thank you for your feedback.

The same applies to Set-DkimSigningConfig. I am updating this article to fix it.

Thanks again.

**Comment by KCCross** [comment]
Updated powershell syntax for Get- and Set-DKIMSigningConfig throughout. New-DKIMSigningRequest did not change, it's still -DomainName.
