### ISSUE TITLE
How do I access the Powershell cmdlets?

### ISSUE THREAD

**Issue by MichaelMc64** [MicrosoftDocs/OfficeDocs-o365seccomp#92]
I've been logging in to Office 365 remote powershell sessions daily for about four years. When I try "New-ActivityAlert" I get "The term 'New-ActivityAlert' is not recognized as the name of a cmdlet, function, script file, or operable program". 
More details on how to access these cmdlets are needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb61519-dd23-0fc2-f91a-4c9db668875c
* Version Independent ID: 618e4a73-a59e-39e1-13d2-3d1ad7ebb9b5
* Content: [Create activity alerts in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/create-activity-alerts)
* Content Source: [SecurityCompliance/create-activity-alerts.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-activity-alerts.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@MichaelMc64 please make sure that you are assigned the Organization Configuration role in the Office 365 Security & Compliance Center and that you are connecting to Office 365 Security & Compliance Center PowerShell to run this cmdlet. See [Connect to Office 365 Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps)  and 
[New-ActivityAlert](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/new-activityalert?view=exchange-psl)--If you still can't run the cmdlet, please open a support ticket. Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y
