### ISSUE TITLE
Provide examples of a way to list many domains

### ISSUE THREAD

**Issue by Lowell-Syncrety** [MicrosoftDocs/OfficeDocs-o365seccomp#921]
A phish testing product has 21 domains to add to the "do not rewrite" URL list. Is there a way to add many domains at once? I don't see an example of this, and adding the domains from the clipboard just adds them all in one line. If you have to do this for many clients it becomes very time consuming.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f466441b-e9f7-f7ce-ade9-ec78b879699c
* Version Independent ID: 57d4a26b-0f05-cb76-5e05-6077e88c9495
* Content: [Set up a custom do-not-rewrite URLs list using Office 365 ATP Safe Links](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp#feedback)
* Content Source: [SecurityCompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@Lowell-Syncrety Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @Lowell-Syncrety, thank you for your feedback.

I think there is no way but I will try to confirm it.

**Comment by MSFTTracyP** [comment]
There is no bulk add that I'm aware of, but you could test copying any entries from a Get-SafeLinksPolicy, and sum them in a TX file for pasting in a Set- command.
