### ISSUE TITLE
DLP Encrypt Rules Don't Allow Custom Branding

### ISSUE THREAD

**Issue by dawander** [MicrosoftDocs/OfficeDocs-o365seccomp#922]
If we choose to encrypt a message containing sensitive financial information, it will encrypt it just fine.  However, even if we change the default OME template, it will not apply custom branding.  There doesn't appear to be a workaround for this and support has been working on it for weeks now.  Ticket #15425756 if anyone is interested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069dc3ae-47bf-2ef4-dba4-de552277e201
* Version Independent ID: 729d2cb6-aaa6-5eb9-8200-2b7c469598b0
* Content: [How DLP works between the Security & Compliance Center and Exchange admin center](https://docs.microsoft.com/en-us/office365/securitycompliance/how-dlp-works-between-admin-centers)
* Content Source: [SecurityCompliance/how-dlp-works-between-admin-centers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/how-dlp-works-between-admin-centers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by scanum** [comment]
@dawander Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @dawander, thank you for your feedback.

Looks like it's a bug or product issue and you managed it in the right way, opening a support ticket. We are here to help with docs and the issues that we can find there. So, I think we cannot help you in this case.
Please let me know if I am wrong and you think we can help you.
Thanks!
