### ISSUE TITLE
the unified labeling client runs only on Windows, so this feature is not yet supported on Mac, iOS, and Android.

### ISSUE THREAD

**Issue by osalem** [MicrosoftDocs/OfficeDocs-o365seccomp#924]
How correct this statement is ? 

please check
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#choose-which-azure-information-protection-client-to-use

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e6acb7-ffbb-8d2b-db9b-45eeb3aaae7a
* Version Independent ID: e72bdf43-5d83-ff4b-4d3c-e61a960e7d39
* Content: [Apply a sensitivity label to content automatically](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/apply-sensitivity-label-automatically)
* Content Source: [SecurityCompliance/apply-sensitivity-label-automatically.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@osalem Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @osalem, thank you for your feedback.

I think it's correct. Automatic labeling is only supported on the unified labeling client which cannot be installed on Mac, iOS and Android.
"Manual" labeling ability built in to Office apps is available for mobile devices (iOS and Android) and Mac computers. Please check:
https://support.office.com/en-us/article/apply-sensitivity-labels-to-your-documents-and-email-within-office-2f96e7cd-d5a4-403b-8bd7-4cc636bae0f9

**Comment by stephow-MSFT** [comment]
@osalem The AIP topic you link to says this --

Install the Azure Information Protection unified labeling client for labels and policy settings that can also be used by MacOS, iOS, and Android, and if you don’t need the few features that aren't yet supported by the classic client. These features include protecting content with an on-premises key (HYOK) and a scanner for on-premises data stores.

-- It's true that these labels and be used on other OS's, but the unified labeling client itself can't be installed on those OS's.

**Comment by stephow-MSFT** [comment]
So to clarify, sensitivity labels can be used on multple OS's, but some specific features (like auto-apply) need the unified client and so are only available on Windows.
