### ISSUE TITLE
Conflicting information regarding labels when moving a document

### ISSUE THREAD

**Issue by IsabelleGH** [MicrosoftDocs/OfficeDocs-o365seccomp#928]
This page contains these two sentences which provide conflicting information :

"If you move an item with a default retention label from one folder to another folder with a different default retention label, the item will get the new default retention label."

"If you move an item with a default retention label from one library, folder, or document set to another library, folder, or document set, the item keeps its existing default retention label, even if the new location has a different default retention label."

Which is true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0370f12-6d98-e63e-5edd-74abf32a2e04
* Version Independent ID: d202ec1f-87ef-ab8b-37d3-f16889e84a38
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/office365/securitycompliance/labels#feedback)
* Content Source: [SecurityCompliance/labels.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@IsabelleGH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @IsabelleGH, thank you for your feedback.

The first sentence applies to Exchange Online/Outlook, and the second sentence applies to SharePoint.

**Comment by stephow-MSFT** [comment]
Yes the first sentence is in the Exchange section, the second is in the SharePoint section.
