### ISSUE TITLE
EFV:NLI;

### ISSUE THREAD

**Issue by RALGIE** [MicrosoftDocs/OfficeDocs-o365seccomp#929]
X-Forefront-Antispam-Report: EFV:NLI; is not listed

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f9055529-6153-c137-d7ad-d42ce3b55f38
* Version Independent ID: c85c5506-ef63-3815-c26e-1b5a74fe29d7
* Content: [How to prevent false positives from happening in Office 365](https://docs.microsoft.com/nl-nl/office365/SecurityCompliance/prevent-email-from-being-marked-as-spam#feedback)
* Content Source: [SecurityCompliance/prevent-email-from-being-marked-as-spam.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@RALGIE Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @RALGIE, thank you for your feedback.

EFV:NLI should disappear soon:
https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/211

**Comment by KCCross** [comment]
Closing for Chris, we're moving this to the new repo.
