### ISSUE TITLE
Submission outcome

### ISSUE THREAD

**Issue by 0acff4be45** [MicrosoftDocs/OfficeDocs-o365seccomp#930]
What happens when a URL is scanned, and determines that the page is not phishing, when I know 100% that it is a phishing site, can it be contested and rescanned?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45422fa-0acc-d2ea-0e00-c9a40a137a92
* Version Independent ID: be96c523-752a-c947-8cd7-2509d85d63f2
* Content: [Admin submissions in Office 365, O365 submissions, Office 365 spam problem, O365 false negative, submit phish in office 365, submit email for scanning, suspicious email in Office 365, scan a mail, have Microsoft scan for phish, have Microsoft scan for spam, submit e-mail, submit email](https://docs.microsoft.com/en-gb/office365/securitycompliance/admin-submission)
* Content Source: [SecurityCompliance/admin-submission.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/admin-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Hi @0acff4be45, if that happens, and it shouldn't happen often, please don't wait. Follow the steps in this article to submit to Microsoft!

**Submit spam, non-spam, and phishing scam messages to Microsoft for analysis**
https://docs.microsoft.com/en-us/office365/SecurityCompliance/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis

**Comment by MSFTTracyP** [comment]
Oh! I forgot to add that you can also submit a ticket to Support in this case, and create a URL block. I hope this helps!
