### ISSUE TITLE
Missing Instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#931]
The actual Configure Phishing Template screen has a Category field which is not mentioned in the Instructions above. Please update the instructions to tell us how this field is supposed to be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18285bf-d947-f324-50d4-7e647beabde7
* Version Independent ID: 0ecfe6c1-a306-cc01-edf1-ad31b698b2cd
* Content: [Attack Simulator in Office 365](https://docs.microsoft.com/en-us/office365/SecurityCompliance/attack-simulator)
* Content Source: [SecurityCompliance/attack-simulator.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by stuartcl** [comment]
At the moment no direct use, but some features coming later this year that will let you tag templates with them, so for example you can tag templates that had a particular theme, such as branding, spoof, malware etc

**Comment by denisebmsft** [comment]
Thank you @stuartcl. And thank you @DeanGross for raising this question. We'll take a work item to add a note to the article. @scanum thanks!

**Comment by denisebmsft** [comment]
Hello, everyone! Although I am going to close this issue out, I have a work item in my queue to update the Attack Simulator content, and that will include a note about the Category field in the phishing attack template. So please know that even though I'm closing the issue, this isn't off my radar.
