### ISSUE TITLE
End-user spam notifications for a policy

### ISSUE THREAD

**Issue by JBurdGitsIT** [MicrosoftDocs/OfficeDocs-o365seccomp#936]
A step may be wrong or missing. I see the end-user spam notifications section in the summary, but I cannot find where to edit the setting. Regarding step 3: in the right pane, where the summary information about my policy appears, end-user spam notifications isn’t a clickable link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ff95c3-b69f-ae49-03ab-994c6fb97f3c
* Version Independent ID: 788c6b03-ce4a-73e3-0e1a-07a7c5fa127d
* Content: [Configure end-user spam notifications in EOP](https://docs.microsoft.com/en-us/office365/securitycompliance/configure-end-user-spam-notifications-in-eop#feedback)
* Content Source: [SecurityCompliance/configure-end-user-spam-notifications-in-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/configure-end-user-spam-notifications-in-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
@JBurdGitsIT, I'm wondering whether you might have permissions issues going on in this case, for which I'm going to refer you to Support:

https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone

They will be able to work with you on your system to further investigate!
