### ISSUE TITLE
there are 2 "italy" the second one is latvia

### ISSUE THREAD

**Issue by grex86** [MicrosoftDocs/OfficeDocs-o365seccomp#938]
https://docs.microsoft.com/en-us/office365/securitycompliance/eu-national-identification-number#italy-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1923bfd2-fddd-19d5-ae85-47312564df32
* Version Independent ID: d011d81a-f200-bd14-a876-2dcb008e409d
* Content: [EU National Identification Number](https://docs.microsoft.com/en-us/office365/securitycompliance/eu-national-identification-number#see-also)
* Content Source: [SecurityCompliance/eu-national-identification-number.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/eu-national-identification-number.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by markjjo** [comment]
@grex86 Thanks for the heads up. This is fixed and updated topic will be live shortly.

https://docs.microsoft.com/en-us/office365/securitycompliance/eu-national-identification-number#latvia
