### ISSUE TITLE
PST Import failure

### ISSUE THREAD

**Issue by jeffry-chacon** [MicrosoftDocs/OfficeDocs-o365seccomp#94]
Can we share an action plan for failed PST imports? Typically keep adding new imports is not a best practice, but rather to troubleshoot the existing one. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a65de3-b878-b20a-3823-11a9dbc3e37c
* Version Independent ID: 28499237-e103-b204-12b2-11d72f685370
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files)
* Content Source: [SecurityCompliance/use-network-upload-to-import-pst-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@jeffry-chacon Thank you for your feedback

I agree that we should have an action plan for failed PST imports available. Let me get this in front of the o365seccomp team so we can see what they have and get that included into the article. 

I was able to get this into the backlog for the o365seccomp team. I am going to close this issue so we don't have two tickets open for this. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by grandpappy1224** [comment]
Are there any updates on this?  I cannot find any information on the correct steps to take when a PST import fails/hangs.  The data shown in the status window has very limited data, and no options to take actions on existing jobs.

**Comment by markjjo** [comment]
@grandpappy1224 If you have a PST import job that failed for selected mailboxes, you can try to create a new import job and submit a new CSV mapping that only contains rows for the mailboxes that failed. Otherwise, please open support request with Microsoft Support.
