### ISSUE TITLE
security group

### ISSUE THREAD

**Issue by gnerd** [MicrosoftDocs/OfficeDocs-o365seccomp#944]
Why do you have us create a security group?   Its not like you assign it any specific RBAC roles or anything - what is the point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647fcae2-0331-43a3-9280-1e87ccbd197d
* Version Independent ID: 5e6e6150-c6e6-90e7-a4b3-8c50ece8071c
* Content: [Create custom sensitive information types with Exact Data Match](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification#feedback)
* Content Source: [SecurityCompliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Thanks for asking, I have forwarded your question to the owning PM

**Comment by chrfox** [comment]
Hi - The PM responded that this security group is used to identify the users who have been granted authorization to manage EDM data.
