### ISSUE TITLE
Defaults Could Be Improved

### ISSUE THREAD

**Issue by tdrusk** [MicrosoftDocs/OfficeDocs-o365seccomp#95]
When a company goes out of their way to enable auditing, it strongly implies they wish to audit an account. However, the defaults don't do a good job of auditing user actions. Why not just enable all of the auditing features? It certainly doesn't hurt to have the extra data and filter it later. Please change this so all auditing is enabled by default [or at least when auditing is turned on!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@tdrusk Microsoft is in the process to enabling mailbox audit logging by default. Currently this is being rolled out worldwide, but not sure when this will be available for organizations. The help article that you commented on will be updated accordingly. Here's a blog that explains this new capability: https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Exchange-Mailbox-Auditing-will-be-enabled-by-default/ba-p/215171
