### ISSUE TITLE
The URL for Admin Portal of Exchange Online Protection is not working

### ISSUE THREAD

**Issue by paulmietvuon** [MicrosoftDocs/OfficeDocs-o365seccomp#951]
https://admin.protection.outlook.com/ecp/&lt;companydomain&gt;. For example, https://admin.protection.outlook.com/ecp/contoso.onmicrosoft.com
all of them is not working, I have to access via this link: https://outlook.office365.com/ecp/
Please check again.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d65f7c05-fff9-aad2-c5eb-cc6e96c939b4
* Version Independent ID: 33691c6f-fce3-9c84-b02c-b1ad51ce93e3
* Content: [Exchange admin center in Exchange Online Protection ](https://docs.microsoft.com/en-us/office365/securitycompliance/exchange-admin-center-in-exchange-online-protection-eop#feedback)
* Content Source: [SecurityCompliance/exchange-admin-center-in-exchange-online-protection-eop.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/exchange-admin-center-in-exchange-online-protection-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Hi @Paulmietvuon, so the best way to open a Support issue is through these methods:

https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone

This forum is not an effective way to get an issue troubleshot by Support Engineers. Please do keep a copy of these URLs on hand for your use!

Thanks!
