### ISSUE TITLE
New-OMEConfiguration not available

### ISSUE THREAD

**Issue by AndyDring** [MicrosoftDocs/OfficeDocs-o365seccomp#953]
When I attempt to use New-OMEConfiguration in my tenant, it's not available ("The term 'New-OMEConfiguration' is not recognized as the name of a cmdlet...").

I have a test OME rule in place that works, so RMS is enabled for Exchange, and I am using the same Global Admin account that I used to set up the Transport Rule.

I also can't retrieve more than the default OME config with Get-OMEConfiguration - there is no parameter to specify a template name.

Am I missing something?

Thanks,

Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eca82ca-4de3-9cfb-19bc-7adc2120b954
* Version Independent ID: e41fc575-6e2d-da06-5a6b-dee1372f3c22
* Content: [Add your organization brand to your encrypted messages](https://docs.microsoft.com/en-us/office365/securitycompliance/add-your-organization-brand-to-encrypted-messages#feedback)
* Content Source: [SecurityCompliance/add-your-organization-brand-to-encrypted-messages.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/add-your-organization-brand-to-encrypted-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
Hi AndyDring. Multiple branding templates are available with Advanced Message Encryption.
