### ISSUE TITLE
Formatting update

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/OfficeDocs-o365seccomp#97]
It looks like there's some formatting exposed on this page.  I see the following text - 

&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD 2. In the Office 365 Admin Center, open Admin centers and then click Security & Compliance.
2.In the Office 365 admin center, open Admin centers and then click Security & Compliance.

master

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb598b7-9868-2686-9c57-c50e6e000cd7
* Version Independent ID: 1a3362b5-f106-8e97-df93-30d69daf9a3c
* Content: [Give users access to the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/grant-access-to-the-security-and-compliance-center)
* Content Source: [SecurityCompliance/grant-access-to-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/grant-access-to-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@kellybos Thank you for pointing this out. 

I will get this in the backlog for the 0365seccomp team for editing. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@kellybos and @dbirks thank you very much!
